### ISSUE TITLE
RB-25s & RB-35s LUA Script crashes telemetry

### ISSUE THREAD

**Issue by Chilie78** [FrSkyRC/ETHOS-Feedback-Community#4003] opened 2024-05-08 15:52 UTC
I have encountered what is probably a bug or a conflict with the LUA scripts that manage the RB-25s and RB-35s. 
On each device, I have a total of two TDMX receivers that have been flashed to v1.0.12. Both RB's have been updated with the latest version of firmware and LUA Script that is listed on FrSkys website. I am running Ethos 1.5.7 and have the TD-ISRM v2.2.6 module installed.
When the unit powers on for the first time, I can see all the telemetry for the RB. Everything is working as it should be. When I open any of the 3 scripts to attempt to configure the RB, within a few seconds, the telemetry for the RB drops off completely and I can no longer configure any of the parameters for the device. As long as I don't open or attempt to configure the scripts, it will continue to work. I can still see the telemetry for the TDMX.
In an attempt to rule out variables, I have unplugged one of the TDMX and am only running one of them and I still get have the same issue. Here is a video of what I'm talking about. 
https://www.dropbox.com/scl/fi/tgji2dl9tvy6glyfiuste/20240506_154719.mp4?rlkey=j6i59d3lcccaeatuazhd6vryn&dl=0

**Comment by Kreisflieger** [comment] 2024-05-09 17:43
I can confirm your findings. 

I updated my RB25S with firmware:  RB25S_v20240313.frsk which was the latest version in the FrSky download page.
But I was not able to configure the RB by the LUA scripts, all fields were grayed out of showed "???"
Then, a few days later, this version was deleted from the web.

Returning to the official "old" Firmware  RB25S_v20230509.frsk did not help. My RB25S is still defect. No configuration by LUA script possible anymore.

It is a desaster, Frsky is not responding.

**Comment by Chilie78** [comment] 2024-05-20 16:53
I just tested this with Ethos 1.5.8. I had some hope this was resolved, but it still isn't working. I was able to go through all the calibration parts which is a step in the right direction. However, after the first screen for the calibration, I got the same "Sensor lost" announcement. Even though it lost telemetry, it let me go through with the calibration. None of the other scripts though were working.

**Comment by Chilie78** [comment] 2024-05-28 23:16
On a side note, I needed to make some adjustments to my Power Switch via the LUA script and it ended up doing the same thing. A couple of seconds into opening the LUA script, I get the same "Telemetry Lost" notification and can not make any other adjustments. That makes two fairly expensive pieces of hardware that I have and cannot use it as designed. I really wish someone at Frsky would take note of this issue. I have a hard time believing only me and a couple others are having this problem.

**Comment by 3wintro** [comment] 2024-05-29 14:27
Is it possible to use the RB-25S for flying or is it risky? I have 3 x RB-25S, two of them behave exactly the same. 1x RB-25S no longer works at all, after I installed the FW-RB25_RB25S_v20240314.zip, reset does not work at all. The RB-25S is at the service for exchange.

**Comment by Chilie78** [comment] 2024-05-29 15:11
From what I can tell, its fine to use. I do get positive radio link telemetry. The problems start when you use any of the LUA scripts for configuration or calibration. You just cant adjust anything and are stuck using the default values. One of the nice features of the RB-35 is that you can set different output voltages to two different sets of servos or devices. By default they're stuck at 5v output. Whats the point in spending 200+ dollars on something that you cannot configure. Plus if you cannot configure anything and have the stabilized version of the RB-25S or RB-35S, you're even more screwed. I have no idea what is causing the problem. Is it a scripting issue such as bad code? Or is it that something in that code is breaking the telemetry which is needed for configuration? All I know is I have hundreds of dollars just sitting on the bench being unable to be used in addition to spending hundreds of dollars on "temporary" receivers that I can use in the mean time which will become redundant once (if it ever happens) the problem(s) get fixed. Its getting someone at Frsky to pay attention to this post and assign it to someone to be fixed.
I'm glad their adding new features, but clearly something has been broken and it has been going on for quite some time.

**Comment by 3wintro** [comment] 2024-05-29 15:46
I find it very regrettable that the problems have not been resolved. I'll have to email the dealer as I still have the warranty on them and will send them back as they don't work. I'm already thinking about switching to another brand where the accessories also work. I actually switched to Frsky because of Ehtos. I should have switched to another provider where the things work.

**Comment by mawzthefinn** [comment] 2024-06-24 16:48
Is this still occuring with the updated Lua recently released?

**Comment by Chilie78** [comment] 2024-06-24 18:51
They are working properly on my end. I was only able to verify the RB-25S though. I haven't been able to verify on the RB-35s, but I would assume its the same situation.

**Comment by Kreisflieger** [comment] 2024-06-25 04:38
The new LUA script does work for my RB25S. 

But the Automatic mode during Failsafe is still not functional, even if I set CH14 to -100 %.

As I understood from the other Issue ( https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4109 )

Nicholas stated, that this function seems to be implemented in a new Firmware Version of the RBs.

Please refere to:
**[Nicholas-Luoyi](https://github.com/Nicholas-Luoyi) commented [3 weeks ago](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4109#issuecomment-2151678995)
RB 25S doesn't support this feature for now. And it would be available in the future.**

So I still hope that FrSky will offer an Update in near future, but I am still pessimistic.

Regards  Stephan

**Comment by mawzthefinn** [comment] 2024-06-25 13:29
Closing this issue off as it's been addressed.

The failsafe issue is an RB firmware behaviour, not a Lua issue.

**Closed as completed by mawzthefinn** 2024-06-25 13:29 UTC

**Comment by Kreisflieger** [comment] 2024-06-25 14:11
Yes, correct to close the issue regarding the LUA.

Would like to have a reporting/ issue tool for hard/ firmware problems which is run directly by FrSky.

**Comment by mawzthefinn** [comment] 2024-06-25 14:20
> Yes, correct to close the issue regarding the LUA.
> 
> Would like to have a reporting/ issue tool for hard/ firmware problems which is run directly by FrSky.

We do still have FrSkyRC/RF_Feedback_Group#26 for the failsafe issue. The RF firmware team does look at this Github, even if it is ETHOS focused.

**Comment by Kreisflieger** [comment] 2024-06-25 14:28
Hi Adam,

thanks for your clarification.

Kind regards Stephan
