### ISSUE TITLE
Missing unit for fuel sensor

### ISSUE THREAD

**Issue by tadamox** [FrSkyRC/ETHOS-Feedback-Community#410] opened 2021-06-06 17:12 UTC
I cannot change unit for Fuel sensor sent by iNav (Id 1B 0600). The only unit available is "Percentage". Please provide mAh and mWh for that sensor. 
X20 with Ethos 1.0.7 Flex, TD-ISRM 2.1.8, R8Pro, Matek405Wing iNav 2.6.1

**Comment by bsongis-frsky** [comment] 2021-06-06 17:15
Why iNAV doesn't use the right sensor?

**Comment by tadamox** [comment] 2021-06-06 17:26
iNav can send values both as a mAh value or Percentage value. I prefer to use mAh. When I set mAh value is sent as power consumption correctly but unit show is %. Rexolution is to set mAh as a unit in Ethos.

**Comment by islandflight** [comment] 2021-06-06 17:54
This is the same issue I have with the YGE esc which reports Mah used to ID 600 but is displayed as %fuel. I tried to explain this in #339.

**Comment by bsongis-frsky** [comment] 2021-06-06 18:26
Consumption sensors should have an appId between 0x0B60 and 0x0B6F

**Comment by Hobby4life** [comment] 2021-06-06 19:07
> This is the same issue I have with the YGE esc which reports Mah used to ID 600 but is displayed as %fuel. I tried to explain this in #339.

Correct, same as for SM Modellbau S32 loggers.
(I prefer to choose the unit myself.)

**Comment by tadamox** [comment] 2021-06-06 19:07
Frsky produces own flight controllers which can be programmed with iNav eg R9|RXSR Pilot. I am pretty sure that it sends consumed power as an id 0600 sensor. Default % as a unit is OK but giving mAh option will do the job.

**Comment by bsongis-frsky** [comment] 2021-06-11 05:58
Duplicate of #459 
We will add DIY sensors with custom ID, unit, ratio, etc.

**Closed by bsongis-frsky** 2021-06-11 05:58 UTC
