### ISSUE TITLE
UI Request - Wrap around for Outputs

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1526] opened 2022-03-09 14:15 UTC
Please can we have wrap around for the Outputs so we can easily get to the high channel numbers?

This is already possible with Model selection, Mixers, LS, SF, Curves so would seem to be consistent. 

Thanks

**Comment by mawzthefinn** [comment] 2022-11-27 17:23
Good idea, however it is also a duplicate of #80 

Closing as a duplicate

**Closed by mawzthefinn** 2022-11-27 17:23 UTC
Labels: duplicate
