### ISSUE TITLE
How can Compile a LUA for ETHOS

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1592] opened 2022-04-08 09:45 UTC
Hello,
is there a way to compile a telemetry LUA to publish it
Thanks Benno

**Comment by mmasch** [comment] 2022-04-08 11:56
Hello Benno. You do not compile LUA. It is "just" a plain text document. 
I do not know how to write a LUA script my self, but I can somewhat modify a existing script.
I see you have found the FrSky Ethos LUA thread at RCGroups. 
https://www.rcgroups.com/forums/showthread.php?4018791-FrSky-ETHOS-Lua-Script-Programming/page25
Here are some LUA examples from this (FrSky Ethos) GitHub page: https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua
Hope this helps :-)

**Comment by Benno00** [comment] 2022-04-08 17:02
Hello,
I know how a script is written, that's why I'm asking how I can protect it against unauthorized changes.
OTX will create a luac then you cannot change this without decompiling. I have written an extensive telemetry script which I want to protect against changes.
Hence my question

**Comment by Benno00** [comment] 2022-04-08 17:14
![Screen](https://user-images.githubusercontent.com/97786547/162490054-e63b5562-aa6c-44c9-84cf-6e76c89eef3f.png)
Here is a Screen from my Script

**Comment by Benno00** [comment] 2022-04-08 17:16
With the script, 15 sensors can be configured, arbitrarily positioned and any fonts and colors can be used.
The 15 sensors can be displayed on 4 screens Digital, Lipo Analog Screen has max. 10 instruments and on Screen 5, as you can see, they can all be displayed together.

**Comment by i3dm** [comment] 2022-04-08 18:06
> With the script, 15 sensors can be configured, arbitrarily positioned and any fonts and colors can be used. The 15 sensors can be displayed on 4 screens Digital, Lipo Analog Screen has max. 10 instruments and on Screen 5, as you can see, they can all be displayed together.

beautiful job, i know how much work that requires!
would love to play with it if you make it available :)

**Comment by Benno00** [comment] 2022-04-09 09:20
Hello, I would like to make it available if I knew how to protect it from changes

**Comment by i3dm** [comment] 2022-04-09 09:55
i think this feature is not available so far

**Comment by Benno00** [comment] 2022-04-09 10:08
It should be possible to write back the LUA that is currently running as LUAC, and publish the LUAC. possibly via a function e.g. write_luac.

**Comment by i3dm** [comment] 2022-04-09 10:12
> It should be possible to write back the LUA that is currently running as LUAC, and publish the LUAC. possibly via a function e.g. write_luac.

there is no luac on ethos

**Comment by Benno00** [comment] 2022-04-27 13:25
Hello Lior,
you can find the script here https://frsky-forum.de/index.php?thread/6344-lua-einbindung-in-ethos/&postID=93631#post93631
Greetings Benno

**Comment by andika207** [comment] 2022-05-14 07:14
@Benno00 that is a private forum and guests don't have access to the download link.

**Comment by Benno00** [comment] 2022-05-21 13:44
@andika207
then sign up

**Comment by andika207** [comment] 2022-05-21 14:26
@Benno00 I have no interest. 
if you want to share something with everybody, either you provide a direct download link or upload it to different server.

**Comment by andika207** [comment] 2022-05-21 14:29
@Benno00 btw what gyro and what ESC and what battery sensors are you using to display all this info on the ETHOS screen menu ?

**Comment by bsongis-frsky** [comment] 2022-06-20 13:56
Duplicate of #1342

**Closed** 2022-06-20 13:56 UTC
