### ISSUE TITLE
1.5.0 RC7 X20 PRO Ext1 + Ext2 swapped?

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3503] opened 2024-02-25 14:32 UTC
On my X20 PRO:
Ext1 is moved on the RIGHT stick, but displayed on the LEFT in the hardware monitor ???
Switch SM is on the left on the stick and also on the left in the hardware monitor - correct.

Ext2 is moved on the LEFT stick, but is updated on the RIGHT in the hardware monitor ???
Switch SN is on the right on the stick and also on the right in the hardware monitor - correct.

On my XE it is like this:
Ext1 is on the left on the stick and on the left in the hardware monitor.
Ext2 is on the right on the stick and on the right in the hardware monitor.

Is it the same on your X20 PRO?
Ext1 + Ext2 work.

Greetings Eugen

**Comment by yak55** [comment] 2024-03-08 10:53
Hello dear Ethos team, I would like to completely recreate my models with 1.5.1.
Before I start, it would be nice to know if there will be a change.

Or should I send the X20Pro in for repair?

Thank you, regards Eugen

**Comment by bsongis-frsky** [comment] 2024-04-03 12:41
Duplicate of #3783

**Closed by bsongis-frsky** 2024-04-03 12:41 UTC
