### ISSUE TITLE
1.5.0 Nightlies X20S - Clone makes Model Invalid Data 

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3145] opened 2023-12-15 08:07 UTC
X20S Flex 1.5.0

Every time I clone a model either new created model or an old model, the result is a model invalid data as soon I try to load in
it seem that is corrupting models created with 1.5.0

**Comment by yufasa** [comment] 2023-12-17 17:01
I did a quick search but failed to find it. 
Thanks for confirming the problem - note however that it is not just cloning, editing also corrupts the model file.
I can restore the model files from backup and use them but I cannot edit or clone them.
This is on a X20S if that makes any difference.

**Comment by bsongis-frsky** [comment] 2023-12-18 08:08
Duplicate of #3149

**Closed by bsongis-frsky** 2023-12-18 08:08 UTC
