### ISSUE TITLE
ISTANT TRIM

### ISSUE THREAD

**Issue by LProia** [FrSkyRC/ETHOS-Feedback-Community#1351] opened 2022-01-15 21:02 UTC
hello, 
I want to ask if it is possible to insert the instant trim. pressing a button to adjust the trims simultaneously. 
Luca X20S ethos 1.0.18 thank you

**Comment by MIKE-DAILEY** [comment] 2022-01-15 21:27
Duplicate of #295

**Closed by MIKE-DAILEY** 2022-01-15 21:27 UTC
