### ISSUE TITLE
Simulator XES switch assignment 1.5.0

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#2472] opened 2023-03-06 08:20 UTC
Simulator XES switch assignment 1.5.0

Assignment is wrong - 

C pressed results in H
D pressed results in E
E pressed results in I
G pressed results in J
H pressed results in K
L pressed results in G

Changing the keyboard layout does not result in an improvement

Greetings Eugen

**Comment by bsongis-frsky** [comment] 2023-03-06 09:18
Only XES ?

**Comment by bsongis-frsky** [comment] 2023-03-06 09:19
I cannot reproduce, I use a french keyboard

**Comment by strgaltdel** [comment] 2023-03-06 10:02
I'm pretty sure that Eugen uses a German keyboard / operating system, as I do.

So I simply installed the XEs Sim and checked the assignment with the help of value widgets and switches:
E,D,H

could **not** find any misbehaviour, mapping was correct

![image](https://user-images.githubusercontent.com/20392683/223077892-2fef97b4-283c-4ab4-923f-ea1f60d9706f.png)

**Comment by yak55** [comment] 2023-03-06 13:49
Hello Udo, please check it again in:
Settings/Hardware/Switches Settings and then test the switches via the Tatstaur of your PC.

Greetings Eugen

**Comment by yak55** [comment] 2023-03-06 18:35
Hello Udo, yes it is adapted, otherwise how will you take over the models from the X20 sensibly into the XE.
The mapping is specially made for this.

Greetings Eugen

**Comment by strgaltdel** [comment] 2023-03-06 19:08
hi Eugen
"yes it is adapted"

that's the "missing link"

without this very important info nobody would be able to determine the problem / root cause with ease

so it seems the sim-keys are connected to the "physical switches" like switch1 etc..
all you want is to get them "connected" to the native FrSky "labels" or whatever they should be named

let's see what Bertrand will say..

regards
udo

**Comment by bsongis-frsky** [comment] 2023-03-06 19:24
Agreed that SA should be SA, not Switch1. But it's true that the issue was not clear enough for me!

**Comment by yak55** [comment] 2023-03-06 20:54
Hello Bertrand, is also not really important.

Just had noticed it when testing - thought it may be useful when 1.5 is released.

Yes, there I had already adjusted my X20 models and nothing written about it.

Sorry, greetings Eugen

**Comment by bsongis-frsky** [comment] 2023-03-07 08:39
Fixed in next nightlies

**Closed** 2023-03-07 08:39 UTC
Labels: bug
