### ISSUE TITLE
1.5.12 If "select model at power on" is set to "on" previous loaded model is lost.

### ISSUE THREAD

**Issue by pmullen503** [FrSkyRC/ETHOS-Feedback-Community#4356] opened 2024-08-08 21:39 UTC
In 1.5.12 if "select model at power on" is selected, the last model loaded is selected by default.  If you try to use it it returns "invalid data". If you then select another model and go back, the previous model disappears.  A .bin file with that name still exists but appears corrupted and can't be loaded even when copied to another transmitter.

This behavior was observed on both my X18 and X20RS.

**Comment by Nicholas-Luoyi** [comment] 2024-08-09 00:17
Duplicate of #4351 

Please continue conversation there

**Closed as not planned** 2024-08-09 00:18 UTC
Labels: duplicate
