### ISSUE TITLE
Sound Problem with X 20 S

### ISSUE THREAD

**Issue by OberlinRC** [FrSkyRC/ETHOS-Feedback-Community#2575] opened 2023-04-10 06:29 UTC
Hi, i have a Problem with  no sound coming out of my X20s. I have programmed alerts on  some switches, like "Thermal, Speed, Hight, Zell Voltage and Vario Sound. 
It happens that after a few flight minutes the Sound is off. No alerts, no vario sound. Nothing at all. After landing and switch the Radio On/Off sound is back on.
It happens approx. every 3 to 5 flights.

**Comment by mawzthefinn** [comment] 2023-04-10 13:16
What firmware? 
Have you tried a different SD card?

**Comment by Tonio62** [comment] 2023-04-10 14:46
> What firmware? Have you tried a different SD card?

Same problem on issues/2567

**Comment by OberlinRC** [comment] 2023-04-10 16:40
FW 1.4.4 EU
SD Card nearly new. Will check another one. 
Under General: audio setting "Standard"

Issue never happens right after start. Takes about 4 to 8 Minutes to occur.

**Comment by chenbevis** [comment] 2023-04-10 18:49
I also have this issue, which occurs approximately once every four flights, and each time it happens, the flight lasts for more than 4 minutes. The problem persists even after replacing the SD card with a new one, and also persists after updating to FCC versions 1.4.5 and 1.4.7.

**Comment by bsongis-frsky** [comment] 2023-04-11 06:51
Interesting. I thought we only have a problem with XE.
Duplicate of #2567

**Closed by bsongis-frsky** 2023-04-11 06:51 UTC
Labels: information needed

**Comment by OberlinRC** [comment] 2023-04-11 13:43
At the German Frsky Forum from Engel there are 2 More Issuses with the X20 reported. Looks like it happens more often to X20 and XE users than expected. 
Hope you can fix it.
