### ISSUE TITLE
Emergency Mode SF-Screeshot 

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#4870] opened 2024-12-13 20:26 UTC
When I tried the special function screenshot today, my radio went straight into emergency mode. 
The screenshot was directly from the special function screen. Unfortunately, I can no longer reproduce it. 

Furthermore, I can only open a snapshot in the file manager, after that I can no longer see anything in the preview.

Radio x20pro , Ethos 1.5.19

**Comment by bsongis** [comment] 2024-12-16 11:12
> Furthermore, I can only open a snapshot in the file manager, after that I can no longer see anything in the preview.

I don't understand what you mean?

**Comment by WhiskeyGolf** [comment] 2024-12-16 12:18
Do you just not understand the last part, or the whole issue?
 In the preview on the RX I can no longer see a screenshot after I have opened an image. Maybe the RAM is full after one image?

**Comment by WhiskeyGolf** [comment] 2024-12-16 12:20
![AC9DF11D-C608-4A25-9A7C-D3B84298BE81](https://github.com/user-attachments/assets/0eec6be7-3cb4-410b-94c7-110909ec89f5)
![78356F07-E0D1-4C08-878E-5B34B8604957](https://github.com/user-attachments/assets/62b414b6-f0b4-4ba7-8c2e-6e6422078dd9)
![E2D8A4E8-CD9D-49A9-BCB8-B7D6B7AB377D](https://github.com/user-attachments/assets/cdfac818-ab24-49e1-adb8-0ad509fd994d)

**Comment by WhiskeyGolf** [comment] 2024-12-16 12:21
I hope the photos describe it a little better

**Comment by bsongis** [comment] 2024-12-16 13:49
Yes, it's better!

**Comment by bsongis** [comment] 2024-12-16 14:04
I cannot reproduce this problem. And I wonder how much RAM left you have ... which could explain the screenshot issue! I will try to do a screenshot with very little RAM available, perhaps the issue is there!

**Comment by WhiskeyGolf** [comment] 2024-12-16 14:29
In this model I also noticed that the ModelBitmap is sometimes not shown ( on the first screen )

**Comment by bsongis** [comment] 2024-12-16 14:32
Yes, I can reproduce it! There is indeed a bug which has never been catched. It happens with low memory, when it is impossible to do a screenshot because not enough RAM available.

I will fix it in Ethos 1.6.0 before the release. But I still suggest that you understand why you have so little RAM available. Any Lua script which eats too much?

**Comment by bsongis-frsky** [comment] 2024-12-16 15:24
Fixed in 1.6.0 RC9

**Closed as completed by bsongis-frsky** 2024-12-16 15:24 UTC

**Comment by WhiskeyGolf** [comment] 2024-12-16 17:16
In this model I use 2x AdvGauge and the latest Xicoy Turbine widget. 
Unfortunately you can't see how much RAM is being used. 
Is this problem responsible for everything? (EM, preview, missing ModelBitmap). 
I have the feeling that in the model, when Airspeed Callouts are made, other callouts suddenly appear completely randomly that are not selected. 
Maybe all the same problem?

**Comment by bsongis** [comment] 2024-12-16 18:11
Yes it is the addition of all the problems
1. Too much RAM used. Indeed we need a way to check that, easily, on a per-script basis! This is another request to open ;)
2. Preview = not a bug, the bitmap is not displayed, but I do agree that an warning would be very useful here
3. Missing Model Bitmap = same problem, the code is well protected, but we again need a warning like 2.
4. Screenshot = bug, the code was not protected when the bitmap could not be allocated - fixed in 1.6.0 RC9

It remains the way you have programmed your NFC Switch, which is not good. I have to come to you with a better proposal

**Comment by WhiskeyGolf** [comment] 2024-12-16 19:53
I tested the preview on a new, empty model without any LUAs. The small icons work better here, but when you open a screenshot the preview no longer works. Does that mean that the RAM is full again? It seems that the RAM in Ethos fills up after a while and nothing is released again, which means that you can always easily run into EMs that you haven't tested before. No matter how many LUAs you use. I'm really not an expert, but I have the feeling that a full RAM in Ethos leads to many known problems. Thank you so far !

**Comment by bsongis** [comment] 2024-12-16 19:56
Would you rename your directory 'scripts' to '_scripts', to ensure nothing is loaded (it's possible to use RAM even if nothing is displayed, Lua can do a lot, and can also eat a lot!)

**Comment by WhiskeyGolf** [comment] 2024-12-17 11:28
In fact, the preview works as it should if I change scriptz to _scripts

**Comment by WhiskeyGolf** [comment] 2024-12-17 11:29
But which script can fill the RAM like that without obviously being used?

**Comment by bsongis** [comment] 2024-12-17 13:17
I will return the question to you ;)
Would you add the scripts inside the 'scripts' directory, one by one?
You will discover the one which eats too much!

**Comment by bsongis-frsky** [comment] 2024-12-17 16:07
![screenshot-2000-02-12-54661](https://github.com/user-attachments/assets/342e23f2-09b5-481e-82aa-b4b83e3b9e64)

**Comment by bsongis-frsky** [comment] 2024-12-17 16:08
This will help you in future versions!

**Comment by bsongis-frsky** [comment] 2024-12-17 16:17
![screenshot-2000-02-12-55463](https://github.com/user-attachments/assets/dab3106b-dc68-4955-8680-a8514b9372e2)

**Comment by bsongis-frsky** [comment] 2024-12-17 16:19
One screenshot needs 800x480x2 = 768K available!
This is why this function will be the first one to fail if you are missing RAM

**Comment by WhiskeyGolf** [comment] 2024-12-17 20:40
That looks very practical. I hope to see it soon. I'll have a look tomorrow to see which Luas are causing the problems.

**Comment by WhiskeyGolf** [comment] 2024-12-17 20:46
Unfortunately, I discovered a new problem on the same model today. I don't know if it's related to the same problem. 
As soon as I start the engine (which also activates WriteLogs), some XACT servos show me abnormal values. 
If there is no connection, I'll open a new issue.

**Comment by bsongis** [comment] 2024-12-17 20:49
I am afraid it is not related!
Tomorrow in Ethos 1.6.0 RC10 you will have the "RAM available" feature

**Comment by WhiskeyGolf** [comment] 2024-12-17 20:51
![8BB0C6B2-9B02-41E2-A816-1D8A2C3E1E6F](https://github.com/user-attachments/assets/cd1f920c-ebad-4f33-a5d8-384f7a48f8f7)

**Comment by bsongis-frsky** [comment] 2024-12-17 20:54
It is hot!

**Comment by bsongis-frsky** [comment] 2024-12-17 20:55
Unless you are in Groenland and Ethos has a bug displaying negative values?

**Comment by bsongis-frsky** [comment] 2024-12-17 20:55
252°C would mean -4°C ?

**Comment by bsongis-frsky** [comment] 2024-12-17 20:56
You are using which release?

**Comment by WhiskeyGolf** [comment] 2024-12-17 21:02
I use ETHOS 1.5.19 ( Last stable ) and latest FW on Servos .

**Comment by bsongis-frsky** [comment] 2024-12-17 21:06
And you are testing with negative temperatures?

**Comment by WhiskeyGolf** [comment] 2024-12-17 21:19
Unfortunately I don't live in Greenland, today it was 7° Celsius.

**Comment by WhiskeyGolf** [comment] 2024-12-17 21:38
Unfortunately, you can't edit every telemetry value to make it positive again. But there must be a problem with the interpretation of Ethos, because otherwise the servo wouldn't show the status OK at 250°C, right?

**Comment by bsongis** [comment] 2024-12-17 21:47
This status is always "OK". It is removed in Ethos 1.6.0, because not very useful.

**Comment by bsongis** [comment] 2024-12-17 21:48
In Ethos 1.6.0 RC10 I have just written a small modification to allow negative temperatures...

**Comment by WhiskeyGolf** [comment] 2024-12-18 13:00
In warm environments the value seems to be positive again. It is probably the same problem as in the issue #70 on RF_Group which unfortunately no one has responded to yet. My temperature values ​​also differ by easily 20°C from the start. This can then lead to a negative reading for some servos. It would be really helpful if you could adjust the ratio of the telemetry data, like with the voltage.

**Comment by bsongis-frsky** [comment] 2024-12-18 13:10
OK. Then the negative temperature is fixed in Ethos 1.6.0 RC10.
The difference problem (by 20°C) is not from Ethos. Ethos just displays what the telemetry reports!
Agreed for the Temperature offset. You may open another issue for it, I will implement ASAP

**Comment by WhiskeyGolf** [comment] 2024-12-18 13:22
Okay, thank you very much! I'll create a new issue. Would it be possible to implement this for all sensors (except RSSI and VFR)?

**Comment by WhiskeyGolf** [comment] 2024-12-19 16:52
> I will return the question to you ;)
> Would you add the scripts inside the 'scripts' directory, one by one?
> You will discover the one which eats too much!

Actually, the LUAs that use up the most memory in Standby are the TD-TW 3.0.0 tools and the Xicoy widget. I wonder why the Xicoy widget uses RAM without being selected.
