### ISSUE TITLE
FRSKY X20HD Video component V2 issue

### ISSUE THREAD

**Issue by austinpowers1977** [FrSkyRC/ETHOS-Feedback-Community#3033] opened 2023-11-06 15:23 UTC
hi i have a issue with the X20HD handset. tried to update it to V2 as it was showing as a blank in the ethos suite. Thought i had updated it but i now have a black screen. I have followed others way of getting this sorted but i can not get it to update at all. I go into bootloader (black screen) and download then flash the V2 component leave it to update but the lights dont flash to indicate its updated. Its mean to beep to say its updated but nothing changes. 

Can someone from FRsky sort this issue. Ive had this handset for a few months and cant resolve this at all. I only wanted to update so i can use the OSD feature on betaflight!

**Comment by mawzthefinn** [comment] 2023-11-06 15:36
Duplicate of your previous issue #3023, Please continue discussion under that issue

**Closed by mawzthefinn** 2023-11-06 15:36 UTC
Labels: duplicate

**Comment by austinpowers1977** [comment] 2023-11-06 15:43
i need FRSKY to help this is why ive opened a new issue!

**Comment by mawzthefinn** [comment] 2023-11-06 15:50
You already had an FrSky engineer respond to you in your initial issue. Opening additional issues just clutters things up and will actually slow receiving support.

If you need a faster response, I would encourage you to reach out to FrSky support directly.

**Comment by bsongis-frsky** [comment] 2023-11-06 17:52
@austinpowers1977 The team in China is sleeping now. I will try to ask for help tomorrow morning. No need to be rude, it won't help!

**Comment by austinpowers1977** [comment] 2023-11-06 18:02
I am sick of frsky not coz of lack of response. It's lack or respect. Being
ignored when I make a point of how bad things are. The lack of structure of
files and not being able to get 2 matching firmwares for freestyle v2
mobula and X20HD. It should be this difficult!
