### ISSUE TITLE
Bug on 1.5.15: all buttons inoperative when powering up the radio with a confirmation logical switch + default checklist active

### ISSUE THREAD

**Issue by neuhausj** [FrSkyRC/ETHOS-Feedback-Community#4596] opened 2024-10-02 19:27 UTC
Hello,
This bug is easily reproductible: 

* Create a logical switch with "Confirmation before active" set
<img width="352" alt="image" src="https://github.com/user-attachments/assets/927737ed-7fc8-440a-a99f-87324a20b701">

* Power down the radio with the switch in position
* When the checklist and confirmation appears, put the switch back to position 0
* press yes or no on the confirmation window > all buttons+wheel will be locked

Only way to get buttons working is to reboot the transmitter

Here a video of the issue:
https://www.youtube.com/shorts/72qorowFHi8

**Comment by bsongis-frsky** [comment] 2024-10-17 10:10
Duplicate of #4352

**Comment by bsongis-frsky** [comment] 2024-10-17 10:20
I cannot reproduce it anymore in 1.5.16/1.5.17

**Closed as completed by bsongis-frsky** 2024-10-17 10:20 UTC
