### ISSUE TITLE
Add Ability to move/organize/re-arrange Models in Model Manager

### ISSUE THREAD

**Issue by plesogor** [FrSkyRC/ETHOS-Feedback-Community#4677] opened 2024-10-29 15:24 UTC
Add Ability to move/organize/re-arrange Models in ETHOS Model Manager

**Comment by plesogor** [comment] 2024-10-29 15:26
some drag and drop move models, or right touch hold / up\down left/right move models, or move mostly recently used top 5 models to the first row for examples.

Add some nesting structure for model types / folder structure. Airplanes / Helicopters / Drones / Other ..  

Main page shows a "Model Type" and then Models which are able to be re-arranged and/or allow top 5 recent models on first row.

Just some ideas that I think might be useful.

**Comment by mawzthefinn** [comment] 2024-10-29 19:19
Duplicate of #3060 

Please continue discussion there

**Closed as not planned by mawzthefinn** 2024-10-29 19:19 UTC
Labels: duplicate
