### ISSUE TITLE
[Archer X] OTA FW update not possible in ETHOS 1.5.8

### ISSUE THREAD

**Issue by joy2417** [FrSkyRC/ETHOS-Feedback-Community#4050] opened 2024-05-19 20:12 UTC
For some FW files the option for flashing receivers OTA is not available any more.

Archer-X_2.1.14.frsk no OTA flashing possible.
AP_RS_1.0.9.frsk the OTA option is there.

Renaming the files does not help.

**Comment by strgaltdel** [comment] 2024-05-19 20:32
Hi Lutz,
i am right, you are using x18s and x14s?
did you try both transmitters ?

regards Udo

**Comment by MikeActron** [comment] 2024-05-20 06:53
It's the same for me. I use an X18 with version 1.5.8. 
I am also missing the menu items "Flash Rx by int. OTA" and "Flash Rx by ext. OTA"

Regards Mike

![IMG_20240520_082928](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116504700/8218f649-c638-4878-aeee-e2c81fa656bd)

**Comment by joy2417** [comment] 2024-05-20 09:51
I've tested with the X18S and X14S. They show the same behaviour.

Archer-X_2.1.14.frsk no OTA flashing possible.
AP_RS_1.0.9.frsk the OTA option is there.

Maybe some problems with checksums?

**Comment by ftc2629** [comment] 2024-05-20 16:07
OTA Update for RX Archer R8pro was not working since Ethos version 1.5.3. Had to update this receiver via cable.

**Comment by bsongis-frsky** [comment] 2024-05-21 12:59
@Nicholas-Luoyi "Archer X" is marked as hidden, which means it is not known by Ethos. I wonder why.

**Comment by joy2417** [comment] 2024-05-21 13:28
For the older Archer RS (not plus) the OTA option is missing too

**Comment by bsongis** [comment] 2024-05-21 13:34
Interesting ... @Nicholas-Luoyi Archer RS (not plus) is not in the list (so it doesn't exist)!

**Comment by ghost** [comment] 2024-05-22 00:04
Confirmed same issue on X20s, Archer-X_2.1.14.frsk attempting to update archer GR8, ethos 1.5.8

**Comment by bsongis-frsky** [comment] 2024-05-22 06:42
Mike says it's the same with "Archer R8 PRO" too.

**Closed as completed** 2024-05-22 09:31 UTC
