### ISSUE TITLE
When you edit one curve it  doesn't show the position of the stick

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#812] opened 2021-08-18 16:30 UTC
https://user-images.githubusercontent.com/87758703/129935414-868441b2-ae08-4781-a4a0-81895e25e6b0.mp4

It would be interesting if it showed the position of the stick when we are adjusting a model

**Comment by mawzthefinn** [comment] 2021-08-18 17:41
Agreed, that would be VERY valuable add. Spektrum has this on their Curve editor and it's really useful.

**Comment by df7320** [comment] 2021-08-19 01:08
Finally,  a duplicate of issue #24.

**Comment by andreavi90** [comment] 2021-11-26 17:13
Any news? It's very difficult to setup correctly a servo travel without this function...Thank you

**Comment by jasalca** [comment] 2021-11-26 18:53
No news yet, I hope they include it soon because setting up a curve for helicopter is more complicated without this function.

**Comment by jasalca** [comment] 2021-11-26 18:54
It would also be interesting to have direct access to the curves with a long press on the menu buttons

**Comment by andreavi90** [comment] 2021-12-20 06:56
Please fix this problem...it's impossible to setup correctly a plane/Heli, without the position of the curve...

**Comment by andreavi90** [comment] 2022-03-22 22:44
Any news?

**Comment by mawzthefinn** [comment] 2022-11-15 01:46
Duplicate of #24, please continue any discussion on that issue

**Closed by mawzthefinn** 2022-11-15 01:46 UTC
