### ISSUE TITLE
Bug with Failsafe - TWR6 / TWGR6

### ISSUE THREAD

**Issue by arshish1612** [FrSkyRC/ETHOS-Feedback-Community#2788] opened 2023-07-31 02:41 UTC
There may be a possible Bug with FS: https://youtu.be/MTEYkdGwHpo

X20S: ETHOS 1.4.9
Twin Lite Pro: v1.0.4
TWR6: v1.0.4

Failsafe does not trigger in certain scenarios as indicated in the video.

**Comment by arshish1612** [comment] 2023-07-31 14:48
Now we have 2 other people confirming the same thing...

1. https://www.rcgroups.com/forums/showpost.php?p=51300699&postcount=800
2. https://www.rcgroups.com/forums/showpost.php?p=51301651&postcount=802

**Comment by arshish1612** [comment] 2023-07-31 17:43
And one more user reported the same issue. So now 3 users in addition to me have reported this:

https://www.rcgroups.com/forums/showpost.php?p=51302361&postcount=803

**Comment by bsongis-frsky** [comment] 2023-07-31 18:59
It's very strange that it depends on the previous stick position!
Do you wait 10 seconds after the transmitter is ON? 
Because the failsafe positions are sent every 10 seconds.

**Comment by bsongis-frsky** [comment] 2023-07-31 18:59
Does anybody reproduce this problem on other receivers?

**Comment by mawzthefinn** [comment] 2023-07-31 19:19
One person has confirmed they are unable to duplicate on the TW GR8. It appears to be TW R6/GR6 only at this point.

**Comment by arshish1612** [comment] 2023-08-01 03:27
> 

Do you have to wait 10S every time the TX starts? Or only after making any changes to the FS settings? No I did not wait 10S every time the TX was started.

In any case this is very intermittent. I have one TWR6 where the FS does not work at all.. not even the First time regardless of how long I wait. I can take a video of that one if you like.

**Comment by bsongis-frsky** [comment] 2023-08-01 09:41
Normally no the failsafe are sent when the first telemetry frame is received, but just in case I would wait for 10 seconds. In the video the failsafe is KO after far more than 10 seconds I think.

**Comment by arshish1612** [comment] 2023-08-01 16:19
I just have been trying to take another video and I am unable to replicate the issue now.... I did exactly the same thing and infact waited for 10 seconds ONLY on the first instance. Basically the exact same test I sis yesterday and the FS is working.

Ill keep trying...



The 2nd receiver I had a problem with had an older FW version so updating it brought the behaviour in sync with the others so thats not an issue.

**Comment by arshish1612** [comment] 2023-08-01 16:44
Some absolutely crazy results.. The new video I've taken shows that the issue I am facing is not related to the 10 second wait. As long as I do not touch the throttle the FS works even under 10 seconds on subsequent attempts. However once I touch the throttle the FS stops working until I disconnect the battery and reconnect it. Once this state is reached, even after waiting 10 seconds for subsequent attempts the FS does not start working again until you disconnect  reconnect the battery. Hope this video helps narrow down the root cause.

https://youtu.be/Au59NzbmKOw

**Comment by bsongis-frsky** [comment] 2023-08-01 17:10
In fact the FS is sent to the module / receiver from Ethos:
- on module start (after each model load)
- when a failsafe setting is changed
- every 10s under normal conditions (this is why I suggested you wait for those 10s, because I am sure they are sent)
I forward this issue to the RF team

**Comment by arshish1612** [comment] 2023-08-01 17:11
Ill take the same Video with the 10 Second wait

**Comment by arshish1612** [comment] 2023-08-01 17:21
Here you go...

And another video now incorporating a wait of more than 10 seconds with the same issue. Apologies about the bad camera angle and video this time as I did not have any one to hold the camera for me. I show the TX Screen for the last test though.

https://www.youtube.com/watch?v=ISGerydodY0

@bsongis-frsky @mawzthefinn

**Comment by arshish1612** [comment] 2023-08-01 17:25
let me know if I need to test differently again....

**Comment by arshish1612** [comment] 2023-08-02 15:23
Can we remove the Awaiting Information tag and change it to Bug now?

**Comment by arshish1612** [comment] 2023-08-04 02:34
Update - Ive been provided a test FW for the TWIN Lite Pro module by the RF team. I have tested last night and it looks good. I am unable to reproduce the issue with the new firmware. I guess it will be uploaded to the website soon

**Comment by mawzthefinn** [comment] 2023-10-16 19:39
Closing off, TWLP Firmware 1.0.5 and TW-ISRM firmware 1.0.5 released with the fix on Sept 11

**Closed by mawzthefinn** 2023-10-16 19:39 UTC
Labels: bug, RF issue
