### ISSUE TITLE
(Feature Request) Special Function to switch pages

### ISSUE THREAD

**Issue by craigywsm** [FrSkyRC/ETHOS-Feedback-Community#2475] opened 2023-03-06 16:56 UTC
Could there be a special function option to scroll to the next page(s).
e.g. 
With multiple pages setup 
Page 1 having alot of sensors listed
Page 2 having Zavionics Lua Turbine telemetry 

Then the buttons on the back of the radio could navigate back and fourth between the pages

**Comment by mawzthefinn** [comment] 2023-03-06 17:29
This is a duplicate of #652 

Please continue discussion under that issue.

**Closed by mawzthefinn** 2023-03-06 17:29 UTC
Labels: duplicate

**Comment by craigywsm** [comment] 2023-03-06 17:32
Sorry @mawzthefinn I did try to find a ticket already open. Thank You
