### ISSUE TITLE
Telemetry for all receivers

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#275] opened 2021-05-19 07:50 UTC
Several customers wish to get the Telemetry ( RSSI, VFR, RxBt) for all receivers. In the moment we got it only for the "activ" 2.4 GHz reciver.

 I think that this is an important and meaningful expansion.

At the moment I don't understand why only the values of the active 2.4 GHz receiver are displayed under Telemetry. While the Range Test at least shows RSSI and VFR for the active 2.4 GHz receiver and the 868 MHz receiver.

**Comment by bsongis-frsky** [comment] 2021-05-19 08:06
Duplicate of #251

**Closed by bsongis-frsky** 2021-05-19 08:06 UTC
