### ISSUE TITLE
Slow up / down

### ISSUE THREAD

**Issue by seilfly** [FrSkyRC/ETHOS-Feedback-Community#909] opened 2021-09-06 09:15 UTC
Wish it was possible to set slowly up / down in **Flight Mode** as well as there is in some other menus !

**Comment by i3dm** [comment] 2021-09-07 04:33
yes this is a very useful function

**Comment by seilfly** [comment] 2021-09-08 06:04
Hope someone can do a job to fix this

**Comment by Sudar-ch** [comment] 2021-09-08 11:05
absolut necessary! Would be great to see it in the next releases!

**Comment by Njerre** [comment] 2021-09-08 18:14
I'm having the same problem,
have butterfly mix, and want to set my flaps and ailerons with a delay! 
But nowhere can you choose this option, not in the curves, or mixers. 
Only in the menu of the outputs. But don't think this is the right place! 
I would rather expect this in the mixers or inputs!
If I choose delay on flaps or ailerons in the exits, it is always the case during a normal flight. 
Good for a gear door, but not in my option
So I don't see an immediate solution.
Does anyone do that? or is this a problem?
Greeting

**Comment by Hobby4life** [comment] 2021-09-08 18:23
This has been a request almost from day one, stil not knowing why this is not implemented yet.
I rather seen this fixed/added then adding new features at the moment.

**Comment by seilfly** [comment] 2021-09-08 20:19
> I'm having the same problem,
> have butterfly mix, and want to set my flaps and ailerons with a delay!
> But nowhere can you choose this option, not in the curves, or mixers.
> Only in the menu of the outputs. But don't think this is the right place!
> I would rather expect this in the mixers or inputs!
> If I choose delay on flaps or ailerons in the exits, it is always the case during a normal flight. of course it is the last option.
> Good for a gear door, but not in my option
> So I don't see an immediate solution.
> Does anyone do that? or is this a problem?
> Greeting

Assume that you, like me, mean a menu button where you can adjust slowly up and slowly down !
Greatings

**Comment by bsongis-frsky** [comment] 2021-09-09 05:56
Duplicate of #903

**Closed by bsongis-frsky** 2021-09-09 05:56 UTC
