### ISSUE TITLE
Timer control by means of gas

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#1785] opened 2022-07-07 09:24 UTC
Hello,
Recently, the stopwatch with Throttle % control is no longer controlled by the gas channel, but by the gas mixer. The consequence of this is now that this stopwatch cannot be controlled from any other source. I use e.g. the control of the timer "engine run time" in the same model by means of log. Switch and slow automatic start-up, then control by throttle stick and a 3-step switch during landing. This does not work now, as this is realized by means of several free mixers.
Is there any way to move this type of timer control back to the throttle channel?

Thanks for the time.

**Comment by hrenz** [comment] 2022-07-13 09:25
This change was not good, 
it should stay with the gas channel
or be immediately available open

**Comment by pstasek** [comment] 2022-07-18 12:10
I believe the Throttle% timer in Ethos was never controlled by a channel output but the stick. Controlling by a mix is a step further, but the problem with the channel output is, it may sometimes be reversed, so it would need to be from the channel output before the output processing (without endpoints and reverses)

**Comment by Wolepo** [comment] 2022-07-19 08:43
And if you now had the possibility to select the source: Gas duct or gas mixer. I don't know any flight controller whose channel input doesn't work from -100% to +100%. This is independent of the control type of the gas stick.

**Comment by mawzthefinn** [comment] 2022-11-27 16:34
@pstasek is correct, the trigger was moved from stick to mixer to correct issues like #207

**Comment by Wolepo** [comment] 2022-11-27 17:09
I don't really see the point. If the gas channel in the gas mixer should be controlled from 0 to+100% (which is not the rule), then one must be able to offer the controller, i.e. the gas channel the range between -100% and +100%. If the timer control is then on the gas channel, it is again universally applicable.

**Comment by mawzthefinn** [comment] 2022-11-27 18:10
Regardless of what the current state is, there should be selectable sources for the canned Throttle timer activations.

That request is under #654 and this is a duplicate of it in terms of the needed fix. Closing this issue off, please continue the discussion there as this does need to get addressed.

**Closed by mawzthefinn** 2022-11-27 18:10 UTC
Labels: duplicate
