### ISSUE TITLE
Allow to select channel numbers in the Model Wizard.  

### ISSUE THREAD

**Issue by MeniLew** [FrSkyRC/ETHOS-Feedback-Community#531] opened 2021-06-23 11:14 UTC
Hello,
 in Wizard setting up the model you can choose the number of channels for each servo but you can not choose the location of the channels, it is frustrating because you then have to go to the mixer and start crossing between them.  When it comes to an airplane with a lot of electronics it's really frustrating.  Is it possible to change so that it will be possible to choose not only the number of channels but also their location?  
Thanks

I use x20s with Athos version 1.0.9 fcc

**Comment by Hobby4life** [comment] 2021-06-23 11:36
Already discussed in many issues.
Dev team is on it.

**Comment by bsongis-frsky** [comment] 2021-06-23 14:39
Duplicate of #165

**Closed by bsongis-frsky** 2021-06-23 14:39 UTC
