### ISSUE TITLE
EMERGENCY MODE

### ISSUE THREAD

**Issue by afdofdez** [FrSkyRC/ETHOS-Feedback-Community#3497] opened 2024-02-24 09:52 UTC
When you turn on the radio in model selection mode the first time after updating the RC6 and RC7 version, when you select the aircraft model, the radio goes into emergency mode and you have to turn it off to exit this mode.

X18SE Tandem Transmitter with Ethos 1.5.0 RC6/RC7

**Comment by strgaltdel** [comment] 2024-02-24 11:05
hi, 
just another end user report:

updated my x18se (rc6 >rc7) via filecopy of firmware.bin into root

had no problems to switch between models

**Comment by bsongis-frsky** [comment] 2024-02-26 08:29
Can you reproduce it? Any additional info will be interesting!

**Comment by bsongis-frsky** [comment] 2024-02-26 11:34
@afdofdez Have you kept a copy of your models? Perhaps they are older? There is no data conversion from RC6 to RC7!

**Comment by bsongis-frsky** [comment] 2024-02-26 14:58
I tried the procedure you described above and I really cannot reproduce it. Have you kept a copy of your radio.bin and model used? Perhaps you have some global function?

**Comment by afdofdez** [comment] 2024-02-26 15:45
ONLY radio.bin and model

 

De: ***@***.*** ***@***.***> 
Enviado el: lunes, 26 de febrero de 2024 16:41
Para: 'FrSkyRC/ETHOS-Feedback-Community' ***@***.***>; 'FrSkyRC/ETHOS-Feedback-Community' ***@***.***>
CC: 'Mention' ***@***.***>
Asunto: RE: [FrSkyRC/ETHOS-Feedback-Community] EMERGENCY MODE (Issue #3497)

 

Attached is a complete backup of my Tandem X18SE radio with Ethos 1.4.17 before upgrading to version 1.5.0 RC6.

 

The model you select and produced EMERGENCY MODE is Extra 300EXP.

 

De: Bertrand Songis @ FrSky ***@***.*** ***@***.***> > 
Enviado el: lunes, 26 de febrero de 2024 15:59
Para: FrSkyRC/ETHOS-Feedback-Community ***@***.*** ***@***.***> >
CC: Fernando Fernández ***@***.*** ***@***.***> >; Mention ***@***.*** ***@***.***> >
Asunto: Re: [FrSkyRC/ETHOS-Feedback-Community] EMERGENCY MODE (Issue #3497)

 

I tried the procedure you described above and I really cannot reproduce it. Have you kept a copy of your radio.bin and model used? Perhaps you have some global function?

**Comment by bsongis-frsky** [comment] 2024-02-26 15:48
I see you have attached some files to your email, but github doesn't keep attachments, you have to upload them on their interface directly. Would you please do it so that I can have another couple of tests with your real data?

**Comment by afdofdez** [comment] 2024-02-26 18:29
[modrad.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14409300/modrad.zip)

Contains radio.bin and the extra300exp model

**Comment by ilioSS53** [comment] 2024-03-02 22:37
Hello ,
Today upgraded to 1.5.0  x20s
Made new model with archer sr10plus.
For fixed wing with flaps on one channel 6
During programming the transmitter switched to emergency mode.
This was again happening so structural.
My steps mixer chanel 6 flaps
                  Vieuw per channel
                 Flaps channel
                Flaps add
               Table vieuw     Oeps in emergency mode.

Also my sounds not available. Looks the old folder is no longer where the souns will be taken from.

Hope this helps to solve the emergency mode hick-up.
Regards Theo

**Comment by ilioSS53** [comment] 2024-03-03 21:12
The above set-up for a Tundra after the selftest the receiver lost channels function apart from the throttle.
So the servos moved rapidly came to a standstill. No more posdible to steer the servo,s.
Made a new model register and bind no succes.
So the receiver can register,bi d control the channel 3 throttle. For the rest of the channels no control possible.
Bottom line it cost me a receiver from 70 euro.
Very disapointted.

**Comment by bsongis-frsky** [comment] 2024-03-03 21:23
@afdofdez is it possible that your problem is linked to #3545?

**Comment by bsongis-frsky** [comment] 2024-03-03 21:23
@ilioSS53 from your description it IS linked to #3545
I don't get how it could cost you a receiver, this is something different, no?

**Comment by ilioSS53** [comment] 2024-03-03 21:26
I will send the receiver for analises no problem. Realy nearly everything I treid no succes.
Kind regards,
Theo

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment] 2024-03-03 21:39
OK, but it has nothing to see with this issue, right?

**Comment by ilioSS53** [comment] 2024-03-03 21:42
If you mean emergency mode. Correct.
The receiver should be a new issue you are right.
I will make one.
Kind regards,
Theo

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment] 2024-03-03 21:44
Yes, thanks, because the EM is already something. I will be happy to forward the other one, I have enough with mine ;)

**Comment by bsongis-frsky** [comment] 2024-06-03 07:48
This EM on Model Select has been fixed in the latest release. It was a Watchdog Timeout which was not big enough.

**Closed by bsongis-frsky** 2024-06-03 07:48 UTC
Labels: information needed
