### ISSUE TITLE
Ethos suite missing spanish languaje

### ISSUE THREAD

**Issue by Luznatural** [FrSkyRC/ETHOS-Feedback-Community#2241] opened 2022-12-23 17:43 UTC
Ethos suite settings (v1.4.4 and v1.4.5) does not allow for selecting Spanish languaje.

**Comment by bsongis-frsky** [comment] 2022-12-24 07:33
![image](https://user-images.githubusercontent.com/50834778/209426054-a249166f-ec9b-4871-bf52-dba7c3112448.png)

**Comment by bsongis-frsky** [comment] 2022-12-24 07:34
Because nobody translated it!

**Comment by bsongis-frsky** [comment] 2022-12-24 07:47
https://github.com/FrSkyRC/ETHOS-Feedback-Community/wiki/Ethos-Suite-localization

**Comment by Luznatural** [comment] 2022-12-24 08:51
If you send me the files in English, I will do it

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Luznatural** [comment] 2022-12-24 17:05
Good Afternoon Bsongis,
Thanks for the clues to update the file.
Please, find attached the file containing the translation of ETHOS Suite v 1.4.5 for ESPAÑOL languaje.
I double checked it several times, but I couldn't test it on the Suite properly as version 1.4.5 does not allow me to select ESPAÑOL as it does not have the option, despite the fact that I included the file in the correct folder in my computer and re-started the program.
[Es.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10298927/Es.zip)
I hope you might be able to include it in the release version of Ethos Suite v1.4.5
Best regards and Merry Christmas

**Comment by Luznatural** [comment] 2022-12-26 02:22
I have performed the following tests with Ethos 1.4.4, realted to this issue:

- I checked that the version of Visual Studio Code that I used for editting the file I sent you (v1.74.2) is writing the file in UTF-8 format.
- I changed the name of my file Es.json to any other existing languaje (I tried with german, changing the name of the file to de.json) and copied it to the directory  frsky\Ethos suite\i18n
- Tried selecting German languaje, and restarting the Suite made no effect. The suite continued appearing in the original German languaje.
- I tried with some other languajes with the same effect.
- I tried changing just a paragraph in the original de.json file, also without effect. Ethos continued with the original German translation.
- In fact, if you delete all the files from the i18n directory, Ethos suite continues working perfectly, and you are able to select the different languajes without problem.

Conclussions:
- The process described in the github to produce your own translations appears no longer to be valid, as you are not able to modify the translations when you try.
- The languajes in Ethos Suite appear to be coded in the program itself, and not accessing the list of files in the i18n directory.
- ESPAÑOL (Spanish) does not appear in the list of languajes to select in Ethos settings.
- This issue appears not to be related only to translation.

I offer myself to produce any necessary translation from English to Spanish in order to get ESPAÑOL in the program.
Best regards

**Comment by bsongis-frsky** [comment] 2022-12-27 10:11
As written in the release note, this feature has been added to 1.4.5, not 1.4.4!
Your file will be included in 1.4.5

**Comment by bsongis-frsky** [comment] 2022-12-27 10:11
![image](https://user-images.githubusercontent.com/50834778/209651011-59658663-3e95-4340-881f-5e584560b8c3.png)

**Closed by bsongis-frsky** 2022-12-27 10:11 UTC
Labels: translations

**Comment by Luznatural** [comment] 2023-01-02 05:41
Dear bsongis-frsky,
Please find attached an update of the translation to Spanish of Ethos Suite. Changes are:
- Adjusted for phrases to appear correctly in the allocated space in the menus
- Fine-tuned translations to beter understanding
- Corrected the spacing between phrases and interrogation/exclamation simbols.
[es.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10330142/es.zip)
Best regards

**Comment by Luznatural** [comment] 2023-01-18 20:19
Dear Bsongis-frsky,
Please, find attached the [ES]X20 and Ethos user manual v1.4.6 Rev 0 (initial revision) in pdf format.
I kindly request you to publish it in Github. 
[[ES] X20 and Ethos user Manual_1.4.6_rev0.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10450358/ES.X20.and.Ethos.user.Manual_1.4.6_rev0.pdf)
Best Regards

**Comment by bsongis-frsky** [comment] 2023-01-18 20:53
Thanks, I am uploading it right now

**Comment by Luznatural** [comment] 2023-01-29 07:42
Dear Bsongis-frsky,
For your information, the manual included in the link https://github.com/FrSkyRC/ETHOS-Feedback-Community/blob/main/doc/%5BPB%5D%20X20%20and%20Ethos%20User%20Manual_1.0_rev0.pdf is described in the notes as Spanish Languaje manual, when in reality is a Portuguesian Manual.
I kindly request you to modify the note.
Thanks in advance

**Comment by bsongis-frsky** [comment] 2023-01-30 08:28
Done

**Comment by Luznatural** [comment] 2023-01-31 17:13
Apparently the change has not been effective, as the note continues saying Spanish Languaje Manual, when it should read Portuguese-Brasilian Manual.
Sorry!!!

**Comment by bsongis-frsky** [comment] 2023-02-01 22:02
I have changed the first page of this repository

![image](https://user-images.githubusercontent.com/50834778/216173480-bec1aba5-e099-42c0-bf01-b37256c91145.png)


But you mean the problem is in Ethos Suite?

**Comment by Nicholas-Luoyi** [comment] 2023-02-02 02:39
Do you mean the issue is for Suite? In Suite V1.4.6. It has been able to reload language file on users side. To try this, please:
- Update the Suite to the latest release version
- Find the i18n folder under the root directory of Ethos Suite
- You will find your language json file under i18n
- Modify the strings if you want
- Please notice that the string after the "Language" key indicates the language name which will be displayed in Suite app. You will take "Language": "Englich" in en.json as an example
- Replace the language json file with yours
- Reopen Suite and select your language
- And if possible. You could share your json file here.

I have seen your es.json in the zip. But it's outdated. Thanks.

**Comment by Luznatural** [comment] 2023-02-02 04:12
What you have done is perfectly correct, but if you go to https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/doc
You will find in the list of documents available in that repository the following:
![Manuals](https://user-images.githubusercontent.com/43551716/216229595-64e8b72b-7744-41b9-9b4d-8a5b260584f3.jpg)
I think the note for the description of the file should also be modified to avoid confusion.
Best regards

**Comment by bsongis-frsky** [comment] 2023-02-02 08:13
This is not the description of the document, but the comment of the latest commit where this file was modified!

**Comment by bsongis-frsky** [comment] 2023-02-02 08:15
The same here, you can see that the comment is not a description for the "doc" directory.

![image](https://user-images.githubusercontent.com/50834778/216268562-d527bc42-7672-4e8e-8ad4-ddfb909183ac.png)
