### ISSUE TITLE
In a glider with V tail differential Rudder 

### ISSUE THREAD

**Issue by plusxstd** [FrSkyRC/ETHOS-Feedback-Community#2334] opened 2023-01-15 18:01 UTC
Hello everyone, kindly insert the possibility of having the differential with Rudder command for the drift.
 I saw the differential on the elevetor command which is not needed.

**Comment by strgaltdel** [comment] 2023-01-15 18:16
#119
#1746
#1822
#1921

(-;

**Comment by mawzthefinn** [comment] 2023-01-16 01:36
Duplicate of #119 

Closing in favour of that one.

**Closed** 2023-01-16 01:36 UTC
Labels: duplicate
