### ISSUE TITLE
Telemetrie Current Sensor ProblemTandem X20S 1.07

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#322] opened 2021-05-23 21:19 UTC
I have a problem with my current Sensor.
I use a Tandem X20 S Firmware 1.07
Only the current is displayed in the telemetry data.
Unfortunately, it is not possible to display the consumption,
regards bluelex

**Comment by bsongis-frsky** [comment] 2021-05-24 08:14
Duplicate of #4

**Closed by bsongis-frsky** 2021-05-24 08:14 UTC
Labels: enhancement
