### ISSUE TITLE
v1.5: Mixer curve reference is lost when migrating from 1.4.12 to 1.5

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3006] opened 2023-10-27 22:55 UTC
_Occurs in:_ X20S, simulator and actual tx.

How to reproduce:

1. In Ethos 1.4.12, create a mixer with a reference to a curve. 
2. Upgrade to Ethos 1.5

_Expected:_ After migration, the curve should appear as an action in the new mix.
_Actual_: The curve action is missing.

**Comment by bsongis-frsky** [comment] 2023-10-30 20:53
Duplicate of #3008

**Closed** 2023-10-30 20:53 UTC
