### ISSUE TITLE
Cannot flash TD R12 after 1.5.11

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#4473] opened 2024-09-01 19:52 UTC
I got an "Unsupported RX" message when trying to update my TD R12 when I was on 1.5.15 and rolled back to 1.5.9 trying to find where it broke:

1.5.9 - Works
1.5.10 - Works
1.5.11 - Works
1.5.12 - Unsupported RX

TD R12 started on 1.0.6, but was also an issue on 1.0.11.

I see someone else encountered the same issue and I could not find an existing issue here on GH: https://www.rcgroups.com/forums/showthread.php?4595073-FrSky-TD-R12-flash-problem

**Comment by ronron84** [comment] 2024-09-02 16:21
i've got the same issue with a td r10 the radio is x20 pro

**Comment by glipski50** [comment] 2024-09-02 17:50
Same with TD receivers.

Issue categorized as bug is here https://github.com/FrSkyRC/RF_Feedback_Group/issues/6

**Comment by pmullen503** [comment] 2024-09-05 00:19
Same problem with TW SR8. X20RS 1.5.15 firmware.

**Comment by bsongis-frsky** [comment] 2024-09-06 21:40
Duplicate of https://github.com/FrSkyRC/RF_Feedback_Group/issues/6

**Closed as completed by bsongis-frsky** 2024-09-06 21:40 UTC

**Comment by rburrow87** [comment] 2024-09-06 21:51
It would be nice if we could still force it to flash and ignore the check.

**Comment by pmullen503** [comment] 2024-09-06 22:35
> It would be nice if we could still force it to flash and ignore the check.

Until you accidentally flash the wrong firmware onto a receiver. I appreciate the check.

**Comment by rburrow87** [comment] 2024-09-06 23:09
Right... but right now all the receiver firmwares need to be updated by FrSky or you have to roll back Ethos in order to OTA flash anything.

I'm not saying get rid of the feature, I just mean have a workaround at least until all the receivers get firmware updates so I don't have to downgrade my radio at the field if I forget I haven't flown something in a while :)

**Comment by bobojh** [comment] 2024-11-22 07:59
> I got an "Unsupported RX" message when trying to update my TD R12 when I was on 1.5.15 and rolled back to 1.5.9 trying to find where it broke:
> 
> 1.5.9 - Works 1.5.10 - Works 1.5.11 - Works 1.5.12 - Unsupported RX
> 
> TD R12 started on 1.0.6, but was also an issue on 1.0.11.
> 
> I see someone else encountered the same issue and I could not find an existing issue here on GH: https://www.rcgroups.com/forums/showthread.php?4595073-FrSky-TD-R12-flash-problem

Have this same problem with Twin xlites 1.5.18 and sr6 mini from 1.0.10 to 1.0.11
with 1.5.9 update reciever sr6mini to 1.0.11 is OK

**Comment by bsongis** [comment] 2024-11-22 08:36
It is fixed in 1.5.19!

**Comment by bobojh** [comment] 2024-11-22 17:26
Hi.

I already saw the conversation in ETHOS Feedback community. That was my question. “Have this same problem with Twin xlites 1.5.18 and sr6 mini from 1.0.10 to 1.0.11
with 1.5.9 update reciever sr6mini to 1.0.11 is OK“

 

You answered me, that it is fixed in 1.5.19.  In Ethos suite 1.5.11 app there are written these changes:

*	"Negative" option added to Trims sources

*	Xact voltage offset bugfix

but nothing about what you said. This mistake is not written in fixed changes 1. 5. 19.  Is there some place, where I can find all fixed changes about all versions? 

 

Thank you

Jiri Jandera

**Comment by bsongis-frsky** [comment] 2024-11-27 18:06
Release note updated today
