### ISSUE TITLE
Speaker audio not muting when BT

### ISSUE THREAD

**Issue by Zadrob** [FrSkyRC/ETHOS-Feedback-Community#2741] opened 2023-07-11 15:05 UTC
Hello, I have Tandem XE with added bluetooth audio module - I can use BT audio and telemetry together. 
When I am on Bluetooth audio menu, I can set speaker mute switch, which actually mutes speaker. When I go away from this menu to setup e.g. BT telemetry this switch does not work = speaker is on together with BT audio. 
I can use both telemetry and BT audio, but speaker stays always on.

**Comment by mawzthefinn** [comment] 2023-07-11 23:28
This is a duplicate of #1370 

Please continue the conversation under that issue

**Closed by mawzthefinn** 2023-07-11 23:28 UTC
Labels: duplicate
