### ISSUE TITLE
Vario ADV sensor in the S. Port mode blocks gyro settings SR8 Pro

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#1596] opened 2022-04-10 21:19 UTC
Transmitter: Tandem X20

Receiver: SR8 PRO

Sensor: VARIO ADV

Software transmitter: Ethos 1.1.4 and 1.2.1

Error: No gyro settings possible if Telemetry Port is set to S.Port

For F.Port or FBUS, the settings are available again

**Comment by yak55** [comment] 2022-04-10 21:26
Addition: Software SR8PRO is 2.1.10

**Comment by yequhuashiren** [comment] 2022-04-12 02:37
The problem you mentioned was not found after the test. Please confirm whether the receiver version is up to date

**Comment by yak55** [comment] 2022-04-12 05:35
Receiver and transmitter are up to date.
Vario ADV is new with original software.
Problem is only with plugged vario.
If the vario is unplugged or the protocol is changed under Sensor Configuration / SxR the settings are possible again!

At the receiver S8R it works correctly!

Greetings Eugen

**Comment by pete-1970** [comment] 2022-10-27 09:51
This is a still existing major issue / bug, which I can confirm based on two SR8 Pro receivers in conjunction with a vario sensor plugged into the receiver S-Bus port. As soon as the vario is plugged in, all settings in the SxR menu (Device Config -> SxR) are greyed-out, i.e. not available. Thus, the receiver can't be configured anymore. 
Unplugging the sensor from the receiver immediately enables all settings in the SxR menu.  

Transmitter: Tandem X20S (FW: 1.4.2)
Receiver: Archer SR8 Pro (FW: 2.1.10)
Sensor: Vario "Vari ADV"

**Comment by mawzthefinn** [comment] 2022-11-12 01:42
Closing as the issue is now resolved

**Closed by mawzthefinn** 2022-11-12 01:42 UTC
