### ISSUE TITLE
2.4 stays shows connected on X18 after receiver disconnected 

### ISSUE THREAD

**Issue by rud3dog** [FrSkyRC/ETHOS-Feedback-Community#4322] opened 2024-08-01 05:34 UTC
Hi I updated my x18 and TD-R18 to the latest software. When I disconnect the receiver the radio still shows it’s connected to the receiver. It’s only on the 2.4 band. The 900 band shows it’s disconnected on the radio.on the telemetry screen it shows 89db on the 2.4g band. I hope I’m explaining this right

**Comment by i3dm** [comment] 2024-08-01 13:27
could be related to my issue FrSkyRC/ETHOS-Feedback-Community#4323

**Comment by mawzthefinn** [comment] 2024-08-01 13:56
This is a duplicate of FrSkyRC/RF_Feedback_Group#9 

Please continue discussion there

**Closed as not planned by mawzthefinn** 2024-08-01 13:56 UTC
Labels: duplicate
