### ISSUE TITLE
Release 1.0.11 candidate 3

### ISSUE THREAD

**Issue by timmybeetle** [FrSkyRC/ETHOS-Feedback-Community#851] opened 2021-08-24 20:00 UTC
Fault in screen Fail safe settings.
for example
Failsafe is at -10 and  should be at -100 (channel is at -100) ?
see pic bellow
![screenshot-2021-08-24-77804](https://user-images.githubusercontent.com/84274019/130681676-1304eecd-5b3c-4601-a8a4-c1792d27e394.jpg)
regards Hans

**Comment by MIKE-DAILEY** [comment] 2021-08-24 20:05
Duplicate of #842

**Closed by MIKE-DAILEY** 2021-08-24 20:05 UTC
