### ISSUE TITLE
Background music

### ISSUE THREAD

**Issue by fnnwizard** [FrSkyRC/ETHOS-Feedback-Community#1610] opened 2022-04-23 18:14 UTC
Can we have a dedicated background music player? One that allows flight sound to play over the BG music file?

I am able to get Ethos to play some long .wav files now, but it keeps looping and will not stop unless TX is turned off.

Also, the audio signal is clipping pre-amped. Need to adjust that gain lower. 

Thank you!

**Comment by mawzthefinn** [comment] 2022-11-24 03:41
Duplicate of #773, closing as such

**Closed by mawzthefinn** 2022-11-24 03:41 UTC

**Comment by thedalethompson** [comment] 2023-10-22 04:52
I am requesting this BG Music in ETHOS issue be brought up again.  The F5j community uses BG music for audio timers in OTX and would like this feature in ETHOS.  Running  layers of BG music files synced up with diffferent timer events allows the pilot to fly the F5j task with needed audio feedback.  Play Track and Play Value should be able to play over the BG Music.  In OTX the lower #SF BG music file is the one played on the speaker. When that file ends the next BG Music file in the SF stack takes the speaker.  Custom length audio tracks with critical silence can be layered as needed to provide the needed audio information for the pilot.   This is not about playing music ,  it's a valuble special function from OTX that is needed in ETHOS.
