### ISSUE TITLE
ADC check values fluctuate?

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#408] opened 2021-06-06 10:07 UTC
Two problems.
1) Why do the ADC check values fluctuate?

https://user-images.githubusercontent.com/84585992/120920547-a426ee00-c6bf-11eb-905e-527ef27fe8a8.mp4

https://user-images.githubusercontent.com/84585992/120920558-b012b000-c6bf-11eb-8c00-51175e772d01.mp4

https://user-images.githubusercontent.com/84585992/120920567-bacd4500-c6bf-11eb-835e-1fad05d2e56f.mp4

Outputs screen, why do the values fluctuate? 
Very disturbing phenomenon!
What is causing the fluctuation?

2) The push button on the bottom of the unit. When I press it, it clicks and turns on.  However, if I slowly and gently start to release it, it doesn't click yet, but it turns off and turns back on. No click, but it's going back and forth.
This switch is no good! It is useless.  Designed for F3K aircraft.  If it switches back before dropping (and this is not noticed), the aircraft will end up on the ground in a bad case! Either you have to hold it firmly pressed and it's good, or it doesn't click yet but it's already back on. This surface switch is not good! Unsafe operation!  It needs to be changed to a switch that will stably (flip) switch on and off in the same way and not switch back on.
It's not the push button that's wrong, both push buttons behave the same way.

**Comment by hrenz** [comment] 2021-06-06 16:08
you can do this with a log switch flipflop

**Comment by jufelap** [comment] 2021-06-06 17:53
I don't see how a logic switch can solve this problem.
I don't know what you mean.

It was just a comment about the switch on the bottom of the radio.
Not perfect, unstable operation. Totally different type of switches should be used in such places. That is my opinion.

I was glad that there is a push button on the bottom of the radio, and that you don't have to change the spring switch on the other side. But if I want to start safely (with F3K aircraft) then this push button does not work properly.

**Comment by MIKE-DAILEY** [comment] 2021-06-06 17:58
If you are describing the two push-button switches on the back of the system it looks like you have a hardware issue with the switches.  They work correctly on my systems.  They click when pressed and click when released.

**Comment by jufelap** [comment] 2021-06-06 18:06
Of course, mine also click. Watch the video with sound. You will see what I wrote about.
Try very gently releasing the push button, or reduce the force you push a little.
The switch will break down before it clicks back on and you can see in the video that holding your new one there, it will turn on and off nicely and there is no click at all. I'm not the one pushing it on and off that fast.

**Comment by bsongis-frsky** [comment] 2021-08-09 17:48
It's normal that ADC values fluctuate.
I will add a dead band zone around center
Duplicate of #308

**Closed by bsongis-frsky** 2021-08-09 17:48 UTC
