### ISSUE TITLE
Add Display Text File Option for checklists

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2344] opened 2023-01-18 13:21 UTC
Currently the Checklist only supports switch positions etc.. Would it be possible to add displaying a text file option to this please (as per opentx) where a text file / picture can be displayed as part of the model selection? Ideally, more than a single screen of text, perhaps scrollable? 

Possible uses? 
I can never remember the incantation needed to calibrate the gyro for my SxR rx, so being able to display a reminder of how to access it would be very useful. 
I fly power gliders which can last on one battery all day, but I do need to reset the countdown timer each day so I know when I've used the motor for more than 3mins and may be running out of motor use. 

On opentx I have a text reminders for the above, this would be most welcome on ethos. I'm also thinking that some may  also like a photo or similar to be displayed.

Thanks

**Comment by mawzthefinn** [comment] 2023-01-18 13:51
Duplicate of  your  own #1465 

Closing off in favour of that request

**Closed by mawzthefinn** 2023-01-18 13:51 UTC
Labels: duplicate
