### ISSUE TITLE
full screen widget - top and bottom bar overlay

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1284] opened 2022-01-03 09:20 UTC
X20 V1.1.0 alpha 12
when entering and exiting widget options (of a full screen widget) - sometimes the top and bottom bard are mixed and overlay on the full screen widget screen.
this behavior is erratic so not easy to reproduce but happened on several occasions.

**Comment by bsongis-frsky** [comment] 2022-01-03 10:25
You should see the top bar only when sliding the home screen pages

**Comment by bsongis-frsky** [comment] 2022-01-03 10:25
Need your script to reproduce, I cannot reproduce with standard widgets

**Comment by Hobby4life** [comment] 2022-01-03 12:06
![image](https://user-images.githubusercontent.com/55426642/147928493-ef36e22c-8872-4fc7-a373-1bab46c98bc1.png)

Same sort of issue..

**Comment by i3dm** [comment] 2022-01-03 12:14
thanks. same as happened to me.

**Comment by bsongis-frsky** [comment] 2022-01-03 12:49
how do you reproduce it?

**Comment by Hobby4life** [comment] 2022-01-03 12:56
> 

As i3dnm say, it happens now and then. hard to reproduce it.. maybe when clicking RTN when a  lcd.invalidate() is performed?

**Comment by bsongis-frsky** [comment] 2022-01-03 15:15
I hope my latest change will fix it in alpha14, feel free to reopen if needed

**Comment by i3dm** [comment] 2022-01-03 15:43
is alpha 13 cancelled?

**Comment by i3dm** [comment] 2022-01-05 12:08
just tried alpha 14, 
opened a full screen widget, coordinates were off (as can be seen in photo) and then when i wanted to configure screen with a full screen widget, this happened:
![image](https://user-images.githubusercontent.com/8968780/148215301-37c804bc-6589-4414-a8c5-3b50352aed23.png)

**Comment by bsongis-frsky** [comment] 2022-01-05 12:20
because you are sliding, so it is normal

**Comment by i3dm** [comment] 2022-01-05 12:24
no its not, im not sliding.
restarted and tried again, now worked correctly:
![image](https://user-images.githubusercontent.com/8968780/148217136-e184faa3-fe0b-4841-969b-9b50f1d9ff75.png)

something was quirky here anyway.. as the coordinates were all off too.
looks like a bug.

**Comment by bsongis-frsky** [comment] 2022-01-05 12:35
I reproduced something weird, needs more time to investigate

**Comment by bsongis-frsky** [comment] 2022-01-05 14:00
Fixed in alpha15

**Closed** 2022-01-05 14:00 UTC
Labels: bug
