### ISSUE TITLE
add: "system triggers/logics" to  sources and active conditions

### ISSUE THREAD

**Issue by poge-st** [FrSkyRC/ETHOS-Feedback-Community#528] opened 2021-06-22 10:32 UTC
it would be very nice to use logics / values / states which are used by the Os anyway inside the sources/active/ conditions.
With this I mean events/states like:

- timer x elapsed
- Throttle Cut Active
- Throttle Hold Active
- RSSI low 
- .....

with this information it would be very nice and easy (without programming own logic switches which rebuild that info) to for example play some important sound files , or use them in some additional logics.

**Comment by MrD-RC** [comment] 2021-06-26 14:23
Totally agree. No one seemed to notice my issue (https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/474) though. It’s great that this time it has been.

**Comment by bsongis-frsky** [comment] 2021-08-02 18:03
Duplicate of #474

**Closed by bsongis-frsky** 2021-08-02 18:03 UTC
Labels: enhancement
