### ISSUE TITLE
Slow between flight modes

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#768] opened 2021-08-08 21:37 UTC
In addition to the slow elevator compensation for flap mixes as previously requested, slow changes/date in and out between flight modes would be good to avoid abrupt changes in trim etc

**Comment by Hobby4life** [comment] 2021-08-09 05:46
Duplicates of #599 , #93 , #42 and I gues there are many more.

I hope this will be implemented in v1.0.11

**Comment by bsongis-frsky** [comment] 2021-09-09 05:59
Duplicate of #93

**Closed by bsongis-frsky** 2021-09-09 05:59 UTC
