### ISSUE TITLE
Trims to subtrims

### ISSUE THREAD

**Issue by Liverboy77** [FrSkyRC/ETHOS-Feedback-Community#41] opened 2021-04-08 18:54 UTC
Ethos v1.0.1
X10s isrm
Could you please add a trims to subtrims, this is important so when you have trimmed your model you can store the trims in the sub trims, so the trims reset to 0.
Thanks
Scott

**Comment by bsongis-frsky** [comment] 2021-06-04 10:39
Duplicate of #368

**Closed by bsongis-frsky** 2021-06-04 10:39 UTC
