### ISSUE TITLE
Where to address OTA AP sr10+ problem?

### ISSUE THREAD

**Issue by ilioSS53** [FrSkyRC/ETHOS-Feedback-Community#4434] opened 2024-08-25 11:28 UTC
Good day,
After I updated my x20s tx to 1.5.13  I also wants to update my APsr10+ by means of OTA.
This failed.
I register and bind the rx.
When I try to update xr to 1.0.11  from 1.0.9
The tx didn,t find the rx. The voice repeatedly asked for bind?
Where am I going wrong?

Like to hear.

**Comment by glipski50** [comment] 2024-08-25 12:26
Seems to be this bug here
https://github.com/FrSkyRC/RF_Feedback_Group/issues/6

**Comment by bsongis-frsky** [comment] 2024-08-26 06:09
Duplicate of FrSkyRC/RF_Feedback_Group#6

**Closed as completed by bsongis-frsky** 2024-08-26 06:09 UTC
