### ISSUE TITLE
PC application to allow model configuration/simulation/backup?

### ISSUE THREAD

**Issue by higheronnitro** [FrSkyRC/ETHOS-Feedback-Community#520] opened 2021-06-19 06:46 UTC
I see there are several posts that mention conversion and some about a “companion" equivalent. I am not fussed it we can't transfer from OTX to Ethos (Will give me a chance to rethink some of my model templates) ... But not having the ability to type text and numbers, copy and paste chunks of logic between models, test and simulate models/outputs, swap templates between friends, backup and restore on a PC with a keyboard and full screen ( or screens ) is frustrating. 
If there is something in the wings? (I will throw you a freebie name ... (Logos - The Greek word logos (traditionally meaning word, thought, principle, or speech) 
If so, do you have an estimated time? If not, then we need to be told so we don’t keep hanging in the breeze.( or left in a holding pattern )..
Looking forward to your feedback.

**Comment by bsongis-frsky** [comment] 2021-06-21 08:10
Duplicate of #319

**Closed by bsongis-frsky** 2021-06-21 08:10 UTC
