### ISSUE TITLE
Problem when changing from a model connected via ACCESS 900Mhz to a 2,4Ghz ACCST

### ISSUE THREAD

**Issue by kaiqueqds** [FrSkyRC/ETHOS-Feedback-Community#3013] opened 2023-10-31 14:06 UTC
When i try to change from a model using the R9STAB via ACCESS 900Mhz to annother mode using a X8R ACCST 2,4Ghz, or the other way around, my X20 do not conect to the new receiver, or when conect it behaves erraticaly, losing conection and/or "vibrating" the servos , requiring to restart the transmiter and receiver, sometimes needing to reset and rebind the receiver to get it to work normaly again.

**Comment by mawzthefinn** [comment] 2023-10-31 14:17
Which ETHOS version and which TD-ISRM firmware? These are available from System->Info.

**Comment by mawzthefinn** [comment] 2023-10-31 14:19
Duplicate of #2704 - Please continue the conversation under that issue and try the provided firmware if that radio matches yours.

**Closed by mawzthefinn** 2023-10-31 14:19 UTC
Labels: duplicate
