### ISSUE TITLE
Simulator Software that can configure models and then Transfers to radio?

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1376] opened 2022-01-23 19:56 UTC
Is there any chance that PC base software can be created and can configure models then transfer them to the radio or does it already exsists? thanks

**Comment by MIKE-DAILEY** [comment] 2022-01-23 19:59
Duplicate of #319

**Closed by MIKE-DAILEY** 2022-01-23 19:59 UTC
