### ISSUE TITLE
FBUS and Xact servos config - change applied to all servos

### ISSUE THREAD

**Issue by marciomc-github** [FrSkyRC/ETHOS-Feedback-Community#1841] opened 2022-08-07 11:59 UTC
Hi, I managed to adjust Physical ID when connecting servos to CH1 one by one in TD R18. Output was set to Fbus to each port (6 in total).

I am running on latest firmware: X20S Ethos 1.3.0, internal module 2.2.1, TD R18 Rx firmware 1.0.7, servo firmware 2.1.0.

Everything went fine but when I needed to change any config, I went to the telemetry screen, find the servo status (OK) and clicked to its options. After applying the changes all servos got updated with the same parameters  and lost previous configuration all acting as same.. 

Do I need a servo id changer  device or this is a bug in Ethos?

**Comment by TalperRC** [comment] 2022-08-08 06:04
I also spent some time configuring the FBUS servos.. 
it was not easy - but it works.... 

please keep in mind that when you setup FBUS servo you need to: 
1. setup the reciver output to Fbus (from ethos choose RF, select desired reciver and set options, the coose output) 
2. connect only 1 FBUS device at the time when you configure it (you need to set the addrees of the servo so only one servo needs to be connected) this done from Ethos through Device config, Xact 
3. after setting up each servo at the time you can connect all the rest and test the system 

Hope this helps

**Comment by marciomc-github** [comment] 2022-08-08 12:23
> I also spent some time configuring the FBUS servos.. it was not easy - but it works....
> 
> please keep in mind that when you setup FBUS servo you need to:
> 
> 1. setup the reciver output to Fbus (from ethos choose RF, select desired reciver and set options, the coose output)
> 2. connect only 1 FBUS device at the time when you configure it (you need to set the addrees of the servo so only one servo needs to be connected) this done from Ethos through Device config, Xact
> 3. after setting up each servo at the time you can connect all the rest and test the system
> 
> Hope this helps

Thanks, I did that exactly! The point is after having all configured, if you need to adjust a center for example, you need to disconnect all other servos in order to change a specific one setting from one servo. 
Is it the way to go? It seems like a bug to me. Since one servo has an unique ID it should be able to get updated without having to disconnect all others from the BUS.

**Comment by TalperRC** [comment] 2022-08-11 07:56
This needs to be verified by FRSKY team 
when i enter to the Xact configuration i make sure that only one servo will be connected. 

to my understanding - when you enter servo configuration settings you save the servo configuration to all servos since they are all listening to the same bus. 

I agree with you that everything related to fbus servo configuration should be improved, and there needs to be different menu for intial configuration (where you setup the servo ID - this needs to be done when only one servo is connected - if this can be done from the programing port on the transmitter it would make it much easier.... ) , and Tuning menu where you have the ability to  change some of the parameters of specific servo without disconnecting all the other  

so we need to open this as new feature request - as  enhancement

**Comment by marciomc-github** [comment] 2022-08-11 17:47
That is it! I thoght this as a bug because there is an id previously assigned to each servo. Telemetry is already addressed by device id. Now the configuration should be applied also id by id. I agree that this can be a new feature request.

**Comment by ZS-Man** [comment] 2022-09-27 07:29
Hi,
I vote for solving this problem..... + the possibility of upgrading FW to FBUS2 devices OTA .
I have 2x HV5701 and 2xD5701 on one connector (in F3K) and I need to upgrade FW.

Or is it possible to upgrade using s.port two servos at the same time?

Thanks

**Comment by mawzthefinn** [comment] 2022-11-24 14:59
Duplicate of #989 

closing in favour of that issue

**Closed by mawzthefinn** 2022-11-24 14:59 UTC
Labels: duplicate
