### ISSUE TITLE
X18SE goes into EMEGENCY MODE after unplugging USB cable from computer

### ISSUE THREAD

**Issue by gflash01** [FrSkyRC/ETHOS-Feedback-Community#4051] opened 2024-05-19 23:42 UTC
I updated from Ethos 1.5.7 to Ethos 1.5.8 today.   After ejecting the drives in Ethos, I unplugged the USB cable, and the transmitter went into EMEGENCY MODE and was beeping. Power cycling the transmitter cleared the error.  Now whenever I remove the USB cable after backing up my model files, the transmitter goes into EMERGHENCY MODE.  I have tried this on two different computers and the behavior is the same.  It does not appear to have impacted the performance of the radio, I did a range check prior to flying and flew two flights successfully.

**Comment by FlipAirboost** [comment] 2024-05-20 05:47
The same thing happened to me with my x18!

**Comment by strgaltdel** [comment] 2024-05-20 06:50
duplicate #4047

**Comment by hershg21** [comment] 2024-05-20 12:45
Also on my X10S Express

**Comment by bsongis-frsky** [comment] 2024-05-21 07:52
Duplicate of #4047

**Closed as completed by bsongis-frsky** 2024-05-21 07:52 UTC
