### ISSUE TITLE
X20 V1.5.9 Stick mode is globally assigned and not model-dependent, this is incorrect.

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#4148] opened 2024-06-08 00:53 UTC
X20 V1.5.9 Stick mode is globally assigned and not model-dependent
This is incorrect.

The respective stick mode must be entered into the model when creating a new model.

Example:
A helicopter is flown with mode 1
A fixed-wing model is flown with mode 4
A hydraulic excavator has a different assignment again

The stick mode is then only used as an assignment when creating a new model so that the automatic system knows what to do.

If this is not taken into account, only the active stick mode will be used when a model is called up.

This goes wrong

The stick mode can be changed at any time
then the next new model creating will have the different stick mode.

**Comment by Hartinger** [comment] 2024-06-08 06:18
If this is changed, I suggest that a global setting is retained defining if the throttle stick is on the left or right side. Any model specific modification of the stick assignment needs to take into account this setting, as changing this would imply a mechanical modification of the configuration.

**Comment by Hartinger** [comment] 2024-06-08 06:45
If any change is considered, it could be an additional flag (model specific), which swaps the horizontal stick functions.

**Comment by Didier-L** [comment] 2024-06-08 09:31
I do not agree at all with your request. It is perfectly correct as it is designed today.
I fly for more than 40 years planes, gliders, helicopters and multirotors with the same mode (mode 1) and more than 95% of pilots I know (whatever the brand of the radio) do the same.
It is your particular case. You can easily manage it by editing the mixers.
So, I don't want to have a mode per model, it has to be global. Moreover, if you want to play with the 4 modes, as explained, you have to open the radio to change the spring location...

**Comment by mawzthefinn** [comment] 2024-06-08 15:26
Duplicate of #1790 

please continue the conversation there

**Closed as not planned by mawzthefinn** 2024-06-08 15:26 UTC
Labels: duplicate
