### ISSUE TITLE
Voice Call Outs (Enhancement Request)

### ISSUE THREAD

**Issue by 3Dholic** [FrSkyRC/ETHOS-Feedback-Community#4590] opened 2024-10-01 07:03 UTC
Hi Frsky Team,

I’m currently using both a Jeti and Frsky system across different locations, and I've noticed a significant difference in the behavior of voice call-outs between the two.

On the Jeti system, when I toggle a switch, the system immediately announces the new switch position. If I switch again before the previous announcement finishes, the system interrupts the current voice call-out and starts the new one. This allows for faster and more responsive updates.

However, with Frsky, I’ve noticed that the system doesn't interrupt ongoing voice call-outs. If I change switches quickly, I have to wait for the previous announcement to finish before hearing the next one. This delay can result in losing important time, especially in scenarios where switch changes happen frequently.

Would it be possible to introduce an option in future firmware updates to enable immediate interruption of voice call-outs upon a new switch activation? This feature would greatly enhance the user experience and improve responsiveness in dynamic situations.

Thank you for considering this enhancement!

**Comment by chenbevis** [comment] 2024-10-01 11:00
I responded to this issue a year ago but it was not accepted

**Comment by loetefix** [comment] 2024-10-02 05:18
For this it would be useful to have a Group number 
option  to voice call outs. 

voice call outs with the same number can interrupt an other with same groupnumber but not call outs with different numbers. 

For example you attach number 1 to flightmode and number 2 to valtage call outs, flightmodes will not interrupt a voltage call out . a flightmode call out will interrupt an other flightmode callout with same "ID" (1) in this case. And group 0 will never interrupted (reseved for alarms).

I think this would be a good solution.

**Comment by bsongis-frsky** [comment] 2024-10-02 07:33
Duplicate of #4456

**Closed as completed by bsongis-frsky** 2024-10-02 07:33 UTC
