### ISSUE TITLE
ethos issue with spirit fbl

### ISSUE THREAD

**Issue by daman691003** [FrSkyRC/ETHOS-Feedback-Community#1601] opened 2022-04-13 09:56 UTC
Great job so far, to adjust spirit fbl properly like in open tx i need to be able to adjust the center pulse width of each channel.  Is this possible if not could it be in future updates soon? thanks so much

**Comment by i3dm** [comment] 2022-04-13 21:19
you can do that via subtrim?

**Comment by mawzthefinn** [comment] 2022-04-14 01:28
Subtrim only shifts the center, not the ends. The FBL needs the range shift.

This is the PPM Center feature that people have been asking for.

**Comment by i3dm** [comment] 2022-04-14 05:00
as a work around at leasr.. you can always shift end points too by the same amount?

**Comment by daman691003** [comment] 2022-04-14 09:41
so the problem is spirit makes u set in software endpoints to match theres so you cant do that.  subtrim you are supposed to not use. thanks everyone.

**Comment by mawzthefinn** [comment] 2022-04-14 14:08
You certainly can use the endpoint and subtrim adjustment to get the radio to match the Spirit,  you just can't do it with a single tool, you have to set each endpoint and the center separately

This fundamentally is poor design on Spirit's side, but PPM Center Adjustment would solve this generally.

**Comment by daman691003** [comment] 2022-04-14 14:18
spirit has its own software and kinda think it is a shortfall  like you say.  I made it work using subtrim, but in spirit software you need to adjust so  you have 100 -100 exactly in software.  So that means i need to lower my endpoints in radio to get it there.

**Comment by daman691003** [comment] 2022-04-14 14:18
in open tx it works seemlessly

**Comment by bsongis-frsky** [comment] 2022-04-22 10:27
how do you make it work in opentx? using PPP center - not 1500us?

**Comment by bsongis-frsky** [comment] 2022-04-22 10:28
Duplicate of #1264 if I understand it right

**Closed by bsongis-frsky** 2022-04-22 10:28 UTC
