### ISSUE TITLE
Bar(s) widget

### ISSUE THREAD

**Issue by OlegStelmakh** [FrSkyRC/ETHOS-Feedback-Community#665] opened 2021-07-19 18:19 UTC
Is it possible to add a widget that would display value bar for the values of the selected channel and one more widget for several channels at once?

**Comment by bsongis-frsky** [comment] 2021-07-27 10:32
Duplicate of #592

**Closed** 2021-08-05 16:21 UTC
Labels: enhancement

**Comment by bsongis-frsky** [comment] 2021-08-05 16:24
![image](https://user-images.githubusercontent.com/50834778/128385890-46a504c5-1b47-460d-b39d-697687e6c187.png)

**Comment by OlegStelmakh** [comment] 2021-08-05 16:40
Goood! Please, link to release candidate? :)
