### ISSUE TITLE
emergency mode

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#4053] opened 2024-05-20 12:39 UTC
After updateing my X10S Express to 1.5.8 and disconnecting from the desktop computer I get the Emergency mode evertime.

**Comment by strgaltdel** [comment] 2024-05-20 19:12
probably duplicate of
#4051 
#4047

**Comment by bsongis-frsky** [comment] 2024-05-21 07:52
Duplicate of #4047

**Closed as completed by bsongis-frsky** 2024-05-21 07:52 UTC
