### ISSUE TITLE
When you edit one curve it doesn´t show the position of the motor stick

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#2570] opened 2023-04-08 22:44 UTC
This refers to #812 and # 24 that were closed at the time and I think it is because the purpose of what was proposed was not understood.
When you have a curve with for example 20 points, if a vertical line is not represented in the curve indicating the position of the engine stick, I can not know with point of the curve I should correct.

I would like if it were possible to show a vertical line indicating in what position the motor stick is to know which point to correct.

I send an image with an example.

Thanks
![tempImagel6YoHt](https://user-images.githubusercontent.com/87758703/230745571-95db7574-2af7-4ae6-8769-c837689b4a99.gif)

**Comment by mawzthefinn** [comment] 2023-04-09 02:18
This is a duplicate of #24 which is still open. 

The curve doesn't know what the input is, as it can be assigned to any number of items at the same time. There is a possibility in the future to display input in cases where there is only one possible input assigned to the curve, but that requires some work to create the logic to detect when this is the case.

Please continue this conversation under #24

**Closed by mawzthefinn** 2023-04-09 02:18 UTC
Labels: duplicate

**Comment by jasalca** [comment] 2023-04-09 16:32
With all my respect, to begin with I do not know who you are to close this tread, and second if you were right, then the 
position of stick could not be seen in any curve and that does not happen, because in the example that I command below, the position of the stick is perfectly seen in the curve

https://user-images.githubusercontent.com/87758703/230784603-90ea9047-bdd5-4128-95ab-e24e5ddd4c1d.mp4

**Comment by mawzthefinn** [comment] 2023-04-09 20:04
I help manage this Github community for FrSky. 

This issue was closed because it is a duplicate of a currently open issue, namely issue #24, duplicates of open issues are closed in favour of the original issue. 

Please continue the discussion in the already open Issue. 

You are displaying the mixer view. The mixer knows what curves are assigned to it, the curve itself does not and can be assigned to any number of items (this is very common to do when using a mix for input conditioning, like a 0-100 curve which has a multitude of uses). When editing the curve it does not have any idea what input you are using.

**Comment by jasalca** [comment] 2023-04-09 20:25
Clarified. Thank you and my apologies
