### ISSUE TITLE
Horus 12s w. Ethos 1.4.4. Flight modes/Fade In, Out

### ISSUE THREAD

**Issue by Habasek** [FrSkyRC/ETHOS-Feedback-Community#2227] opened 2022-12-21 09:19 UTC
Horus 12s w. Ethos 1.4.4. Flight modes/Fade In, Out - no value works in any mode.

**Comment by mawzthefinn** [comment] 2022-12-21 15:07
Where are you watching? 

For trims, on the main menu it jumps immediately, but if you check Outputs, you will see the fade in/out.

I just tested on my X12S/1.4.4

**Comment by Habasek** [comment] 2022-12-21 15:33
Model menu: Flight modes/Fade in, Fade out - I give values for example 10sec and I don't see any slowdown on the model.
Model menu: Outputs - no slow motion is visible, among all the flight mode, the slider immediately jumps ...

**Comment by mawzthefinn** [comment] 2022-12-21 15:34
Can you post the model file? I'd like to take a look at it.

**Comment by Habasek** [comment] 2022-12-21 15:57
Yes ...
[clik 21.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10279237/clik.21.zip)

**Comment by mawzthefinn** [comment] 2022-12-21 16:22
In testing, I see what is happing on Ch4 only. Is that correct?

If so, the issue is unrelated to flight modes. You are using Switch G to select your rates, not your Flight Modes to select your rates (even though Switch G also selects your flight modes). Use Flight modes to select rates and it will work correctly.

**Comment by Habasek** [comment] 2022-12-21 17:01
The model is for the indoor, Clik from RC Factory -  4ch is OK.
I use the SG switch to switch Flight modes and then in the Mixer the SG switch for different channel ranges. Switching ranges works OK. The deceleration that I set in flight modes does not work.

For example, deceleration in Outputs on an individual channel works, but it slows down the movement of the lever and the channel coasts according to the set value. I don't want this.

**Comment by Habasek** [comment] 2022-12-21 17:03
Printscreen:
[screenshots.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10279730/screenshots.zip)

**Comment by Habasek** [comment] 2022-12-21 17:24
Can you send me your model where the deceleration between flight modes is used, it will be easier for me to understand where I am doing wrong.

**Comment by mawzthefinn** [comment] 2022-12-21 18:48
You need to have settings tied to the Flight Mode for fading to work. You have configured Flight Modes, but have no functions tied to them

All your settings are tied to switch SG, not to the Flight Modes, so fading doesn't exist as far as those settings are confirmed. Only settings controlled by Flight Modes will fade.

**Comment by mawzthefinn** [comment] 2022-12-21 19:19
And yes, I'll post the model file later today

**Comment by mawzthefinn** [comment] 2022-12-22 02:44
[clik 21.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10283339/clik.21.zip)

**Comment by Habasek** [comment] 2022-12-22 11:06
Thank you very much. I understood. ;)
One more question, is there a way to upload my models from the radio in Ethos Simulator?

**Comment by mawzthefinn** [comment] 2022-12-23 00:02
I don't believe there is a way to do that at the moment. 

Closing off this issue as you have your flight modes figured out now

**Closed by mawzthefinn** 2022-12-23 00:02 UTC
