### ISSUE TITLE
Request: A delay mix (like gear to door)

### ISSUE THREAD

**Issue by Asimos32** [FrSkyRC/ETHOS-Feedback-Community#600] opened 2021-07-06 20:10 UTC
if its possible to add to the mixer library a "time based mix"
lets say "gear up" and in "X" seconds "door closing" 
and the opposite.

also if its possible to explain how to do this sequence with  the 1.0.9  firmware

 thank you

**Comment by MIKE-DAILEY** [comment] 2021-07-06 20:14
Here is an example using Logic Switches that provide more fixability with time related functions https://www.rcgroups.com/forums/showpost.php?p=46708519&postcount=3621

**Comment by Asimos32** [comment] 2021-07-06 20:24
MIKE-DAILEY
thank you

**Comment by MIKE-DAILEY** [comment] 2021-07-06 21:50
Duplicate of #534

**Closed by MIKE-DAILEY** 2021-07-06 21:50 UTC
