### ISSUE TITLE
Spezial Funktion : Override

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#327] opened 2021-05-24 10:48 UTC
is still missing in the special functions. Override 
for example:
when the landing gear is retracted, the nosewheel servos can be deactivated.
is this issue noted?

**Comment by Hobby4life** [comment] 2021-05-24 10:55
I opened same question earlier: #324

**Comment by MIKE-DAILEY** [comment] 2021-05-24 11:04
Duplicate of #324

**Closed by MIKE-DAILEY** 2021-05-24 11:04 UTC
