### ISSUE TITLE
Can irange IRX4 Lite be used on Tandem X20S

### ISSUE THREAD

**Issue by krokusvej** [FrSkyRC/ETHOS-Feedback-Community#971] opened 2021-09-18 12:59 UTC
Hi I have tryed to find an answer if Irange IRX4 lite TX modul can be used on or is supported by Ethos on Tandem X20S, at the speking moment I am running Version 1.0.10 any one who nows this? Sorry if it´s not in the right forum..

**Comment by MIKE-DAILEY** [comment] 2021-09-18 14:03
Duplicate of #7 and #885

**Closed by MIKE-DAILEY** 2021-09-18 14:03 UTC
