### ISSUE TITLE
Mixer screen refresh bug

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2673] opened 2023-06-04 21:46 UTC
I made a video: https://youtu.be/bK01ZNDaeBI

Mixer screen has some weird problem with showing mixer value. If a given mixer is highlighted, it shows the value correctly always. If it's not highlighted, it sometimes is not updated when changed. 

In video I change switch for flight mode, which changes 'Thr level'. But as you see, screen is only updated if 'Thr Level' is selected.

However 'Ail Expo' and 'Rud Rate' (also dependent on flight mode) get updated always.

I can't find a rule how it works. It works correct for selected mixer, and for other it's a bit random. 

This is how 'Thr level' is defined (VAR mixer)
![20230604_234230](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/fde63749-084c-4288-987d-2a320d2b7492)

And 'Ail Expo'
![20230604_234242](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/9ba186bf-6ecc-48f7-8db5-17040becc09a)

**Comment by azaz44** [comment] 2023-06-04 21:56
Update: sometimes even selected mixer doesn't get updated. Below two images with different flight modes. Graph on the right side shows correct value, but 'Source' column is wrong. it should be 60 in one case and 45 in the other, but shows 60 always.

![20230604_235244](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/7fd19086-54d3-455a-be30-1b146cbd522e)

![20230604_235242](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/724b1122-ed72-4d59-9e66-3dc8fbc4d4a0)

**Comment by bsongis-frsky** [comment] 2023-06-05 07:18
This has already been fixed in 1.4.9 and in current nightlies

**Comment by bsongis-frsky** [comment] 2023-06-05 07:18
Checked this morning, I cannot reproduce it

**Closed by bsongis-frsky** 2023-06-05 07:18 UTC
