### ISSUE TITLE
System sounds (beep/ring/siren etc)

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#2551] opened 2023-03-27 10:48 UTC
Hi there, thanks Bertrand and team for all the hard work you do-just a minor gripe/query from me. 

When using OTX i always found the "Ring/Ring2/beep/beep2/ratata/Siren" etc tones massively useful and far less annoying than having a radio screaming "low battery" or something else-any chance we can have these sounds added by default into the default Ethos system soundtrack because yes voice alerts are nice, but sometimes you just want a simple "beep or Ring". We had the choice in OTX to "play track" or "play sound" but its not in ETHOS and i would imagine its not too difficult to add them to the default soundpack and an option to "play sound" in the special functions menu. 

Cheers

X-lite-S, X18SE, X20S, X10SE, O/G taranis user

**Comment by mawzthefinn** [comment] 2023-03-27 13:08
Duplicate of #781 please continue conversation under that Issue

**Closed by mawzthefinn** 2023-03-27 13:08 UTC
Labels: duplicate
