### ISSUE TITLE
V- Tail mixer diff. 

### ISSUE THREAD

**Issue by m0p3d** [FrSkyRC/ETHOS-Feedback-Community#1746] opened 2022-06-21 19:07 UTC
Creating model via wizard
Using V tail - the elevator mixer has per default the option to use diff- which results is no effect for any value
(+ i do not know any application for V tail elevator where it makes sense using diff - maybe just eliminate the diff in this case - v tail, elevator)

Using diff for rudder if v tail is active makes sense ! (but there is not the option)

**Comment by Hartinger** [comment] 2022-06-22 13:15
In fact, there is an effect, i.e. a positive value for the ele. diff. reduces the upwards travel of the elevator. (I checked this with the X20 simulator at version 1.2.8.) I agree, however, that ele. diff is actually quite useless, whilst rud. diff. for the v-tail would make much more sense.

**Comment by hrenz** [comment] 2022-06-22 19:16
at V-tail, the ruder has noch diff,  but its importand

**Comment by mawzthefinn** [comment] 2022-11-10 02:28
Duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/119

**Comment by bsongis-frsky** [comment] 2022-11-10 07:28
Closing it then

**Closed** 2022-11-10 07:28 UTC
