### ISSUE TITLE
Ethos Suite 1.2.6

### ISSUE THREAD

**Issue by bluelex73** [FrSkyRC/ETHOS-Feedback-Community#1658] opened 2022-05-13 19:32 UTC
Hello frsky team I am excited about the ethos suite 1.2.6 good work! So easy I could never bring my X20S up to date. Is it possible to make a backup of the transmitter via the ethos suite? Possibly even before update begin the question: Should a backup be created before update begin?
Greetings 
bluelex73

**Comment by mawzthefinn** [comment] 2022-05-14 12:36
Not currently, although you can simply make a copy of the SD card before updating.

This functionality has been requested before, and really should be implemented

**Comment by bsongis-frsky** [comment] 2022-05-16 08:13
Duplicate of #1567

**Closed by bsongis-frsky** 2022-05-16 08:13 UTC
