### ISSUE TITLE
Allow gimbal ADC Filter to be set per model

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#2318] opened 2023-01-10 18:33 UTC
On the System > Hardware screen. You can enable and disable the ADC Filter. This is a global setting. But it would be more useful if it could be set per model. So you could have a model for a quad with a flight controller, where it's better to have the ADC Filter off. Then another model for a LOS plane where you may want the ADC Filter on.

**Comment by mawzthefinn** [comment] 2023-01-10 19:35
This is a duplicate of #2260 and is IIRC scheduled for 1.4.6

**Closed by mawzthefinn** 2023-01-10 19:35 UTC
Labels: duplicate
