### ISSUE TITLE
Problems with edge-controlled logical switching and stopwatches 1.5.0

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#3184] opened 2023-12-27 19:26 UTC
After the update, some stopwatches and logical switches no longer work.

Cause: The switches had an edge function in 1.4.15
After the conversion, the icon is still ok, but the edge option no longer exists - the switch no longer works correctly.

Is there a better way to convert this?

Attachments: Screenshot of stopwatch and logical switches

Greetings Eugen

![Logische Schalter](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/d5581a4a-8a4d-4a28-a358-48aa250d02d9)

![Stoppuhren](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/85737356/6c3c2566-2dfc-46c5-bfee-d5c2eb3b6eab)

Greetings Eugen

**Comment by spoke2570** [comment] 2024-01-15 14:30
#3221 is a duplicate of this.

**Comment by yak55** [comment] 2024-01-15 20:35
Hi Spoke2570, I use 3 different transmitters.
X20S, X20Pro and Tandem XE.

I have 30 active models on each transmitter.
After the update, stopwatches and logical switches with edges no longer function correctly on all 3 transmitters.
The function after the update is still incorrect.

Do I really have to change the stopwatches and logic switches on 3x30, i.e. 90 models?

Can't an update do this better?

I hope it works better.

Greetings Eugen

**Comment by spoke2570** [comment] 2024-01-15 20:52
Eugen,
I don't have as many models as you. On my X20s the edge condition held for all my logic switches. I added some logic switches to run the adjustment of var values and one to replace that edge condition in timers. All the mixers got a complete overhaul.

You might want to roll back to your last stable setup and wait for the full release to drop. I imagine the migration woes will be fewer.

Best
Peter

**Comment by bsongis-frsky** [comment] 2024-01-16 08:52
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/7c62fd67-21cd-4ea4-9457-6c6218509360)

**Closed by bsongis-frsky** 2024-01-16 08:52 UTC
