### ISSUE TITLE
request: make the active weight in VAR mixer adjustable

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#1436] opened 2022-02-08 09:50 UTC
It would be realy nice if we can INC/DEC the current active weight in a VAR mixer by a switch or a logical switch (like in the trim mixer)

so in the VAR mixer field there you can choose one switch/logical switch for increase and one for decrease value.
now you can adjust the "active"(if more than one is defined)  weight in flight by a defined function.

every weight should get a checkbox for adjustable or not adjustable.

with that feature we have a digital potentiometer channel with a variable numbers of adjustable values.

this is nice for gyro value or throttle values on helicopters.
so you can quick and easy adjust gyro and rpm or other values while flying the model.

**Comment by hrenz** [comment] 2022-02-08 21:31
this is the missing  counter function with inc, dec , steps, reset, autoset, autoreset

**Comment by loetefix** [comment] 2022-02-09 05:51
Basicly in the trim mixer it is allready possible. But with only one value. So every flightmode needs one trim mixer line. Very annoying.

**Comment by Jedsters** [comment] 2022-02-11 16:59
Would another solution be to allow the trim mixer output to be either per FM or across all FM?
e.g. a trim mixer output may always be channel 30, but channel 30 would either be consistent across all FM or you could adjust ch30 so it could be e.g. 10 on FM0 and 20 on FM1 etc.
(If I'm understanding you correctly.)

**Comment by loetefix** [comment] 2022-02-11 17:04
Trim mixer should store one value per flightmode,just like the normal mixer.but this is a different story.

**Comment by mawzthefinn** [comment] 2022-11-10 03:53
Yuu can combine trim mixers and VAR mixers to achieve most of this now that VAR mixer values can be 'use a source', but the lack of per-FM trims in the trim mixer limits you. 

Note that if you have a spare trimmer (T5/T6 if present) this is fully achievable using the Trimmer as a source for the VAR Mixer weights.

**Comment by mawzthefinn** [comment] 2022-12-02 04:15
Note I have a proposal for an implementation of this in #1602

**Comment by mawzthefinn** [comment] 2023-02-02 21:36
This is being addressed under #779 

Please check out the proposal there.

**Comment by mawzthefinn** [comment] 2023-02-02 21:42
Closing as a duplicate of #779 as per last comment

**Closed by mawzthefinn** 2023-02-02 21:42 UTC
Labels: duplicate
