### ISSUE TITLE
Model Data invalid

### ISSUE THREAD

**Issue by jhammann13** [FrSkyRC/ETHOS-Feedback-Community#4351] opened 2024-08-07 08:37 UTC
Hello,
On my X20Pro  with 1.5.12  I get after switching on and when selecting a model : Model data invalid.
The model then disappears from the selection list.

This happens when I select the setting _System/General/Model when switching on_ = on

If I set this to = off      then everything is fine.

**Comment by jhammann13** [comment] 2024-08-07 08:54
A guy at RCG have the same problem:
https://www.rcgroups.com/forums/showpost.php?p=52794205&postcount=31533

**Comment by jasalca** [comment] 2024-08-07 11:06
Yes ,I do have the same problem

**Comment by Nicholas-Luoyi** [comment] 2024-08-08 06:11
Would you please share the model which cannot be read on the start up?

**Comment by jhammann13** [comment] 2024-08-08 06:26
It is usually the last model used, if you want to select this, the message "Model data invalid" comes up.
I have compared the corrupted model file with the backup, there is nothing more in it...
This only happens when I select the setting _System/General/Model when switching on_ = on

**Comment by jhammann13** [comment] 2024-08-08 06:35
Here a model data.... renamed to .txt
[m5 stuart.txt](https://github.com/user-attachments/files/16538654/m5.stuart.txt)
[m5 stuart_corrupt.txt](https://github.com/user-attachments/files/16538655/m5.stuart_corrupt.txt)

**Comment by jasalca** [comment] 2024-08-08 06:59
It does so with all the saved models, and it always gives an error with the last one you used. As soon as you turn on the radio and want to go back to using the last model with which you turned off the radio, the problem occurs.

**Comment by jasalca** [comment] 2024-08-08 07:03
If you turn on the radio with another model, everything goes well.

**Comment by Nicholas-Luoyi** [comment] 2024-08-08 07:16
Reproduced

**Comment by jasalca** [comment] 2024-08-08 07:36
How good and what a relief ! Thanks!

**Comment by Alex00101** [comment] 2024-08-08 10:59
So I guess Pro/Pro AW owners should not be upgrading to 1.5.12?

**Comment by jhammann13** [comment] 2024-08-08 11:35
> So I guess Pro/Pro AW owners should not be upgrading to 1.5.12?

There is no problem as long as you use the function _Select model at power on_ is not activated....

**Comment by jasalca** [comment] 2024-08-08 12:17
The problem will be those people who update and do not know what the issue is about. And if they don't have a backup , then you have a big problem.

**Comment by jhammann13** [comment] 2024-08-08 12:31
You should create a backup before each update....this is really very easy with the suite

**Comment by pmullen503** [comment] 2024-08-09 01:20
From my earlier comment "t
In 1.5.12 if "select model at power on" is selected, the last model loaded is selected by default. If you try to use it it returns "invalid data". If you then select another model and go back, the previous model disappears. A .bin file with that name still exists but appears corrupted and can't be loaded even when copied to another transmitter.

This behavior was observed on both my X18 and X20RS."

Both TX were successfully flashed back to 1.5.11, model backups reloaded and the problem went away.

This is a pretty serious bug. 1.5.12 should be pulled until this is fixed to protect those who have not upgraded yet.

**Comment by Alex00101** [comment] 2024-08-09 01:24
> From my earlier comment "t In 1.5.12 if "select model at power on" is selected, the last model loaded is selected by default. If you try to use it it returns "invalid data". If you then select another model and go back, the previous model disappears. A .bin file with that name still exists but appears corrupted and can't be loaded even when copied to another transmitter.
> 
> This behavior was observed on both my X18 and X20RS."
> 
> Both TX were successfully flashed back to 1.5.11, model backups reloaded and the problem went away.
> 
> This is a pretty serious bug. 1.5.12 should be pulled until this is fixed to protect those who have not upgraded yet.

Totally agree and that is what I meant asking if users should really upgrade to 1.5.12. Of course at that time I assumed it is only Pro/AW specific

**Comment by woltervdberg** [comment] 2024-08-09 20:30
I had the same issue. Luckily I made a backup but I saw this behaviour on both my X18S and X20pro. Turning off the "select model at power on" solved the issue but I totally agree that Frsky should pull this update as long as this isn't fixed. 
I don't mind beta-testing a product but the fact that Frsky continuesly keeps releasing buggy updates while calling them stable is very misleading.

**Comment by philippe-warnotte** [comment] 2024-08-14 04:13
Reproduced by Nicholas, declared as duplicate, closed but still not reported as BUG !

**Comment by Dsrenger** [comment] 2024-08-14 04:18
This one is not closed...it is open. 

chill. People are on vacation sometimes. 
There is a fix. Just turn off the option. 

Pretty sure it will be fixed, once vacation time is over.

**Comment by bsongis-frsky** [comment] 2024-08-14 13:14
Fixed in 1.5.13

**Closed as completed by bsongis-frsky** 2024-08-14 13:14 UTC
