### ISSUE TITLE
Instant trim

### ISSUE THREAD

**Issue by MeniLew** [FrSkyRC/ETHOS-Feedback-Community#532] opened 2021-06-23 11:22 UTC
Is it possible to add an "instant trim" function to the "Special Functions" menu? 
 This function determines the position of all trims except the throttle at the push of a button while flying, according to the position of the sticks while pressing the button.  Thanks

I use x20s with Athos version 1.0.9 fcc

**Comment by Hobby4life** [comment] 2021-06-23 11:32
Already mentioned: #513

**Comment by MeniLew** [comment] 2021-06-23 13:55
I could not find an answer there

**Comment by MeniLew** [comment] 2021-06-23 13:56
> Already mentioned: #513



> Already mentioned: #513

I could not find an answer there

**Comment by bsongis-frsky** [comment] 2021-06-23 14:33
Duplicate of #295 
Don't open too many issues for the same request, it takes time to sort

**Closed by bsongis-frsky** 2021-06-23 14:33 UTC
