### ISSUE TITLE
[WISH] - SEQUENCER

### ISSUE THREAD

**Issue by WOODY1958UK** [FrSkyRC/ETHOS-Feedback-Community#2691] opened 2023-06-16 23:53 UTC
HI - FIRST - PLEASE EXCUSE CAPS - BUT I AM PARTIALLY SIGHTED AND IT HELPS - I KNOW YOU PROBABLY HAVE BEEN ASKED THIS BEFORE - BUT A SEQUENCER - FOR EXAMPLE - TO OPEN UNDERCARRIAGE DOORS AND THEN LOWER UNDERCART - AND AT THE SAME TIME LOWER LANDING FLAPS - SO WOULD IMAGINE STEPS - IN EACH STEP YOU CAN PUT IN AS MANY CHANNELS AS YOU LIKE - GIVING EACH CHANNEL IT'S OWN FADE IN - FADE OUT TIME - EACH STEP WOULD JUST HADE A TIMER TO NEXT STEP AS FADES ARE DONE IN EACH CHANNL - NEED TO EASILY COPY STEPS - SO UNDECART WOULD HAVE - STEP 1 5 SECS - OPEN UNDERCART DOORS 3 SEC FADE IN- AS SLOWLY AS REQUIRED - START FLAP DOWN WITH LONG FADE - STEP 2 5 SECS - DROP REAR UNDERCART - 3 SECS FADE - STEP 3 - 5 SECS - DROP FRONT UNDERCART - ALL THE TIME THE FLAPS ARE SLOWLY MOVING THE 5 DEG DOWN SET IN STEP 1 - HOPE THIS ALL MAKES SENSE - WORKING ON A GLIDER SLS SYSTEM - SO THIS WOULD COME IN VERY USEFUL - THANKS - CATCH YOU LATER - TAKE CARE - HAPPY FLYING - DAVID - WOODY1958UK

**Comment by mawzthefinn** [comment] 2023-06-17 17:39
This is a duplicate of #657 I will close in favour of the original issue

The functionality is already present, just not labelled as a Sequencer

See the following video & article on how to do it
https://www.rcgroups.com/forums/showpost.php?p=46708519&postcount=3621

**Closed by mawzthefinn** 2023-06-17 17:39 UTC
Labels: duplicate
