### ISSUE TITLE
Missing ratio and offset buttons from rxbat telemetry using elrs module

### ISSUE THREAD

**Issue by mortehoe** [FrSkyRC/ETHOS-Feedback-Community#4679] opened 2024-10-30 13:18 UTC
X10S running Ethos 1.5.18 .
After discovering telemetry from elrs receiver I need to adjust the voltage calibration however the Ratio and Offset buttons are missing from the screen (see attached)

![screenshot-2024-10-30-38524](https://github.com/user-attachments/assets/e8a5d996-586f-44f5-bec6-c1725bf456cc)
![screenshot-2024-10-30-38500](https://github.com/user-attachments/assets/daa02c38-1f43-43f2-b2e8-b2671cd8b823)
![screenshot-2024-10-30-38511](https://github.com/user-attachments/assets/5d8e1a82-827f-4a09-8fe8-d7d2218319f7)

**Comment by mawzthefinn** [comment] 2024-10-30 14:52
Duplicate of #3767 

Please continue the conversation there.

**Closed as not planned by mawzthefinn** 2024-10-30 14:52 UTC
Labels: duplicate
