### ISSUE TITLE
Sequencer

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#4837] opened 2024-12-04 14:04 UTC
As our discuion before is retract sequencer being applied in 1.6 as with other mfg has already included it.

**Comment by mawzthefinn** [comment] 2024-12-04 14:25
This is a duplicate of #657 

There is no sequencer in 1.6.0, as that release is aligned primarily to the RF features of RF firmware 3.0.0

Note that the Free Mix includes single-channel sequencing capabilities as of 1.5.0 (simply put a Curve action after a slow action and that curve becomes the sequencer curve, different curves in each direction are possible using Active COnditions to control which is active), it's only configuring multiple channels on one screen that is missing.

**Comment by mawzthefinn** [comment] 2024-12-04 14:26
Closed as this is a duplicate of #657 please continue conversation there.

**Closed as completed** 2024-12-04 14:26 UTC
Labels: duplicate
