### ISSUE TITLE
RSSI Warnings do not appear to repeat or Reset

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3882] opened 2024-04-20 16:18 UTC
From my been testing it appears that the 'RSSI Critical Warning' is only played when the RSSI drops below the specified value (Edge). This doesn't seem ideal as if you fail to hear the warning properly (e.g. due to wind on a windy slope) and the RSSI doesn't go above the critical value then you may totally miss this (although you may hear the RSSI Low warning first). I can't help think that the RSSI warnings should repeat so long as they remain true. If it is very windy and I hear a warning but can't hear what it says I normally put the tx close to my head in the hope of hearing what it says - but this won't help unless the RSSI value is floating around the critical value. 

It also appears that the Reset doesn't work. I'm assuming that Reset is intended to reset the warning, so that if the trigger is triggered and the condition is still true then the warning will repeat, however this does nothing other than briefly clear the RSSI value in the top row, it doesn't replay the warning. 

Maybe Reset could be one of the existing conditions or also a duration? 

Note: I've tested RSSI Critical and have not tested RSSI Low but assume the same to apply to that too. 

Of course one can fix this with some LS and SF, but I wonder how many will feel the need to do this rather than rely in the built in warnings.

Also see #3242 for a similar problem with tx voltage warnings. 

Thanks

**Comment by bsongis-frsky** [comment] 2024-05-15 12:01
Duplicate of #3902

**Closed as completed by bsongis-frsky** 2024-05-15 12:01 UTC
