### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by MichaelETHOS** [FrSkyRC/ETHOS-Feedback-Community#829] opened 2021-08-21 12:24 UTC
current firmware 1.0.10
error in log files. cannot be opened in companion.
![log](https://user-images.githubusercontent.com/84266308/130321654-383aa35d-d427-487b-9623-090a4b07bd40.PNG)

**Comment by OldGazer** [comment] 2021-08-21 13:52
Using  1.0.11RC2 on an X20.  Works for me.  Try loading a log into a spread sheet like Excel or OpenOffice Calc (which is what I use...).

**Comment by STC148** [comment] 2021-08-21 21:05
I can confirm that it works for me with companion and with data explorer.

**Comment by pld74** [comment] 2021-08-22 01:34
This happened to me as well. Try uninstalling companion, reboot, reinstalling companion, reboot again. That worked for me.

**Comment by FBarrao** [comment] 2021-08-23 06:49
Logs open ok for me on 1.0.10, no way to open them with companion under 1.0.11 RC1 or RC2. 
Able to open the csv on excel, but after convert to xlsx the rudder column has errors. ( Always the rudder column error)
![log](https://user-images.githubusercontent.com/88581380/130402966-e203082d-915e-471b-8e6f-8ee6bb69d804.JPG)

**Comment by bsongis-frsky** [comment] 2021-08-31 06:04
These files are simple CSV files, you will open them in Microsoft Excel / LibreOffice Calc
GPS fixed in 1.0.11RC4

**Closed by bsongis-frsky** 2021-08-31 06:04 UTC
