### ISSUE TITLE
point on curve not showing X10S

### ISSUE THREAD

**Issue by mortehoe** [FrSkyRC/ETHOS-Feedback-Community#3937] opened 2024-04-29 08:34 UTC
https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/3820551/1bbf9dec-5df7-4c19-9c56-14ef18469bec

Frsky X10S ISRM running Ethos 1.5.6 .
If I select a curve the points on the curve are not highlighted when moving the stick i.e on a three point curve for aileron when I move the stick it does not highlight the position on the curve, which makes it very difficult on a more complex curve to know which point to adjust.

**Comment by mawzthefinn** [comment] 2024-04-29 18:50
This is a duplicate of #24 

Please continue the discussion there

**Closed as not planned by mawzthefinn** 2024-04-29 18:50 UTC
Labels: duplicate
