### ISSUE TITLE
lua: system.playTone(freq,dur) messed up in 1.4.x ?

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#2045] opened 2022-11-04 12:57 UTC
Hi,

these days i got a X20 for test purpose (old pre-production unit)

I recognized, that a system.playTone(1600,250) command didn't output any tone
It's my understanding that this command should generate a 1.6kHz tone for 250ms
[system.playNumber() outputs a number call, so i can rule out a wrong volume setting] 

running the code on a win10-sim does crash the sim (closing sim & debug window; Ethos 1.4.0)
a 1.3.3 sim doesn't crash, but even outputs no sound.

So it seems for me that 1.4.x isn't able to support the playTone method

regards

**Comment by MiRe-CZ** [comment] 2022-11-04 13:34
I can confirm the issue on sim 1.4.0. It was reported already on sim 1.2.11 & 1.3.2 (#1915) and perhaps partly corrected in 1.3.3, but I haven't tested that time and release notes do not indicate it

**Comment by bsongis-frsky** [comment] 2022-11-04 17:24
Duplicate of #1915

**Closed by bsongis-frsky** 2022-11-04 17:24 UTC
