### ISSUE TITLE
Voltage ranges displayed as percentages % in logical switches

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1247] opened 2021-12-27 11:42 UTC
If you create a logical switch using Range, and a Battery as the source, it correctly displays as a voltage on the definition screen (first image), however on the Logical Switches screen it shows as a percentage (second image). Obviously this should also be a voltage. 
This happens on release 1.0.14 and simulator 1.1.0-alpha2

Correct display of voltage as V
![image](https://user-images.githubusercontent.com/96293240/147468512-a5aa9173-4e9f-4fa6-bbce-bdc28cee1ac7.png)

Incorrect display of voltage as %
![image](https://user-images.githubusercontent.com/96293240/147468548-15a54304-f286-4882-8c1b-98c1199b8c48.png)

**Comment by bsongis-frsky** [comment] 2021-12-27 11:47
Fixed in 1.1.0 alphas

![image](https://user-images.githubusercontent.com/50834778/147468947-d7b35927-c5f3-473a-baf7-c634d531825d.png)

**Comment by bsongis-frsky** [comment] 2021-12-27 11:49
Duplicate of #1189

**Closed by bsongis-frsky** 2021-12-27 11:49 UTC
