### ISSUE TITLE
Post 1.4.7 Update Hebrew Language issue.

### ISSUE THREAD

**Issue by Idan69** [FrSkyRC/ETHOS-Feedback-Community#2559] opened 2023-03-29 11:59 UTC
Post Update to 1.4.7 on my X18S i got Hebrew Language issue. 
All the letters are messed up and cannot be read

**Comment by mawzthefinn** [comment] 2023-03-29 13:44
This looks like a duplicate of #2520 

Please continue the conversation there

**Closed by mawzthefinn** 2023-03-29 13:44 UTC
Labels: duplicate
