### ISSUE TITLE
[enhancement] Numeric value input in calculated sensor

### ISSUE THREAD

**Issue by mszulen** [FrSkyRC/ETHOS-Feedback-Community#4192] opened 2024-06-24 14:58 UTC
Would't it be more user friendly to be able to enter numeric value in calculated sensor directly instead of holding the option icon and selecting "convert to value" and then getting the numeric field active?
Like here:
option 1: activate the field and enter the value directly
oprion 2: select the "value" item as a source and then enter the value
 
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6932464/690b5321-838b-4734-9e31-6068174a104c)

That would be more handy than current way (also "Convert to value" sounds confusing - perhaps "Enter the value" or something like that would sound more clear)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6932464/cd3db15a-12b8-4669-9fdf-739033efae67)

**Comment by mawzthefinn** [comment] 2024-06-24 16:44
Duplicate of #2244 

Please continue conversation there

**Closed as not planned by mawzthefinn** 2024-06-24 16:44 UTC
Labels: duplicate
