### ISSUE TITLE
Expresslrs

### ISSUE THREAD

**Issue by Travo04** [FrSkyRC/ETHOS-Feedback-Community#1346] opened 2022-01-14 20:02 UTC
Expresslrs on tandem

**Comment by kakashi2018** [comment] 2022-01-15 01:50
Yes. Please add crsf support to tandem tx. It is really good to fly micro quads with my x20s will be even better if we could make use of those teeny tiny ELRS receivers.

**Comment by bsongis-frsky** [comment] 2022-01-24 07:31
Duplicate of #5

**Closed by bsongis-frsky** 2022-01-24 07:31 UTC
