### ISSUE TITLE
Enable SBUS Trainer input on SPort plug

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#2295] opened 2023-01-06 14:30 UTC
Enhancement

Enable SBUS Trainer input on SPort pins. 
I currently use a head tracker that send SBUS as Trainer inputs. Its quite handy because I dont need to use any bec on the tracker and can power it from the UART on my old radio. But the SPort on the X20 doesn't provide power (and has no SBUS in function)...

**Comment by mawzthefinn** [comment] 2023-01-06 16:29
This is a functional duplicate of #784, note the DSC port is probably what you should be using here rather than the S.Port (although it's not Sbus compatible either at this time).

I'm closing this off as a duplicate and recommend discussion continue under #784 as this would be a very valuable function.

**Closed by mawzthefinn** 2023-01-06 16:29 UTC
Labels: duplicate
