### ISSUE TITLE
reading the logs on the radio screen x20s

### ISSUE THREAD

**Issue by Fernandolewandowski** [FrSkyRC/ETHOS-Feedback-Community#1752] opened 2022-06-28 01:16 UTC
I would like you to add the possibility of seeing in the field the readings of logs csv file on the radio screen x20s..without having to read it in excel on the computer

**Comment by loetefix** [comment] 2022-06-28 08:03
Duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/284

**Closed** 2022-07-29 19:12 UTC
