### ISSUE TITLE
Logic switch Edge does not trigger Vars actions if its duration is 0

### ISSUE THREAD

**Issue by gordonchenyx** [FrSkyRC/ETHOS-Feedback-Community#3636] opened 2024-03-12 17:07 UTC
As described in the title, an edge logic switch with 0 duration does not trigger the actions in vars.

**Comment by bsongis-frsky** [comment] 2024-03-13 11:39
Why don't you set a min duration? 
Otherwise the switch can be so short that no function sees it!

**Comment by gordonchenyx** [comment] 2024-03-13 16:55
Yes, i get around this by having a duration of 0.1 sec for the edge logic switch.

But logically speaking, shouldn't the action being triggered immediately when condition being met? instead of requiring to stay in the condition for some time.

Also, I noticed that using the same edge logic switch with 0 duration, it can trigger another logic switch consistently without problem, but it never triggers the actions in vars. My point is, shouldn't they follow the same logic?

**Comment by lthole** [comment] 2024-03-18 10:08
If there is a possibility that Edge (or for that matter any LSW) might not trigger functions, then it should have a built-in min duration. Otherwise to what purpose would anybody want a min of 0.0?

**Comment by RC-SOAR** [comment] 2024-04-11 14:31
This issue also affects migration of my sailplane templates from 1.4.

Here's an example LS which triggered in 1.4 but fails to trigger in 1.5.6:
```
LS25: Function=AND
Value1 = !FM2
Value2 = !FM3
Value3 = {other LS generating an Edge}
Duration = 0

SPECIAL FUNCTION
ActiveCondition=LS25, Action=PlayAudio
```

_Expected_: Audio should play when Value3 (edge) triggers

_Actual_: 
good in 1.4
fails in 1.5.6 unless LS25.duration is set to 0.1 sec.

The 0.1 sec workaround is described on my Support page, but it would be great if this was fixed (it's the last remaining migration issue for my templates - 1.5.6 is looking really good otherwise!).

**Comment by bsongis-frsky** [comment] 2024-04-11 20:37
We are on the right way for stability again, with a lot of new features!
As I said in another room, at the minute you mark a version as "Official Release" (even after 10 release candidates), you receive the bugs notifications and your life becomes a nightmare.
I will try to fix this one tomorrow, I have an idea, but I will need help for testing ...

**Comment by RC-SOAR** [comment] 2024-04-11 22:07
Bertrand I'd be happy to check out the affected templates (there are six instances).

https://rc-soar.com/ethos/support/#h1

**Comment by bsongis-frsky** [comment] 2024-04-13 19:57
This scenario has been tested successully with my fix:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/1c2ed2b3-0184-4232-98fd-d66f8d0aada8)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/38ad6e51-00b7-448e-bcab-1d06e3c06323)

**Comment by RC-SOAR** [comment] 2024-04-13 22:02
Thanks! If the fix is included in the nightlies I'll check it out on the templates.

**Comment by bsongis-frsky** [comment] 2024-04-15 09:32
It's still not finished. It's a big refactoring!
I am doing another test session today to be sure.

**Comment by bsongis-frsky** [comment] 2024-04-15 09:33
Test ON on this one

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/c893c317-4c32-4f4a-a94b-837523d2ed2d)

**Comment by bsongis-frsky** [comment] 2024-04-15 09:52
Tests to be done by hand:

1) Logic Switch ↑Edge of SA↑ with a 0 (default) duration
    - the logic switch must be written in BOLD during 100ms on UI
    - the var should increment, only 1 step

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d8dc6b5b-5e07-4e0e-82c9-9a6f7d99802b)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/ab5b2127-f8e3-4f66-8df4-b59bd45b313d)

2) Switch SA↑ with Edge option used in Var
    - the switch must be written in BOLD during 100ms on UI
    - the var should increment, only 1 step

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/37a6d431-b89d-4dd9-a875-cb9145628a2c)

3) Play audio (executed from the main task, not the mixer). Same tests than above

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/50f48769-6660-4608-8c1e-8d6dba917ba9)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/53623ed2-1a38-4de6-a566-452d8362b544)

**Comment by bsongis-frsky** [comment] 2024-04-15 10:10
More complex use cases which have been tested OK. Some were KO in previous versions (1.4.X and 1.5.X)

4) Boolean Logic Switch, one condition has the Edge option

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/f590f2cd-db63-4f1a-b4eb-af96cdd675bc)

5) Boolean Logic Switch, one condition has the Edge option and the other is the same, but working with a Edge switch

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/35694974-bf2c-411d-9db5-16a6a764cf15)

**Comment by bsongis-frsky** [comment] 2024-04-15 10:14
Edge option tested in Extra trims too

**Closed as completed** 2024-04-15 20:34 UTC

**Comment by bsongis-frsky** [comment] 2024-04-16 10:46
Nightlies are online now, please tell me if the problem is fixed for you? Take care, it is not visible, but it has been a huge change in source code!

**Comment by RC-SOAR** [comment] 2024-04-16 13:21
Okay, I've started testing, and have found an issue described below. First, my method of testing:

1. Establish USB connection
2. Copy 5 templates native 1.4 format to /models folder
3. Copy 5 templates native 1.5 format to /models folder
4. Flash 1.5.7 nightly (xe5e0c294)
5. Test each template 

_Issue_: at startup, several Play Audio special functions trigger unexpectedly - these are driven by a number of logical switches.  This only happens at initial power up - it does not happen when switching models. Both the 1.4 and 1.5 format setups are affected.

I will continue with testing.

**Comment by bsongis-frsky** [comment] 2024-04-16 21:33
Reported in #3848
The fix is ready for the next nightlies

**Comment by bsongis-frsky** [comment] 2024-04-22 07:54
@RC-SOAR Would you confirm that now nightlies are good? I have fixed the bug you have reported above

**Comment by RC-SOAR** [comment] 2024-04-22 09:14
Sure, will have a look and report back. Should be within a couple of hours.

**Comment by RC-SOAR** [comment] 2024-04-22 11:28
1.5.7 pre-release works well with my templates - both (a) the original issue and (b) SFs triggering at startup are fixed.

For the first time, all my 1.4 templates convert to 1.5 without any modifications necessary :-)
