### ISSUE TITLE
ELRS Trouble, yet again...

### ISSUE THREAD

**Issue by Mellonoma420** [FrSkyRC/ETHOS-Feedback-Community#2353] opened 2023-01-20 13:37 UTC
I thought I got this figured out. I am honestly just at a loss because it just doesn't make any sense.

I have been using EthOs with ELRS successfully for about 2 months now. No issues other than noob issues.

I decided to build another plane, so I bought a few receivers so I could have a stock. they're easy to use and cheap. I updated the firmware on one of the new receivers for my quad, one for my T1 ranger, one for my new build, and one spare. Also updated the Firmware for the Jumper, and downloaded/updated the new lua script.  Everything was fine last night. Everything worked, I could access the ELRS module from the radio, I could connect to all of my receivers. My ass went to sleep.

I woke up this morning to start working on the plane. Got everything set up and tried to enter the configuration for ELRS, and..... nothing. Blank screen. I'm connected to the plane, and both the receiver, AND ardupilot show up, but NOT my ELRS module. I don't know what steps to take because everything works. It's just frustrating that I can't make this work smoothly.

How do I get the configuration script to load? Like I said, it was working last night; the only difference is that I'm at my computer and not my couch. WTH?

Is there any alternative to Ethos for the X18? I'm basically burnt out on Ethos at this point.

Radio: Tandem X18 with firmware updated yesterday.
Receivers: MATEK R24D * 3 + MATEK R24 PWM.
ELRS Module: Jumper Aion nano Tx
MATEK H743 Flight controller running Arduplane
    
 *If this is not enough information then please kindly just ignore the post, other people are actually helpfull and it is unnecessary to tell me you can't help*

**Comment by mawzthefinn** [comment] 2023-01-20 14:33
Are you able to get into the configuration script and are just not seeing the Jumper Module there?

Or is nothing happening when you tap 'Configure'?

If it's the former, the issue is the module not responding, not the script.

Frankly, I've heard consistently of trouble from that module even on OpenTX/EdgeTX, I'd hesitate to blame ETHOS over a module that's known to be somewhat flaky. 

I personally recommend the HappyModel ES24TX Slim Pro modules for use on the TANDEM radios. they are proper in-spec Lite modules unlike the Jumper (which will not fit several Lite Bay equipped radios since Jumper copied TBS's out of spec case design) and the HappyModel stuff is a lot more reliable than Jumper in general. 

I've had consistently good luck with the HM modules on both ETHOS and OpenTX/EdgeTX since I started working with ELRS a few months ago.

**Comment by Mellonoma420** [comment] 2023-01-20 15:20
The protocol shows up just fine, but when I press configure the module
doesn't show up. The receiver shows up, ardupilot configuration shows up, I
can even use the damn thing just fine, but it will not show up when I press
configure; but it DID last night.. idfk really, I just gave up for now. Too
wet cold, and windy to fly, so it isn't worth my hairline.

I think I might just try a different module. It wouldn't fit in my Taranis,
and has just been weird for lack of better explanation. I'm new to this
hobby, but I'm not stupid; I shouldn't be having this much trouble with
simple things with clear steps that I understand, and are readily available.

Thanks.

**Comment by mawzthefinn** [comment] 2023-01-20 15:23
That sounds like the module not responding, if the receiver shows up then the link is good, so the module itself must be having issues. The script handles the receiver side as well.

And if your Taranis is an X9 Lite, that's one of the units that the out of spec case on the Jumper and TBS modules has issues with.

**Comment by Mellonoma420** [comment] 2023-01-20 15:23
The past couple months with EthOs really hasn't been bad tbh. I love the
feel of the radio, I love the look of the screen, I didn't even hate the TD
MX receiver they gave me with the radio.

I want flying robots, but I guess I want them too soon... fml right?

**Comment by Mellonoma420** [comment] 2023-01-20 15:33
Fuckin' yep. I had to 3d print a back piece for it to make it fit. I think
it even said it was compatible with the X9 lite by name lol. Whatever.

I've heard Happy Model enough times now that I'll probably go with it this
time. Whatever the best possible ELRS module is for the Tandem X18 is, I
want it, so I'm totally open to any and all suggestions.

I don't have anyone here that knows anything about this stuff, so I rely
entirely on the internet for learning. I appreciate your time. Thank you.

**Comment by Target0815** [comment] 2023-01-21 20:24
> Whatever the best possible ELRS module is for the Tandem X18 is, I want it, so I'm totally open to any and all suggestions.

> HappyModel ES24TX Slim Pro

I also use it myself with an X18S.

**Comment by Mellonoma420** [comment] 2023-01-21 20:28
I think that's what I'll go with. Now if I could get ardupilot to detect my
gps I'll be doing okay. It's an M8Q 5883, and I keep seeing other people
having issues with it too. I love learning new things, but it does get
frustrating lol. Thanks for your time, I appreciate the help.

**Comment by mawzthefinn** [comment] 2023-01-23 14:43
Closing off as an answer has been provided.

**Closed by mawzthefinn** 2023-01-23 14:43 UTC
Labels: information needed
