### ISSUE TITLE
FW 1.1.3  chronos on throttle stick not working.

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#1553] opened 2022-03-28 09:26 UTC
Hello, on the new programmed models, the chronos do not work via the throttle stick commands. on the latest firmware version 1.1.3.
But with other older models, there are no problems.

**Comment by Mobidick1966** [comment] 2022-03-28 09:29
My radio : X 20  eu.lbt  fw 1.1.3

**Comment by bsongis-frsky** [comment] 2022-03-28 19:52
Duplicate of #1547

**Comment by Mobidick1966** [comment] 2022-03-29 09:06
Still not working in 1.1.4  ...

**Comment by MIKE-DAILEY** [comment] 2022-03-29 14:01
Working here too.  X20S FCC 1.1.4 using throttle absolute and count down.

**Comment by bsongis-frsky** [comment] 2022-03-31 07:36
We need more info about this one, everything is working as expected too here.

**Comment by Mobidick1966** [comment] 2022-03-31 08:20
Hello everyone.
Here I am in FW 1.2.1rc1, if I want the timer to work, I have to delete the model and reprogram it. On the older ones there are no problems.
In other words, it works.
Thank you ........

**Comment by mawzthefinn** [comment] 2022-11-24 03:31
Are you still having issues on current firmware?

**Closed** 2022-11-27 16:53 UTC
Labels: information needed
