### ISSUE TITLE
X20PRO Issues with SD Card Read and Write operations, cause the transmitter to disconnect all volumes

### ISSUE THREAD

**Issue by exceltw** [FrSkyRC/ETHOS-Feedback-Community#4132] opened 2024-06-04 02:17 UTC
On my X20PRO when I connect VIA USB on either PC or MAC. Version 1.5.9 appropriate bootloader level. 
Steps to create issue I have:

1. Put a Sandisk SD card I tried varying sizes, 16, 32, 64 in the transmitter try opening up file manager and I don't see the SD Card.
2. Connect to a pc or mac, the system will mount the three volumes, Flash, Camera, SDCARD once you select Ethos on the transmitter for it to connect to the pc/mac
3. Try manipulating files between the SDCard and pc and or copy from PC/MAC to SDCARD, Try copying from SDCARD to Radio mount point. This will cause the transmitter to disconnect all the mount points for it and not be detected by ethos.

Important to note, I have gotten read operation issues when trying to load a model as well on the transmitter from the SDCARD.

Steps tried multiple times:
Recovery and reformat of storage
Reflash Ethos and Bootloader
Tried Macbook pro and PC
PC will crash or give error reading storage when its trying to attach to the storage volumes on the transmitter.

PLEASE HELP!

**Comment by Joetrin** [comment] 2024-06-04 15:43
@mawzthefinn Hi Adam, are you able to duplicate on your pro?

**Comment by mawzthefinn** [comment] 2024-06-11 16:04
@Joetrin Just tested, unable to duplicate. 

NB - I was using a cheap Amazon special Class 10 16GB card. If the Sandisk cards are UHS-1, I'd recommend trying a lower-end Class 10 only card. I've seen a lot of weird behaviour with UHS-1 cards on slower card interfaces

**Comment by bsongis-frsky** [comment] 2024-07-01 19:07
Problem reproduced on X20S:
In firmware mode (not bootloader), during the copy of 1500+ files, the USB disconnects because of a Write timeout.
It will be fixed in 1.5.10

**Closed as completed by bsongis-frsky** 2024-07-01 19:07 UTC
