### ISSUE TITLE
Crazy Range at ADC2

### ISSUE THREAD

**Issue by Devil-IdT** [FrSkyRC/ETHOS-Feedback-Community#358] opened 2021-05-28 18:16 UTC
Hello,
i would like to have the battery voltage displayed via connection AIN2 on my SR6.
An ADC2 sensor is also found but has a crazy range.
You cannot edit this area either, unless you make the rotary knob glow.
A long press would be a good fit to enter your own value.
Hope this gets a little better.

![ADC2](https://user-images.githubusercontent.com/64803366/120025835-8d163b00-bff1-11eb-8177-11635da8f27e.jpg)

TX is a X10S with ISRM-Update.

**Comment by hrenz** [comment] 2021-05-28 18:25
and string "Drehwinkel" must be changed to "Bereich"

**Comment by jfint** [comment] 2021-05-29 18:07
@Devil-IdT Please verify is #290 is working or not for you.

**Comment by Hobby4life** [comment] 2021-05-30 13:25
Besides the weird value, I am missing "Ratio"

You need that to correctly correct the ADC input to whatever "real" voltage you are using.

**Comment by jfint** [comment] 2021-05-31 15:34
I think this could be marked a duplicate of #290 I hope this gets fixed soon, its holding up F5J style airplanes from being viable with this TX without a much large3r gamble than I would like to take.

**Comment by bsongis-frsky** [comment] 2021-06-11 06:03
Duplicate of #290

**Closed by bsongis-frsky** 2021-06-11 06:03 UTC
Labels: bug
