### ISSUE TITLE
Alpha 16: emergency mode due to error telemetry data

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1360] opened 2022-01-18 14:30 UTC
Alpha 16 X20:
made an mlvss simulator (using an online s.port lib) and at some point had an error in the sensor code which caused the radio to go immidiately to emergency mode any time i connected the sensor to Rx.

on OpenTX it just lost the sensor (acceptable) but on Ethos emergency mode due to telemetry data should not be accepted as telemetry could always have errors. 
perhaps a data validation layer for telemetry data needs to be added.

i can post the arduino hex file for the faulty sensor that caused the error if required.

**Comment by bsongis-frsky** [comment] 2022-01-18 15:13
Please post the frame which caused the error, it would help more than adding another week extra work

**Comment by i3dm** [comment] 2022-01-18 15:18
i have not read the specific frame. will.try.

**Comment by i3dm** [comment] 2022-01-18 18:49
should be:

0x10 0x00 0x30 0x26 0x00 0x00 0x00 0x99

**Comment by RealTadango** [comment] 2022-01-19 07:26
> should be:
> 
> 0x10 0x00 0x30 0x26 0x00 0x00 0x00 0x99

This is the frame the sensor sends as a reply to the poll from the RX.
prim: 0x10 (Data header
application id: 0x0300 (mvlss lipo sensor)
value : 0x26 (cell id 0x06 (out of bound since normally only 6 is the maximum to index 6 means cell 7 & 8 data which never occurs with a real sensor) and total cell of 2 (which is an error combination also).

**Comment by bsongis-frsky** [comment] 2022-01-19 07:51
Our code is protected again this sort of error in the frame. May I know which is the Lua code you use to parse this frame? It should be rather easy to reproduce and find where is the issue

**Comment by i3dm** [comment] 2022-01-19 07:57
> Our code is protected again this sort of error in the frame. May I know which is the Lua code you use to parse this frame? It should be rather easy to reproduce and find where is the issue

the fault occurs without any cells widget on the SD.

**Comment by bsongis-frsky** [comment] 2022-01-19 08:03
I see no possible crash with your frame, instead I have found one if cells count is > 6

(0x70 instead of 0x26)

**Comment by bsongis-frsky** [comment] 2022-01-20 07:33
It is fixed in next alpha

**Closed by bsongis-frsky** 2022-01-20 07:33 UTC
Labels: information needed
