### ISSUE TITLE
Spirit Lula Script

### ISSUE THREAD

**Issue by blware** [FrSkyRC/ETHOS-Feedback-Community#4085] opened 2024-05-27 15:15 UTC
I went from 1.4 to 1.5 with no issues a month or so ago but when I updated last week no my spirit LULa scrip is not connecting, I have rolled back and it sill is inoperable. I feel it was a module update that changed it but I didnt pay attention honestly. I have reinstalled the scrip and still nothing. This is the same on 7 units and different receivers. 
any input of what I can look at ?

**Comment by bsongis-frsky** [comment] 2024-05-27 16:26
Duplicate of #4083

**Closed as completed by bsongis-frsky** 2024-05-27 16:26 UTC
