### ISSUE TITLE
V1.5.0  Simulator X20S HardwareTest no FS1 ..FS6  Trims only with US Keyboard

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3079] opened 2023-11-22 19:10 UTC
Testing  V1.5.0 Simulator X20S

Trims only works with US-Keyboard layout sigsn, not with German Keyboard layout signs

FS1...FS6 no funktion, think should be with numbers 1 2 3 4 5 6

Poti3 (middle red slider) no funktion

all others elements at Simulator Hardware works fine

**Comment by bsongis-frsky** [comment] 2023-11-22 19:41
1 2 3 4 5 6 are used for trims

**Comment by hrenz** [comment] 2023-11-22 19:58
No
Trims are used with  US Keyboard  and  then 9 0  - =  and with STR plus  9 0 - =

**Comment by noamkrief** [comment] 2023-11-23 15:33
Sorry - where is the user manual for the simulator? I didn't even know I can control the analogs via keyboard.
Also - I don't see V15. I'm on 1.4.8

Is there a way to reload LUA widgets? Right now as I'm developing LUA, I have to reboot the sim everytime I make a change.

**Comment by strgaltdel** [comment] 2023-11-24 11:38
Some infos about keyboard layout can be found on rcg
https://www.rcgroups.com/forums/showpost.php?p=47748621&postcount=10729

you can download Sim 1.5n from the "nightly release" assets 
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/nightly15

look into the 1.5 milestones for further improvements
..maybe this will help you
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2935

**Comment by bsongis-frsky** [comment] 2024-02-15 14:22
Duplicate of #3440 
Opening multiple time the same issue doesn't help, I just spend more time in sorting issues rather adding new functions!

**Closed by bsongis-frsky** 2024-02-15 14:22 UTC
