### ISSUE TITLE
Bug: Two Neuron 60S doesn't work on Ethos telemetry at the same time

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#1532] opened 2022-03-14 14:26 UTC
Hi Developer,
in my Snowcat I'm using a Neuron 60S for the left an a Neuron 60S for the right motor (2 Neuron 60S). Every Neuron can be shown in the telemetry as stand alone. But together it doesn't work. The telemetry of both get in conflict and can not be displayed. I also changed in BLHeli32 the physical address to 1 and 2. This doesn't has any effect. Ethos seems to be not able to deal with 2 Neuron at the same time in the telemetry. 
Later I would expect some calculations when it works. Sum of current and sum of capacity would be nice to get the real added values. This als needed for plans with 2 props and 2 ESC's as well.
Please can you create a fix to show both Neuron's telemetry in parallel?
Best Regards
Bernhard

**Comment by dap35** [comment] 2022-03-17 16:30
Did you change both the device ID and application ID?  You should be able to do this from the radio, probably connecting one sensor at a time.

I found this section in the latest Ethos manual ~pg 117:
"Each sensor may have multiple Application IDs, one for each sensor value being sent.
The Physical ID and the Application ID are independent and unrelated. For example the
Variometer sensor has just one Physical ID (default 00), but two Application IDs: one for
Altitude (0100) and the other for Vertical Speed (0110).
Another example is the FLVSS Lipo Voltage sensor, which has a Physical ID (default 01),
and an Application ID for Voltage (0300). If you want to use two FLVSS sensors to
monitor two 6S Lipo packs, you will need to use Device Config to change the Physical ID
to an empty slot (say 0F hex), and also to change the Application ID from 00 to say 01,
which will make the complete Application ID (0301). Because the Physical ID and the
Application ID are independent and unrelated, both must be changed. The Physical ID
must be changed for exclusive communication with the host receiver, and the Application
ID must be changed so the receiver can distinguish between the data from Lipo 1 and 2."

**Comment by Hartinger** [comment] 2022-03-17 17:20
This is not what I have experienced.

I have connected a SM UniSense Sensor to the S-Port of an Archer R8pro, which provides a variety of telemetry data under a special Physical ID. At the same time I have connected a FrSky Vario and a FAS Sensor, both of which have their own Physical ID. These two sensors provide data using the same Data (Application) IDs as also used by the UniSense. The Tandem X20S with ETHOS 1.1.1 was perfectly able to differentiate and display those values that have the same Data ID but different Physical IDs.

The Neurons are a special case, as they use Data IDs that allow the transmission of two telemetry parameters in one S-Port package. So maybe the problem is related to this very fact.

**Comment by BernhardFe** [comment] 2022-03-18 07:56
As far as I understand the protocol works as following your both explanation and my experience now:
Every Sensor Type (application) has a defined address range to define who the sensor is doing. The application ID is like you mentioned (300). A physical ID is added to this address and allows to distinguish between die individual sensors with the same application ID (300+1). The Sub-ID allows to distinguish between several values, delivered by an application. Additional it can happen, that a Application with a Sub-ID can have several values. In Open TX the Neuron has for example the application ID 0B50 and the Sub-ID 17 for Volt and Amp. I assume that an application with a sub-ID can deliver in one data package several values (minimum 2) that must be correct interpreted. Following this logic, it explains 2 bugs in ETHOS telemetry.
Bug1: If the physical ID is ignored in some cases, then the two sensors with the same Application ID will crash. This is here described.
Bug2: I mentioned in another thread that the DIY sensor can not distinguish Volt and Ampere if I have one Neuron. This means that the data package will only in the DIY sensor (not in the auto sensor) not correct interpreted and that's why it jumps between both values Volt and Ampere randomly.
For me it sounds like a programming error and that several cases are not have been taken in consideration.
The consequence should be:
Bug1: Just the change of the physical ID must be good enough to distinguish between the 2 Neurons.
Bug2: The DIY sensor must get an additional programming to be able to consider if 2 values are delivered in the same application, physical address and Sub-ID.
Please can you have a look into the code? What is different to OpenTX?
Thanks a lot for any effort to find this issues. It wold really help!

**Comment by Hartinger** [comment] 2022-03-18 12:08
I think you have interpreted the term "Sub-ID" incorrectly, probably because it is slightly misleading. The "Sub-ID" used in OpenTx actually represents the Physical ID, with the counting of IDs starting with 1. For example, the voltage value of the LiPo sensor has ID 0300 and Sub-ID 2 in OpenTx. In ETHOS the same parameter has the composed ID 01 0300, where the first two digits represent the Physical ID. NB that ETHOS starts counting the Physical IDs with 0.

**Comment by BernhardFe** [comment] 2022-03-18 17:04
Hi Hartinger, I think Doug is right, increasing the Neuron Physical ID + 1 innBL Heli the four digit code for the application ID increases 1 number in Ethos. Why the Neuron didn't start with 0 ?. In OpenTX I have in 3 planes the same OpenTX configuration for the Neuron and the Physical ID in BL Heli is always 1
OpenTX Example: Voltage Bat = 0B50 SubID 17, Temp = 0B70 SubID 17
None of my sensors have a SubID =0 or 1 in OpenTX
<img width="606" alt="Bildschirmfoto 2022-03-18 um 17 29 56" src="https://user-images.githubusercontent.com/86232280/159043731-aa83f2d9-727e-4620-aded-644b23298b68.png">
In Ethos the same Neuron has the value Voltage Bat=10 0B50 and Temp=10 0B70. If I change the physical ID in a Neuron BL Heli, the 4 digit Hex value in Ethos increases one digit, but not the Physical ID = 10. In the DIY Ethos says that the physical ID is 10 and the application ID is the 4 digit Hex value 0B50.
Implementing 2 Neurons what should I do then? 
I have only the chance to change the physical ID in BL Heli. This increases the 4 Digit code in one Neuron. That should be good enough for distinguish, but Ethos ignores the change and can not show both sensors at the same time. But if I take one sensor away with different Physical ID in BL Heli and different Application ID, Ethos can interpret them correctly. In my German translation Ethos says that the physical ID is 10 and this is from my point of view now the wrong interpretation.

**Comment by dap35** [comment] 2022-03-18 22:07
I don't have any of the Neuron ESC's.  Have you tried making the change from within Ethos while a single ESC is connected?

**Comment by BernhardFe** [comment] 2022-03-19 16:14
Hi Doug,
I understood your request (in the latest manual it is good described) but all what I tested doesn't work, as well to change the physical ID in BL Heli32 (This must stay to Auto).
Then I found a possibility to change the Neuron 60S physical ID and the application ID. Only one telemetry sensors/values of all of a Neuron has an additional option. SBEC V has additionally the possibility to change the configuration in the Neuron. I changed for one Neuron the physical ID from 10 to 11 and an Application ID from 00 to 01. The ID changed from 10 0E50 to 11 0E51. Important is that the change can be done if only one ESC telemetry is connected. And it works!!!!
Both Neurons are displayed in the telemetry at the same time. Thanks a lot for the hint! But to use for the Neuron the SBEC V parameter to make this change, I found nowhere any hint. This should be a part of the ETHOS Manual as well. To find out that this parameter was the key I did by coincidence. Thanks a lot again. BR Bernhard

**Comment by bsongis-frsky** [comment] 2022-03-23 06:49
It should work out of the box if your 2 Neuron sensors have a different AppID and a different PhysID. We will do some testing.
The SubID is just used when 2 values (here voltage and current) are transmitted inside the same frame, then split into 2 different sensors.

**Comment by BernhardFe** [comment] 2022-03-23 07:36
Hi Bertrand, yes it works, but you need to know how to change in Ethos the both ID's manually. I did this for the 2nd Neuron and then it works. It will not change automatically if 2 Neurons detected. Then the values change into red and empty and no result will be shown.

**Comment by BernhardFe** [comment] 2022-03-23 07:39
Please have also a look on #1531 where I used the DIY sensor with one of the both Neurons. The DIY Sensor is also not working for V and A. It is fixed to maximum with the new ETHOS version 1.1.2.

**Comment by bsongis-frsky** [comment] 2022-03-23 07:55
Right, it won't change automatically. Good that it works, I will close the issue then.

**Closed by bsongis-frsky** 2022-03-23 07:55 UTC
Labels: information needed
