### ISSUE TITLE
Telemetry Sensor Conflict message every 30 seconds

### ISSUE THREAD

**Issue by michelkorthout** [FrSkyRC/ETHOS-Feedback-Community#1818] opened 2022-07-30 10:46 UTC
X20S running release 1.3.0
Receiver: Archer GR8 (fw 2.1.10)
Extra sensor: Unisens-E connected to the Sport (fw version 120)

Even after updating to this version, every 30 seconds a message is announced that there is a sensor conflict.

Tried using another sensor address for the Unisens-E but no luck.

**Comment by KevinFairgrieve** [comment] 2022-07-30 10:52
May not be related, but have you updated the "firmware" on the Unsense-E?

https://www.sm-modellbau.de/Firmwareupdates

Latest version 1.20

**Comment by michelkorthout** [comment] 2022-07-30 10:56
Hi, 
thanks for this tip, but my unisens-e is running this version.

**Comment by m0p3d** [comment] 2022-07-31 06:23
Confirmed - same here, all models mit unisense-e have the sensor conflict warning.
@bsongis-frsky Shouldnt this been fixed in 1.3.0

**Comment by m0p3d** [comment] 2022-08-26 05:24
@bsongis still open

**Comment by bsongis-frsky** [comment] 2022-08-26 07:01
Duplicate of #1827

**Closed** 2022-08-26 07:01 UTC

**Comment by m0p3d** [comment] 2022-08-26 09:35
@bsongis-frsky #1827 closed by the thread creator because he was able to confirm he could solve it.

But not true for all unisense related problems - several user still face the problem .

**Comment by bsongis-frsky** [comment] 2022-08-26 10:38
You have to change the AppId in your unisense sensor!
