### ISSUE TITLE
Add custom elevator curve butterfly

### ISSUE THREAD

**Issue by mirko91** [FrSkyRC/ETHOS-Feedback-Community#2740] opened 2023-07-10 21:50 UTC
Curently the butterfly mix allows to add a value to the elevator that will change proportionally to the input movement. Example: elevator weight 20%, I use the throttle stick as the source, stick full up, 0% butterfly, 0% elevator compensation, half stick 50% butterfly, 50% multiplied by the weight so 10% elevator, down stick, 100% butterfly, 20% elevator. Since the response it's never linear it will be a great addition to input straight into the mixer the elevator curve. I currently use a free mix with throttle stick as source, a 5 point curve and straight to elevator output. It will save one mixer and be faster to make

**Comment by mawzthefinn** [comment] 2023-07-10 23:08
This is a duplicate of #2375 

Please continue discussion under that issue

**Closed by mawzthefinn** 2023-07-10 23:08 UTC
Labels: duplicate
