### ISSUE TITLE
Copy Model from X20S -> X20 Pro (access)

### ISSUE THREAD

**Issue by jkeesaman** [FrSkyRC/ETHOS-Feedback-Community#2901] opened 2023-09-18 20:44 UTC
When you copy a model via the computer the output RF power is set for "????" which seems like range check power. If you just register and bind to the new transmitter it remains there, even after a range check. Probably should default to 25mw.

**Comment by mawzthefinn** [comment] 2023-09-19 02:09
Have you updated to 1.4.11?

I'm checking my X20PRO and models that were copied via computer and use ACCESS all are set to 25mW default, not ???

They came from an X18 on 1.4.9

**Comment by jkeesaman** [comment] 2023-09-20 07:07
Just checked 1.4.11 on both the X20S and X20 Pro.

Copy another model over and attached the screen grab.

![screenshot-2023-09-21-569](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50940192/ccba97f4-8283-415d-983e-7a53b7a71886)

**Comment by bsongis-frsky** [comment] 2023-10-05 15:49
Duplicate of #2946 which has been fixed yesterday. It will be available in 1.4.13 soon.

**Closed by bsongis-frsky** 2023-10-05 15:49 UTC
Labels: information needed
