### ISSUE TITLE
no sound after firmware update from 1.4.xx to 1.5.0

### ISSUE THREAD

**Issue by vasyly71** [FrSkyRC/ETHOS-Feedback-Community#3532] opened 2024-03-02 23:27 UTC
update firmware from 1.4.xx to 1.5.0.
Update process did not set default for general->audio->language->voice 1 (main) to some reasonable default. Sound did not work - greetings,goodby,check list etc.
 
After i manually updated it to us - started to work fine.

Would be nice if update process setup this value to some reasonable default.

**Comment by mawzthefinn** [comment] 2024-03-03 05:17
Functionally a duplicate of your #3532

Closing in favour of the second issue

**Closed as completed by mawzthefinn** 2024-03-03 05:17 UTC
Labels: duplicate
