### ISSUE TITLE
Feature: Ability to move screens

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#277] opened 2021-05-19 12:33 UTC
Hey there,

Currently, if you add a screen, its position is fixed and it goes to most right position of the screen (you always need to scroll right). Is there any chance to be able to change its position and re-arrange them? 
 
Thanks

**Comment by MrD-RC** [comment] 2021-05-22 06:01
While talking about screens. It would be nice to have the ability to change the screen type. Currently if you create a screen, the only option is to delete it. It would be great to have an edit, which pops up the screen layout selection box again.

**Comment by bsongis-frsky** [comment] 2021-09-28 11:41
Duplicate of #872

**Closed by bsongis-frsky** 2021-09-28 11:41 UTC
Labels: enhancement
