### ISSUE TITLE
Welcome to Ethos message ignores volume control

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#3417] opened 2024-02-12 06:27 UTC
1.5.0 RC2

The 'Welcome to Ethos' message ignores audio volume control settings. I have volume on the middle slider, and with the volume al the way down the audio is only muted half way through the word 'Welcome'.

**Comment by RealTadango** [comment] 2024-02-12 06:52
Duplicate of #3399

**Comment by bsongis-frsky** [comment] 2024-02-12 08:17
Duplicate

**Closed by bsongis-frsky** 2024-02-12 08:17 UTC
