### ISSUE TITLE
fonction in emergency mode

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#4440] opened 2024-08-26 18:49 UTC
Hi,

i add some conditions lines (quite a lot !) in the file below, everything is working on the simulator, so i put the file in my x20r. when i try to select the fonction menu the radio goes into emergency mode. I use ethos 1.5.13.
[mytho s5e.zip](https://github.com/user-attachments/files/16752503/mytho.s5e.zip)

Thanks

**Comment by bsongis-frsky** [comment] 2024-08-26 22:25
What do you mean by the "fonction menu"?

**Comment by bsongis-frsky** [comment] 2024-08-26 22:46
It is exactly the issue #4263 which should be fixed since 1.5.12

**Comment by bsongis-frsky** [comment] 2024-08-26 23:01
Reproduced here

**Comment by bsongis-frsky** [comment] 2024-08-26 23:13
It will be fixed in 1.5.15

**Closed as completed** 2024-08-26 23:13 UTC

**Comment by ronron84** [comment] 2024-08-27 05:17
Thanks
