### ISSUE TITLE
Lua-telemetry?

### ISSUE THREAD

**Issue by Aerial-Image** [FrSkyRC/ETHOS-Feedback-Community#772] opened 2021-08-10 07:00 UTC
Will the script 'lua-telemetry' for iNAV run on Ethos on a X20S?

**Comment by OldGazer** [comment] 2021-08-10 22:33
Not yet...  Supporting LUA is not as easy as changing a couple of lines of code.  Just be patient.  I'm waiting for LUA support so I can use Yaapu Telemetry.

**Comment by bsongis-frsky** [comment] 2021-08-11 06:47
Duplicate of #202

**Closed by bsongis-frsky** 2021-08-11 06:47 UTC
