### ISSUE TITLE
radio wont bind when I switch from a 900MHZ model to a 2.4GHZ moddle

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2704] opened 2023-06-24 22:12 UTC
when I have a 900MHZ model running then I switch to a 2.4GHZ model, it won't bind until I turn the radio off.  2.4 to 2.4 model is no problem.  haven't tried td mode to or from anything else. as I recal l2.4 to 900 works.

1.4.8 frsky 20S

**Comment by williajgr** [comment] 2023-06-27 12:37
anyone going to comment on this issue?

**Comment by bsongis-frsky** [comment] 2023-06-27 14:40
It has been pushed yesterday to the RF Team. Checks are needed, you will get an answer when available

**Comment by williajgr** [comment] 2023-07-11 19:02
seems like this is a dead issue??  seams like it could still be an ethos issue to me.

**Comment by williajgr** [comment] 2023-07-24 11:33
I still think this is an Ethos issue. it is not getting looked at.  anyone going to fix it????

**Comment by williajgr** [comment] 2023-07-26 13:47
Do i have to open a new issue to get someone to look at this?

**Comment by mawzthefinn** [comment] 2023-07-27 00:05
@bsongis-frsky confirmed the issue is on the RF side, not ETHOS. It's pending an update from the RF team.

**Comment by williajgr** [comment] 2023-07-27 11:34
Thanks, this will just be a firmware update to the isrm module correct?Sent from my iPhoneOn Jul 27, 2023, at 5:00 AM, LiNan ***@***.***> wrote:﻿
Hi, thank you for your feedback. we have fixed this, and will post the release version after internal testing. There is a test version for you:
TD-ISRM_2.2.5_TEST_20230727.zip

**Comment by williajgr** [comment] 2023-07-28 13:38
that did the trick, thanks

**Comment by kaiqueqds** [comment] 2023-10-31 14:49
On the FrSky site the last version still the 2.2.4, the testing of the firmware is done?

**Comment by mawzthefinn** [comment] 2023-11-22 03:58
TD ISRM V2.2.6 and TD ISRM PRO v1.1.12 have been released witha  fix for this issue

**Closed** 2023-11-22 08:50 UTC
Labels: RF issue
