### ISSUE TITLE
x20RS says that disk is unreadable on MacBook.

### ISSUE THREAD

**Issue by cdasso** [FrSkyRC/ETHOS-Feedback-Community#4647] opened 2024-10-21 11:45 UTC
When I connect my x20RS to my Mac is says that the disk is unreadable. Is it ok to format the disk in the disk utility on Mac?

**Comment by mawzthefinn** [comment] 2024-10-21 13:09
Are you on the latest MacOS? There's a known issue with current MacOS 15 having issues reading some USB storage devices. It's a MacOS issue, not an ETHOS issue.

**Comment by kramgrand** [comment] 2024-10-21 23:22
Assuming you are on 15.   If you click Ignore to the popups about the drive/s and then click switch to ethos (If you are in boot loader) Or switch bootloater (If you are in ethos) it will hopefully load correctly.   It's probably not a good idea to format.  I have found another way round it. I have a small USB C converter that has a USB A and SD card reader.  I put an SD card in the reader, the Mac identifies it....    and then I plug the TX into the USB A port.  So far, it has worked 100% of the time in loading the radio drives without any errors.   X20Pro..

**Comment by cdasso** [comment] 2024-10-21 23:46
Thank you. Now it seems to be hit or miss. I tried a different adapter and used the usb A port and it worked. I have to doubt it’s the Mac since it works on windows all the time. Was just hoping folks might have a fix. Yes I am on the latest version of macOS.

Thanks for the help! I know it’s not an ETHOS issue.

Cameron Dasso
________________________________

**Comment by kramgrand** [comment] 2024-10-22 23:17
Correct it is not the Mac or ETHOS..   It is Mac OSX.   Many issues reported on Mac forums about OS 15 and problems with flash drives etc.  Do a search..

**Comment by mawzthefinn** [comment] 2024-10-23 20:26
This is a functional duplicate of #4526 

It's a MacOS 15 issue, needs addressing by Apple one way or another

**Closed as not planned by mawzthefinn** 2024-10-23 20:26 UTC
Labels: duplicate
