### ISSUE TITLE
Ethos X20 telemetry max values wrong

### ISSUE THREAD

**Issue by combat-marcus** [FrSkyRC/ETHOS-Feedback-Community#393] opened 2021-06-02 17:59 UTC
Hello,

I am using the X20 with firmware 1.07.
I tested my new plane with a non-frsky sensor which is able to record speed, voltage, hight...

Ethos max value height: 126 m
Real hight: 169 m

Ethos max value vertical speed: 17 m/s
Real speed: 41 m/s

How can that be fixed?

Current, voltage and battery consumption works fine.

Best Regards and thank you
Marcus

**Comment by jreis1** [comment] 2021-06-03 07:34
which sensors (vario) are you using? 
I've been using Archer GRx8 and it seems very accurate to me. 

Bare in mind that 41 m/s is around 150kph which is a considerable airspeed already. (are you flying a wing or an hotliner?)

**Comment by combat-marcus** [comment] 2021-06-03 07:41
It is a Durafly Goblin model.
I am using a Sensor made in Germany with Frsk R9 SX OTA. Ist dont understand the difference in the date, 17 m/s to 41 m/s and als the height difference.

**Comment by bsongis-frsky** [comment] 2021-06-03 07:51
Duplicate of #363

**Closed by bsongis-frsky** 2021-06-03 07:51 UTC

**Comment by AfterburnerRC** [comment] 2021-06-17 21:26
Can you elaborate on the sensor being used as I am also looking for a speed sensor?
