### ISSUE TITLE
1.5.13 TIMER Edit: Mode down: No announcement audio for negative values.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4401] opened 2024-08-18 06:58 UTC
TIMER setup: Audio Actions: 
1) Count down: no audio when the timer goes negative.
2) Play value: Start audio before the start value.
No audio for negative values.

**Comment by mawzthefinn** [comment] 2024-08-18 13:48
Duplicate of #253 

please continue the discussion there

**Closed as not planned by mawzthefinn** 2024-08-18 13:48 UTC
Labels: duplicate

**Comment by philippe-warnotte** [comment] 2024-08-18 13:56
Ok for negative time but when you choice "Play value", the audio start  before the "start value"
