### ISSUE TITLE
X20 , Ethos 1.4.11 . ext ELRS Module no Vario sound

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2864] opened 2023-08-31 19:04 UTC
Using X20, ETHOS 1.4.11 with ext ELRS Module and new Radiomaster receiver ERxx. 

Vspd is transmitted correctly and can be displayed. Vario sound cannot be enabled with a switch since  the Vspd setup does not contain the option for a switch 
![screenshot-2023-08-31-58114](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/116186946/725b746c-9546-4046-896b-5a1420b9d522)

The CRSF protocoll has two baro packets defined. An old one (ID 0x07) which is no longer used, that contains only Vspd and a new one (ID 0x09) with Vspd and Alt. The Matek PWM converter uses the old ID 0x07 but is discontinued anyway (I think). All new ELRS PWM receivers like the Radiomaster ERxx use the new ID 0x09 with Vspd and Alt.

Ethos should support the new ID 0x09 so that the vario  tone can be enabled.

**Comment by mawzthefinn** [comment] 2023-08-31 19:26
Duplicate of #2801 

Fixed in 1.5.0

**Closed by mawzthefinn** 2023-08-31 19:26 UTC
Labels: duplicate
