### ISSUE TITLE
X20 Pro Timers issue going from 1.4.17 to 1.5.4

### ISSUE THREAD

**Issue by T16-Pilot** [FrSkyRC/ETHOS-Feedback-Community#3824] opened 2024-04-11 13:56 UTC
Hi, i just did a big mistake and upgraded my X20 Pro from 1.4.17 to 1.5.4, new is always better right? 

Not this time...

Out of my 23 models in the radio 6 now got a timer problem.

The issue is that when the TH Cut is active, that meaning motor not running. The timer is running.

When TH Cut is inactive and motor is running the timer is starting and stopping according to the TH stick no problem.

So the problem is when the motor is inactive and the timer is running even if the TH stick is down.

I have checked my programming and it is exactly as all the working models where the timer is working.

All this happend right after i did the update to 1.5.4

I even tried to make a new model and that had the same problem with the timer...

You might say that i am no too happy about this.

I uploaded one of the model files that has the timer issue.

[futura v3.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14946987/futura.v3.bin.zip)

Best regards
Simon

**Comment by bsongis-frsky** [comment] 2024-04-11 14:23
This one is fixed already in 1.5.6

**Comment by strgaltdel** [comment] 2024-04-11 14:24
...[edit]  sorry, overlapped posting ..

i don't use this kind of functionality,
but have read some comments in the german forum

maybe it's related to #3777,
which should be fixed in Ethos 1.5.6

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/726d9fba-06b5-470d-b498-4c24bb6c5c94)


may be you could try the 1.5.6 sim to check for success

**Comment by bsongis-frsky** [comment] 2024-04-11 14:25
I have checked his model in the simulator, the Timer stops when the Throttle is idle.

**Comment by T16-Pilot** [comment] 2024-04-11 18:30
> ...[edit] sorry, overlapped posting ..
> 
> i don't use this kind of functionality, but have read some comments in the german forum
> 
> maybe it's related to #3777, which should be fixed in Ethos 1.5.6
> 
> ![grafik](https://private-user-images.githubusercontent.com/20392683/321667460-726d9fba-06b5-470d-b498-4c24bb6c5c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTc1NDEsIm5iZiI6MTcxMjg1NzI0MSwicGF0aCI6Ii8yMDM5MjY4My8zMjE2Njc0NjAtNzI2ZDlmYmEtMDZiNS00NzBkLWI0OTgtNGMyNGJiNmM1Yzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE3NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZGMyODBlZjU5OTgwNWZlOTgzYmM3NmQ2ZDJlYjAzZGQ2ZDIzNTEyYjdiMzcyNTQ1NmE2NDNhZGRjMTIzYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K8Wn7TJBixfwFftvj0rux7fu1npTXKtNXamnGrYDV-Q)
> 
> may be you could try the 1.5.6 sim to check for success

Sorry No can do Sir, no simulator for MAC...

@bsongis-frsky Is 1.5.6 stable to fly? I am not going to upgrade before that happens.

I forgot to do a backup before leaving 1.4.17, so i am stuck on 1.5.4 for the time being...

**Comment by bsongis** [comment] 2024-04-11 21:06
You are punished then :)

**Comment by bsongis** [comment] 2024-04-11 21:07
1.5.6 will be marked as stable if no issue raises until tomorrow
I cannot see why it would be less good than 1.5.4 as it only fixes things

**Comment by T16-Pilot** [comment] 2024-04-11 21:48
> 1.5.6 will be marked as stable if no issue raises until tomorrow I cannot see why it would be less good than 1.5.4 as it only fixes things

@bsongis  Funny thing, i just flashed 1.5.6 and the problem is still there!

I am going to try an explain it again.

On some models Timer1 is running even when the TH stick is down AND the TH Cut switch is active, aka motor is not running.

If i flip the TH Cut switch and activate the motor. The timer only run when the TH stick is moved...

So the issue is NOT fixed in 1.5.6

I found a backup of my models, and restored back to 1.4.17 and the Timer is working again.

Best regards
Simon

**Comment by bsongis-frsky** [comment] 2024-04-12 06:40
I have checked the model you pasted above. Are you talking about another model? Would you attach it here?

I reopen the issue to be sure not to forget it!

**Comment by T16-Pilot** [comment] 2024-04-12 19:39
> I have checked the model you pasted above. Are you talking about another model? Would you attach it here?
> 
> I reopen the issue to be sure not to forget it!

Yes it is that model and 5 more. Out of the 23 models i got in my X20 Pro, 6 has this timer issue.

I also tried to setup a new model and that had the same problem with the timer.

This problem might be special for the X20 Pro. Others in my club with X20, X20s and X18 do not have this problem.

Testing my model file in the X20/X20s simulator might not show the problem?

By the way, i am a MAC user and can´t test the simulator because it is Windows only at the moment.

I am now back on 1.4.17 and all my models are ok now. No problems with timers.

Best regards 
Simon

**Comment by bsongis-frsky** [comment] 2024-04-15 13:08
Duplicate of #3842

**Closed as completed by bsongis-frsky** 2024-04-15 13:08 UTC

**Comment by T16-Pilot** [comment] 2024-04-15 16:07
> Duplicate of #3842

Not realy, i was the first to start the topic... #3842 was opened after my tread.

But i don´t care as long as it is being fixed.

Best regards
Simon
