### ISSUE TITLE
Feature request: trim enhancements

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2402] opened 2023-02-09 19:11 UTC
After the 1.5.0 nightly, there are just two features remaining which are needed for my sailplane templates to achieve the same functionality as OpenTX.  These are:

**1. Disable trim**
- Disable a trim so it behaves like two dumb momentary switches (one for up, one for down). No beeps or repeats. Configurable per flight mode.
- A way to return the state of a disabled trim button, so that clicks can be detected in Lua scripts. Maybe something like the Eu, Ed etc. switches in OpenTX.

This is required in order to port my [dynamic curve adjuster Lua script](https://rc-soar.com/opentx/lua/adaptivetrim/index.htm):

**2. Share trim settings**
- share trim settings between two or more flight modes

This is useful for sailplanes and other models the elevator trim may be the same in two or more flight modes.

**Comment by mawzthefinn** [comment] 2023-02-09 20:54
This is a duplicate of #1382 which is on the milestone for 1.5.0 at the moment, regarding disabling trims per-FM and shared trims per-FM. 

Trim Positions are always available as momentaries in ETHOS today, regardless of trim active condition. They are a category of switches.

**Closed by mawzthefinn** 2023-02-09 20:54 UTC
Labels: duplicate

**Comment by strgaltdel** [comment] 2023-02-10 08:30
Hi Mike,
regarding Trim Positions within lua:
this should be available in the upcoming 1.4.7
by chance i opened an issue for the same reason some days ago:
#2396

regarding curve adjuster,
did you port it ?
yesterday i published a similar script as a beta in a german forum
in case you're interested in the code for "inspiration reasons", pm me
unfortunately by now no english docu,
you can get an impression by looking into a video
https://youtu.be/vIm0cenvDsw
inflight curve editor
from 0:55 until 3:15

**Comment by RC-SOAR** [comment] 2023-02-10 12:06
Hi Udo, I started porting it to Ethos the last year, then but it on the back burner as it was clear it could not be fully implemented. Thank you for raising #2396 - this will be key for the completion of the script.  Your In flight curve editor also looks like a great basis for a dynamic trim system!
