### ISSUE TITLE
trim adjust

### ISSUE THREAD

**Issue by akallmann** [FrSkyRC/ETHOS-Feedback-Community#2389] opened 2023-02-02 18:31 UTC
Could it be possible to transfer trim to subtrim with a simple action on X20 software.
This solution is available on other remote brand and it is very easy to get neutral trim when a model is set up.

**Comment by mawzthefinn** [comment] 2023-02-02 21:22
Duplicate of #368 

Closing off in favour of the earlier Issue, please continue the discussion there

**Closed by mawzthefinn** 2023-02-02 21:22 UTC
Labels: duplicate
