### ISSUE TITLE
1.1.0-alpha17 Minor bug i displaying model images

### ISSUE THREAD

**Issue by mmasch** [FrSkyRC/ETHOS-Feedback-Community#1366] opened 2022-01-21 19:37 UTC
After installing 1.1.0-alpha17, and after sorting the models into new groups, it seems the model images takes more time to display than before. All images are .bmp files.
As said... Minor bug. 

Br. Morten  Masch.

**Comment by bsongis-frsky** [comment] 2022-01-24 07:29
Duplicate of #1378

**Closed by bsongis-frsky** 2022-01-24 07:29 UTC
