### ISSUE TITLE
X12S Add Sbus  in and Sbus out on  Module bay for Student Trainer Wireless Link 

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2339] opened 2023-01-17 12:00 UTC
X12S add Sbus in and Sbus out on module bay for wireless trainer System Add support for  Access or D16 V2

![OpenTX_Manual_Deutsch_1-99 (1)-combined_Page_112_Image_0001](https://user-images.githubusercontent.com/9161926/212895765-48ad0d8c-50c0-4b1a-b6e0-8846979c628a.jpg)

**Comment by mawzthefinn** [comment] 2023-01-18 04:41
This is functionally a duplicate of #784.

Closing off in favour of that one. SBus on the DSC sockets, Module bay and S.Port jack would all be useful additions.

**Closed by mawzthefinn** 2023-01-18 04:41 UTC
Labels: duplicate

**Comment by yak-54** [comment] 2023-01-18 07:17
i dont wont it dsc on the model pins in the module bay

**Comment by yak-54** [comment] 2023-01-18 08:05
and i have some with JR radios and spectrum  i still help out that i use the cable for

**Comment by yak-54** [comment] 2023-01-18 08:36
> This is functionally a duplicate of #784.
> 
> Closing off in favour of that one. SBus on the DSC sockets, Module bay and S.Port jack would all be useful additions.

don't think its better i would say its isolates more of the older frsky radio

**Comment by yak-54** [comment] 2023-01-18 08:57
In use the DCS plug  with an sbus to Cppm now works fine with the master on ethos  with all the older Accst systems with the XM receiver 
but now  they are getting  newer X20 and X18 and i don't wish use the cable as it gets in the road 
![20210204_173745](https://user-images.githubusercontent.com/9161926/213126154-cd3bee12-12cf-4a64-85b1-c61b7c0bedd1.jpg)
