### ISSUE TITLE
Feature request: Add +/- values to telemetry data

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#242] opened 2021-05-14 21:27 UTC
Hey guys, 

Open TX has the chance of adding to the telemetry screen, the current value of a specific parameter (e.g. RSSI) but also its min (-RSSI) and max (+RSSI) values. 

I'm not able to find this feature in Ethos. Can you please add this to the OS?  

Cheers :)

**Comment by MIKE-DAILEY** [comment] 2021-05-14 21:30
Duplicate of #240

**Closed by MIKE-DAILEY** 2021-05-14 21:30 UTC
