### ISSUE TITLE
Little issue in 1.5.11. Return icon not active

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#4260] opened 2024-07-12 11:45 UTC
To be clear, this is what I mean. It does not work on any screen.
![image](https://github.com/user-attachments/assets/e8208e22-23ce-4594-b8fd-615ce5f36f1e)

**Comment by bsongis-frsky** [comment] 2024-07-12 12:26
Duplicate of #4248 and already fixed in latest nightlies

**Closed as completed by bsongis-frsky** 2024-07-12 12:26 UTC
