### ISSUE TITLE
V1.5.0. RC2 X20S  Test for a Counter with VAR does not work

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3421] opened 2024-02-13 06:47 UTC
V1.5.0.RC2 X20s tests for a counter with the Var function
upwards downwards in fixed steps, preset
Test with up down with switch, with FS buttons, with clock generator 0.5s
The Ede function does not work
The hardware is too fast
What works on the simulator does not work with the real hardware 

Instead of only one step per impulse, there are always several steps. sometimes 1, sometimes 2, sometimes 3 steps

Same effect with extra trim

so you can not realise counters with inc, dec

and the autorepeat ist to fast

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/3814f05a-e4c8-4c11-ae87-db1448408a65)

![2024-02-13_074708 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/127be4f3-60ac-4f5a-ad13-18b0af638de5)

![2024-02-13_075953 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/e4ebdeb8-255c-4703-a4e7-25aeb1c2c05b)

![2024-02-13_080113 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/3dd2fb87-44b5-4a7b-97ec-bc56123a224e)

**Comment by bsongis-frsky** [comment] 2024-02-13 08:17
It's already fixed in the latest nightlies! I would appreciate to have your feedback!

**Comment by bsongis-frsky** [comment] 2024-02-13 08:18
Duplicate of #3413

**Closed by bsongis-frsky** 2024-02-13 08:18 UTC
Labels: bug

**Comment by hrenz** [comment] 2024-02-13 11:23
Thanks will to tonight

**Comment by hrenz** [comment] 2024-02-13 20:59
Yes it works 
thanks
