### ISSUE TITLE
[req] "Special function" to activate telemetry screens

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2248] opened 2022-12-27 11:51 UTC
It would be so great to have sth like this:

![image](https://user-images.githubusercontent.com/42830563/209662606-2d23fcaa-27f2-4478-a61e-520a41641fcb.png)

This would allow us to define what we want to see on the screen depending on flight mode or situation (like preflight, flying, post flight checks).

Examples:
- in preflight (throttle cut engaged, timer is at zero) show screen number 1
  - model image
  - battery voltage
  - BEC voltage
- if flying (no throttle cut) show
  - timer
  - RPM
  - current
  - etc.
- after flight (throttle cut engaged, timer > some value)
  -  show flight stats to find out if there were any problems, like
  - max current during flight
  - max ESC temp
  - lowest battery voltage
  - lowest BEC voltage
  - lowest RSSI and VFR
  - etc.

This would be super useful.

**Comment by miksterr** [comment] 2022-12-28 10:53
Great idea - could toggle through with a switch also.

**Comment by mawzthefinn** [comment] 2022-12-28 13:50
Great idea, and a duplicate of #652 

Closing off in favour of the older Issue, but please add your full comment there, it's excellent.

**Closed by mawzthefinn** 2022-12-28 13:50 UTC
Labels: duplicate
