### ISSUE TITLE
LUA / storage in `registerSystemTool` or `registerSource` scripts does not work

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2315] opened 2023-01-09 13:26 UTC
Trying to use `storage.read` or `storage.write` in "system tool" or "source" scripts always fails with one of those:

```
029232 storage.read error: storage not ready
029232 storage.write error: storage not ready
```

(numbers vary).

My guess is, it is implemented only for widgets now, and storage is probably per widget instance.

But we do need some way of configuring and persisting configuration of system tools and also of LUA sources. `system.registerSource` allows to mimic in some way open tx mixing scripts, but it lacks any configuration or input (in mixing scripts these were "inputs"):

![image](https://user-images.githubusercontent.com/42830563/211318024-1f5ed14e-5afb-4aa2-b1de-4efec33b26cb.png)

I suspect the idea is to configure such LUA source over a system tool, but for this we need working forms and storage. Storage is needed in both types of scripts.

It would be also great to have both model-wide and system-wide storage option.

**Comment by azaz44** [comment] 2023-04-14 07:07
Still needed. But maybe solutions will come with #2338

**Comment by bsongis-frsky** [comment] 2023-04-14 08:05
Duplicate of #2338

**Closed by bsongis-frsky** 2023-04-14 08:05 UTC
Labels: enhancement, Lua
