### ISSUE TITLE
WAV format ?

### ISSUE THREAD

**Issue by aviat40** [FrSkyRC/ETHOS-Feedback-Community#815] opened 2021-08-18 17:41 UTC
Hello bertrand

Did you change something with the wav format, homemade wav files don't work anymore ?

Was working fine on 1.0.10 !

Thanks

**Comment by mawzthefinn** [comment] 2021-08-18 17:42
Check to see if it's 16bit, 32KHz, mono

I know 16KHz wav files were working on 1.0.9, but 1.0.10 seems to require 32KHz.

**Comment by aviat40** [comment] 2021-08-18 17:48
Same as #807, i will try. 

Thanks

**Comment by hrenz** [comment] 2021-08-18 17:57
There is no reason to change everything to 32khz that has been running up to now, 
No one needs that.
Good software accepts both 16kHZ und 32khz

**Comment by aviat40** [comment] 2021-08-18 18:04
I checked, all my files was already in the good format.

**Comment by Hobby4life** [comment] 2021-08-18 19:03
Please guys more details with your issues.. radio?!???

**Comment by aviat40** [comment] 2021-08-18 19:08
X20 with 1.0.11 RC1 with SD / FLASH updated

**Comment by bsongis-frsky** [comment] 2021-08-19 08:30
Duplicate of #816

**Closed by bsongis-frsky** 2021-08-19 08:30 UTC
