### ISSUE TITLE
GPS Map Tracklog

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3888] opened 2024-04-22 09:38 UTC
I tested the GPS map yesterday and was wondering if it was somehow possible to make the flown track visible on the map.  Breadcrump is the name of the tracklog in general aviation.  Thank you

**Comment by bsongis-frsky** [comment] 2024-06-18 13:23
Duplicate of #3881 which is fixed in 1.5.10

**Closed as completed by bsongis-frsky** 2024-06-18 13:23 UTC

**Comment by WhiskeyGolf** [comment] 2024-06-18 17:20
I actually wanted the route flown to be visible on the transmitter. As a line in the GPS map on the GPS widget. So far you can only see a point here. But since I can't look at the display during the flight, it's no use to me. However, it would be important for me to be able to see whether I stayed within the area. You could then delete the line using flight reset. Hope that works! Thank you very much!
