### ISSUE TITLE
Request: Instant Trim in Special function for ethos

### ISSUE THREAD

**Issue by wizan9z** [FrSkyRC/ETHOS-Feedback-Community#513] opened 2021-06-18 02:29 UTC
It will be a great help to have instant trim assignable to a momentary switch in special functions similar like the one in OpenTx. This greatly helps out the pilot during maiden of any planes. Thank you.

**Comment by centertrim** [comment] 2021-06-18 10:13
Duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/295

**Closed** 2021-06-18 10:33 UTC
