### ISSUE TITLE
Xact servo - interface enhancements 

### ISSUE THREAD

**Issue by TalperRC** [FrSkyRC/ETHOS-Feedback-Community#2130] opened 2022-11-27 12:36 UTC
1. access single Servo based on it's address to store parameters  while connected to Fbus 
today accessing and saving servo parameters requires a single servo connection to FBus if more than one servo is connected when you save the configuration you override the data on all the connected servos. 

2. servo adjustment and telemetry screen 
The Frsky Xact servo provides useful telemetry data that can be quite useful when adjusting servo endpoints

In the current interface
Adjusting servo endpoint is being done in one screen (ch output screen) and monitoring servo current is being done in different screen (Telemetry screen)

It could be very usful if you can provide a screen that allow servo endpoint calibration and display relevant servo current on the same screen

**Comment by mawzthefinn** [comment] 2022-11-27 14:33
1. Duplicate of #989
2. Duplicate of #1617 

Both are worth asks, but already being tracked under other issues

Closing as Duplicate, please continue discussion of these requests under those issues.

**Closed by mawzthefinn** 2022-11-27 14:33 UTC
Labels: duplicate
