### ISSUE TITLE
X20S Emergency mode in model switch

### ISSUE THREAD

**Issue by HirezRa** [FrSkyRC/ETHOS-Feedback-Community#1163] opened 2021-11-27 20:00 UTC
While changing model, the remote goes into emergency mode.
Turning the remote off and on, eliminated the problem.
I was able to recover later from the glitch, see attached video.

When switchi from **model04.bin** to **model01.bin**

[model04.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7612355/model04.zip)
[model01.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7612357/model01.zip)

I copied all the files to another SD card, and now can not recover the failure.
I uses again the original SD card, and also failed to recover the glitch failure.

https://user-images.githubusercontent.com/43018322/143720599-f40e056b-9f95-4e32-985d-9282f5b006b2.mp4

Also upload LOG files.
[logs.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7612334/logs.zip)

Firmware Version 1.0.14, FCC
TD-ISRAM 1.4.0 FW: 2.1.9 (FCC)
![20211127_152824](https://user-images.githubusercontent.com/43018322/143720498-cf5ec7f3-e939-4046-9f2d-6203f3e6752e.jpg)

**Comment by mkdaw** [comment] 2021-11-28 10:43
Horus X10 ismr the same problem

**Comment by mkdaw** [comment] 2021-11-28 10:44
In alpha version 2

**Comment by KAID-YANG** [comment] 2021-11-30 07:38
can you upload all your files in the SD card?

**Comment by HirezRa** [comment] 2021-11-30 21:28
> can you upload all your files in the SD card?

Here it is

**Comment by HirezRa** [comment] 2021-11-30 21:31
Here a link to my Files 
https://drive.google.com/file/d/1_xzdk9fSbUkCGT_mzg7OzJ0VEuMrHb8A/view?usp=sharing

**Comment by HirezRa** [comment] 2021-11-30 21:31
> can you upload all your files in the SD card?
https://drive.google.com/file/d/1_xzdk9fSbUkCGT_mzg7OzJ0VEuMrHb8A/view?usp=sharing

**Comment by bsongis-frsky** [comment] 2021-12-03 15:19
I cannot reproduce it.

**Comment by bsongis-frsky** [comment] 2021-12-03 15:39
Duplicate of #1162

**Closed by bsongis-frsky** 2021-12-03 15:39 UTC
