### ISSUE TITLE
TW R8 Blackbox still no data in Ethos 1.5.0

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#3182] opened 2023-12-27 15:23 UTC
X20 Ethos 1.5.0 RC0 EU LBT
Twin Lite Pro Module 1.0.5.EU LBT
TW R8 1.0.7

Black Box has all lines empty, no data is shown at all.  Telemetry screen shows all receiver telemetry .data.

**Comment by mawzthefinn** [comment] 2024-01-01 19:34
Duplicate of #2910 

Issue is with receiver firmware.

**Closed by mawzthefinn** 2024-01-01 19:34 UTC
Labels: duplicate, Not a bug in Ethos, RF issue
