### ISSUE TITLE
Switch mapping - XE

### ISSUE THREAD

**Issue by miksterr** [FrSkyRC/ETHOS-Feedback-Community#2229] opened 2022-12-21 12:24 UTC
Would be good if the XE could allow mapping of all switches. Would give flexibility when adding, moving or changing switches.

**Comment by Dsrenger** [comment] 2022-12-21 13:49
Second that

Would be great to allow mapping. 
Would make the change from the X20S to the XE and back much easier.

**Comment by mawzthefinn** [comment] 2022-12-21 15:01
I thought it did allow that? 

https://www.rcgroups.com/forums/showthread.php?4231101-New-FrSky-XE-Tandem-24-Channels-with-ETHOS

Check the last image posted on the original post.

**Comment by Dsrenger** [comment] 2022-12-21 15:37
E.g. if you use switch SA on the X20S for the brakes.

You can change the switches in the XE hardware menu E.g. rename SE to SA and SA to SE.

After importing the x20s model the mixer shows SE as input instead of SA. The physical switch on the XE that you need use is always the same. You need to go into the mixer and reassign the switch.

The menu is not a remapping, it is just a renaming.

My expectation was that I can remap the switches.

My brakes on the x20s are always on the upper left switch. The switch name of the upper left switch in the x20s does not correspond to the switch in the upper left of the XE.
If I rename the upper left switch of the XE to the name of the x20s upper left switch, the physical switch I need to use on the XE does not change, because the input in the mixer does get renamed as well.

At the moment I have to go into every mixer, special function and reassign every input.

But perhaps I do something wrong or it is working as designed.
 Would be great if you can check.

Sorry, I hope you can understand what I mean. English is not my native language :)

**Comment by Dsrenger** [comment] 2022-12-21 16:02
To enhance on my comment.

It is clearly a renaming. You can assign the name SA to every switch.

Seems the mixer identifies the switch on a internal ID instead of the name.

Guess a real remapping should use a pull down menu instead of a text field.

**Comment by Target0815** [comment] 2022-12-21 16:46
> Check the last image posted on the original post.

Jet_Flyer removed these images from the linked post a few minutes ago ...

**Comment by hrenz** [comment] 2022-12-21 19:00
The technically easiest software solution now would be to integrate a real switch mapping into ETHOS, 
which has the 8 same default mappings of all FrSky transmitters in the basic version.
EFx --- xGH
ABx --- xCD

This could also be selected in the General menu as.
Switch assignment compatible to: "X20 1-8" or "XE 1-12" or "Freely adjustable".
Then the whole incompatibility problem would be eaten
and one could copy models of the X20 1:1,
with exactly the same switch assignments and switch designations.



Translated with www.DeepL.com/Translator (free version)

**Comment by hrenz** [comment] 2022-12-21 19:03
The technically easiest software solution now would be to integrate a real switch mapping into ETHOS, which has the 8 same default mappings of all FrSky transmitters in the basic version.
EFx --- xGH
ABx --- xCD

This could also be selected in the General menu as.
Switch assignment compatible to: "X20 1-8" or "XE 1-12" or "Freely adjustable".
Then the whole incompatibility problem would be eaten
and one could copy models of the X20 1:1,
with exactly the same switch assignments and switch designations.



Translated with www.DeepL.com/Translator (free version)

**Comment by bsongis-frsky** [comment] 2022-12-21 19:21
Good idea for 1.5.0

**Comment by Sudar-ch** [comment] 2022-12-21 20:20
also very important for faders. E.g the fader with dented center position from the X20 is not a fader on the XE even worse its a pot without dent position....

**Comment by Dsrenger** [comment] 2022-12-21 20:30
Agreed

**Comment by strgaltdel** [comment] 2022-12-22 06:48
Under oTx I have also migrated models from the X12 to the X-Lite.
A mapping of switches AND analogue inputs would have been helpful,
So i support both options.

As a supplement:
By migration to a "smaller" Tx, the user usually lacks inputs, so that not all switches etc. can be remapped.
In a further expansion stage, I would even like to be able to replace these "gaps" with fixed values.

These values would then "simulate" the missing inputs in the "neutral position", which would make it easier to migrate back to a larger transmitter.

I guess this could be helpful in view of an upcoming X24.

**Comment by bsongis-frsky** [comment] 2023-02-20 12:22
![image](https://user-images.githubusercontent.com/50834778/220106167-cb6b8564-62bc-46e5-9fb6-a4146e6d578c.png)

**Comment by bsongis-frsky** [comment] 2023-02-20 12:23
It will be available in the next nightlies!

**Closed by bsongis-frsky** 2023-02-20 12:22 UTC
Labels: enhancement

**Comment by flyingeek** [comment] 2026-04-07 03:18
Why is this available only only on XE ? I think this would allow to remap switches more easily no ?
Example: TWXLITE switches:
SC and SD are at the back
![twlite](https://p169.p3.n0.cdn.zight.com/items/lluLonAz/6bf29e1c-08a4-4a1d-bd6f-ce11b6dd6515.jpg?v=83ef42b42bfacd8aa800ce14d3b76643)
SF and SH at the back
![x18](https://p169.p3.n0.cdn.zight.com/items/12uYvKjA/4f6dde13-3a25-466a-b830-4ef633c9b3ce.jpg?v=426babab659f28dbe7899233ca5bb4e2)
So it would make sense when running the same model on two different radios to says I want to remap switch SC to switch SF, currently you have to use complex logic programming to assign switch using logic switches.

I would not have asked for it, but since you have already developed it for the XE, why not entend the possibility ?
