### ISSUE TITLE
Issue with flight phases since 1.2.11

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#1771] opened 2022-07-01 11:08 UTC
![IMG_20220701_130036](https://user-images.githubusercontent.com/89158034/176883209-9d3bc5f1-f64e-4e7b-927f-c915bf4997f0.jpg)

Since the 1.2.11update, we can no longer tick the desired flight phases in the mixes.
X20 eu firmware

**Comment by bsongis-frsky** [comment] 2022-07-01 12:19
Duplicate of #1765

**Closed by bsongis-frsky** 2022-07-01 12:19 UTC
