### ISSUE TITLE
"Reset Telemetry" does not work for calculated sensors

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4242] opened 2024-07-08 08:39 UTC
Ethos 1.5.9.
Related to this one: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/4217 and there's an example of calculated sensor there. But I think this is a different issue.

"Reset Telemetry" does not reset min/max values for calculated sensors.
Examples (normal sensor on the left, calculated on the right):

Before reset:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/092b7fc4-726e-4c74-8b3f-3fda7ded2e7a)

After reset:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/7dcfb8c0-06d1-4f5a-ae66-e812331a164c)

It is possible to reset this data by going to this widget and selecting "Reset V cell Min", then it works. So it looks like some reset code for calculated sensors is there. But maybe "Reset Telemetry" just forgets to include these.

**Comment by doppleganger53** [comment] 2024-07-08 14:30
I just noticed the exact same issue in 1.5.9 for my voltage callout while flying yesterday. Strangely I think it was working on a different model last week, will have to do some checking to see if that's the case.

**Comment by bsongis-frsky** [comment] 2024-07-09 05:35
Duplicate of #4217

**Closed as completed by bsongis-frsky** 2024-07-09 05:35 UTC
