### ISSUE TITLE
Scrolling broken in text / md browser

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4036] opened 2024-05-16 15:11 UTC
Ethos 1.5.7

When browsing .txt or .md files which take more than one screen, it is not possible to scroll the view. Rotary wheel doesn't do anything, nor the "page" button. Scrollbar indicator is visible though.

**Comment by bsongis-frsky** [comment] 2024-05-16 18:28
Duplicate of #4029

**Closed as completed by bsongis-frsky** 2024-05-16 18:28 UTC
