### ISSUE TITLE
Request: Trim mixers should be availabe per flight mode (as an option)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#1530] opened 2022-03-12 13:42 UTC
Currently the 4 physical trims can either be Independent per flight mode or not. 
However the Trim mixers are (as far as I can work out) always applied across all flight modes.

It is often useful to be able to adjust things while airborne such as differential, weights of various other mixers etc. which we may want to be differrent in different flight modes (especially differential and elevator compensation). Currently the options appear to be 
a) to repurpose the throttle and rudder physical trims which isn't always ideal.
b) to use one channel for each trim per flight mode, so with 5 FM, you'd use 5 channels to have different differential trim in each FM, another 5 for elevator compensation etc. and perhaps using SI/SJ to adjust the trim values.
c) to use sliders / rotary dials as trims, however these are then incorrect each time you change flight mode
d) to only be able to adjust one trim flight mode per flight gradually hard coding each trim - again this isn't ideal as sometimes different conditions require different amounts of various trims. 

I can't help think that the Var mixer could partially be repurposed for this (or a new Trim Values mixer) with the Default weight being applied if a mixer trim is not per FM while additional weights would be automatically created for each FM and which would be adjusted instead of a channel (I'd imagine one set or another would be greyed out as appropriate.)  The output presumably could still be a single channel which is then used as input as normal but which acquires the value appropriate to the FM in use.

If mixer trims could be independent per flight mode without using a channel for each flight mode that should enable multiple mixer trims to be adjusted whenever desired.

I suspect this is similar to opentx GVars and am not sure whether this is already covered in the Add GVar request (which I don't exactly understand at present).

Thanks!

**Comment by loetefix** [comment] 2022-03-13 08:02
I did the same request from one of the first Ethos version.But seems it will be ignored. Also the preview on the right side (the graphic) did not work for the trim mixer lines.

**Comment by MrD-RC** [comment] 2022-03-31 19:33
It would be good to be able to disable trims per flight mode too. Again, requested ages ago.

**Comment by mawzthefinn** [comment] 2022-12-02 04:14
This is a duplicate of #577 and is being closed off in favour of the older issue for the same request.

Please continue discussion on that issue, this does need to be addressed.

**Closed by mawzthefinn** 2022-12-02 04:14 UTC
Labels: duplicate
