### ISSUE TITLE
RB35 & RB25 Failsafe Settings

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3485] opened 2024-02-22 10:02 UTC
Using RB35S or RB25S if you set your failsafe it will be important to set by default to 1500us to reduce the risk of breaking everything (servo and linkage and all others things) as per #2605 the issue should be solved  via new Lua script... 
and also the choice between **"ignore" "hold" "no impulse" and "normal"** 890 to 2110 ms

it's really important to solve this for the real use of the RB25/RB25S RB35/RB35S

with "old" RB30 and RB30+ failsafe work permitting to user to decide how to setup

**Comment by bsongis-frsky** [comment] 2024-02-22 11:06
It is not inside Ethos, yes?

**Comment by mgsanna** [comment] 2024-02-22 12:07
It's inside a Lua widget from frsky, instead the "old" rb30 and rb30+ is inside ethos in devices config.... 
without any hurry it would be nice to include as devices just like the "REMOTE NFC",  without the need to be like a third party devices with Lua widget

**Comment by mawzthefinn** [comment] 2024-02-22 14:26
This is actually an RB firmware issue, the Lua just supports what the firmware allows (including the default settings). The underlying issue is that the RB firmware doesn't support the other failsafe settings and defaults to 988uS. 

That makes it a duplicate of #2605 please continue the conversation there.

**Closed by mawzthefinn** 2024-02-22 14:26 UTC
Labels: information needed
