### ISSUE TITLE
Throttle lever

### ISSUE THREAD

**Issue by dobosatti** [FrSkyRC/ETHOS-Feedback-Community#78] opened 2021-04-14 07:07 UTC
I can't set up a basic thing with ETHOS.
That the throttle base position is reversed. That's how I use gas. (see picture)
It’s ridiculous that ETHOS doesn’t know. During my 35-year RC career, all the radios I used knew this feature. Why doesn't ETHOS know?
When turned on, it warns you that the throttle is in the wrong place. I can't start the timer with the throttle either, because the clock is already running when the Tx is turned on.
![IMG_20210414_084955](https://user-images.githubusercontent.com/32070803/114668067-962ca080-9d00-11eb-8421-9ab4723c0f31.jpg)

**Comment by MIKE-DAILEY** [comment] 2021-04-14 15:35
Duplicate of #12

**Closed** 2021-04-27 12:17 UTC
