### ISSUE TITLE
"Sensor lost" false alerts

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#2052] opened 2022-11-06 20:23 UTC
My buddies and I are using ethos in various 1.2.x - 1.3.x versions, and with all of them, running 3rd party sensors we get occasional "sensor lost" voice prompts.
1. all sensors are configured for 10s timeout
2. the logs (or live data) never loose any sensors for 10 seconds.
any idea why?

**Comment by bsongis-frsky** [comment] 2022-11-06 20:40
Perhaps the 3rd party sensors don't send any telemetry in due time? Perhaps you should try to increase the timeout?

**Comment by i3dm** [comment] 2022-11-06 20:44
> Perhaps the 3rd party sensors don't send any telemetry in due time? Perhaps you should try to increase the timeout?

as mentioned in the post all sensors are increased to maximum timeout of 10 seconds.
no sensors are lost for that long at any point.

**Comment by i3dm** [comment] 2022-11-07 05:02
seems like despite being configured for 10 seconds timeout, i get the alert on some sensors much faster.
this is a bit of a tough one as you never know whats lost and when in real time. but does seem like there may be a bug in there somewhere.

**Comment by bsongis-frsky** [comment] 2022-11-07 07:31
Please send your logfile

**Comment by i3dm** [comment] 2022-11-07 08:04
i will make aome flights where there is certainly some alerts. and will upload the log.

**Comment by EngelMT** [comment] 2022-11-08 05:28
Sensor lost is not only an issue with 3rd party sensor. This also happens with FrSky sensors.  And even with internal sensors.

**Comment by i3dm** [comment] 2022-11-08 06:46
> Sensor lost is not only an issue with 3rd party sensor. This also happens with FrSky sensors. And even with internal sensors.

thanks Andreas, i suspected that was the case from my feeling as well. do you have some logs to share?

**Comment by Target0815** [comment] 2022-11-08 07:26
The topic is quite extensive, because many sensors are used in combination with many different receivers, which may also use different firmwares.

It would probably help the user and the development and accelerate the troubleshooting if a log is written with sensor lost, which sensor is affected. From this, a pattern can be derived and one can work specifically on the problem.

Another problem will be that the PhyID and AppID are not consistently used together for the identification of a sensor. Some 3rd party manufacturers already have to specially modify the AppID, because otherwise allegedly duplicate sensors occur. Although the combination of PhyID and AppID was proven to be unambiguous. I would say that this is a systematic bug in the system, the cause of which should be eliminated as soon as possible.

**Comment by i3dm** [comment] 2022-11-08 07:37
> The topic is quite extensive, because many sensors are used in combination with many different receivers, which may also use different firmwares.
> 
> It would probably help the user and the development and accelerate the troubleshooting if a log is written with sensor lost, which sensor is affected. From this, a pattern can be derived and one can work specifically on the problem.
> 
> Another problem will be that the PhyID and AppID are not consistently used together for the identification of a sensor. Some 3rd party manufacturers already have to specially modify the AppID, because otherwise allegedly duplicate sensors occur. Although the combination of PhyID and AppID was proven to be unambiguous. I would say that this is a systematic bug in the system, the cause of which should be eliminated as soon as possible.

we have no means to find which sensor is affected, as no sensors are actually lost for 10 seconds, ever.
this is why i think it is an Ethos bug and not an RF fw bug. Ethos seems to accept all sensors in time (or at least for long enough to be under the timeout) and still alert of sensor lost occasionally.
configuring the timeout from 5s to 10s improves (lowers) the frequency of the alerts, but to me it feels like 10s might be more like 1s in real life and 5s is maybe 0.5s? perhaps a scaling issue?
either way, this bug is not critical in any means, but is very annoying and does cause people to keep asking me what is this alert, so its more of an appearance thing.

**Comment by bsongis-frsky** [comment] 2022-11-08 08:44
The CSV file would help to see if the values of all sensors are refreshed within the delay of 10 seconds.

You may silent this warning like this:
![image](https://user-images.githubusercontent.com/50834778/200517132-4008ca39-769e-4c79-b52c-3180f7d83400.png)

It would help to know which is the sensor which is not refreshed on due time!

**Comment by bsongis-frsky** [comment] 2022-11-08 08:46
> Sensor lost is not only an issue with 3rd party sensor. This also happens with FrSky sensors. And even with internal sensors.

Please elaborate? If you are referring to #2050 then it's a user connection issue I think

**Comment by i3dm** [comment] 2022-11-08 09:09
> The CSV file would help to see if the values of all sensors are refreshed within the delay of 10 seconds.
> 
> You may silent this warning like this: ![image](https://user-images.githubusercontent.com/50834778/200517132-4008ca39-769e-4c79-b52c-3180f7d83400.png)
> 
> It would help to know which is the sensor which is not refreshed on due time!

unfortunately that will not help too much, my jets usually run about 15 sensors (coming from two 3rd party devices) - and i have no idea about which sensors are causing issues (if any really).

**Comment by bsongis-frsky** [comment] 2022-11-08 09:22
Yes it will help, as it will silent the sensor(s) which don't send the values on due time. And perhaps you will be able to tell us which is the sensor which is involved!

A CSV file would help too

**Comment by i3dm** [comment] 2022-11-08 09:24
from looking at the telemetry menu live, all sensors seem to send live data all the time. im not seeing anything even remotely close to 10 seconds. i will try to get a log with the issue in it, it is sporadic so a bit hard to log as well.

**Comment by i3dm** [comment] 2022-11-11 18:25
no long to offer yet.
but hearing people seeing this issue more and more. its definitely a bug which needs investigating.

**Comment by mondiman** [comment] 2022-11-13 00:15
I'm also having this issue.  I'm also running the same 3rd party telemetry device as i3dm (Zavionix RDT). Log file attached
[VIPER-2022-11-11-14-04-30.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9996272/VIPER-2022-11-11-14-04-30.csv)

**Comment by EngelMT** [comment] 2022-11-14 08:25
Even if it is perhaps off topic. But the problem is not only with third-party sensors. It also happens with Frsky sensors. Many customers report about it in our forum. Please, please FrSky team, check the problem and fix it. I know it is not easy to reproduce.

**Comment by bsongis-frsky** [comment] 2022-11-14 08:56
@mondiman Does your VIPER file shows a Sensor lost? Otherwise I am afraid it won't help. 

@EngelMT you are saying it happens with FrSky sensors. Please tell us which are those sensors (the full setup, including radio and receiver), so that we can try to reproduce.

**Comment by bsongis-frsky** [comment] 2022-11-14 08:57
@i3dm we are still waiting for the logs as you promised

**Comment by i3dm** [comment] 2022-11-14 09:23
> @i3dm we are still waiting for the logs as you promised

sorry i dont fly so frequently. but i agree with Andy Engel this issue exists for a long time on different setups and needs to be remedied.

**Comment by i3dm** [comment] 2022-11-14 09:31
> All the log files we have looked at so far do not show a Sensor Lost although the warning does come up. However, there is also a Sensor Conflict warning.

my friends radios are usually kn 1.2 or 1.3 fw. we have sensor lost alerts but not sensor conflict.

**Comment by EngelMT** [comment] 2022-11-14 11:07
There are also reports here that something must have changed from 1.3.X onwards. Apparently, the sensor conflict warnings have been appearing since then. Could it be that the sensors were previously described via the Physical ID and the Application ID and then only via the Application ID from 1.3.X?

**Comment by bsongis-frsky** [comment] 2022-11-14 16:45
Right after takeoff ... perhaps one telemetry value is off limits during the timeout delay?

**Comment by i3dm** [comment] 2022-11-14 16:47
> Right after takeoff ... perhaps one telemetry value is always off limits during the timeout delay?

what does that mean? can you elaborate?

**Comment by mondiman** [comment] 2022-11-14 16:50
> @mondiman does your VIPER file shows a Sensor lost? Otherwise I am afraid it won't help.
> 
> @EngelMT you are saying it happens with FrSky sensors. Please tell us which are those sensors (the full setup, including radio and receiver), so that we can try to reproduce.

I don’t believe it shows any sensors lost unfortunately

**Comment by bsongis-frsky** [comment] 2022-11-14 16:58
@phaedra-tm What is ADC4 in your log file?

**Comment by i3dm** [comment] 2022-11-14 17:00
> Right after takeoff ... perhaps one telemetry value is always off limits during the whole duration of the takeoff? If values received are off limits then they are trashed as invalid.

 will recieve a value off limits trigger a "sensor lost" alert? if so that may be it.

**Comment by phaedra-tm** [comment] 2022-11-14 17:02
I have no idea.

**Comment by bsongis-frsky** [comment] 2022-11-14 17:10
Which is the sensor which sends ADC4? Is there a documentation? If I am not mistaken, either this sensor stops sending ADC4, or it doesn't fullfill the specification. Both cases I can close this issue ;)


![image](https://user-images.githubusercontent.com/50834778/201722417-c576289f-5d10-4904-a562-63652f05121a.png)

**Comment by i3dm** [comment] 2022-11-14 17:15
@bsongis-frsky  please do not close this issue until it is clear why so many people and setups are suffering from this.

will a value out of range cause a "sensor lost" prompt ?

**Comment by bsongis-frsky** [comment] 2022-11-14 17:17
I will close this issue either if it is fixed or when I am sure it's an issue which doesn't belong to the project

**Comment by bsongis-frsky** [comment] 2022-11-14 17:17
What is the 3rd party sensor, where is the documentation, what is ADC4?

**Comment by i3dm** [comment] 2022-11-14 17:18
> I will close this issue either if it is fixed or when I am sure it's an issue which doesn't belong to the project

ok.
can you answer my question please?
will a value out of range cause a "sensor lost" prompt ?

**Comment by EngelMT** [comment] 2022-11-14 17:23
If it were ADC4 in this case then it wouldn't explain the many reports with FrSky sensors.  These reports can be found on RCG and on our forums here. Something is wrong here.  But as long as FrSky does not write in the instructions what is allowed and what is not, we have to expect incorrect configurations from customers in addition to an error in ETHOS.  For example, nowhere does it say that only 2.4 GHz or 868 MHz receivers can be coupled via the SPort with ACCESS.  FrSky's advertisement for ACCESS only said that telemetry can now be received from 3 receivers at the same time.  I asked FrSky for an explanation.

**Comment by bsongis-frsky** [comment] 2022-11-14 17:31
> > I will close this issue either if it is fixed or when I am sure it's an issue which doesn't belong to the project
> 
> ok. can you answer my question please? will a value out of range cause a "sensor lost" prompt ?

Wrong values (out of bonds) will be ignored. If the sensor sends only wrong values during the timeout, it will be considered as lost.

Now you answer my questions? Which is this sensor, what is ADC4, what is the range used? It has to follow the FrSky specification of S.Port devices.

**Comment by i3dm** [comment] 2022-11-14 17:43
are you asking me about someone elses logs? sorry i do not know.
in my RDT sensor ADC4 is used for pump voltage. but thats not what youre asking?

**Comment by phaedra-tm** [comment] 2022-11-14 18:41
I'm trying to find information from the Unisens-E sensor, but it seems to me that it is the mAh consumed, when I compare it to my calculated sensor for consumption.  You see the ADC4 getting stuck at 34.89, then nothing.  That would explain why it happens after takeoff: when the consumption reaches a certain value.
It thus seems that it is a Unisens problem in my case, I will investigate further.

**Comment by bsongis-frsky** [comment] 2022-11-14 19:04
@phaedra-tm [Unisens-E] ADC4 should not be used for consumption, it is not inline with the S.Port specification. It would be nice to use the right AppID so that the sensor would be discovered automatically with the right unit and precision. Here Volts and precision are very wrong. Also the upper limit of ADC4 is not compatible with a consumption. Please not that FrSky is open to allow the creation of new AppID if needed. The vendors who have signed the NDA should just ask.

**Comment by phaedra-tm** [comment] 2022-11-14 19:14
I do not actually use it as such, I added my own calculated sensor.  The ADC4 value just happened to be there, I didn’t even know what it was.
It appears that there is a firmware update for this sensor, I will install that and then test whenever I get to do the next flight (or maybe just an engine run-up, to see what this value does after firmware update).

**Comment by i3dm** [comment] 2022-11-14 19:33
> @i3dm can you upload logs of your issue? Right now the only data @bsongis has for troubleshooting are the logs provided by others.

i dont have any at the moment. have seen this iasue with pretty much all of my buddies X20S.

**Comment by Target0815** [comment] 2022-11-15 07:57
> i dont have any at the moment. have seen this iasue with pretty much all of my buddies X20S.

I can understand why Bertrand becomes increasingly impatient with such answers ... You say you have messages with sensor lost, then please also see that you provide the data of the respective configuration. And if you don't know that at the moment, then ask for it ... 

Developers can not solve problems in which they only look into the crystal ball ...

**Comment by i3dm** [comment] 2022-11-15 08:18
> > i dont have any at the moment. have seen this iasue with pretty much all of my buddies X20S.
> 
> I can understand why Bertrand becomes increasingly impatient with such answers ... You say you have messages with sensor lost, then please also see that you provide the data of the respective configuration. And if you don't know that at the moment, then ask for it ...
> 
> Developers can not solve problems in which they only look into the crystal ball ...

sorry im doing what i can, no need to get upset. there are enough testimonies from different people to understand this is really an issue. i am trying to source the logs, but im not the only one having the issue.

**Comment by Target0815** [comment] 2022-11-15 08:47
> sorry im doing what i can, no need to get upset. there are enough testimonies from different people to understand this is really an issue. i am trying to source the logs, but im not the only one having the issue.

But **you** started this issue 9 days ago and have provided zero information so far. Doesn't that make you think? 

Whether other people also have problems is secondary. @EngelMT is already collecting information about this in the German forum and will certainly post it. But that doesn't change the fact that you don't document your problems so that Bertrand or FrSky can take a closer look.

By the way, I am so interested in it myself, because this topic costs Bertrand unnecessary time and other issues have to take a back seat because of that.

**Comment by phaedra-tm** [comment] 2022-11-15 12:52
Ok, my issue can be disregarded, I think.  I flashed the latest firmware in the Unisens-E sensor, and after that, the ADC4 telemetry parameter was inactive red  (according to the release notes, it has been replaced by another for consumption, which I didn't add).  I deleted the ADC4 from the list of telemetry values.
I did a ground test, running up the motor and letting the calculated consumption increase over 100mAh, and I didn't get any "sensor lost" message anymore.

**Comment by EngelMT** [comment] 2022-11-16 13:20
Today I start with own tests. Two 2.4 GHz receivers used wirh newest firmware. X20 also with newest ETHOS and TD-ISRM. I got only telemetry warnings if the receivers switched between Master (0) and Slave (1). This is o.k. so far.

But it doesn't match FrSky's advertising that telemetry can be transmitted simultaneously from 3 receivers in ACCESS.  Because the warnings in this test only come from switching because one receiver was an SR8 pro and the other a GR8.  Both have different sensors.

I will do more tests next days.

**Comment by EngelMT** [comment] 2022-11-17 11:16
Yes I have connected the SPort line.

I will test more today to give you a feedback.

**Comment by i3dm** [comment] 2022-11-17 21:31
One thing i found so far.
on my friend's model, which really suffered from this issue a lot, with RDT linton sensor, the ADC4 went out of range above 25 (maybe his Tx was set to ADC4 max 25V? i dont know) and may have caused part of the issue. in his old log, ADC4 marked in yellow:

![image](https://user-images.githubusercontent.com/8968780/202563546-df8ecfbf-2fdf-4903-a3dd-2b9e7f0b54de.png)

this is definitely part of the problem but NOT all of it, as some other RDT sensors limit ADC4 to 10.00V and still occasionally alert a sensor loss.
one thing i dont understand, why is ETHOS being an s.port protocol officer here? lets just display whatever comes in telemetry without a sensor lost alert. this limitation makes no sense to me.
PS this issue never existed in the past with OpenTX, possible to this limitation not being imposed by the OS.

**Comment by EngelMT** [comment] 2022-11-18 09:07
Hi together,

last days I do a lot of own tests with several different receivers and Frsky sensors. Of course, I could not wait for hours to see if a warning would come. But I would like to carefully note that with correct handling of the receivers (cable connection SPort etc.) I only received sensor warnings when switching from the master to the slave. That is also correct. FrSky has assured me that they will do a better documentation to make clear to the customer what is allowed and what is not. Because there are already some things that are not documented. For example, that you can only connect 2.4 GHz ACCESS receivers via the port, but not mixed with 868 MHz. And the fact that you can connect TDMX and TDR6 to the Sport, but not a TDR-18 or TDR-10 to a TDMX or TDR6 is also not documented anywhere.

I therefore think that the problem occurs primarily with third-party sensors. However, I will continue to keep an eye on reports from customers. If there is any other information, I will let you know.

**Comment by i3dm** [comment] 2022-11-20 08:06
i think were already certain that some (maybe most) of the alerts are due to third party sensors sending out of range values, causeing a false "sensor lost" alert when in fact sensor is operating fine but simply not obeying S.port protocol.

@bsongis-frsky is it possible to remove this limitation from Ethos? as an operating system, i think its not the OD job to limit this. but it is the S.port implementer (sensor) job to obey to the protocol.

**Comment by mawzthefinn** [comment] 2022-11-20 19:45
@i3dm - There have been issues in the past with not bounds checking sensors in ETHOS and OpenTX, particularly around altimeters.

I would not expect the OS to do anything with invalid data other than discard it, there’s no way to differentiate between ‘sensor is sending valid but out of bounds data’ and ‘sensor is sending garbage data’ and so the OS simply follows the defined spec. The same goes for CRSF data (spec says 1 decimal place of precision, so that’s what is displayed).

By following the spec exactly, the OS ensures that invalid data is not used for any channel inputs or logical tests, which is quite important if in-flight functionality is tied to those functions.

**Comment by mawzthefinn** [comment] 2022-11-20 19:46
Closing as per discussion with @bsongis.

**Closed by mawzthefinn** 2022-11-20 19:46 UTC
Labels: information needed
