### ISSUE TITLE
Low battery warning

### ISSUE THREAD

**Issue by faldomak** [FrSkyRC/ETHOS-Feedback-Community#2188] opened 2022-12-10 17:39 UTC
Yesterday while setting up  an model I turned radio volume down (mute) and also turned haptic off. Suddenly radio powered off because of empty battery without any visible warning (audible warning was not possible anyway). Battery low alarm should override volume setting (and haptic) and give big flashing screen warning. Radio is X18 and Ethos is 1.4.4

**Comment by mawzthefinn** [comment] 2022-12-10 17:45
Duplicate of #923, please continue conversation there.

**Closed by mawzthefinn** 2022-12-10 17:45 UTC
Labels: duplicate

**Comment by mawzthefinn** [comment] 2022-12-10 17:48
Also #919 is relevant
