### ISSUE TITLE
Apparent bug in Ethos 1.5x Nightlies Var programming. 

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#3127] opened 2023-12-07 22:28 UTC
![Ethos 1 5 variable increment test](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/7997610/e861a770-626d-4565-94eb-865e4942f5fd)
When using Actions 'Add(+)' and 'Subtract(-)' to change the value of a variable (Var), the selected action intermittently double counts. For instance, if a variable is programmed as per the attached picture, when switch H or J is clicked and released numerous times the count will sometimes jump 2 digits instead of 1. At times the switch may have to be pressed 100 or more times for this to occur, at other times the value might double count 3 or 4 times for every 10 times the switch is activated. This occurs in both the simulator and transmitter. I have tried using a Logic Switch programmed as an 'Edge' to increase/decrease the Var count with the same results. This leads me to believe it is caused by a bug in the Var Action programming.

**Comment by bsongis-frsky** [comment] 2023-12-18 10:56
Bug reproduced on simulator right now, trigger happens 2 times, searching for the reason ...

**Comment by bsongis-frsky** [comment] 2023-12-18 18:30
I hope it will be fixed in the next nightlies, please confirm!

**Closed by bsongis-frsky** 2023-12-18 18:30 UTC
Labels: bug
