### ISSUE TITLE
For the future, I ask that the timer' fonts size be proportional to the widgets' size. 

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4226] opened 2024-07-05 08:12 UTC
For the future, I ask that the timer' fonts size be proportional to the widgets' size.

**Comment by mawzthefinn** [comment] 2024-07-05 18:57
Duplicate of your #4065

**Closed as completed by mawzthefinn** 2024-07-05 18:57 UTC
Labels: duplicate

**Comment by philippe-warnotte** [comment] 2024-07-06 06:43
Ok but you closed this post too. So no one will take my remark. Look
powerbox

Le ven. 5 juil. 2024, 20:58, mawzthefinn ***@***.***> a
écrit :
