### ISSUE TITLE
Lua used too much RAM, it will be killed

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#4278] opened 2024-07-15 18:22 UTC
I have X20 Pro AW  1.5.11 and 2 Lua scripts ( Color Widget-Benno001),( status widget - Lothar Thole) and since I've updated to 1.5.10 this is happening to me on a few occasions. It is difficult to reproduce because it does not always happen.

When I was in 1.5.9 this didn't happen to me

![tempImagetiH1Sw](https://github.com/user-attachments/assets/45f0c6f9-b2dc-4fee-abe3-fa7bfc34890e)
![tempImageIVq7Ws](https://github.com/user-attachments/assets/ed6727b1-4105-452c-a42a-75730f42726f)
![tempImageGA9l1J](https://github.com/user-attachments/assets/f074c1a0-5ae4-4b8d-8053-6732003c9987)

**Comment by strgaltdel** [comment] 2024-07-15 20:45
out of curiosity
this appears to be an individual saturated red color of the Pro,
not the typical red-orange.
Is that right?
... very nice.

How did you get it?

about the scripts:
I would assume that one of the scripts does not call the garbage collector in time.
is it benno's script that is called multiple times?
he doesn't publish any source code for it
maybe it would be good to email him to see if he could check it

**Comment by jasalca** [comment] 2024-07-15 21:20
The radio is the typical orange of the Pro AW. The color varies a lot depending on the light you give it.I love it.

About the scripts, I have tried to contact Benno ,but he has been missing for almost a month, but the strange thing is that before updating this did not happen.

**Comment by strgaltdel** [comment] 2024-07-16 08:45
I've contacted Benno,

maybe it's a good idea to upload the template.
So Benno & Lothar would have a better chance to reproduce the issue.

**Comment by bsongis-frsky** [comment] 2024-07-16 08:55
I would say there is some memory leak in the Lua script, or some kind of history which is stored in RAM? 
I cannot review the script!

**Comment by jasalca** [comment] 2024-07-16 09:15
I'm still testing, and what I've done now is uninstall Benno´s Lua to see if it reproduces the problem with other scripts.
We´ll wait and see what Benno does now that he's been warned. Thanks to Strgatldel, and I understand Bertrand cannot review the script.

**Comment by Benno00** [comment] 2024-07-16 09:36
Hello,

since there is no longer a version 1.5.10, I unfortunately cannot understand it and there is still no documentation about what has changed in ETHO. So I am powerless at the moment.
Go back to 1.5.9 or uninstall the script

**Comment by Benno00** [comment] 2024-07-16 09:39
Hello Bertrand,

some of my LUA scripts are currently no longer running under 1.5.10 or 1.5.11. What has changed?
I need the information on what has changed so that I can fix it.

Thank you very much

**Comment by bsongis-frsky** [comment] 2024-07-16 09:48
Everything is written in the release note. But here there is no error, just too much RAM used. It would be interesting to know why so much RAM is used, or if there is something wrong on Ethos side. 

Without the script, I don't know how I can help!

**Comment by Benno00** [comment] 2024-07-16 10:57
Hi jasalca, 
here is a new Version for ETHO S1.5.11 
[colorwert 2.2.zip](https://github.com/user-attachments/files/16247554/colorwert.2.2.zip)

**Comment by strgaltdel** [comment] 2024-07-16 11:08
quick & dirty a simple source script which returns the lua free ram (kB)
could be used as the source for the line-chart widget:
(1 sec log duration / auto scaling  in my example:)
So one can monitor what happens in case he adds widget for widget

![image](https://github.com/user-attachments/assets/38612793-6980-4133-a7ff-82859bfec06b)

[srcLuaMem.zip](https://github.com/user-attachments/files/16247654/srcLuaMem.zip)

**Comment by jasalca** [comment] 2024-07-16 11:09
I can't believe it, the truth is that what spectacular job is done here. Benno00, I´m very grateful to you for you work and I recognize that this script is very very good. GOOD job!!!.I will test it.

**Comment by jasalca** [comment] 2024-07-16 11:12
> quick & dirty a simple source script which returns the lua free ram (kB) could be used as the source for the line-chart widget: (1 sec log duration / auto scaling in my example:) So one can monitor what happens in case he adds widget for widget
> 
> ![image](https://private-user-images.githubusercontent.com/20392683/349057895-38612793-6980-4133-a7ff-82859bfec06b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg2MDAsIm5iZiI6MTcyMTEyODMwMCwicGF0aCI6Ii8yMDM5MjY4My8zNDkwNTc4OTUtMzg2MTI3OTMtNjk4MC00MTMzLWE3ZmYtODI4NTliZmVjMDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExMTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZThhNTdhNzFiMGE5ZjliNDFiZmQxNGNkNjllMDcyNDE3YjE5YTllNjA5ZGZmZDIzMTc0NWY5ZTk2YWJhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j1qNwDTxIWFC5uYMnu-9Isb-_qyoIDeNH8lItyC0goE)
> 
> [srcLuaMem.zip](https://github.com/user-attachments/files/16247654/srcLuaMem.zip)

That's great!! Thank you very much

**Comment by jasalca** [comment] 2024-07-16 11:19
Every day I am more convinced of the great team behind all this. In this way Frsky together with Ethos system will be the strongest system and will get to be al the top. Congratulations!!!

**Comment by bsongis-frsky** [comment] 2024-07-16 11:26
@Benno00 I am interested in knowing what you had to change in your script?

**Comment by jasalca** [comment] 2024-07-16 11:43
It keeps giving an error, when you try to set up a new widget. The error message reads: 1: attempt to index a nil value ( field´source´)

**Comment by strgaltdel** [comment] 2024-07-16 12:17
@jasalca:
this might be the case on very first configuration, when config fields were not filled.
maybe Ethos "buffers" this error statement even after widgets were configured
stays the message even after configure all widgets & reboot tx?

**Comment by Benno00** [comment] 2024-07-16 12:42
> @Benno00 I am interested in knowing what you had to change in your script?


Hi Bertrand,

I now read the min/max values ​​of a sensor as follows
min_source = system.getSource({name=mename,options=OPTION_SENSOR_MIN})
max_source = system.getSource({name=mename,options=OPTION_SENSOR_MAX})
Before, I determined the min. and max. values ​​using **source_value()

The loading of bitmaps
previously took place like this
lcd.loadBitmap(widget.swbmp[nr])
now like with complete path
lcd.loadBitmap(bitmappath..widget.swbmp[nr])

that was actually it

**Comment by Benno00** [comment] 2024-07-16 12:55
i testet with this Version 
![image](https://github.com/user-attachments/assets/424e7539-8ec7-499c-bc03-c9c573ac33b4)

![image](https://github.com/user-attachments/assets/296bd69b-9fef-49a2-ab21-0e22c8a88a7f)

the mem script fluctuates between 1157 and 1170
![image](https://github.com/user-attachments/assets/bb43400d-9d84-4ad1-bd0c-f545c3f71dbd)

is done for me and can be closed by me

**Comment by jasalca** [comment] 2024-07-16 13:00
Thanks

**Comment by bsongis-frsky** [comment] 2024-07-16 13:31
OK. In the next release 1.5.12 it will be possible (and more efficient) to do this:

```lua
local minValue = source.value({options=OPTION_SENSOR_MIN})
```

**Comment by jasalca** [comment] 2024-07-16 15:32
I have to continue investigating.It remains the same problem, or worse, because is now in emergency mode. I turn on the radio, select any model, and now monitor with the RAM widget.
The counter starts at about 1800, and in course of 20 minutes without touching the radio, that counter reaches 0, the Lua Killer warning appears and then enters in Emergency mode.

**Comment by bsongis-frsky** [comment] 2024-07-16 15:36
If there is an EM after the script is killed and the warning shown, then we have a problem!

**Comment by jasalca** [comment] 2024-07-16 15:43
Now I have created a new model without scripts, only the Ram counter one to see, al the moment it seems to be going well. Then now I will create another model and include the script lua from Benno00 to see what happens.

**Comment by jasalca** [comment] 2024-07-16 16:05
At the moment everything seems to be going well..Now I'm going to take an already created model, I'm going to delete all the widgets and I'm going to reinstall them again , lest there be a conflict by not having deleted the previous ones.

**Comment by bsongis-frsky** [comment] 2024-07-16 16:20
I have found an EM, after the script has been killed. If you try to enter inside the widget configuration. Is that what you did after the warning raised?

**Comment by jasalca** [comment] 2024-07-16 16:25
I think it did it without touching anything. Now I confirm it to you

**Comment by jasalca** [comment] 2024-07-16 16:51
I confirm you, EM if you try to enter inside the widget configuration , after the script has been killed

**Comment by jasalca** [comment] 2024-07-16 17:09
https://github.com/user-attachments/assets/b8110029-469c-4dd3-8a60-1a9a093b5916

**Comment by strgaltdel** [comment] 2024-07-16 18:39
just to rule out lothars widget could be involved
(it seems you 've configured a lot of widgets, spread over three homescreens)
only bennos, my one, and one or two "system" widgets were running ?

**Comment by jasalca** [comment] 2024-07-16 19:01
I'm doing different tests, now I'm just with Benno's widget. I have Lothar's uninstalled at the moment.

**Comment by bsongis-frsky** [comment] 2024-07-16 21:13
EM fixed tomorrow. You have the perfect scripts to confirm that the issue is fixed in the next nightlies ;)

**Closed as completed** 2024-07-16 21:12 UTC
