### ISSUE TITLE
Feature request :x20(s) Checklist switches ---> activate or deactivate without entering every single switchmenu

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#241] opened 2021-05-14 19:06 UTC
It would be nice if we can activate or deactivate every switchwarning by just touching the switch-name in  the menu instead of entering every "dropdown" menu in the switches menu.

BTW it would be nice if we can rename the switch-name in hardware menu.
In my case i replace some switches so switch F is in place switch C. 

Thanks

**Comment by MrD-RC** [comment] 2021-05-15 15:18
What would also be cool is a _set all_ button. Put the switches in the positions you want, then press the set all button. All switches are set except for those chosen to be ignored.

**Comment by jfint** [comment] 2021-05-19 18:42
Agree with above suggestion, a way to take the current switch state as the checklist would be ideal.

**Comment by loetefix** [comment] 2021-06-04 21:09
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/353

**Comment by bsongis-frsky** [comment] 2021-06-04 21:48
Right, duplicate of #353

**Closed** 2021-06-04 21:48 UTC
