### ISSUE TITLE
Curve settings

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#3345] opened 2024-01-29 10:11 UTC
Hi together,

a customer wrote me the following.

To the Engel team and Frsky, 

We are very unhappy with the curve setting option on the FRSKY Tandem X20S.
We have taken the trouble to demonstrate to you how easy and really good it is (Graupner MX20s).

we think FrSKY could certainly implement this very easily! there is not so much missing...  (we hope for your help as you are the main importer!!!)

Graupner MX24s - has a super
curve setting option!!!! This
must be in the FRSKY Tandem X20S!!!!!!!!
The curves can be created so easily and clearly. There are only 8 points, but they can be
with the e.g: throttle stick on X and Y simply by pressing the enter button and
fixed/adjusted/changed using the rotary wheel. There is no need to search around and try out when
and where a setting fits. Perfect settings for all throttle and surface combinations immediately
possible (e.g.: by ear how the engine is running, how the flaps are positioned etc... !!!) and this also with
time delay which is also displayed with a time delay, the bar runs with a time delay !!!!!
Can't this also be integrated into the X20s FrSKY? This is
a real MANKO of the X20S system 
Mfg. F. Schmidl -> a small video is attached, see description below.
Please pass this on to FrSky ! This is a concern for everyone we know - and there are many!

https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/16795828/93af2ea2-e372-4804-a2d5-b656710b2b0e

thanks f. schmidl

**Comment by mawzthefinn** [comment] 2024-01-29 14:54
This is a duplicate of #24 

It has not been addressed because of a simple reason. You cannot definitively link an input to a curve in ETHOS

In that ancient JR radio (it's JR software, not Graupner) the curves were dedicated settings within the function, in ETHOS they are a separate building block where one curve can be referenced by multiple other functions (0-100 input conditioning curves might be used by functions that adjust gain, adjust weight, adjust differential and more, one curve called by 3+ different functions in the radio). 

I'd love to see a cursor type input for editing, but I can't see how that would be possible to implement since the curve and the input are not linked 1:1

**Comment by EngelMT** [comment] 2024-01-29 16:16
@mawzthefinn Many thanks for explain it. Perhaps Betrand has an idea of how to realise this. We have this type of enquiry more often. The users really seem to be missing it.

**Comment by bsongis-frsky** [comment] 2024-01-29 21:55
We have a work in progress on this feature. Duplicate of #24

**Closed by bsongis-frsky** 2024-01-29 21:55 UTC
Labels: duplicate
