### ISSUE TITLE
X12s freezes on boot logo

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#1823] opened 2022-07-31 13:41 UTC
firmware 1.3.0
bootloader 1.2.11

update to ethos 1.3.0 2 days ago
been good for 2 day i have not done any editing on models or swapping models I just been turn it on and off to see if it freezes 
today the second turn on it froze

here is the radio bin and the model-bin
 https://drive.google.com/file/d/1l-N1dTy_RjiaC3FvKEzxLGkXuAeQ-Yca/view?usp=sharing

**Comment by Nerenye** [comment] 2022-07-31 13:45
Duplicate with Issue #1816

**Comment by yak-54** [comment] 2022-07-31 13:51
i had this issue for months [https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1800#](url)

**Comment by nikwalnikwal** [comment] 2022-08-07 13:45
I still have this issue...  can I trust 1.2.7 not to do that?

**Comment by yak-54** [comment] 2022-08-27 23:27
i am still getting this issue on 1.3.1 on my All 3 of my X12S

**Comment by yak-54** [comment] 2022-08-30 00:06
after many hours of testing this last 3 days  it looks like its windows 10 issue with SD formatter 
I have a Linux server so i put the SD card in it formatted SD  copied the ethos files  back to it the SD card
put back in the X12S i have turned this off and on over 30 time editing models work fine and it looks like it loads ethos faster as well
so hopping that's fixed it issues because i was getting sick pulling back off the tx to unplug the battery

**Comment by yak-54** [comment] 2022-08-31 08:37
i spoke to soon i update 1.3.2 it was fine as long as i don't edit any models
i soon as i started editing a model exit the mix menu and turn off the radio go back later on them turn it back on its freezes on the boot logo i think its trying to load that model   i just edited

**Comment by yak-54** [comment] 2022-08-31 08:39
i spoke to soon i update 1.3.2 it was fine as long as i don't edit any models
i soon as i started editing a model exit the mix menu and turn off the radio go back later on them turn it back on its freezes on the boot logo i think its trying to load that model i just edited

**Comment by yak-54** [comment] 2022-08-31 08:57
i did put the sd card in a windows PC to put the firmware 1.3.2 Bin file on it
i will put it back in Linux PC format under Linux copy files back across see how it goes

**Comment by Nerenye** [comment] 2022-08-31 09:22
@bsongis thats the type of Issue thats killing your reputation and the trust in your company. #1869 aswell. And there is not even a comment from Frsky on this issues.
I realy feel like your release Quality is declining by a lot. There´s a lot of shop owners in this repo. 
Don´t think they can easily say it´s 100% safe to use Frsky at the moment.
Please, focus on these issues and stop working on new functions for a couple of weeks. it will be good for your reputation.
Nobody whants a transmitter wich is not at least 99% reliable. (not including Hardware malfunctions and stupid use of course)

**Comment by bsongis** [comment] 2022-08-31 09:50
Duplicate of #1816

**Comment by bsongis-frsky** [comment] 2022-08-31 09:51
Duplicate of #1816

**Closed by bsongis-frsky** 2022-08-31 09:51 UTC
