### ISSUE TITLE
REPOST: Doubled sensor using RB-30 and dual frequencies 2.4 GHz - 900 MHz

### ISSUE THREAD

**Issue by federicobelfi** [FrSkyRC/ETHOS-Feedback-Community#1517] opened 2022-03-06 14:31 UTC
Repost of ISSUE #1092 

The Issue was first in the milestones 1.0.13, postponed on milestones 1.1.0 and now is no more present in any milestones.
Have you discovered that this issue cannot be resolved? Have you any workoround?

**Comment by bsongis-frsky** [comment] 2022-03-07 08:06
Duplicate of #1092

**Closed by bsongis-frsky** 2022-03-07 08:06 UTC
