### ISSUE TITLE
Ethos Suite 1.5.5 fails to install on Mac

### ISSUE THREAD

**Issue by GilMSheinfeld** [FrSkyRC/ETHOS-Feedback-Community#3928] opened 2024-04-26 13:25 UTC
Hi, when trying to install Ethos suite on Mac, I get the following error:
The Finder can’t complete the operation because some data in “Ethos Suite” can’t be read or written.
(Error code -36)
My Mac is Mac mini 3.2 GHZ 6-Core Intel Core i7, running Mac OS 14.4.1.

Thanks!

Gil.

**Comment by mawzthefinn** [comment] 2024-04-26 13:26
Duplicate of #3923  please continue conversation there

**Closed as not planned by mawzthefinn** 2024-04-26 13:26 UTC
Labels: duplicate
