### ISSUE TITLE
Multiprotocol telemetry for Graupner HoTT

### ISSUE THREAD

**Issue by AlexEger** [FrSkyRC/ETHOS-Feedback-Community#2755] opened 2023-07-16 17:31 UTC
referring to issue #2061 

It would be great to have telemetry for the Graupner HoTT protocol too, as I have a bunch of receivers I would like to use. I would appreciate it also very much to have the Graupner HoTT.lua for OpenTX rewritten for Ethos.

Cheers, Alex

**Comment by Fordster39** [comment] 2023-07-17 00:00
I too would very much need this protocol. I am migrating from Graupner to Frsky and keeping my Graupner gyro receivers and need the Hott.lua for the receiver configuration. 
thanks , Gil

**Comment by bsongis-frsky** [comment] 2023-07-17 07:04
Duplicate of #2745

**Closed** 2023-07-17 07:04 UTC

**Comment by edgeflyer30** [comment] 2025-01-24 09:37
I need it too
