### ISSUE TITLE
ETHOS Suite: X18 NAND not found, plus hardware issue after repair tool

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#2062] opened 2022-11-08 18:45 UTC
I am having problems updating my X18 in ETHOS Suite. The NAND drive is never found. I can clearly be seen in Windows. But the drive is not found in ETHOS Suite. The result of this is the update fails and the model manager is blank.

![image](https://user-images.githubusercontent.com/17590174/200647599-7c203748-7864-4990-b4f0-39fc394176f2.png)

You can see in the image that the **Radio Internal Storage** does not show an **Out of date** or **Up to date** info box along side. Yet, it does know the size of the storage. On the right, you can see the NAND storage. It is named **RADIO** after attempting to use the **Repair Tool**.

I could update the **Bootloader** and **Flash Bitmaps** by manually selecting them in the updates list. But the **Firmware** and **Audio** components failed to update. The **Audio** failure is strange, as I store the audio files on the SD Card.

![image](https://user-images.githubusercontent.com/17590174/200648535-bccbfd76-d9f2-419f-9bb4-78f8e9fff907.png)

As I mentioned briefly. I have tried the **Repair Tool** But, after doing so, it has now added a hardware issue to my problems. The right slider now does nothing, and the left slider operates both sliders in the firmware. For example, when recalibrating the radio after the repair. Moving the physical left slider operated both sliders on the screen. The physical right slider did nothing. I notice that I also now have a calibrate gyro option, which I didn't have before. My radio is an X18 (not S), but does have the gyro.

Any assistance on this would be most welcome.

**Comment by bsongis-frsky** [comment] 2022-11-10 08:09
Duplicate of #2022

**Closed by bsongis-frsky** 2022-11-10 08:09 UTC
