### ISSUE TITLE
Entering values ​​in logical switches

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#2534] opened 2023-03-22 17:37 UTC
Dear Ethos Team, It would be extremely helpful if you could enter the values ​​in the logical switches using the on-screen keyboard. When entering, for example, height or voltage, you spin the wheel to death.
![bild](https://user-images.githubusercontent.com/68751162/226990628-9eda947f-9e1d-4b3c-80c4-12d2ccecc83d.jpg)
 Thanks a lot

**Comment by strgaltdel** [comment] 2023-03-23 11:45
just my 2 cents:

the adjustor is a very good step forward, but there are many cases so that a direct number input would be much more efficient.

typically you have to perform several steps:
- set the adjustor to a "rough" stepsize
- "scoll" to the "area" of the value
- set the adjustor back to tiny steps
- "scoll" to exact value

a direct number input would be even more efficient.

But the "reducement" of the issue on LSW's is an absolute NoGo

In case there would be acceptance for an implementation all sorts of number input fields where "excessive scolling" can occure should  be flagged as a property and so a method could be used to offer direct number input.

to be fair,
(imho) it would be a good enhancement, 
but there are so much implementations / enhancements waiting for completion in 1.5.0, it would expect this one on a "long term list"

**Comment by jurajjurej** [comment] 2023-03-23 12:40
Wouldn't it be a good idea to add a step setting of x1, x10 and x100
![Screenshot_269](https://user-images.githubusercontent.com/85956904/227206467-9a3008bb-f535-4936-a943-be2714a12dc8.jpg)

**Comment by loetefix** [comment] 2023-03-23 18:31
this is the best solutin i think

**Comment by RealTadango** [comment] 2023-04-17 14:33
Just allow me to type those values. It is VERY annoying if you want a big number wit the current input. Can't think of any good reason i would ever want this......

**Comment by jurajjurej** [comment] 2023-04-22 16:28
It's hard to tap back to step x1. It also needs the icon "+,-" or "x1, x10"

**Comment by jasc76** [comment] 2023-04-24 11:04
Good idea to have a number keypad 
+1

**Comment by jurajjurej** [comment] 2023-05-02 01:38
It would be good to adjust the value entry in the entire OS Ethos.

**Comment by azaz44** [comment] 2023-05-03 11:00
I think number would be good sometimes. I found some places where it isn't possible to adjust the step and was scrolling to death really. Like value in image below (in Calculated telemetry sensor)

![image](https://user-images.githubusercontent.com/42830563/235898023-ce4645e1-775d-4196-a543-16c43b10fc85.png)

**Comment by mawzthefinn** [comment] 2023-07-31 16:09
Duplicate of #2244 

Please continue discussion there

**Closed by mawzthefinn** 2023-07-31 16:09 UTC
Labels: duplicate
