### ISSUE TITLE
Hebrew Fonts on Firmware Version 1.4.7 FCC looks Corrupted

### ISSUE THREAD

**Issue by ilansch2910** [FrSkyRC/ETHOS-Feedback-Community#2520] opened 2023-03-18 16:02 UTC
![IMG_7377](https://user-images.githubusercontent.com/27518455/226117082-0051ad26-38a4-4030-9bbe-c5f694cefa26.jpg)

**Comment by bsongis-frsky** [comment] 2023-03-20 07:30
Who can reproduce this issue, I cannot reproduce it here!

**Comment by bsongis-frsky** [comment] 2023-03-20 07:50
Would you take a screenshot of System / Information to be sure we are on the same firmware?

**Comment by Idan69** [comment] 2023-03-29 15:58
![Uploading 20230329_185827.jpg…]()

**Comment by Idan69** [comment] 2023-03-29 16:00
![20230329_185827](https://user-images.githubusercontent.com/129287404/228598263-082ff9d0-2ea5-4f84-9789-cb0d4e3afb82.jpg)

**Comment by i3dm** [comment] 2023-04-10 14:12
> Who can reproduce this issue, I cannot reproduce it here!

i just did, in 1.4.7 all hebrew fonts are gibrish (unreadable)
![20230410_171105](https://user-images.githubusercontent.com/8968780/230918337-608e8e39-4392-4d13-a061-ab7df9705ab5.jpg)

**Comment by i3dm** [comment] 2023-04-10 14:38
Its actually worse, even in english this part is still in gibrish unreadable hebrew font.
![20230410_172407](https://user-images.githubusercontent.com/8968780/230923259-5d6c93a1-c6d5-41c3-b2f5-ec18740ab7ae.jpg)

**Comment by i3dm** [comment] 2023-04-11 14:30
> The same on 1.4.8?

just tested X18S:
147 corrupted.
148 is OK!

**Comment by bsongis-frsky** [comment] 2023-04-11 20:37
I close the issue then, thanks for the feedback

**Closed** 2023-04-11 20:37 UTC
Labels: bug
