### ISSUE TITLE
Inactivity alarm bug

### ISSUE THREAD

**Issue by Sigee3** [FrSkyRC/ETHOS-Feedback-Community#491] opened 2021-06-14 07:40 UTC
Once the inactivity alarm is triggered it doesnt turn off even when flying.

**Comment by loetefix** [comment] 2021-06-14 08:41
Allready here: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/466

**Comment by Sigee3** [comment] 2021-06-14 08:46
> 
> 
> Allready here: #466

About time it was fixed then ;)

**Comment by bsongis-frsky** [comment] 2021-06-14 09:54
Duplicate of #466

**Closed by bsongis-frsky** 2021-06-14 09:54 UTC
