### ISSUE TITLE
Something seems wrong with VAR Actions Percent

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3410] opened 2024-02-11 12:10 UTC
Please see the following setup

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/96293240/00d26c41-1a1d-4162-9114-888da2e0db65)

The action is intended to take 40% as a starting value and outut a percentage of that according to the position of switch SG. This has values of 100%, 80% and 60% taken from another VAR SG Dual Rates.

When switch SG is moved from the 100% position to the 80% position I'd expect the resultant value to change to 32%, however it changes to 0.2%

If I move SG between the 100% and 80% positions it remains at 0.2%.

If I move SG to the 60% position then the output changes to 0.1%.

It now remains there regardless of what I do with SG.

The first problem is that 0.2% is not 80% of 40%.
The second problem is that the outut value only ever decreases. 
If I use another VAR as a source instead of 40% then everything works as expected.  
I understand that the actions change the Value, but surely there should be a way to return to the original value other than by means of another source / VAR? Currently the percent is just taking a percentage of the last value. Perhaps the top VALUE should be locked at in this case 40% and the calculations done off that?

I confess I'm slightly confused as to how this is intended to all work. 

Thanks

**Comment by hrenz** [comment] 2024-02-11 14:08
your first Var SGDualRate is in %
and then you calculate here again in %
for example 
40% = 0,4  
20% = 0,2
0,2 * 0,4 = 0,08%

**Comment by bsongis-frsky** [comment] 2024-02-12 09:39
Duplicate of #3413

**Closed by bsongis-frsky** 2024-02-12 09:39 UTC

**Comment by Jedsters** [comment] 2024-02-14 14:53
I've just tested this with RC3 and the problem seems to persist.
Thanks

**Comment by bsongis-frsky** [comment] 2024-02-14 15:24
The trigger is "Always ON"?
