### ISSUE TITLE
feature request : Logical switch impuls : << in second during parameter 

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#196] opened 2021-05-09 07:42 UTC
Please add the << value on the second parameter in during on impuls logical switch like in openTX.

now it is not possible to get an impuls if a switch is only longer than x seconds in on position. ( now it is only if longer than x and shorter than y).

Thanks

**Comment by Hartinger** [comment] 2021-05-09 16:28
I guess you mean what I have already raised in #89.

**Comment by loetefix** [comment] 2021-05-09 18:16
Yes.

**Comment by MIKE-DAILEY** [comment] 2021-05-09 18:18
Duplicate of #89

**Closed by MIKE-DAILEY** 2021-05-09 18:18 UTC
