### ISSUE TITLE
Missing drive Ethos Suite 1.5.3 

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#3830] opened 2024-04-13 07:22 UTC
Running Ethos Suite 1.5.3.

Whenever I try to update my X18SE, I can see that the Tx need a firmware update, but when I hit `Write outdated components' it will do it's things to update, but then it comes `Waiting for disk', then a message `Missing drive'.

The only way to update is to select `Write firmware and i18n', and then the update will go through.

**Comment by Target0815** [comment] 2024-04-13 09:50
The current version is Suite 1.5.4 ...

**Comment by salibaj2** [comment] 2024-04-14 16:27
Thanks Target0815,

Problem is that FrSky ETHOS page is down and cannot locate latest version, as ETHOS Suite v1.5.3 is not asking to update.

**Comment by Nicholas-Luoyi** [comment] 2024-04-15 02:36
Please manually download the 1.5.4 and try again...

**Comment by salibaj2** [comment] 2024-04-15 21:08
Tried with 1.5.4 and still the same. Not only, I went back to 1.5.4, again selecting the firmware manually, did not accept to write to try it out and I had to recalibrate the radio, and all settings where wiped out.

**Comment by salibaj2** [comment] 2024-04-15 21:27
Ok. Looks like the radio was reset. Now I went to update again and looks that firmware through Write All Components went through. However, I still had all previous settings wiped out.

Doing a restore of models seems that I got everything back. 

However, If the problem was because I was still using Ethos Suite 1.5.3 when trying to update to 1.5.6, why the Ethos Suite let me do the update in the first place if they are not compatible? 

Should there be a check in Ethos Suite to let you make an update up a certain Ethos version?

This surely will restrict further user error during updates.

**Comment by Nicholas-Luoyi** [comment] 2024-04-16 06:36
Would you please open the debug mode and go to update the firmware which will show the "Missing drive" dialog. And then post the debug file here. The you can find the file by clicking the OPEN button in Suite settings tab.

**Comment by salibaj2** [comment] 2024-04-16 14:33
Uploaded debug file for your attention.

Last file with errors: - crash-20240413.txt

Thanks

[Crashpad.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14998390/Crashpad.zip)

**Comment by Nicholas-Luoyi** [comment] 2024-04-17 00:35
It looks like a driver issue when the radio is connected as a storage disk. Can you see two disks in your file explorer when you X18SE is connected without Suite running?

**Comment by Nicholas-Luoyi** [comment] 2024-04-17 00:38
And you are running Suite on a macOS or a Windows?

**Comment by salibaj2** [comment] 2024-04-17 09:15
Windows 10 PRO. I can see 3 drives as I have the SD card on the x18SE.

In fact, I first wait for all drives screen to open before I proceed to update.

**Comment by Nicholas-Luoyi** [comment] 2024-04-18 00:13
I have made some possible fix for your issue. But I'm not very sure if it could actually fix your issue because I cannot reproduce it on my PC. The fix will be included in the next Suite release. If it still there. Please reopen this issue.

**Closed as completed by Nicholas-Luoyi** 2024-04-18 00:13 UTC
Labels: information needed
