### ISSUE TITLE
Bluetooth Trainer function not working

### ISSUE THREAD

**Issue by wizan9z** [FrSkyRC/ETHOS-Feedback-Community#350] opened 2021-05-28 04:50 UTC
Set up my BT head tracker for the Tandem x20S. Radio able to discover and connect to the Arduino 33BLE head tracker board but not able to function Set up as per my Horus X10S on OTX, using “Trainer 7” and “Trainer 8” for the Tilt and Pan function on the X20S that are hooked up to the ACCESS R8Pro receiver on Ch7 and Ch8. Not sure if this is a known issue for wireless trainer on the x20/x20s.

**Comment by bsongis-frsky** [comment] 2021-05-28 13:03
Duplicate of #160

**Closed by bsongis-frsky** 2021-05-28 13:03 UTC
