### ISSUE TITLE
Issues on the 'saving ' feature

### ISSUE THREAD

**Issue by Billy60** [FrSkyRC/ETHOS-Feedback-Community#1321] opened 2022-01-08 13:25 UTC
Beware, I could experience a nasty trick:
* when you 'save the SD Card' please note that the BMP file is empty (only 1 bmp ans none others).
* When you upgrade from a previous FW, note that some of your models will be corrupted: the conversion does not always work. I just lost half of my models trying to upgarde !
More than ever : if it is not broken, don't fix it   !

**Comment by Hobby4life** [comment] 2022-01-08 13:48
What is 'saving' feature?

Be more clear what you mean.

And what about 'empty BMP file' ?

**Comment by Billy60** [comment] 2022-01-08 14:03
When you want to save the content of the SDCard content, you ... save it to a PC or elsewhere. 'Copy' if you prefer. This to avoid what happened to me (loosing half of my models because the conversion went wrong somewhere).
BMP file: in the SDCard there is a file called 'BMP' which contains all system graphics and model images. The system graphics are in the 'system' file and the images are in the 'user' one.

**Comment by Hobby4life** [comment] 2022-01-08 14:44
So what you are saying is exactly what is mentioned in the Manual ;-)

**Comment by Billy60** [comment] 2022-01-08 16:36
Right,
Happy to learn there is a manual !
Anyway, this is for me an issue which should be adressed. I lost some of my models and can't find it normal.
So it forbids an upgrade...
Thanks for your help and file, it ws most needed and useful.
Have a very good day !

**Comment by bsongis-frsky** [comment] 2022-01-10 08:56
It seems duplicate of the other issue you already opened yourself, no?

**Closed** 2022-01-10 08:55 UTC
