### ISSUE TITLE
Bug: Top display widgets values are not updating on XE in 1.5.4

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3752] opened 2024-03-30 14:42 UTC
On XE radio in version 1.5.4, the widgets used on the top display are not updated when the radio is running.  The displayed value is only what's there on power on.

**Comment by Dsrenger** [comment] 2024-03-30 14:49
When did you do the update?

The issue got fixed a couple of hours ago.

Just reflash 1.5.4

It should be fixed then.

**Comment by bsongis-frsky** [comment] 2024-03-30 14:52
Duplicate of #3743

**Closed as completed by bsongis-frsky** 2024-03-30 14:52 UTC
