### ISSUE TITLE
sport telemetry byte stuffing issue on incoming frames

### ISSUE THREAD

**Issue by yaapu** [FrSkyRC/ETHOS-Feedback-Community#2235] opened 2022-12-22 13:13 UTC
_transmitters_:
X20
Ethos 1.4.4
TD-ISRM W:1.4.0 FW:2.2.2 (FLEX-868)

Horus X10
OpenTX 2.3.15
ISRM-S-X10S 1.1.0/2.1.0EU

_receiver_:
X4R FW: X4R_ACCST 2.1.0

Same test on both OpenTX and Ethos using the very same receiver.
X4R is connected to ArduPilot. ArduPilot sends custom sport frames.
A LUA widget dumps the incoming sport frames with  sportTelemetryPop() on OpenTX and popFrame() on Ethos.

**Ethos issue: sport frames that require byte stuffing never reach LUA under Ethos**

Ethos: example of traffic
1 TX: 0x32 0x00 0x0C 0x16 0x00 0x00 0x00 0xAB
2 TX: 0x32 0x01 0x00 0x51 0x5F 0x45 0x4E 0x88
3 TX: 0x32 0x02 0x41 0x42 0x4C 0x45 0x7D 0x5E 0x38  ** stuffed frame 0x32 0x02 0x41 0x42 0x4C 0x45 0x7E 0x38

1 RX: 0x32 0x00 0x0C 0x16 0x00 0x00 0x00 0xAB
2 RX: 0x32 0x01 0x00 0x51 0x5F 0x45 0x4E 0x88
3 is missing

OpenTX
1 TX: 0x32 0x00 0x0C 0x16 0x00 0x00 0x00 0xAB
2 TX: 0x32 0x01 0x00 0x51 0x5F 0x45 0x4E 0x88
3 TX: 0x32 0x02 0x41 0x42 0x4C 0x45 0x7D 0x5E 0x38  ** stuffed frame 0x32 0x02 0x41 0x42 0x4C 0x45 0x7E 0x38

1 RX: 0x32 0x00 0x0C 0x16 0x00 0x00 0x00 0xAB
2 RX: 0x32 0x01 0x00 0x51 0x5F 0x45 0x4E 0x88
3 RX: 0x32 0x02 0x41 0x42 0x4C 0x45 0x7E 0x38

**Comment by bsongis-frsky** [comment] 2022-12-22 20:02
How is Horus X10 + Ethos 1.4.5? Same issue?

**Comment by yaapu** [comment] 2022-12-23 15:41
> How is Horus X10 + Ethos 1.4.5? Same issue?

not tested, X10 on OpenTX is my daily radio right now

**Comment by bsongis-frsky** [comment] 2023-01-04 07:46
I am not sure it's an Ethos issue
I will send a firmware which will dump the incoming telemetry to /logs/telemetry.log

**Comment by SmartTommy** [comment] 2023-01-05 10:12
do you mean it works normal when run with the OpenTx on the X10?
we will test it and reply you asap.

**Comment by yaapu** [comment] 2023-01-05 11:13
> do you mean it works normal when run with the OpenTx on the X10? we will test it and reply you asap.
 yes, works on x10 under OpenTX not on X20 under Ethos.
I suspect a TX issue of the ISRM module

**Comment by SmartTommy** [comment] 2023-01-06 03:15
> > do you mean it works normal when run with the OpenTx on the X10? we will test it and reply you asap.
> 
> yes, works on x10 under OpenTX not on X20 under Ethos. I suspect a TX issue of the ISRM module

we test the one LUA include 0x7d/0x7e with X20,it works normal,could you send us your LUA?

**Comment by bsongis-frsky** [comment] 2023-01-06 08:55
> > do you mean it works normal when run with the OpenTx on the X10? we will test it and reply you asap.
> 
> yes, works on x10 under OpenTX not on X20 under Ethos. I suspect a TX issue of the ISRM module

Unless there is a CRC check error in Ethos ... I have sent a firmware with Telemetry Logs enabled, it will tell us if the issue is in the ISRM module or Ethos.

@SmartTommy The problem happens when the radio receives the bytestuffing, not when it sends

**Comment by yaapu** [comment] 2023-01-06 11:57
The custom firmware logs the stuffed bytes so the ISRM seems to be fine

what I send from the RX via ArduPilot:

TX: 0x32 0x00 0x0C 0x16 0x00 0x00 0x00 0xAB
TX: 0x32 0x01 0x00 0x51 0x5F 0x45 0x4E 0x88
TX: 0x32 0x02 0x41 0x42 0x4C 0x45 0x7D 0x5E 0x38  (stuffed for 0x32 0x02 0x41 0x42 0x4C 0x45 0x7E 0x38)

what I receive on Ethos LUA popFrame()
0x32 0x00 0x0C 0x16 0x00 0x00 0x00
0x32 0x01 0x00 0x51 0x5F 0x45 0x4E

/LOGS/telemetry.log
078544 1B 32 00 0C 16 00 00 00
078602 1B 32 01 00 51 5F 45 4E
078625 1B 32 02 41 42 4C 45 7E

**Comment by bsongis-frsky** [comment] 2023-01-09 18:33
I will close this issue as you told me by email that the problem was in your Lua script. Feel free to comment if I have mistaken anything, I will reopen the issue.

**Closed by bsongis-frsky** 2023-01-09 18:33 UTC
Labels: bug, information needed

**Comment by yaapu** [comment] 2023-01-09 20:00
That's correct, the issue was in my Lua and is fixed now. Thanks once again for your help!
