### ISSUE TITLE
Feature request: add addition to calculated sensor

### ISSUE THREAD

**Issue by phaedra-tm** [FrSkyRC/ETHOS-Feedback-Community#1928] opened 2022-09-25 15:19 UTC
I have a twin engine model, each engine with its own current sensor.  In OTX, I added the currents measured by both sensors via a calculated sensor that added both values.  Then I added a calculated sensor for consumption based on the sum of both sensors values.
In Ethos, I seem to have no way of doing this, so I can only calculate half the actual consumption.
Note: I need two sensors, because the total current of both engines together is way over 100A, and the Frsky 150A sensor that I tried has an error of over 30%, which renders it near to useless for monitoring consumption.

**Comment by bsongis-frsky** [comment] 2022-09-29 13:44
Duplicate of #1025 
This feature is ready and will wait for 1.4.0 completeness

**Closed by bsongis-frsky** 2022-09-29 13:44 UTC
