### ISSUE TITLE
A Few Global Logical Switches

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#4512] opened 2024-09-12 23:13 UTC
I would like to have some global logical switches.

In my use case all of my momentary switches (3 on the stock X20S) use 12 lines of logical switching to implement mouse button functionality (single click, double click, long click) on those 3 switches. These 12 lines are repeated on every model. I would like to see some global logicals available for things like this that happen on all the models. Perhaps they could be limited to items where the transmitter is the only hardware that could affect the LS. 

Of course I would also be thrilled to see those mouse button features be baked into momentary switching so I don't have to use those lines of logic to make it work. In this case I would like to see support for 2 position (off-momentary) or 3 position momentary (momentary-off-momentary). The states would be on, off, single click, double click, long click for a 2 position momentary and up, middle, down, single click up, double click up, long click up, single click down, double click down, long click down for 3 position.

**Comment by mawzthefinn** [comment] 2024-09-13 13:14
Duplicate of your #3465

**Closed as not planned by mawzthefinn** 2024-09-13 13:14 UTC
Labels: duplicate
