### ISSUE TITLE
Smal Display in XE is not working right

### ISSUE THREAD

**Issue by Help454** [FrSkyRC/ETHOS-Feedback-Community#3743] opened 2024-03-29 20:13 UTC
Smal display in XE is not working right. 
Changing values will not shown

![DSC_2202](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165424625/a32487fd-49ac-4c3f-abc9-586ae2a82e9f)
![DSC_2203](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165424625/751a5e28-533a-40cf-83ea-56046abbaf4b)

**Comment by bsongis-frsky** [comment] 2024-03-29 22:46
Reproduced and fixed on simulator
Firmware removed from the release section
They will be uploaded again when compilation done

**Comment by bsongis-frsky** [comment] 2024-03-30 09:47
To be as quick as possible to fix this one, and because it's not a critical issue, I have uploaded the new bins in the same release.
Would you please confirm it is OK now? 
Thanks for your help!

**Closed as completed by bsongis-frsky** 2024-03-30 09:47 UTC

**Comment by Help454** [comment] 2024-03-31 10:05
Sorry for late Response. Yes it is okAm 30.03.24, 10:47 schrieb "Bertrand Songis @ FrSky" ***@***.***>:

   
  To be as quick as possible to fix this one, and because it's not a critical issue, I have uploaded the new bins in the same release. Would you please confirm it is OK now? Thanks for your help!
