### ISSUE TITLE
Feature request: Add an option to change the ppm center point 

### ISSUE THREAD

**Issue by npirkes** [FrSkyRC/ETHOS-Feedback-Community#1446] opened 2022-02-10 09:07 UTC
Changing the PPM center is in fact like add simetrical subtrim to the servo. In fact it shift the entire servo throws. 

Unlike the subtrim that we have right now in the system which require to change the endpoints as well to get the same throws to both sides (which is very important when using multiple servos on the same surface)

Note, I did saw the suggestion you mentioned on the manual (to use curve instead) but it should be wonderful to have this option as well.

Thanks in advance.

**Comment by bsongis-frsky** [comment] 2022-02-10 10:04
Duplicate of #1264

**Closed by bsongis-frsky** 2022-02-10 10:04 UTC
