### ISSUE TITLE
Newly created model not showing on model select screen after creation, but BIN file is saved in model folder

### ISSUE THREAD

**Issue by iflyforfood** [FrSkyRC/ETHOS-Feedback-Community#1812] opened 2022-07-26 22:51 UTC
Horus X10S Express 1.2.11

I'm assuming this is a glitch. But I spent a very long time creating a model, and then wanted to switch to a different model to duplicate some settings. When doing so initially the model select screen was blank, no models at all listed. I rebooted and nothing. Finally thought to tap the pgup/dn button and it seemed to switch to a page that listed models, but only my 2 other ones that were previously there. The new one was nowhere to be found. After selecting one of the previous models, the new one I created still did not appear in the model page. I checked the file manager to confirm that all 3 models are indeed stored. But I just cant get the latest one to show up on the model select page. It was created with the model wizard.

**Comment by EngelMT** [comment] 2022-07-27 04:24
How did you spell the model name?  There is a bug in 1.2.11.  This only allows one capital letter at the beginning of the name. Will be fixed in 1.2.12 I think.

**Comment by iflyforfood** [comment] 2022-07-27 04:28
> How did you spell the model name? There is a bug in 1.2.11. This only allows one capital letter at the beginning of the name. Will be fixed in 1.2.12 I think.

Well that explains it then. The name is in all caps.

**Comment by bsongis-frsky** [comment] 2022-07-27 06:49
Duplicate of #1760

**Closed by bsongis-frsky** 2022-07-27 06:49 UTC
