### ISSUE TITLE
No VFR from R9  receiver on X20 Pro when combined with 2.4 receiver both bound on internal module

### ISSUE THREAD

**Issue by raydars** [FrSkyRC/ETHOS-Feedback-Community#2872] opened 2023-09-06 16:42 UTC
Ethos 1.4.11
RX 1 R8 pro on 2.1.14 UID 0
RX 2 R9 mini on 1.3.1 FLEX UID 2

Telemetry discovered, RSSI for both rx discovered but only VFR for 2.4. Is this a bug or by design?

**Comment by raydars** [comment] 2023-09-18 19:34
Update:   Have tried TWR12 on 1.0.5  and R9 mini on Flex and there is no 868mhz VFR when discovering sensors.

Tried a new model and bound R9 mini on Flex 868 and when discovering sensors again no VFR.

Conclusion VFR on all 868mhz usage appears to be missing with x20 Pro on Ethos 1.4.11

**Comment by bsongis-frsky** [comment] 2023-09-19 11:48
Pushed to the RF team

**Comment by SmartTommy** [comment] 2023-09-20 02:51
hi raydars, 
 thank you for your feedback, this is the new firmware,please test. we will release the new firmware after internal testing.


[TD-ISRMPro_1.0.12_test.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/12668101/TD-ISRMPro_1.0.12_test.zip)

**Comment by SmartTommy** [comment] 2023-09-21 00:14
> Hi, am I correct to presume this is a new TX RF board firmware.
> 
> If so I am reluctant to test as at this point as I have no original Pro TX RF board firmware to flash back to if I encounter issues...
> 
> If you can provide the previous RF board firmware so I can roll back if required then I can test the new.

could you show us what is the TD-ISRMPro firmware version you used now?

**Comment by raydars** [comment] 2023-09-21 04:28
![20230921_052647](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/62261271/76e0d1b5-c0b9-41b0-b3b0-562bd60f7b71)

**Comment by raydars** [comment] 2023-09-21 18:00
Ok I have tested various combinations for Flex 868mhz VFR,   I have not flown or tested other aspects of this firmware. 


868mhz R9 mini  by itself,  VFR present along with the other sensors to be expected.

TWR12 with 868 R9 mini,  VFR present for both 2.4 and 868mhz along with the other sensors to be expected.

TDR18, VFR present for both 2.4 and 868mhz along with the other sensors to be expected. 

Conclusion,  flex 868mhz VFR now seems to be present where expected on the test firmware.

**Comment by mawzthefinn** [comment] 2023-10-19 13:11
Sounds like the issue is resolved, closing off

**Closed by mawzthefinn** 2023-10-19 13:11 UTC
