### ISSUE TITLE
Old telemetry values still there after "Reset Flight" and "Reset Telemetry"

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#2612] opened 2023-04-29 08:40 UTC
I'm sorry for coming with several issues at once. Just started my flying season and used X20s for first time with real models (works great!).

This issue is tricky to describe so I made a video.

In short: 
- after "Reset Flight" and "Reset Telemetry" voltage value of main main battery is still remembered by the radio
- after I plug-in new battery, voltage slowly "blends" from previous flight voltage to new battery voltage

Video:
- https://www.youtube.com/watch?v=A220pJ0BOLw

Explaining video
- [0:00] Video starts with situation "after flight". Battery (6s Lipo) is discharged, voltage is 22.36V (`RBOX V1` telemetry counter)
- [0:08] I disconnect the battery, "telemetry lost" voice comes
- [0:19] I do "Reset Flight" and "Reset Telemetry" (although I think just one of them should be enough)
- [0:30] I insert and connect new, fully charged battery
- [0:40] System initialized, getting "Telemetry Recovered" message (which I think is not correct, I'll setup another issue for this)
- [0:47] Voltage value comes from the flight controller for the first time
  - However, as you see, radio shows "old voltage" from previous battery and flight, and voltage is slowly increasing to reach real voltage, which flight controller delivers
  - Which causes alarm sound, which I programmed to warn me, if I connect battery which is not fully charged
- [0:57] Voltage displayed by the radio settles on 24.84V, which is what flight controller is sending

Then in next step I show how it looks, it I would connect same batter after radio power on
- [1:02] I disconnect the battery
- [1:09] Radio power off
- [1:13] Radio power on
- [1:21] Connecting battery
- [1:34] Voltage comes for the first time from flight controller
  - As you can see, it is correct right from the beginning, 24.84V
  - So you can see, that flight controller is sending the right data from the beginning

Problems which I have because of that:
- It makes it hard to setup an alarm, to tell that you connected non-charged battery.
- If you want to check or log "minimum voltage" (`RBOX V1-`), the value will be useless. Because this value might be coming from previous flight

Excuse me lengthy description, I felt it was needed.

**Comment by RealTadango** [comment] 2023-05-05 09:36
Looks like the averaging data for the voltage sensor is not reset.

**Comment by bsongis-frsky** [comment] 2023-05-11 09:40
Duplicate of #2613

**Closed by bsongis-frsky** 2023-05-11 09:40 UTC
Labels: bug
