### ISSUE TITLE
ETHOS V1.4.12 No Timer for runingtime of the TX it self

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#2977] opened 2023-10-15 07:32 UTC
There is
No timer for TX ON-Time
No timer independet from a Model or a global timer Start, Stop, Persistent

**Comment by mawzthefinn** [comment] 2023-10-15 11:14
Duplicate of #1595

**Closed by mawzthefinn** 2023-10-15 11:14 UTC
