### ISSUE TITLE
Request: Telemetry options

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#445] opened 2021-06-09 07:43 UTC
I really like to request the following options to sensor parameters:

1. Analog voltage input options:
Using a ADC input of a receiver gives me incorrect readings..
Using a multiplier option will correct these readings.
Same for VFAS as other analog type sensors.

* [ ] Multiplier (default 1)
* [ ] Offset (default 0)

2. RPM Options
Now I have a reading of 3000rpm, while the real headspeed is 1500rpm..
I need to set a Blade count to 2 blades. to have a correct reading.

Heli Gear ratio:
Maingear teeth / motor pinion teeth = ratio
motor rpm / ratio = headspeed
 
So extra RPM options will be:

* [ ] Blade / Pole count (default 1)
* [ ] Maingear teeth (default 1)
* [ ] Pinion teeth (default 1)

3. Fuel sensor:
* [ ] add mA unit.

4. Cell sensor
* [ ] add lowest Cell of total option.

**Comment by bsongis-frsky** [comment] 2021-06-11 06:05
Duplicate of other issues, please search "sensor" in all open issues

**Closed by bsongis-frsky** 2021-06-11 06:05 UTC
Labels: enhancement
