### ISSUE TITLE
REQUEST FOR ETHOS SUITE

### ISSUE THREAD

**Issue by builda1** [FrSkyRC/ETHOS-Feedback-Community#2812] opened 2023-08-13 15:03 UTC
Hi everyone, just an idea here-in the "firmware updates" section in Suite for the various ISRM modules in radios, how about adding Rx Firmware too for recievers? Then everything is in one place, plus i think most of us keep Rx Firmware in the Firmwares folder too anyway yes?? Not so much a "Need" but a "logical nice to have". 

Keep up the good work guys. @mawzthefinn if @bsongis has this planned already feel free to just close the issue/request ok👍

**Comment by mawzthefinn** [comment] 2023-08-13 15:16
Duplicate of my request #1568 ;-)

It's a good idea, I'm closing this as a duplicate, but feel free to continue the conversation in the linked issue.

**Closed by mawzthefinn** 2023-08-13 15:16 UTC
Labels: duplicate
