### ISSUE TITLE
Improvement: reconnect last BT device on system start

### ISSUE THREAD

**Issue by PiotrSzukalski** [FrSkyRC/ETHOS-Feedback-Community#1885] opened 2022-08-29 12:51 UTC
Add the option for reconnecting last used BT device at system start.
I switch off radio for break on the field, After starting it up again, the radio did not reconnect BT headset.
At least make possible to assign that action for some function button.

**Comment by PiotrSzukalski** [comment] 2022-11-17 07:34
Aby posibility to improve BT reconnection after repowering?

**Comment by mawzthefinn** [comment] 2022-12-15 23:20
This is a duplicate of #1583 , closing in favour of that issue

**Closed by mawzthefinn** 2022-12-15 23:20 UTC
Labels: duplicate
