### ISSUE TITLE
Lua: playNumber() not working (simulator)

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#1167] opened 2021-11-28 10:28 UTC
I have setup a simple example to test **playNumber()** but I dont hear any output in the simulator.
Debug output tells me that it is performend ok.

```lua
system.playNumber(50, UNIT_PERCENT, 0)
```

Debug output
`004819 [en] playNumber(50, unit=%, precision=0)
004820 playFile('/audio/en/system/50.wav', flags=0, id=0)
004822 playFile('/audio/en/system/percents.wav', flags=0, id=0)`

**Comment by bsongis-frsky** [comment] 2021-11-29 06:23
Duplicate of #1169, there is no audio at all

**Closed by bsongis-frsky** 2021-11-29 06:23 UTC

**Comment by Hobby4life** [comment] 2021-11-29 07:00
Hmm, now with lua scripting audio in the simulator would be no luxury.
