### ISSUE TITLE
1.4.8: Conditional mixer weights are limited to +/-100%

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2592] opened 2023-04-20 15:19 UTC
There seems to be a mixer interface issue: conditional weights are limited to +/-100% 

Default weight (on the top line) works as expected.

Ethos 1.4.8
Twin X-Lite S transmitter and sImulator

![2023-04-20_161023](https://user-images.githubusercontent.com/6317479/233411256-56ebef2b-8c13-4b2d-a212-503a4df80b7b.png)

**Comment by mawzthefinn** [comment] 2023-04-21 18:51
Probably the same issue as #1832

**Comment by RC-SOAR** [comment] 2023-04-21 19:49
I hope this can be dealt with.

**Comment by mawzthefinn** [comment] 2023-04-21 20:33
Actually, that's a VAR mix, right? If so this is definitely a duplicate of #1832 

Definitely needs addressing.

**Comment by RC-SOAR** [comment] 2023-04-22 00:06
> Actually, that's a VAR mix, right? If so this is definitely a duplicate of #1832 
> 
> 
> 
> Definitely needs addressing. 

Yes, it's a VAR mix

**Comment by mawzthefinn** [comment] 2023-04-22 00:21
Closing this one off as a duplicate then. It's much older than 1.4.8 as well.

**Closed by mawzthefinn** 2023-04-22 00:21 UTC
Labels: duplicate

**Comment by RC-SOAR** [comment] 2023-04-22 07:49
I would urge the devs to reconsider!! This is clearly a bug or at least highly undesirable behaviour. Conditional weights should have the same limits as default weights!

The issue was reported to me by a user of one of my templates when assigning a condition to the default weight. This kind of thing should not break a setup.

**Comment by mawzthefinn** [comment] 2023-04-26 00:15
@Nicholas-Luoyi 

Probably want to pursue this under the open #1832 instead of the closed duplicate
