### ISSUE TITLE
channel sequenzer 6-8 channels and max 25s timing, Graphically programmable

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#1027] opened 2021-10-03 05:09 UTC
This function is still missing 
Channel sequencer for 6-8 channels
Graphically programmable

Since Ethos is graphically oriented, you could also set a ready-made sequencer for 6-8 channels with a timing of max 25s.
Then you don't need to use a ready made third party product from Jeti or other manufacturers.

**Comment by abelsingla** [comment] 2021-10-03 13:16
I'm agree, I'm comming from Jeti and this is the only funktion missing for me right now.

**Comment by bsongis-frsky** [comment] 2021-10-04 09:37
Duplicate of #657

**Closed by bsongis-frsky** 2021-10-04 09:37 UTC
