### ISSUE TITLE
No F.Port telemetry ? (plug or bluetooth)

### ISSUE THREAD

**Issue by EmbededFabrication** [FrSkyRC/ETHOS-Feedback-Community#975] opened 2021-09-19 09:46 UTC
There is no telemetry signal from the F.Port plug on the back of an X20 and "bluetooth telemetry" in the settings does nothing
when will these features be activated?
It seems to pair with the freelink app but not with telemetry viewer

**Comment by bsongis-frsky** [comment] 2021-09-20 05:47
Duplicate of #160

**Closed by bsongis-frsky** 2021-09-20 05:47 UTC
