### ISSUE TITLE
Slowing transition between flight modes.

### ISSUE THREAD

**Issue by prikrylm** [FrSkyRC/ETHOS-Feedback-Community#125] opened 2021-04-25 18:41 UTC
ETHOS v1.0.3 on X12S
A slow transition between flight modes is almost essential for helicopters. And without this feature, it is not a good transmitter today.

**Comment by aeroplanebelg** [comment] 2021-04-29 18:19
A slow transition between flight modes is almost essential for helicopters , gilders and planes .I agree with you, it's essential !!!!
good see.!! x12s os1.0.3
thank you.

**Comment by PribylV** [comment] 2021-06-23 20:09
I agree. I also consider this feature to be very important.

**Comment by bsongis-frsky** [comment] 2021-09-09 06:01
Duplicate of #93

**Closed by bsongis-frsky** 2021-09-09 06:01 UTC

**Comment by seilfly** [comment] 2021-09-09 13:18
![Flight Mode su_sd](https://user-images.githubusercontent.com/12104820/132693095-263797ef-761d-4c15-855d-5722717ed75c.png)

**Comment by seilfly** [comment] 2021-09-09 13:21
Every time I request such a function, it is closed afterwards. Why?. There are many who want this !

**Comment by Adelaxie** [comment] 2021-09-10 06:27
It's duplicated with #93 which as replied above.
Follow #93 for more progress, please!
@seilfly
