### ISSUE TITLE
Is there a instant trim function

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#1987] opened 2022-10-21 11:13 UTC
Is there an instant trim function yet on Ethos? If so how to use?

**Comment by mawzthefinn** [comment] 2022-10-21 13:04
Duplicate of #295 

It’s been requested, but not implemented.

**Comment by bsongis-frsky** [comment] 2022-10-21 16:42
Duplicate. Too much to do!

**Closed by bsongis-frsky** 2022-10-21 16:42 UTC

**Comment by robertoalmeida** [comment] 2022-12-26 22:32
> Is there an instant trim function yet on Ethos? If so how to use?

Will it be implemented?
