### ISSUE TITLE
Enhancement for 'Sticks' menu will also enhance the 'New Model Wizard'

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3408] opened 2024-02-11 00:48 UTC
I feel that transmitter mode is a dead concept, now that radios can play mix and match with input-output relationships. As a user I feel that the sticks menu should allow a user to define their favorite outputs, so that the wizard produces a model that has mixes that they want. Maybe that is elevator on the center slider and throttle on the right stick. Currently the sticks menu is limiting this. 

I understand that there is also a drive for having the wizard produce a working model for a total noob. Having a TX Mode choice menu that gave options for mode 1, 2, 3, 4, and custom would be great and then a user that flys FPVs with actuator driven old-timer planes can use the analogs to drive their camera gimbals and the momentary switches to run the elevator, rudder AND the wizard will produce a much more useable set of mixers for that as well as the noob's default models.

**Comment by spoke2570** [comment] 2024-02-11 01:06
It would also be nice to override the radios default stick mode on a per model basis. I am sure there are a lot of glider guys using aileron mix for their rudders.

**Comment by mawzthefinn** [comment] 2024-02-11 02:27
Functional duplicate of #1790 

Please continue the conversation there, the addition to Wizard is a pretty good idea

**Closed by mawzthefinn** 2024-02-11 02:27 UTC
Labels: duplicate
