### ISSUE TITLE
Trainer Bluetooth Link Resolution / Refresh Rate Problem

### ISSUE THREAD

**Issue by LaserAV-Calgary** [FrSkyRC/ETHOS-Feedback-Community#1709] opened 2022-05-29 23:28 UTC
Using BT, the Trainer data Resolution is very low and/or the refresh of the data is very slow.
This presents itself as jerky and jittery surface movement when the slave radio is in control.

Using 2 X20S radios with latest firmware/bootloader etc

**Comment by bsongis-frsky** [comment] 2022-06-10 09:44
Duplicate of #1710

**Closed by bsongis-frsky** 2022-06-10 09:44 UTC
