### ISSUE TITLE
Enhancement: Make Throttle cut status available as source for logic.

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#659] opened 2021-07-18 20:55 UTC
The Throttle cut sticky function is a very welcome function in RC4.

The same function I always created it in Logic.
Because I created it in logic, I always knew the status of the throttle cut.
This to trigger other things in logic or special functions.

Now with that function implemented I have no source of status for it to trigger something else.

**Comment by bsongis-frsky** [comment] 2021-07-19 05:21
Duplicate of #528

**Closed by bsongis-frsky** 2021-07-19 05:21 UTC
