### ISSUE TITLE
Emergency Mode on Xicoy Widget 

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3704] opened 2024-03-25 20:47 UTC
During test runs with my turbine aircraft today, emergency mode occurred when using the Xicoy widget.  The widget was very slow, then it disappeared and then entered emergency mode. During emergency mode the turbine stopped and it was no longer possible to control the aircraft.  If it had happened in flight the plane would have been uncontrollable.  How is it possible that a Lua widget causes the entire remote control to fail?  Shouldn't control remain in emergency mode?

X20pro
1.5.2
Xicoy Widget on internal Storage

**Comment by bsongis-frsky** [comment] 2024-03-25 21:01
Would you please attach your model data to the issue?

Le lun. 25 mars 2024 à 21:47, WhiskeyGolf ***@***.***> a
écrit :

**Comment by WhiskeyGolf** [comment] 2024-03-25 21:59
Do you mean the model .bin file?

**Comment by WhiskeyGolf** [comment] 2024-03-25 23:47
[l-39_x45turbs8r.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14750597/l-39_x45turbs8r.zip)

**Comment by bsongis-frsky** [comment] 2024-03-26 09:24
Perfect, please wait for my feedback before flying. There are 2 issues:
1) EM shouldn't occur
2) You should keep control of the model even after EM

**Comment by WhiskeyGolf** [comment] 2024-03-26 12:11
I found out that the widget becomes slower and parts are missing if, for example, I add the unit % to the sensor for fuel.  That would be an explanation for why the widget fails.  But that shouldn't cause a crash.

**Comment by WhiskeyGolf** [comment] 2024-03-26 12:13
Addition: 

-After I changed the colors in the widget several times, the emergency mode appeared again.

-When switching to another model, emergency mode reappeared.  -> I wasn't able to turn off the radio at first.

( new Version 1.5.3 )

**Comment by bsongis-frsky** [comment] 2024-03-26 12:49
Please keep it as much as possible untouched, it will help me to find the first issue (the EM). For now I am on the second.

**Comment by bsongis-frsky** [comment] 2024-03-26 12:53
Emergency mode added to the simulator.
[F12] Restart the simulator
[Shift-F12] Restart the simulator in emergency mode

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/e5c4bdfc-1fd1-483f-8392-972396d653c7)

**Comment by bsongis-frsky** [comment] 2024-03-26 14:26
I have found one bug. It explains why you loose the control in Emergency Mode. It will be fixed in the next nightlies and the release 1.5.4 will come soon as it is critical.

Now I want to understand why you get this EM. Obviously it's because of the Lua script, but it shouldn't happen ...

**Comment by bsongis-frsky** [comment] 2024-03-26 15:25
I don't have your Lua scripts, is it possible you attach them to the issue? Unless they are not public? Then you can send them by email?
Also you write that you change an unit on a Telemetry sensor, but I see no sensor in the model from the file above!

**Comment by WhiskeyGolf** [comment] 2024-03-26 19:49
https://github.com/aviat40/ETHOS-Lua

here you can geht the lua ( xicoy )

**Comment by WhiskeyGolf** [comment] 2024-03-26 20:09
![030B0868-ECD0-4DE6-A39A-FD98D6D5C995](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/3b136403-acbf-44ab-acfc-f4c8099b4f56)
![B6D40785-6418-420F-8724-ED7B0AEB1736](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/8b263426-5133-4911-9583-efc13651905b)
![CE3DBFC4-34D5-489B-B0A1-1389C4164E4B](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/0f6d8da6-6fdb-43b2-9aa3-d2a93f7dc199)

**Comment by WhiskeyGolf** [comment] 2024-03-26 20:11
The last 7 sensors are from the Turbine Telemetry.  These are DIY sensors.  They should actually be in the model file too

**Comment by bsongis-frsky** [comment] 2024-03-26 20:16
I have received a message from Xicoy author in the meantime, perfect!

**Comment by bsongis-frsky** [comment] 2024-03-26 20:17
The model you have attached above seems old, and it uses another Lua script which registers a Lua source "Example".
Would you please attach again your model up to date?

**Comment by bsongis-frsky** [comment] 2024-03-26 20:18
This is the Telemetry screen from the model attached above, there is no sensor!

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/d03df7e9-7601-48e8-a7de-bd0cc187868e)

**Comment by WhiskeyGolf** [comment] 2024-03-26 20:54
[l-39_x45turbs8r.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14764560/l-39_x45turbs8r.bin.zip)

**Comment by WhiskeyGolf** [comment] 2024-03-26 20:54
Hope this works

Unfortunately I can't test it because I only have a Mac

**Comment by bsongis-frsky** [comment] 2024-03-26 21:00
There are 2 Lua scripts that you use in this model:
- agauge (widget)
- Example (source)

**Comment by bsongis-frsky** [comment] 2024-03-26 21:00
Better, I have sensors!

**Comment by bsongis-frsky** [comment] 2024-03-26 21:12
Wow it seems a problem with the Lua widget, I get this message now (I have modified a lot the sensors)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0018b736-a4c0-4e1c-9876-5cf544078c85)

**Comment by bsongis-frsky** [comment] 2024-03-26 21:15
And once the script is killed, I reproduce the EM. I have understood!

I need a good night to fix it and I hope I can release 1.5.4 tomorrow during the evening!

**Comment by WhiskeyGolf** [comment] 2024-03-26 21:33
I'm glad you found the errors.  Thank you very much for solving the problem!  
Can such a serious problem also occur with other Lua widgets (Yaapu / Zavionix)?  
Or is there anything I can do to make operations safer?

**Comment by bsongis-frsky** [comment] 2024-03-27 09:31
Here the full analysis of this issue, as I understand it now:

1) Your model is OFF. You have no value for FUEL sensor. Here the screenshot.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/bc7d52b9-f150-4dca-ac9d-05e7da2ddb1f)

2) As your FUEL sensor doesn't return a value (it returns `nil`), the Xicoy script raises an error, line 394 (percent is `nil`). Here the screenshot.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/f9c5ea6b-a4e5-405c-93ab-8c8ab8df0ea7)

3) There is a memory leak in Ethos (all versions until now), the error is allocated in RAM and is never destroyed

4) After some time (it may be long, the memory leak is not huge, that's why it has never been reported!), we reach the max limit that Ethos allows to Lua scripts. Here the screenshot.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/f5a5767a-db7b-46f2-a439-f5dc574753ec)

5) Now there are many ways to produce the EM. 
- either you click on the widget to open the menu (missing protection, the widget has been destroyed)
- you were modifying some setting inside the widget, you wrote about the colours (missing protection again)

6) The EM doesn't load correctly your model data (bug found and fixed yesterday)

Please tell me if you think I am wrong on any step above. I am fixing this issue and adding non regression tests to avoid it occurs again.

**Comment by bsongis-frsky** [comment] 2024-03-27 09:40
> I'm glad you found the errors. Thank you very much for solving the problem! Can such a serious problem also occur with other Lua widgets (Yaapu / Zavionix)? Or is there anything I can do to make operations safer?

I think those scripts don't raise errors at full speed! And even Xicoy script only produces the errors because your plane is OFF. So you would have been safe in flight.

Then we have all the cascading effects which come to the EM and bad model load. This is why 1.5.4 should come tonight with the fixes as it is critical, in case of Lua script errors!

**Comment by WhiskeyGolf** [comment] 2024-03-27 11:24
I would agree with the whole thing, but the first problem occurred while the turbine was running during ground tests.  Here only the % character was added to a sensor, which caused the Lua to crash.  Of course, it shouldn't be the case that the entire system crashes if one sensor is lost.

**Comment by bsongis-frsky** [comment] 2024-03-27 13:53
Very interesting.

By adding the `%` unit, `sensor:stringValue()` will return i.e. "50%", which is not anymore parseable by the Lua function `tonumber`, and the script will produce the same error, at full speed. Here the screenshot.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/6dc36fc4-064e-4609-9b70-1efe047e92dc)

Then the points 3. 4. 5. and 6. from the analysis above again!

**Comment by RealTadango** [comment] 2024-03-27 13:59
Would it be a good idea to halt a lua script that generates more the x errors a second?

**Comment by WhiskeyGolf** [comment] 2024-03-27 17:53
What does the Xicoy author say about the problem?  Will there be a new widget or should the widget work on 1.5.4?

**Comment by bsongis-frsky** [comment] 2024-03-27 18:45
We have a call tonight ...

**Comment by bsongis-frsky** [comment] 2024-03-28 08:03
Fixes ready for 1.5.4
The Xicoy widget won't make the radio enter into EM even in its current version.
But Xicoy widget will be upgraded soon, it should be far quicker with the use of partial screen updates!

**Closed as completed by bsongis-frsky** 2024-03-28 08:03 UTC

**Comment by WhiskeyGolf** [comment] 2024-03-28 08:48
That's great news!  thanks for that

**Comment by i3dm** [comment] 2024-03-30 03:30
> I'm glad you found the errors. Thank you very much for solving the problem! Can such a serious problem also occur with other Lua widgets (Yaapu / Zavionix)? Or is there anything I can do to make operations safer?

Zavionix no. As I implemented protections in sw against these kind of issues.

**Comment by bsongis-frsky** [comment] 2024-04-03 10:48
Non regression test added for the EM model load
