### ISSUE TITLE
X20S V2.1.8 Beta, X6R ACCST V2.1.0 with Neuron 60, Sensor lost every few seconds

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#357] opened 2021-05-28 15:00 UTC
Test with X20S V2.1.8 Beta 
X6R ACCST V2.1.0 D16 and a Neuron 60 ESC with SBEC
the neuron telemetry  ist not stabile
Every few seconds I get the message 
"sensor lost", then sensor back , etc.

Same test with a TX16S or X9D+2019 or X9E everything is ok
no sensor lost, everything stabile
this has been my test setup for a year
for servo test, currents and voltages

Distance Rx to Tx approx.  1-2m

X20 Telemetry not usable as it is

**Comment by islandflight** [comment] 2021-05-29 06:39
Yes noticed this too and also a lag with the data. This has been discussed in the firmware github page and the lag has been traced back to a filter in ethos. @smartommy has advised this would be fixed in the next ethos update I don't know if this will also address the most telemetry issue.

**Comment by hrenz** [comment] 2021-05-29 07:21
here a Link to the 4-5 Videos with this problem and long commts

https://frsky-forum.de/index.php?thread/5508-x20-mit-td2-1-8beta-und-ethos-v1-07-an-x6r-v2-1-lbt-mit-neuron-60/&postID=71492#post71492

**Comment by SmartTommy** [comment] 2021-05-29 07:47
> here a Link to the 4-5 Videos with this problem and long comments (techn German)
> 
> https://frsky-forum.de/index.php?thread/5508-x20-mit-td2-1-8beta-und-ethos-v1-07-an-x6r-v2-1-lbt-mit-neuron-60/&postID=71492#post71492

@hrenz ,could you show the vedios here or youtobe, I don't have an IDfor this forum your post link. Thank you.

**Comment by hrenz** [comment] 2021-05-29 07:52
will try it, are vey large
ah I seen,
not possible here, max 10MB

**Comment by WismyYao** [comment] 2021-06-04 01:33
We tried many times and failed to reproduce the problem you described.
What version of firmware are you using? Is it 1.0.7 ?
Hope you can provide more information. Thanks for your feedback.

**Comment by hrenz** [comment] 2021-06-04 05:36
as I described above
Test with X20S V2.1.8 Beta
X6R ACCST V2.1.0 D16 and a Neuron 60 ESC with SBEC
there is no later V2.1.0 for X6R, X8R

with TX16S, X9d+2019, X9E its all ok, never sensor lost, realy never
with X20S allways sensor lost from Neuron 60 every few soconds

I can repeat the Test day by day
look a may 4-5 Videos at german Engel ltd, 
or ask Andreas Engel yourself
you will see it.

I was very surprised too because this is the simplest configuration.

were can i upload the videos about 20 to 80MB each

**Comment by Hobby4life** [comment] 2021-06-04 05:43
I have similar issues.

X20S v1.07 fw2.18
Unilog S32 logger, on X8R, X4R-SB constantly telemetry lost.

X10 or other, 100% connection, no lost

**Comment by islandflight** [comment] 2021-06-04 05:50
Have you been able to fix the issue with the filter causing delayed esc telemetry data? Thanks

**Comment by hrenz** [comment] 2021-06-04 05:56
were is a filter to delay?

**Comment by islandflight** [comment] 2021-06-04 06:03
There is no.physical setting I think it must be built into the ethos software @SmartTommy advised on the receiver firmware page that the lag issue had been traced back to a filter in ethos and that it was going to be addressed on the next ethos firmware release.

**Comment by hrenz** [comment] 2021-06-04 06:44
We will see with next V1.0.8

**Comment by bsongis-frsky** [comment] 2021-06-04 07:14
> Have you been able to fix the issue with the filter causing delayed esc telemetry data? Thanks

@islandflight what do you mean by this? where this filter? in Ethos? in the module?

**Comment by islandflight** [comment] 2021-06-04 07:52
> > Have you been able to fix the issue with the filter causing delayed esc telemetry data? Thanks
> 
> @islandflight what do you mean by this? where this filter? in Ethos? in the module?

Please see #121 in frsky firmware git hub page. The telemetry data being displayed from the neuron esc lags behind what the motor is doing ie current capacity rpm @ smartommy says this has been traced back to a telemetry filter in ethos

**Comment by bsongis-frsky** [comment] 2021-06-04 08:04
OK. This one is fixed. We were averaging the RPM over 10 samples.

But it's very different from @hrenz issue

**Comment by WismyYao** [comment] 2021-06-04 08:06
> as I described above
> Test with X20S with V1.0.7 and Tandem V2.1.8 Beta
> X6R ACCST V2.1.0 D16 and a Neuron 60 ESC with SBEC
> there is no other/newer V2.1.0 for X6R, X8R
> 
> with TX16S, X9D+2019, X9E its all ok, never sensor lost, realy never
> with X20S allways sensor lost from Neuron 60 every few soconds, not from RX
> 
> I can repeat the Test day by day
> look a may 4-5 Videos at german Engel ltd,
> or ask Andreas Engel yourself
> you will see it.
> 
> I was very surprised too because this is the simplest configuration.
> Distance RX TX 1m or 10m does not matter
> 
> Were can i upload the videos, each about 20 to 80MB
> 
> other Tests from today
> RX8R with V2.1.x no Problem, no Sensor lost from Neuron 60 with X20s and my other TX´s
> 
> its seems to be a combination of X6R, X8R V2.1.0 with Neuron 60 and X20S intolerance signal timing

It would be great if you could provide some videos . Thanks a lot

**Comment by bsongis-frsky** [comment] 2021-06-04 08:41
@hrenz here a few more questions:
1) which sensor is in RED in Model / Telemetry
2) if you see a red sensor value, what are its limits?
3) please pay attention to the Temp sensor, its low limit should be 0, not 1
If a value is out of range, it is rejected. If you receive only out or range values, the sensor will be considered as wrong and you will get a warning

**Comment by bsongis-frsky** [comment] 2021-06-04 08:41
ESC sensors limits have been updated in 1.0.8

**Comment by hrenz** [comment] 2021-06-04 12:43
its not a Problem from Limits its a combination for X6R (X8R) with a Sensor  to X20  ETHOS

only the telm  values form Neutron60 is in red never the RX values itself

will upload my 5  mp4 Files tomorrow

its never sensor lost with a  RX8R  and X20 ETHOS 
Errors appears only with X6R / X8R and X20 ETHOS

**Comment by bsongis-frsky** [comment] 2021-06-04 13:16
Which is the sensor which becomes red in Model / Telemetry?

**Comment by hrenz** [comment] 2021-06-04 14:01
here are the 5 Videos  mp4  about 210MB 
download link  open for 5 days
https://www.hidrive.strato.com/lnk/BPxEreoV

its the neuron60 with X6R, X8R (V2.1.0 ) and X20 ETHOS with Tandem V2.1.8 and V1.0.8Beta
only at this combinaition, not with RX8R with Neuron60

**Comment by bsongis-frsky** [comment] 2021-06-04 14:27
Look at your ESC Temp, edit it and change the min value to 0°C, not 1°C

**Comment by hrenz** [comment] 2021-06-04 15:22
ok have done set to 0°C

but  the Temp is not 0°C  it is 31°C
can see it with  RX8R at all other TX I have

think there is a data interpreter problem with X6R, X8R to  X20 ETHOS

shall I test more?

**Comment by bsongis-frsky** [comment] 2021-06-04 17:41
Temp needs a fix then

**Comment by hrenz** [comment] 2021-06-05 03:42
But this error with lost Sensor ist only with X6R, X8R V2.1.0
not  with RX6R, RX8R under same condditions.

So it must be  the V2.1.0 at X6R, X8R

**Comment by bsongis-frsky** [comment] 2021-06-06 08:00
Do you see 31°C in OpenTX with the same sensor and same receiver? I don't see any obvious issue in Ethos about it.

**Comment by bsongis-frsky** [comment] 2021-06-06 17:18
@hrenz Do you see 31°C in OpenTX with the same sensor and same receiver? I don't see any obvious issue in Ethos about it.

If YES, then it is a bug in Ethos that I would like to fix quicky in 1.0.8
If NO, it's a RF bug, not Ethos

**Comment by bsongis-frsky** [comment] 2021-06-11 06:04
No answer, please check it is fully fixed in 1.0.9 candidate 4 (or above)
Feel free to reopen if needed

**Closed by bsongis-frsky** 2021-06-11 06:04 UTC

**Comment by hrenz** [comment] 2021-06-11 19:24
Hy Betrand,
Today Test TX, RX, FLVSS, GPS, VARIO
TX:  X20S V1.0.9.C4  TD V2.1.8
RX: X6R, S6R  V2.1.0 V2.1.6 (ACCST)
Akku 5S NiMH 2000mAh
Distance Tx, RX about 1,5m

Test with X20S
with a FLVSS as single Sensor, NO "Sensor Lost" with X6R, S6R
with a Vario as single Sensor,  "Sensor Lost"  about every 1min, seldom "Telemetry Lost" with X6R, S6R
with a GPS as single Sensor, "Sensor Lost" about every 10-15 sec with X6R S6R

with FLVSS, Vario, GPS all 3 Sensors in chain, X6R and S6R shows only the Rx internal Values, no external Sensors!

Test with X9D+SE 2019 (ISRM S-X9 with 2.1.6, and with V2.1.0 tested)
with FLVSS, Vario, GPS all 3 Sensors in chain, S6R and X6R, shows No Data no internal Values, no external Sensors!
with FLVSS, as singel Sensor, Test with X6R and S6R,  shows No Date, no internal Values, no external Sensor
this  error only occurs after I have had been flashed to the latest Tx and Rx firmware, such a mess!

Test with a XJT-Modul v2.1.0 (TX16S 4in1 D16 V2 LBT)
with FLVSS, Vario, GPS all 3 Sensors in chain, S6R and X6R, NO "Sensor Lost", all internal und external Sensor Values ok!

After this test:
I think FrSky has a big big Telemetry problem with their latest V2.1.x  firmware 
for Tx and for RX  and with ACCST, LBT at ISRM Modul, but not with XJT

Have not tested with ACCESS and not ACCST with FCC

**Comment by Hobby4life** [comment] 2021-06-11 19:46
I have seen similar issues, Only with ACCST receivers. Swapped them out with ACCESS receivers, no problems anymore.
Has something to do with the ACCST protocol.

**Comment by hrenz** [comment] 2021-06-11 19:53
All my other TX ( X9E, X9D, Tx16S) have XJT Moduls with ACCST LBT V1.x and V2.1.0  openTx V2.3.11
and they work very well with all sensors in chain, no Problem!

So its a problem from Frsky with their ACCST, LBT  V2.1.0 with ISRM, but not with ACCT, LBT V2.1.0  with XJT

**Comment by SmartTommy** [comment] 2021-06-12 01:41
> Hy Betrand,
> Today Test TX, RX, FLVSS, GPS, VARIO
> TX: X20S V1.0.9.C4 TD V2.1.8
> RX: X6R, S6R V2.1.0 V2.1.6 (ACCST)
> Akku 5S NiMH 2000mAh
> Distance Tx, RX about 1,5m
> 
> Test with X20S V1.0.9.C4 TD V2.1.8
> with a FLVSS as single Sensor, NO "Sensor Lost" with X6R, S6R
> with a Vario as single Sensor, "Sensor Lost" about every 1min, seldom "Telemetry Lost" with X6R, S6R
> with a GPS as single Sensor, "Sensor Lost" about every 10-15 sec with X6R S6R
> with FLVSS, Vario, GPS all 3 Sensors in chain, X6R and S6R shows only the Rx internal Values, no external Sensors!
> 
> Test with X9D+SE 2019 (ISRM S-X9 with 2.1.6, and with V2.1.0 tested) openTx V2.3.11
> with FLVSS, Vario, GPS all 3 Sensors in chain, S6R and X6R, shows No Data no internal Values, no external Sensors!
> with FLVSS, as singel Sensor, Test with X6R and S6R, shows No Date, no internal Values, no external Sensor
> this error only occurs after I have had been flashed to the latest Tx and Rx firmware, such a mess!
> and I can't get rid of this error not even by flashing back, such big mess!
> 
> Test with a XJT-Modul v2.1.0 (TX16S 4in1 D16 V2 LBT) openTx V2.3.11
> with FLVSS, Vario, GPS all 3 Sensors in chain, S6R and X6R, NO "Sensor Lost", all internal und external Sensor Values ok!
> All fine!
> 
> After this test:
> I think FrSky has a big big Telemetry problem with their latest V2.1.x firmware
> for Tx and for RX and with ACCST, LBT, ISRM Modul, but not with a XJT V2.1.0
> 
> Have not tested with ACCESS and not ACCST with FCC

Hi hrenz,

have you test the the new firmware: [https://www.frsky-rc.com/s6r/](url)   
![image](https://user-images.githubusercontent.com/5809355/121761432-50565200-cb62-11eb-889f-94f51b10fb85.png)

**Comment by hrenz** [comment] 2021-06-12 03:51
Next Test

X20S V1.0.9.RC4  V2.1.8 and G-RX8  
with a FLVSS as single Sensor, NO "Sensor Lost" with G-RX8 internal Values and Sensor Values OK
with FLVSS, GPS all 2Sensors in chain,  "Sensor Lost" about every 10-15 sec with  G-RX8 

with X9S+SE2019  ISRM V2.1.0 and V2.1.6
with G-RX8 single   No Data from G-RX8  
with FLVSS, GPS all 2Sensors in chain,   No Data from G-RX8  

with X9E XJT  V2.1.0  and  G-RX8
with FLVSS,  GPS all 2 Sensors in chain, inernal and external Sensor Values ok, All fine! "No Sensor Lost"

with TX16S   4in1  FrSky V2 LBT  (like XJT  V2.1.0)  and G-RX8
with FLVSS,  GPS all 2 Sensors in chain, inernal and external Sensor Values ok, All fine! "No Sensor Lost"

This are all in ACCST LBT V2.1.x  
After this test:
I think FrSky has a big big Telemetry problem with the latest V2.1.x firmware ACCST LBT V2.1.x
but not with a XJT V2.1.0

**Comment by hrenz** [comment] 2021-06-12 04:32
Netzt Test with ACCESS System

X20S V1.0.9.RC4 V2.1.8 and GR8 V2.1.7
with GR8 single No "Sensor Lost" all internal Values ok
with a FLVSS as single Sensor, NO "Sensor Lost" with GR8 internal Values and Sensor Values OK
with FLVSS, GPS all 2Sensors in chain, "Sensor Lost" about every 10-15 sec with GR8
This is a problem of X20S ETHOS TD with more as a FLVSS

X9S+SE2019 ISRM V2.1.0 and V2.1.6 with GR8 V2.1.7
with GX8 single No Data from G-RX8
with FLVSS, GPS all 2Sensors in chain, No Data from GX8
What the hell is this now? X9S+SE 2019 shows No Data

X9S+SE2019 ISRM .0 and V2.1.6 with X6R V2.1.0 never reflashed 
works in a modell since years
with FLVSS and 40A Senor with X6R  YES, All works fine!

What happes?
All other RX tested on the Desk  I have flashed to latest Firmware with  X20S SPort socket direkt
is there a proble with Rx Flashing at X20S SPORT?

**Comment by hrenz** [comment] 2021-06-12 05:25
Summery
Telemetry Tests during last 2 Days
4 TX  X20S, X9D+SE 2019, X9E, TX16S
4 RX, X6R, S6R, G-X8, GR8
4 Sensors  FLVSS, GPS, Vario, Neuron60
ACCST, ACCESS,  all latest V2.1.x at TX and RX

X20S works with all 4 RX,  with internal Values, No"Sensor  Lost", all fine
X20S works with all 4 RX and a FLVSS with internal and external Values, No "Sensor Lost", all fine
X20S works not  if other Sensors or more as one Sensor in Chain, "Sensor Lost" allwys every few seconds

**Comment by hrenz** [comment] 2021-06-12 06:07
Hy,
I have LBT not FCCso have  not tested 2,1,1 für S6R

ETHOS V1.0.9.C4  TD V2.1.8
X20S with only FLVSS works stabil with Telemetry, internal and external Data stabil, No "Sensor Lost"
But other sensors or more sensors in chain you got "Sensor Lost" every few seconds

mfgH. Renz
 
 
 
-----Ursprüngliche Mitteilung-----
Von: LiNan ***@***.***>
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: hrenz ***@***.***>; Mention ***@***.***>
Verschickt: Sa, 12. Jun. 2021 3:41
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] X20S V2.1.8 Beta, X6R ACCST V2.1.0 with Neuron 60, Sensor lost every few seconds (#357)


Hy Betrand,
Today Test TX, RX, FLVSS, GPS, VARIO
TX: X20S V1.0.9.C4 TD V2.1.8
RX: X6R, S6R V2.1.0 V2.1.6 (ACCST)
Akku 5S NiMH 2000mAh
Distance Tx, RX about 1,5mTest with X20S V1.0.9.C4 TD V2.1.8
with a FLVSS as single Sensor, NO "Sensor Lost" with X6R, S6R
with a Vario as single Sensor, "Sensor Lost" about every 1min, seldom "Telemetry Lost" with X6R, S6R
with a GPS as single Sensor, "Sensor Lost" about every 10-15 sec with X6R S6R
with FLVSS, Vario, GPS all 3 Sensors in chain, X6R and S6R shows only the Rx internal Values, no external Sensors!Test with X9D+SE 2019 (ISRM S-X9 with 2.1.6, and with V2.1.0 tested) openTx V2.3.11
with FLVSS, Vario, GPS all 3 Sensors in chain, S6R and X6R, shows No Data no internal Values, no external Sensors!
with FLVSS, as singel Sensor, Test with X6R and S6R, shows No Date, no internal Values, no external Sensor
this error only occurs after I have had been flashed to the latest Tx and Rx firmware, such a mess!
and I can't get rid of this error not even by flashing back, such big mess!Test with a XJT-Modul v2.1.0 (TX16S 4in1 D16 V2 LBT) openTx V2.3.11
with FLVSS, Vario, GPS all 3 Sensors in chain, S6R and X6R, NO "Sensor Lost", all internal und external Sensor Values ok!
All fine!After this test:
I think FrSky has a big big Telemetry problem with their latest V2.1.x firmware
for Tx and for RX and with ACCST, LBT, ISRM Modul, but not with a XJT V2.1.0Have not tested with ACCESS and not ACCST with FCC
Hi hrenz,have you test the the new firmware: https://www.frsky-rc.com/s6r/

**Comment by islandflight** [comment] 2021-06-12 06:37
Someone has just posted on RC groups reporting the same telemetry loss issue with an accst SR8 receiver and x20. They tried the same with an archer access stabilizer receiver and problem resolved so it does look like this issue is related to the accst receivers and x20.

**Comment by SmartTommy** [comment] 2021-06-15 03:21
> Hy, I have LBT not FCC so have  not tested 2,1,1 für S6R ETHOS V1.0.9.C4  TD V2.1.8 X20S with only FLVSS works stabil with Telemetry, internal and external Data stabil, No "Sensor Lost" But other sensors or more sensors in chain you got "Sensor Lost" every few seconds mfg H. Renz
> […](#)
> -----Ursprüngliche Mitteilung----- Von: LiNan ***@***.***> An: FrSkyRC/ETHOS-Feedback-Community ***@***.***> Cc: hrenz ***@***.***>; Mention ***@***.***> Verschickt: Sa, 12. Jun. 2021 3:41 Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] X20S V2.1.8 Beta, X6R ACCST V2.1.0 with Neuron 60, Sensor lost every few seconds (#357) Hy Betrand, Today Test TX, RX, FLVSS, GPS, VARIO TX: X20S V1.0.9.C4 TD V2.1.8 RX: X6R, S6R V2.1.0 V2.1.6 (ACCST) Akku 5S NiMH 2000mAh Distance Tx, RX about 1,5mTest with X20S V1.0.9.C4 TD V2.1.8 with a FLVSS as single Sensor, NO "Sensor Lost" with X6R, S6R with a Vario as single Sensor, "Sensor Lost" about every 1min, seldom "Telemetry Lost" with X6R, S6R with a GPS as single Sensor, "Sensor Lost" about every 10-15 sec with X6R S6R with FLVSS, Vario, GPS all 3 Sensors in chain, X6R and S6R shows only the Rx internal Values, no external Sensors!Test with X9D+SE 2019 (ISRM S-X9 with 2.1.6, and with V2.1.0 tested) openTx V2.3.11 with FLVSS, Vario, GPS all 3 Sensors in chain, S6R and X6R, shows No Data no internal Values, no external Sensors! with FLVSS, as singel Sensor, Test with X6R and S6R, shows No Date, no internal Values, no external Sensor this error only occurs after I have had been flashed to the latest Tx and Rx firmware, such a mess! and I can't get rid of this error not even by flashing back, such big mess!Test with a XJT-Modul v2.1.0 (TX16S 4in1 D16 V2 LBT) openTx V2.3.11 with FLVSS, Vario, GPS all 3 Sensors in chain, S6R and X6R, NO "Sensor Lost", all internal und external Sensor Values ok! All fine!After this test: I think FrSky has a big big Telemetry problem with their latest V2.1.x firmware for Tx and for RX and with ACCST, LBT, ISRM Modul, but not with a XJT V2.1.0Have not tested with ACCESS and not ACCST with FCC Hi hrenz,have you test the the new firmware: https://www.frsky-rc.com/s6r/ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi hrenz,
We tested it in your way(same firmware)，and can't reproduce the problem "sensors lost", we connect the the  FLVSS, GPS,VARIO, Neuron -80, airspeed to X8R(LBT) sport, and it works well.

could you tell me the phyID of your every sensors?

**Comment by hrenz** [comment] 2021-06-27 05:24
Will test it again wiith V1.0.9 today and look at phyID

ID X6R
Empf Batt 18 F104
RSSI 18 F101

ID Neuron 60
Volt 10 0B50
Ampere 10 0B50
Temp  10 0B70
U/min 10 0B60
Verbrauch  10 0B60

ID SBEC
 10 0B50

ID Vario
Höhe 1A 0100
Steigrate 1A 110

ID FLVSS
 01 0300

ID GPS
03 800
03 820
03 800

**Comment by SmartTommy** [comment] 2021-06-28 06:53
> Will test it again wiith V1.0.9 today and look at phyID
> 
> "Sensor Lost" ever few seconds
> and sometimes "Telemetry Lost" too,
> Distance Rx Tx 1,5m
> 
> X20S V2.1.8, LBT, ETHOS V1.0.9
> X6R V2.1.0 LBT
> 
> ID X6R
> Empf Batt 18 F104
> RSSI 18 F101
> 
> ID Neuron 60
> Volt 10 0B50
> Ampere 10 0B50
> Temp 10 0B70
> U/min 10 0B60
> Verbrauch 10 0B60
> 
> ID SBEC
> 10 0B50
> 
> ID Vario
> Höhe 1A 0100
> Steigrate 1A 110
> 
> ID FLVSS
> 01 0300
> 
> ID GPS
> 03 800
> 03 820
> 03 800
> 
> Summery:
> I have 4TX with ACCST, ACCESS, TD, (X9E, X9D+Express, TX16S, X20S)
> I have 4 RX with ACCST and ACCESS (X6R, S6R, GR8, ...
> I have 4-6 Sensors, single and in row ( Vario, GPS, FLVSS, Neuron60, Current40A, ...)
> I have combined all posibilities of Tx, Rx, Sensors single and in row
> and only with X20S ETHOS I got this Sensor Lost
> Not wth X9E, TX16S, X9D+Express,
> I have tested all with LBT not FCC
> No Sensor Lost with Rx internal Sensor ( Vario, Gyro..) only
> 
> If you dont have this sensor Lost with FCC at X20 V2.1.8, and ETHOS V1.0.9
> 
> So my friend: You HAVE a big problem with X20 TD-System or with ETHOS and LBT
> Not more, not less
> 
> ![IMG_2218](https://user-images.githubusercontent.com/6217896/123534437-7ad90b00-d71d-11eb-925f-ace8eb335d94.JPG)

We connect the Sensors and Rx same as your picture shows, but can't reproduce that. could you connect the Sensor one by one? i mean connect the Vario to  the  Rx first, if no Sensor Lost then connect  the Neuron 60, if no Sensor Lost,  plug the GPS, and then FLVSS, i need to know witch one caused the failure.

**Comment by hrenz** [comment] 2021-06-30 17:38
did it with X6R and Vario
at X20 and at X9D+2019
Sensor Lost, and terrible Values with X20, but not with X9D+2019
All parts static on a table, no movement

Results include CSV, pictures, look at frsky-forum.de  at engel
https://frsky-forum.de/index.php?thread/5071-telemetry-sensor-verloren/&postID=73765#post73765
https://frsky-forum.de/index.php?thread/5071-telemetry-sensor-verloren/&postID=73766#post73766
----------------------------
![IMG_2235](https://user-images.githubusercontent.com/6217896/124006036-11395500-d9da-11eb-9fda-19ce38f9d24d.JPG)
![X20S and X6R with Vario 2021-06-29_190136](https://user-images.githubusercontent.com/6217896/124006054-15657280-d9da-11eb-90ee-3df925a019bf.jpg)
![X20S and X6R with Vario 2021-06-29_190709](https://user-images.githubusercontent.com/6217896/124006056-15fe0900-d9da-11eb-9200-d5c3e7ac38fd.jpg)

cant load *.csv here  why?

**Comment by hrenz** [comment] 2021-06-30 17:41
exact same test with X9D+2019 and X6D
No Sensor Lost, no terrible Values

![IMG_2236](https://user-images.githubusercontent.com/6217896/124006918-19de5b00-d9db-11eb-900a-e1ca494dfbcd.JPG)

cant load *.csv here why?

**Comment by hrenz** [comment] 2021-06-30 17:48
then same test from an other person, 300km away from me
he has an other X20, X6R, Vario too

Same bad result Results, X20 Sensor Lost and terrible Values
So dont tell me YOU have no errors with X20

All Data, CSV, Pictures at frsky-forum.de at engel

cant load *.csv here, why?

**Comment by Hobby4life** [comment] 2021-06-30 17:55
> cant load *.csv here, why?

Just zip it and drop it here.

**Comment by hrenz** [comment] 2021-06-30 18:02
Summery
Frsky Telemetry has Errors  with all Tx and Rx and extern sensors
sometimes more sometimes less depending on the combination
with terrible values und sensor lost 
with ACCST and ACCESS , with LBT and FCC
and these errors have been for a long time

Details  with  lots of data at frsky-forum.de
There are many RF specialists and controller developers together.
who also have the corresponding measuring devices

https://frsky-forum.de/index.php?thread/5071-telemetry-sensor-verloren/&pageNo=1

**Comment by hrenz** [comment] 2021-06-30 18:13
Next test with ETHOS V1.0.10
X20,X9E, X9D+2019Express, with ACCST, ACCESS, LBT and 4-6 Sensors
at next weekend

**Comment by hrenz** [comment] 2021-06-30 21:17
On the weekend I will test again systematically with other receivers and sensors
under the same conditions without movement on a table

**Comment by SmartTommy** [comment] 2021-07-01 03:26
> On the weekend I will test again systematically with other receivers and sensors
> under the same conditions without movement on a table

have you test the new firmware :[https://www.frsky-rc.com/tandem-x20s/](url)?

**Comment by hrenz** [comment] 2021-07-04 16:50
Test today with X20 ETHOS V1.0.10RC2
X6R and Vario
Telemetry Lost, Sensor Lost, no improvment all the same error
here are the CSV and a Picture of the CSV
I allways set SF-Switch by Hand after Sensor Lost or Telemetry lost appears.

Error is at X20, Tandem, not X9D+ Express


![2021-07-04_183028](https://user-images.githubusercontent.com/6217896/124392932-4e625780-dcf8-11eb-92e2-b07e0e3dba54.jpg)

**Comment by hrenz** [comment] 2021-07-04 16:56
same Test  with X9D+Express,  X6R and Vario
no Telemetry Lost, no Sensroe Lost, no extrem Values
Picture and CSV as Zip

![2021-07-04_183905](https://user-images.githubusercontent.com/6217896/124393188-89b15600-dcf9-11eb-8bb1-d0b2ea642576.jpg)
[X9DExpress X6R Vario-2021-07-04.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6760275/X9DExpress.X6R.Vario-2021-07-04.zip)

**Comment by hrenz** [comment] 2021-07-04 17:54
Next Test X20s ETHOS mit ACCESS G8R receiver
Here its all ok, No Sensor Lost, No telemetry lost

Result: X20 ETHOS with TD-Moudul has a great Telemetry problem with (all) ACCST Receivers
but not with ACCESS

![2021-07-04_194819](https://user-images.githubusercontent.com/6217896/124394883-a5b8f580-dd01-11eb-9170-4eaad831c1b1.jpg)
[X20S GR8 Vario 2021-07-04-19-27-35.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6760356/X20S.GR8.Vario.2021-07-04-19-27-35.zip)

**Comment by hrenz** [comment] 2021-07-04 19:09
and here Same with X9D+Express ACCESS G8R with intern Vario and extern Vario

![2021-07-04_205124](https://user-images.githubusercontent.com/6217896/124396791-06e5c680-dd0c-11eb-967c-66f6e5517d64.jpg)

[MODELL07-2021-07-05.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6760466/MODELL07-2021-07-05.zip)
