### ISSUE TITLE
Problems latest versions

### ISSUE THREAD

**Issue by JoseAltea** [FrSkyRC/ETHOS-Feedback-Community#3749] opened 2024-03-30 09:23 UTC
Hello everyone, I have the TANDEM XE and when I install version 1.5.1 I noticed that the method of configuring the mixes had changed before it was clearer when configuring them since I could change the data and see how the curve changed, now you have to change the screen, make the changes and return to the previous one to see the result making this method more tedious and complicated. It is also impossible for me to enter the sounds I had in memory to make special functions and the photos of the models, entering the files I see that if they are both on the radio and in the SD, but when I want to access them to change a photo or a sound they do not appear in the drop-down. This is normal or is that there is an error that may affect this transmitter. I would appreciate any help to be able to solve these problems. Thank you for everything and greetings

**Comment by bsongis-frsky** [comment] 2024-03-30 09:32
The curve should change directly. No need to exit the screen and go back.
Have you tried 1.5.4 to be sure the issue has not been fixed since?
Otherwise would you please attach your model and tell me how to reproduce the problem?

**Comment by JoseAltea** [comment] 2024-03-30 09:56
Thanks for your quick response, Bertrand.
 When you enter to modify the actions, it changes to another screen to modify the data but you do not see the curve to observe the changes, if you make a mistake, you have to change the screen again, before you were always on the same screen and as you changed some data you saw the evolution of changes without having to change screens.
Regards.

**Comment by bsongis-frsky** [comment] 2024-03-30 10:10
Now I understand, you would like that the channels + the curve are displayed even on child windows where you can setup the actions.

It makes sense to me, and there is space available for them. Will try to work on this next week.

**Comment by STC148** [comment] 2024-03-30 11:04
that's a good idea, the constant switching between windows is a bit annoying

**Comment by JoseAltea** [comment] 2024-03-30 11:19
Thank you very much, it's much simpler that way.
And what about the images for models and the additional sounds?
Do you know something about this?
Regards.

**Comment by Nerenye** [comment] 2024-04-05 09:18
that would be realy nice. that bugged me aswell

**Comment by bsongis-frsky** [comment] 2024-05-14 18:24
Duplicate of #4025 which has some photoshop inside. I close this one

**Closed as completed by bsongis-frsky** 2024-05-14 18:24 UTC
