### ISSUE TITLE
how to compile .luac?

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1778] opened 2022-07-04 08:53 UTC
Ethos v1.2.11 has the following feature:
[Lua] .luac files (without source) support added

just by running a widget, i do not see a .luac file being created - does this need a type of process performed?
in opentx it was generated automatically.

thanks.

**Comment by bsongis-frsky** [comment] 2022-07-04 11:16
Please check closed issues before opening new ones

**Comment by bsongis-frsky** [comment] 2022-07-04 11:16
Duplicate of #1753

**Closed by bsongis-frsky** 2022-07-04 11:16 UTC
