### ISSUE TITLE
TW protocol : no way to check if FSK (ACCESS) and LoRA are working ok

### ISSUE THREAD

**Issue by Didier-L** [FrSkyRC/ETHOS-Feedback-Community#3352] opened 2024-01-31 09:49 UTC
On Ethos 1.4.15 (X20 PRO) using TW, there is no way to check if LoRA or FSK is working. There is only a "global" RSSI and VFR.

On rx side, there are 2 leds (one per protocol) which are supposed to be ON when the protocol is ok. But on some gliders (at least) like F3B or F3F, you can't guarentee an easy reading of these leds. So, we may be completlty blinded concerning the working status of each link and fly with one failed link.
A solution could be to have at least a dedicated RSSI per protocol (LoRa and FSK).
I don't know how it is managed on TD receivers but it is the same story.

**Comment by mawzthefinn** [comment] 2024-01-31 13:50
This is a duplicate of #2897 in function.

Right now only R9 and TD report LoRA RSSI & VFR, the TW receivers send one set of values.

**Comment by Didier-L** [comment] 2024-01-31 15:16
Thank you for your fast answer.
Is there a way to push Frsky to move forward faster on this topic as it is a important safety issue ?

I will not fly my models using TW as long as this "bug" is not solved => quite frustating ! I bought the X20 PRO mainly for TW...
And new Kavan radio has the same concern.

**Comment by bsongis-frsky** [comment] 2024-01-31 15:23
I am not sure it's a bug. It seems it's the way it has been designed. Closing in favour of #2897, please continue the discussion there

**Closed by bsongis-frsky** 2024-01-31 15:23 UTC
Labels: duplicate, RF issue
