### ISSUE TITLE
[LUA] SystemTool without ETHOS top bar

### ISSUE THREAD

**Issue by JimB40** [FrSkyRC/ETHOS-Feedback-Community#3479] opened 2024-02-21 18:48 UTC
Please add to system.registerSystemTool interface parameter:
` topbar (boolean, optional): Ethos topbar forced ON / OFF`

Example
```
local function init()
  system.registerSystemTool( {name=name, icon=icon, wakeup=wakeup, event=event, paint=paint, topbar=false })
end
```
will hide ETHOS system topbar placing LUA window at 0,0 on LCD
![ETX_topbar](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/46420768/6e61737d-97ec-4d3c-88d3-9011b985f293)

it will give same on screen result as in case of widget with title = false
```
local function init()
    system.registerWidget( {key="lua1", name=name, create=create, paint=paint, title=false } )
end
```

**Comment by bsongis-frsky** [comment] 2024-02-22 10:57
Duplicate of #3478

**Closed by bsongis-frsky** 2024-02-22 10:57 UTC
