### ISSUE TITLE
in Ethos 2.4.4 with external ELRS Vario cannot be activated

### ISSUE THREAD

**Issue by glipski50** [FrSkyRC/ETHOS-Feedback-Community#2155] opened 2022-12-03 17:33 UTC
Referres also to issue #2006
In Ethos 2.4.4 the vario signal of an external ELRS module  is transferred correctly and can be edited in the telemetry page. But the Vario tone cannot be activated.
The section **Play Vario** as marked in the screenshot of an Access-vario below is missing.

![screenshot-2022-12-03-65983](https://user-images.githubusercontent.com/116186946/205453776-20156c73-fe26-44f0-9896-f549b37fafda.jpg)

**Comment by mawzthefinn** [comment] 2022-12-03 19:57
This is a duplicate of #2006, you are showing the functionality that the reporter for that issue is complaining about lacking.

Closing this one as a duplicate, please continue discussion in #2006

**Closed by mawzthefinn** 2022-12-03 19:57 UTC
Labels: duplicate
