### ISSUE TITLE
Request VAR Ranges as other Sources including other VARs

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3312] opened 2024-01-22 18:00 UTC
Would it be possible to have VAR Ranges set from other sources, e.g. other VARs please?

Thanks

**Comment by bsongis-frsky** [comment] 2024-01-23 08:34
`Range<int32_t> range = {-1000, +1000};`

It was so nice :(

**Comment by mawzthefinn** [comment] 2024-01-23 21:22
Duplicate of #3229

**Closed** 2024-01-23 21:29 UTC
Labels: duplicate, enhancement
