### ISSUE TITLE
Some bugs ?? X20 (last FW and LUA)

### ISSUE THREAD

**Issue by Mobidick1966** [FrSkyRC/ETHOS-Feedback-Community#1263] opened 2021-12-28 11:23 UTC
Hello.
I just made the last update (lua and FW) on the X20.
For the first time, I had to make the settings as for the first time (languages ​​and stick mode), and also I have to reprogram different models which no longer appear in the models menus, they are still on the card SD, but since the name of the model is not displayed (just "model 1 .... model 26 ....) it is difficult to find the right model to reinstall.

Question: how to reinstall a model from the SD card to the models menu?

**Comment by bsongis-frsky** [comment] 2021-12-28 11:26
Duplicate of #1254

**Comment by bsongis-frsky** [comment] 2021-12-28 11:27
Please use RCG for this kind of question, thanks

**Closed by bsongis-frsky** 2021-12-28 11:26 UTC
