### ISSUE TITLE
Shutdown while receiver is still on

### ISSUE THREAD

**Issue by Hobby4life** [FrSkyRC/ETHOS-Feedback-Community#413] opened 2021-06-07 09:02 UTC
X20S fw 1.07, TD-ISRM v2,18

When turning off the radio while receiver is on gives the message that the receiver is still on.. but does shutdown.
Is there any way to prevent the radio shutting down like in OTX?
I did not found any setting for this.

**Comment by jreis1** [comment] 2021-06-07 16:36
This has been updated in the 1.0.8 supposedly, if not should be implemented in the near future.

**Comment by Hobby4life** [comment] 2021-06-07 16:46
not fixed in v1.08

**Comment by bsongis-frsky** [comment] 2021-06-07 18:17
Duplicate of #250

**Closed by bsongis-frsky** 2021-06-07 18:17 UTC
