### ISSUE TITLE
[BUG] Mixer logic order wrong

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#2594] opened 2023-04-21 19:51 UTC
The logic order in the mixers is wrong. A curve is applied on the input, not the output. If you use a switch as an input this curve will never be used because the switch action is instant. If you add a slow up and down the mixer output is slowed for the switch but the curve is never used, and i need that to work. And i cannot add a curve on the output because i have multiple curves for a single output channel using different switch inputs and mixers. In OpenTX the curve is applied on the output of the mixer after the slow and this makes more sense.

**Comment by RealTadango** [comment] 2023-04-21 19:52
I think it should be: Input -> Slow -> Curve -> Weight

**Comment by mawzthefinn** [comment] 2023-04-21 20:27
This is a duplicate of your issue #2460 

The issue is the same in both cases, slow applied after weight in the flow. 

Your issue has noting to do with curves, but with slow. You want it applied on the input, not the output.

**Closed by mawzthefinn** 2023-04-21 20:27 UTC
Labels: duplicate

**Comment by RealTadango** [comment] 2023-04-21 20:36
Please reopen because this current order makes no sense

**Comment by mawzthefinn** [comment] 2023-04-21 20:38
Switches don't transition values in ETHOS, the issue there has nothing to do with curves, but with switch/value behaviour, which switch instantaneously between values. 

You don't get a transition until you proxy through a mix (because the mix always behaves as a transition)

You can test this by comparing the behaviour with the switch directly assigned and proxied through a completely stock Free Mix.

**Comment by RealTadango** [comment] 2023-04-21 20:39
OpenTX order makes so much more sense......... That works perfectly. Ethos order is very limited. Different order makes more sense and solves everything.

**Comment by mawzthefinn** [comment] 2023-04-21 20:41
Except it has NOTHING to do with mixer logic order, but the treatment of switches when they transition between values. Change that to behave as a transition instead of a jump, and the curves will behave as you expect.

Also a duplicate, of the stale #1533

**Comment by mawzthefinn** [comment] 2023-04-21 20:46
NB: I've re-opened #1533 as it's no longer stale.

**Comment by RealTadango** [comment] 2023-04-25 08:24
@bsongis please take a look at this. This is NOT a duplicate. @mawzthefinn simply does not understand what i mean.

**Comment by mawzthefinn** [comment] 2023-04-25 12:23
It is a duplicate. In fact it is two different duplicates. 

You have described 2 issues.

1. Slow does not apply at the expected speed, because it's applied after Weights and the speed is calculated from -100 to 100. That is the issue you already reported in #2460 stated in a different fashion.

2. When using a switch as the source, and using a curve that has a V shape (or other shape), no point in the curve between the nominal switch positions is ever reached by the output. This is exactly what is described in #1533 and is why I re-opened that one and labelled this a duplicate. 

In the first case this is an mixer order issue (if slow was processed before curves/weights, it would work exactly as expected.

The second is not. I tested this extensively when #1533 was reported. 

The issue is the input jumps to the next switch point if you use a switch as an input, it does not transition, so the mixer doesn't process the curve between the switch values, just the points that correspond to switch inputs. This is a different behaviour than OpenTX, but not for the reason you propose (this is easily testable using the test I describe, Mixer outputs are processed as if there is a transition, switch positions are not). If the issue was what you propose, stacking mixers that have switch inputs would behave the same way when used as inputs for the curved mix as when a bare switch Is used as the input.

**Comment by bsongis-frsky** [comment] 2024-01-24 12:31
1.5.0 adresses this problem!
