### ISSUE TITLE
Subtrim 

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#1594] opened 2022-04-09 19:19 UTC
Hello,

my Problem is that when i take suptrim for example from 0 to 11% the end positions of the servo are the same as bevor.
My wish is that when i chance the suptrim position that the end positions of the servo chance automatly too.

**Comment by mawzthefinn** [comment] 2022-04-10 20:24
Subtrim is trim and only affects center. This is correct as currently implemented because it assumes your endpoints are set to prevent mechanical binding. If subtrim is altered as you request it will become impossible to ensure that you do not get mechanical binding.

What you are looking for is PPM Center adjustment, which shifts the entire range a given amount. That has been requested in the past and would be useful for adjusting for differing PPM centers (1520uS and 1500uS most notably)

**Comment by bsongis-frsky** [comment] 2022-04-22 10:28
Duplicate of #1264 if I understand it right

**Closed by bsongis-frsky** 2022-04-22 10:28 UTC
