### ISSUE TITLE
V1.50 Input field not optimal  improvement Steps

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3080] opened 2023-11-23 06:31 UTC
the Input field for numbers / ratio is not optimal

open a numerical input field direct
or select first in fix steps so setting is much faster, 
and then you can inc dec with mouse wheel as you need it

Min  0 1  2  5 10 25 50 100  Max
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/e0437db4-11b1-475f-a00f-376185360d47)

or open it as a Num Field

![2024-01-19_152007](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/5dd719e1-11fa-48f2-a391-5a96f73c8a65)

**Comment by bsongis-frsky** [comment] 2024-05-25 22:00
Duplicate of #3908

**Closed by bsongis-frsky** 2024-05-25 22:00 UTC
