### ISSUE TITLE
Feature request: Adding keyboard UI

### ISSUE THREAD

**Issue by wmayvis** [FrSkyRC/ETHOS-Feedback-Community#354] opened 2021-05-28 06:48 UTC
Is it possible to add a keyboard to the UI, so that the names of the models, functions etc. can be easily insert?

**Comment by Hobby4life** [comment] 2021-05-28 06:56
And number pad, like entering values into Logic functions is taking ages with scroll wheel.

**Comment by bsongis-frsky** [comment] 2021-05-28 13:02
Duplicate of #189

**Closed by bsongis-frsky** 2021-05-28 13:02 UTC

**Comment by hrenz** [comment] 2021-06-02 10:25
And please not ABCDEFG keyborad
take QWERTZ or QWERTY form
