### ISSUE TITLE
Delays to flight modes

### ISSUE THREAD

**Issue by FBarrao** [FrSkyRC/ETHOS-Feedback-Community#761] opened 2021-08-07 11:11 UTC
It should be ineresting to have delays for changing the flight modes, when using independent trims for diferent flap setings, things are much more smooth using a delay to position the nwe trims.

**Comment by FBarrao** [comment] 2021-08-07 11:20
Sorry, I don´t meant a delay, but a slow down, so, there is a transition between one flight mode and another..

**Comment by hrenz** [comment] 2021-08-07 15:18
not now, will and must come

**Comment by bsongis-frsky** [comment] 2021-08-09 17:46
Duplicate of #768

**Closed by bsongis-frsky** 2021-08-09 17:46 UTC
