### ISSUE TITLE
Implementing a servo balancer in Ethos

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#1115] opened 2021-10-24 17:42 UTC
Hello

Would it be possible to implement a servo balancer in Ethos? Kind of like Jeti or Spektrum. For example, if you have 2 servos for a hinge surface this would make servo adjustment a lot easier.

Thank you and best regards

Enzo

**Comment by mawzthefinn** [comment] 2022-11-24 00:43
This is a duplicate of #38, closing in favour of that Issue

**Closed by mawzthefinn** 2022-11-24 00:43 UTC
Labels: enhancement
