### ISSUE TITLE
Frsky x20s no longer starts

### ISSUE THREAD

**Issue by ich-wer-sonst** [FrSkyRC/ETHOS-Feedback-Community#2692] opened 2023-06-17 07:03 UTC
Hello, you have my X20s with ETHOS Suite installed a new firmware
since then it no longer starts, not even the bootloader
Does anyone have a tip on how to get it running again?

**Comment by strgaltdel** [comment] 2023-06-18 10:48
it seems the case was solved in Andreas Engels' forum by reflashing bootloader via companion an letting the suite do the rest of the update process.

this shows a lack a functionality  in the suite:
you're not able to perform a "manual" bootloader flash like using companion in case the tx bootloader is inconsistent

maybe it would be a good idea to add this

**Comment by Nicholas-Luoyi** [comment] 2023-06-19 01:42
- Download the bootloader for X20S in Release 1.4.3 and flash it via Suite DFU tool.
- Enter bootloader and use Suite to flash the firmware.

**Comment by strgaltdel** [comment] 2023-06-19 09:43
Hi Nicholas,
thanks for the hint.

The user was reporting that this procedure didn't work for whatever reason.
strangely he was able to flash the bootloader by using companion with a little support.
so i assumed dfu driver was existent and  i'd the feeling suite is something "missing"

i can't examine remotely what caused this behaviour, 
frsky states that the user has to check if the dfu driver (within suite's help a typo "dfu drive") is installed correctly.
.. a little bit a "rough" description.

Frsky docs  
https://www.frsky-rc.com/wp-content/uploads/Downloads/Amanual/Preparing-your-ETHOS-radio-to-use-ETHOS-Suite-to-upgrade-X20-X20S-radios.pdf
are referencing (step 3.2) to this thread, which didn't help a average user i think
https://intofpv.com/t-resetting?pid=130476#pid130476


another interpretion could be "install dfu util"
https://github.com/redbear/Duo/blob/master/docs/dfu-util_installation_guide.md

or "install stm driver" for dfu communication...

**Comment by Nicholas-Luoyi** [comment] 2023-06-20 00:07
Then is it able to install a new firmware with the bootloader flashed by Companion now?

**Comment by strgaltdel** [comment] 2023-06-20 06:04
Yes,
Situation:
- his X20 was "bricked" (something went wrong during update)
- Tx even didn't start / power on in bootloader mode
- suite / dfu tool didn't recognize tx, so no "bootloader reflash" within suite

Solution:
we guided him 
- to download bootloader file from git
- flash this file via companion (he has to ignore the "wrong file" message)
- after bootloader flash succeeded, he could update Ethos via suite

it was a while ago that updated bootloader via companion by myself,
but i think it's calling dfu-util.exe and one can see its command parameters in an info window.

**Comment by bsongis-frsky** [comment] 2023-06-20 06:35
> Will the suite process really work even in case there is a corrupted bootloader on the Tx ?

Yes. Only the ST Bootloader is needed to flash Ethos Bootloader. And ST Bootloader is in ROM.

Both Companion and Ethos Suite launch dfu-util to flash the bootloader, so they should work the same!

**Comment by strgaltdel** [comment] 2023-06-20 06:55
strange,
The user said that the Ethos Suite dfu tool could not connect to the transmitter.

From a distance it is difficult to find the cause.

I will advise the user again to close the issue.

**Closed** 2023-06-20 07:42 UTC
