### ISSUE TITLE
1.5 Var Actions seem ineffective

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2770] opened 2023-07-22 15:35 UTC
I recognise this may still be in development, but in case not (and bearing in mind I'm making assumptions about how this will work in the absence of documentation)

Create a new VAR, accept all the defaults aside changing Value to 10%
Now create an Action e.g. Always on, Add 2.0 
I'm assuming this should result in a Var value of 12%? This doesn't appear to happen.
Similarly with Multiply set to 50, I'm assuming that should result in 50% of 10%, i.e. 5%? This doesn't happen. 

The Action values (e.g. 2.0 or 50.0 above), don't appear to have any unit, if they are meant to be % it would be worth adding that to make it clearer what is meant to happen.

Thanks

**Comment by bsongis-frsky** [comment] 2023-07-24 08:22
Duplicate of #2761

**Comment by bsongis-frsky** [comment] 2023-07-24 08:23
Action Values are not

**Comment by bsongis-frsky** [comment] 2023-07-24 08:28
I think that the current state is better, for example you want to add an offset of 0.2V on something, if I change it to % it will dependent on the value, which is not good!

The unit is the same than the Var itself

**Closed by bsongis-frsky** 2023-07-24 08:28 UTC

**Comment by Jedsters** [comment] 2023-07-24 09:09
This is possibly confusing. I agree that for add and subtract using the same units makes sense. However for dividing and multiplying it doesn't, e.g. if I divide 6V by 3V I'd end up with just 3 rather than 3V.  Or multiply I'd end up with 18Vsquared. 

But I was also finding that trying to add or divide a VAR which is a percentage didn't result in any change to the output, it seemed ineffective. Has this been fixed? 
Thanks

**Comment by Jedsters** [comment] 2023-07-24 09:27
Maybe add and subtract should be done in original units, but instead of multiply and divide there should be a 'percentage' option? i.e. 50 percent would halve and 200 would double etc.?
