### ISSUE TITLE
Unable choose and play files in lower position of folders X20, 1.5.X

### ISSUE THREAD

**Issue by kvak1** [FrSkyRC/ETHOS-Feedback-Community#3624] opened 2024-03-11 09:24 UTC
If I want to choose and play or read files in audio folder or log folder (folders with higher number of files) cursor skip to upper position of files list. First I noticed on 1.5.0 firmare. Karel

**Comment by Wolepo** [comment] 2024-03-11 13:19
I cannot confirm this, the cursor remains at the marked position and I can also play the marked sound file again.
X10S Express / 1.5.2.

**Comment by kvak1** [comment] 2024-03-11 13:44
And if you are at the bottom of the list of files too? Folder has to have many files for example audio folder... I have X20 1.5.2.. thank you

**Comment by Wolepo** [comment] 2024-03-11 14:55
No matter what you mark, whether at the beginning, at the end or in the middle, the cursor remains there after the file has been played

**Comment by kvak1** [comment] 2024-03-11 15:02
So it could be problem of X20 or particulary of my radio... thanks

**Comment by pstasek** [comment] 2024-03-11 16:00
Duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3570

Confirmed on XE within Logs folder with over 500 files. Maybe it can be related to cs localization?

**Comment by kvak1** [comment] 2024-03-11 16:11
Maybe. I have cz localization...

**Comment by pmullen503** [comment] 2024-03-12 00:16
I've experienced this when trying to play a sound file from the file manager. Once I deleted the unused files (which is why I was playing sound files from the file manager) the problem stopped. I never had a problem selecting from a long list of sound files in an SF. It seemed to be an issue in file manager only.

**Comment by kvak1** [comment] 2024-03-12 08:49
I'll try it. Thank you.

**Comment by bsongis-frsky** [comment] 2024-03-12 09:10
Fix ready for 1.5.3

**Closed as completed by bsongis-frsky** 2024-03-12 09:10 UTC
