### ISSUE TITLE
Trainer settings with flaps with 3pos switch as source

### ISSUE THREAD

**Issue by Ze-baloo** [FrSkyRC/ETHOS-Feedback-Community#2281] opened 2023-01-03 18:18 UTC
Hi,

I'm on a X18 firmware 1.4.5 EU
The slave TX is a X9D+ se 2019
I'm using Para Bluetooth connection. 

I think, there is an option missing as you can only affect a trainer Chanel to an analog source or an output channel.

On a plane having two servos on two different channels for the flaps, and the mixer flaps having a three position as a source, I can't affect one trainer Chanel to the three position switch or to the mixer.

I can only affect this trainer channel two an analog input or a channel output.

As a result only one flap is working on trainer

If you need some photos or videos to explain.
Please ask, I'll try my best to upload from my phone.

Laurent

**Comment by Ze-baloo** [comment] 2023-01-03 18:48
Update
Same issue with a wire connection and a x9d+se non 2019.

**Comment by mawzthefinn** [comment] 2023-01-03 19:17
This is normal behaviour. Trainer sends channel data, not switch/stick data, if you want to directly target multiple channels, the mix must be on the student radio. 

The solution is to use a channel as a source conditioner, then you need to create a Free Mix with the switch as a source and a free output channel that the Trainer can address (up to ch8 for wired, but up to ch16 for Wireless). Then use that channel as the Source for your flaps mix, and target the same channel with the Trainer system.

**Comment by Ze-baloo** [comment] 2023-01-03 20:39
OK, thanks for the solution, I will work on it. 

But what I regret for Ethos is that it's as complicated as on opentx to control more than 4 channels with the trainer TX.

A trainer channel should be able to control a simple flap mix.

In my mind this should be simplified for lambda users.

Laurent

**Comment by Ze-baloo** [comment] 2023-01-03 20:53
I'v found an easyest.
Creating a second flap mix with trainer 5 channel as source instead of the SC switch.

Replace the always condition in both mixes by the trainer on or trainer off switch (SC in most situations).

It works fine.

**Comment by mawzthefinn** [comment] 2023-01-03 20:58
I will note 2 things.

1. This exact same issue exists on all radios. You will have the same problem on Spektrum. The issue is inherent to how Trainer works on pretty much every system (it sends channels, not switches/sticks). It's relatively easy for dev's to address this with sticks, as there are only 4 axis and they are easy to know what is what, but for expanded controls it isn't really practical do do directly.

2. The fix is much simpler on ETHOS than on OpenTX, because you would need to create multiple mixers on OpenTX to do a simple input re-assignment targetting 2 channels. ETHOS has multiple solutions here, but all only require a single mix per function. 

I consider the VAR mix the simplest solution because it doesn't require duplication of flap mix settings if using slows or such, it simply selects the active input. If you aren't doing anything fancy in Flaps, then a second flaps mixer does work well.

**Comment by mawzthefinn** [comment] 2023-01-03 20:59
Closing off now as you have a working solution.

**Closed by mawzthefinn** 2023-01-03 20:59 UTC

**Comment by Ze-baloo** [comment] 2023-01-03 21:05
Thanks, I need a bit more reflexion to really understand and apply your var solution...

But, there is a big chance that my son will be autonomous for flying before I understand the var mix solution 😂

**Comment by Ze-baloo** [comment] 2023-01-03 21:09
I agree that it's much easyer on etho 😉

**Comment by Ze-baloo** [comment] 2023-01-03 21:38
@mawzthefinn

Last question related to trainer mode.

Do you think one day could be implemented a trainer feature like the one described here by lapinfou (we are in the same club 😉).
https://opentx-doc.fr/wiki/ecolage-sans-maintenir-le-bouton-appuye

It allows to activate the trainer with a sticky SH switch a catch back the control by touching any gimbal in any way. 

This a very comfortable feature, and if it seems possible to implement as an option in the trainer mode, I think it could be a great plus for Ethos. 

Thanks again for the help. 

Laurent

**Comment by mawzthefinn** [comment] 2023-01-03 21:41
That exact logic should work fine in ETHOS, same as in OpenTX

It would be a nice improvement to have something similar baked in to the trainer function (Spektrum has done so)

**Comment by Ze-baloo** [comment] 2023-01-03 21:49
> 

I agree totally for the improvement.

Add the fact that it's a little tricky to program on opentx, it could please many users 😁

**Comment by bsongis-frsky** [comment] 2023-01-04 07:14
Then you open a new issue, and describe the conditions for Trainer ON / OFF so that it will please all those users?
;)

**Comment by Ze-baloo** [comment] 2023-01-04 07:22
> 

I'll do it from my laptop when back home this evening ;-)

Ps : I miss the possibility to have a custom start screen like on my X9d.
Is definitely impossible or could it be implemented in the future?

**Comment by Ze-baloo** [comment] 2023-01-04 17:46
@bsongis-frsky

Do you need a brief description of the way it works or a complete translation of the detailed programmation on opentx explained by lapinfou on his website?
