### ISSUE TITLE
Instant Trim Feature Required 

### ISSUE THREAD

**Issue by FLYN-001** [FrSkyRC/ETHOS-Feedback-Community#1031] opened 2021-10-03 09:21 UTC
Trying to find & manually clicking trims buttons while fighting an unruly possibly expensive model on a maiden flight is not fun. 
Please please please can we have an instant trim function selectable via a momentary switch that will instantly set trims (not throttle) to currently held stick positions. 

This is by far the BEST way to trim an aircraft!
ETHOS NEEDS THIS FUNCTION 😊

**Comment by MrD-RC** [comment] 2021-10-03 09:47
Duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/295

**Closed** 2021-10-03 11:27 UTC
