### ISSUE TITLE
Enhancement Auto Download of Rx firmware

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2425] opened 2023-02-18 16:48 UTC
I don't know how much of this is possible / could be automated.

In an ideal world I'd like to think that Ethos knows what type of Rx is in each model (otherwise it would have to be user entry from a list).

Given that ethos can be told which rx you have, I'd like to think that this information can be passed to the suite so that the suite can then check for updated versions of rx firmware and automatically download them onto the tx so that when you are ready to update rx firmware the latest version is ready and waiting for you without having to manually find it and download it from the frsky website.

Thanks

**Comment by mawzthefinn** [comment] 2023-02-19 15:54
Good idea, but a duplicate of #1568 :-)

Closing as a duplicate for that reason.

**Closed by mawzthefinn** 2023-02-19 15:54 UTC
Labels: duplicate
