### ISSUE TITLE
model on Twin Xlite gets corruptred in 1.5.12 after reboot

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#4369] opened 2024-08-12 06:45 UTC
Ethos suite update from 1.5.8 to1.5.9
Twin Xlite  afte update from 1.5.11 to 1.5.12 ( worked ok Yesterday on 1.5.11)
![problemtwinxlite](https://github.com/user-attachments/assets/e5f9e008-7244-4bfc-866d-886fbbabaf81)

When I start the transmitter, "Welcome to Ethos" is not fluently pronounced it stutters. The radio is set to select the model first. I cannot see which model is selected ( checkbox) in the first section. 
I can see all the models initially and can choose one. The radio starts up and opens the model. Everything seems to be working. I can change models as long as the transmitter stays on.

Once the radio is closed and restarted, I get the  "Invalid data" message. When trying to open the (last) selected model
Every model had a .png image
Model.bin are still on the radio

**Comment by 00steven** [comment] 2024-08-12 06:50
The problem seems to be gone when "select model" on startup is not selected.

**Comment by filduch** [comment] 2024-08-12 07:38
Yes, that't true. I wonder that this has not been solved since the problem has be discover.

**Comment by jasalca** [comment] 2024-08-12 09:06
This bug was opened a few days ago with that same problem of "invalid data" on the X20 radios, but I see that it is general in all radio´s models. Let's hope they solve it soon!!!
What I don't understand is how they have released this version 1.5.12 knowing about this serious problem!!

**Comment by 00steven** [comment] 2024-08-12 13:11
There should be a warning on the download,.. it is an easy fix to save the models. I I checked the forum but could not find any real problems.  Next Time I will check fixed issues to

**Comment by mawzthefinn** [comment] 2024-08-12 13:27
Duplicate of #4351 please continue the conversation there

**Closed as not planned by mawzthefinn** 2024-08-12 13:27 UTC
Labels: duplicate
