### ISSUE TITLE
Xact Servo endpoint and Matching feature 

### ISSUE THREAD

**Issue by TalperRC** [FrSkyRC/ETHOS-Feedback-Community#1842] opened 2022-08-08 06:12 UTC
Background: 
The Xact Servos with telemetry can be very helpful when performing servo endpoint calibration and or Servo Matching 
because you can see the current when the servo reaches the end point. 
however when you are the output screen for endpoint calibration you can not see the Servo telemetry data. 

Feature request: 
in the output parameters screen allow an option to display telemetry data (servo current)

**Comment by mawzthefinn** [comment] 2022-11-24 14:58
Duplicate of #1617

**Closed by mawzthefinn** 2022-11-24 14:58 UTC
