### ISSUE TITLE
AT RX setup the Engine turn on. 

### ISSUE THREAD

**Issue by AlwinHaas** [FrSkyRC/ETHOS-Feedback-Community#998] opened 2021-09-25 10:57 UTC
I have bind my plane, then I put the RX Setup to Digital Servo an 25mW Telemetrie at both times the engine run on. This is a big problem that is not ok. People can hurt their self with this problem, an the plane can broke too.

I'm really unhappy about this problem.
The second point is that it don't go forward with the update's.

**Comment by loetefix** [comment] 2021-09-25 10:59
Did you set the failsafe before?

**Comment by Nicholas-Luoyi** [comment] 2021-09-26 06:54
Do you have a log file?

**Comment by AlwinHaas** [comment] 2021-09-27 05:51
Hello I have 10.11.3 and no I don't have a log.
All the fail safe are at - 10% but I turn it to - 100%.
That is not ok, this is a big problem...

**Comment by loetefix** [comment] 2021-09-27 08:18
I think the problem is, that the RX goes into failsafe while updateing or make settings. So i think it is not an ethos problem.did the failsafe settings change "automatically" after update / change settings?

**Comment by AlwinHaas** [comment] 2021-09-27 16:12
Hello, yes after the update was the failsafe at - 10% bevor I do the update the Failsafe was at - 100%.

**Comment by loetefix** [comment] 2021-09-27 16:17
This is no good,thats true

**Comment by Hobby4life** [comment] 2021-09-27 16:24
When OTA flashing the receiver should output NO signal at all. PWM/SBUS off

**Comment by loetefix** [comment] 2021-09-27 16:32
Also while change settings of the RX

**Comment by STC148** [comment] 2021-09-27 21:59
> All the fail safe are at - 10% but I turn it to - 100%.
> That is not ok, this is a big problem...

this problem was fixed with 1.0.11 RC4

**Closed** 2022-01-13 14:21 UTC
