### ISSUE TITLE
Sequenzer

### ISSUE THREAD

**Issue by frutsch** [FrSkyRC/ETHOS-Feedback-Community#4575] opened 2024-09-27 12:58 UTC
Please ad a Sequenzer Like Jeti or Powerbox. IT's a Feature Missing in Ethos which makes Gear and Door sequenzing realy easy
Thanks
Chris

**Comment by bsongis-frsky** [comment] 2024-09-27 13:19
Duplicate of #657 which is already in my tasks list. 
1.5.16 already has the Balance curves implemented
Sequencer will be another step.

**Closed as completed by bsongis-frsky** 2024-09-27 13:19 UTC

**Comment by Kreisflieger** [comment] 2024-09-28 19:18
Thanks, this sounds promising, I will wait patiently for this enhancement.

**Comment by xiaoyigg** [comment] 2025-10-23 16:23
> Duplicate of [#657](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/657) which is already in my tasks list. 1.5.16 already has the Balance curves implemented Sequencer will be another step.

It's been so long, why hasn't this feature been implemented yet? It's very important
