### ISSUE TITLE
Were are the custom / mixer scripts? 

### ISSUE THREAD

**Issue by RealTadango** [FrSkyRC/ETHOS-Feedback-Community#2476] opened 2023-03-06 17:39 UTC
In OpenTX there are custom / mixer scripts that i often use. They are missing in ETHOS. This is really an issue for me because i use them to automate tasks like launch control for hand launched models and custom warnings scrtips like stall warnings. Please add this into ETHOS, it should not be that hard since it was great in OpenTX already.

**Comment by bsongis-frsky** [comment] 2023-03-06 19:15
I don't know exactly what you need from Mixer Scripts, but there are already Lua Sources in Ethos 1.4.X and Lua Tasks have been introduced in 1.5.0 nightlies

**Comment by RealTadango** [comment] 2023-03-06 19:17
I need a configurable script that generates outputs, just like custom scripts do in OpenTX. This needs to be configurable per model.

**Comment by bsongis-frsky** [comment] 2023-03-06 19:20
What are the settings you need? There is already a PR for that

**Comment by bsongis-frsky** [comment] 2023-03-06 19:21
Duplicate of #2338

**Closed by bsongis-frsky** 2023-03-06 19:21 UTC
