### ISSUE TITLE
Spectrum Analyzer

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3289] opened 2024-01-16 21:47 UTC
It would be very nice to have a Spectrum Analyzer like in openTX if possible.  
Thank you very much

![276A3AEE-F2A7-4736-B8EA-C4C85EEF8D3A](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/156850523/4ffb49cd-bd2f-4630-84e1-b8f921a854fc)

**Comment by bsongis-frsky** [comment] 2024-01-16 21:50
Duplicate of #3288

**Closed by bsongis-frsky** 2024-01-16 21:50 UTC
