### ISSUE TITLE
End points x20s ethos 1.0.10

### ISSUE THREAD

**Issue by FredAlemaoFPV** [FrSkyRC/ETHOS-Feedback-Community#726] opened 2021-08-01 00:17 UTC
The end point values ​​could be fine-tuned, just like in the sub trim!  with one decimal place, when configuring the radio in the vbar software, it is not possible to set the end of course in the app with a value of 100, the value of 1 on the radio goes from 99 to 101..

**Comment by bsongis-frsky** [comment] 2021-08-02 12:41
Duplicate of #655

**Closed by bsongis-frsky** 2021-08-02 12:41 UTC
