### ISSUE TITLE
Ethos Suite RC3 Restore function is not working

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#3443] opened 2024-02-15 20:56 UTC
<img width="890" alt="Screenshot 2024-02-15 215047" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/805081b1-a072-44cf-a380-e0157e2e589c">
<img width="889" alt="Screenshot 2024-02-15 215056" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/20675e74-75e3-474b-bf77-262e8a5631cd">
<img width="891" alt="Screenshot 2024-02-15 215108" src="https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/15903471/3c4fcd55-6b3d-4d93-89c7-13a2a7f15b74">

Everything seem working, but as you start restore, nothing happens, no restore files are writed back to radio
I've tested even in bootloader mode, same problem

**Comment by spoke2570** [comment] 2024-02-15 23:19
Duplicate of #3361

**Closed** 2024-02-18 00:54 UTC
Labels: bug, suite
