### ISSUE TITLE
Request: curve following the stick position when is assigned to a servo

### ISSUE THREAD

**Issue by Asimos32** [FrSkyRC/ETHOS-Feedback-Community#454] opened 2021-06-10 07:26 UTC

**Comment by Asimos32** [comment] 2021-06-10 07:36
the best way to do "servo balancing" (2 or more servos on the same surface) is to assigned a curve for each different servo in order to much them as good as possible.
when i create a curve and after i assigning to servo (witch belongs to a channel) i would like to see the stick movement on the curve  display.

**Comment by Joetrin** [comment] 2021-06-10 14:59
Hi Asimo,

For balancing 2 servos on a large surface 90% of the time you can just use the 3 position method.
1st is very important to make sure that the starting geometry is correct, as both servos need to mirror each other.  If geometry is wrong, it will be difficult and you'll need a curve.

2) start at the center, and make sure both are equal, use the center position on outputs to do this.  (Establish which servo will be your master servo, I personally use the inboard aileron servo as my master, outboard as the slave)

3) Assign the output to a rotating knob (it's easier), then do with the outer servo rod disconnected, turn the knob fully to one direction.  The surface should move too.  Adjust the endpoint on the slave to match the enpoint location on the master, your pushrod should be aligned to the control horn and not have any pressure and is able to float.

4) Repeat the same process at above for the other end point.

5) To check if you need a curve or not, slowly rotate the knob 1/8 of the travel from the end, and see if your slave pushrod can be put into the control horn with no pressure.  Continue in 1/8 incriments to test this.

What you'll find is, if you're using the same brand and servo model for the surface, 99% of the time you will not need  a curve.

But yes, to see the servo stick travel on the curve will be good to see.

**Comment by mawzthefinn** [comment] 2022-11-15 01:47
This is a duplicate of #24, please continue any discussion on that issue.

**Comment by mawzthefinn** [comment] 2022-11-20 21:54
Closing as a duplicate

**Closed by mawzthefinn** 2022-11-20 21:54 UTC
