### ISSUE TITLE
VAR-Mix reset to value zero after restart

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#1538] opened 2022-03-21 17:00 UTC
![VAR-mix-1](https://user-images.githubusercontent.com/78207054/159317815-cdcb2aa7-4de6-4836-925b-4632395030f1.JPG)
![VAR-mix-2](https://user-images.githubusercontent.com/78207054/159318015-0d8f669f-7685-48d6-b21c-3809d96c2093.JPG)
I don't know if you want the values to reset to zero with every restart.
I have a var-mix which has a weight set by a chanal and source which is not always active. After restart X20S with 1.1.0 the value is set to zero.

**Comment by mawzthefinn** [comment] 2022-03-26 15:20
If your ‘Sound Mix’ is not active on start, then this is exactly the expected behaviour.

VAR mixes don’t behave like GVAR’s and if you are live adjusting, they re-initialize to the default setting on start unless they are immediately  updated

**Comment by Cipta-de** [comment] 2022-03-26 17:26
Thanks for explanation - so it seems we have to wait for GVAR orsomething similar. It could also be selectable if tha last value will be saved till new value ist set. Another function type for example. 

greetings

**Comment by mawzthefinn** [comment] 2022-03-26 21:53
A 'persistance' option would be an excellent addition for the Var mix. But yes, as it stands you need GVAR functionality.

To my understanding, GVAR's are a milestone for 1.2 at this time.

**Comment by mawzthefinn** [comment] 2022-11-27 17:18
The fix for this is #779 Closing as a duplicate of that issue

**Closed by mawzthefinn** 2022-11-27 17:18 UTC
Labels: duplicate
