### ISSUE TITLE
Reverse throttle use.

### ISSUE THREAD

**Issue by dobosatti** [FrSkyRC/ETHOS-Feedback-Community#140] opened 2021-04-27 08:21 UTC
I can't set up a basic thing with ETHOS.
That the throttle base position is reversed. That's how I use gas. (see picture)
It’s ridiculous that ETHOS doesn’t know. During my 35-year RC career, all the radios I used knew this feature. Why doesn't ETHOS know?
When turned on, it warns you that the throttle is in the wrong place. I can't start the timer with the throttle either, because the clock is already running when the Tx is turned on.
![Ethos 1](https://user-images.githubusercontent.com/32070803/116209241-00523600-a742-11eb-836a-6a800c82ba13.JPG)
![IMG_20210427_102008](https://user-images.githubusercontent.com/32070803/116209584-5cb55580-a742-11eb-8442-1d301520aac0.jpg)

**Comment by MIKE-DAILEY** [comment] 2021-04-27 11:39
Duplicate of #78

**Comment by dobosatti** [comment] 2021-04-27 12:00
Yes, I have raised the issue twice already, and yet there has been no change.
The problem still exists!

**Closed** 2021-04-27 12:16 UTC
