### ISSUE TITLE
I can´t connect via USB to my computer

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#753] opened 2021-08-04 22:43 UTC
When I connect my x20 to computer doesn´t recognize my x20 .Is there any USB drivers for windows 10?

**Comment by MIKE-DAILEY** [comment] 2021-08-04 23:28
Witch of the three modes is not working?

**ETHOS Systems USB Connection To PC Modes**

1. ETHOS System power off USB connection to PC is DFU mode for flashing bootloader.
2. ETHOS System started with enter key held down then power on USB connection to PC is bootloader mode for reading and writing files to SD card and on the X20HD/X20S/X20 the flash memory.
3. ETHOS System power on USB connection to PC is joystick mode.

**Comment by cperedamas** [comment] 2021-08-05 00:06
I had a similar problem, it was caused by going through a hub that was preventing recognition.  It is not a problem for everyone, but it might be the case for you as well.

**Comment by giaffone** [comment] 2021-08-05 14:47
On my Mac I can only see the radio drivers mounting (internal and SD card) through the USB cable if I enter the bootloader mode.

**Comment by jasalca** [comment] 2021-08-05 14:56
Uploading 64986807825__79C22061-BC43-47EC-858D-A06900A72BF9.MOV…

**Comment by jasalca** [comment] 2021-08-05 15:07
https://user-images.githubusercontent.com/87758703/128373735-b754a481-dfc6-4fc8-b923-821f8c986a95.MOV

**Comment by MIKE-DAILEY** [comment] 2021-08-05 15:18
The USB connection is not being detected at all by the X20 or PC.  Some things to try:

1.  A different USB port on the PC if another is available.
2.  A different USB cable.
3.  A different computer.

**Comment by bsongis-frsky** [comment] 2021-08-12 05:04
Did you try another cable or another computer?

**Comment by Beastyboy80** [comment] 2022-07-13 15:15
> I have a same problem, X20S not detected with my PC Windows 10.
> 
> USB port is ok with another matérial, USB cable is goog, I try another
> 
> I suspect windows 10 usb driver, as soon as possible I try on another pc

The problem is the weak Pc power supply via USB or a Bad cable

**Comment by Jo-le-Papy** [comment] 2022-07-14 17:03
OK, I try another PC (with a desktop PC) and it work !

I deduce that the usb port does not deliver enough power

Solved, thank's

**Comment by mawzthefinn** [comment] 2022-11-10 03:21
Closing as solved as per previous comment

**Closed by mawzthefinn** 2022-11-10 03:21 UTC
Labels: information needed
