### ISSUE TITLE
Missing editing possibility of the telemetry values

### ISSUE THREAD

**Issue by Andreas-4711** [FrSkyRC/ETHOS-Feedback-Community#2179] opened 2022-12-08 20:19 UTC
In ETHOS you can adjust the values in **RBOX V1** and **RBOX V2** with ratio and offset under the telemetry settings of the RB30.
The values for current **RBOX A1 /A2** and capacity **RBOX C1 /C2** should also be adjustable. They are displayed incorrectly.

**Comment by mawzthefinn** [comment] 2022-12-09 01:34
This is a duplicate of #955 and you can continue discussion under that Issue

At this time ratio/offset are only adjustable for voltage sensors.

**Closed by mawzthefinn** 2022-12-09 01:34 UTC
Labels: duplicate
