### ISSUE TITLE
Ethos v1.5.15 on X10S and X12S, bug in  User Defined Text Checklist?

### ISSUE THREAD

**Issue by gvt70** [FrSkyRC/ETHOS-Feedback-Community#4632] opened 2024-10-15 13:33 UTC
Ethos version 1.5.15
on X10S and X12S
bug in  User Defined Text Checklist

One sentence in the text file will put every word from that sentence on another line on screen.

For example: 
This is a text sample

will be on screen:
This
is 
a
text
sample

**Comment by gvt70** [comment] 2024-10-15 13:41
![Schermafbeelding 2024-10-15 153738](https://github.com/user-attachments/assets/f09ef1a4-1abb-4cdb-96a7-4324e1ed18b1)
![2024-10-15 15 38 27 (Klein)](https://github.com/user-attachments/assets/6022451c-35af-4f70-8697-adf4717232bc)

**Comment by bsongis-frsky** [comment] 2024-10-15 16:45
I think this one has already been fixed in 1.5.16

**Comment by bsongis-frsky** [comment] 2024-10-17 10:03
Duplicate of #4447

**Closed as completed by bsongis-frsky** 2024-10-17 10:03 UTC
