### ISSUE TITLE
Feature Request :  New Model wizard to add option for stabilized RX

### ISSUE THREAD

**Issue by dap35** [FrSkyRC/ETHOS-Feedback-Community#1143] opened 2021-11-25 16:08 UTC
Currently, if you want to use a stabilzed RX such as the SR6 or SR8, you need to configure your model with 1 aileron and one elevator even if the plane does not have elevators.   It would be much more consistent to select the model config they way it is in reality ( such as 2 elevons + rudder) and add a checkbox for stabilized RX. This should create the proper mixes and channel/servo assignments.

**Comment by MIKE-DAILEY** [comment] 2021-11-25 16:49
Duplicate of #924

**Closed by MIKE-DAILEY** 2021-11-25 16:49 UTC
