### ISSUE TITLE
Throttle Cut Default Trigger Value

### ISSUE THREAD

**Issue by darkernoise** [FrSkyRC/ETHOS-Feedback-Community#508] opened 2021-06-17 04:12 UTC
I don't know what the considerations were when setting the default throttle cut trigger value to -85%.  When you pull the throttle cut switch on every mainstream radio, the throttle should go to -100 immediately.  With a trigger of -85%, the throttle cut will not take effect until the throttle value next drops to <= -85.  For example, with heli throttle curves, the stick positions are irrelevant as the throttle stick becomes the pitch stick.  Yes, I know you can manually set the trigger to +100.  

I setup a few models on an X20S with 1.0.8 with a 84 year old pilot who has been flying since he was a kid.  This throttle cut trigger completely confused him and almost led to an injury as he expected the throttle cut to cut the throttle immediately.   If this happened to a seasoned professional, then any one new to FrSky will have no hope.  

Thus, why not adhere to industry standards and set the default throttle cut trigger to +100 so that the radio conforms? Advanced users can still change this value.

**Comment by darkernoise** [comment] 2021-06-17 04:15
Adding, I believe this is exactly what #494 is asking for.  So why not just make the solution to this easy and change the default Trigger value to +100?

**Comment by jreis1** [comment] 2021-06-17 06:27
I need to agree with this one.

**Comment by MIKE-DAILEY** [comment] 2021-06-17 11:26
Duplicate of #494

**Closed by MIKE-DAILEY** 2021-06-17 11:26 UTC
