### ISSUE TITLE
Wrong scripts directory  in  the X20S simulator version 1.5.11

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#4250] opened 2024-07-10 17:56 UTC
Operation system PC: Windows 10
Version Simulator X20S 1.5.11

I try to save my current X20s radio configuration in the X20S simulator. I found this small issue:

Under the scripts directory located on C:\Program Files (x86)\FrSky\Ethos\X20S\Scripts the LUA file cannot see in the simulator. I have copy my LUA and nothing happen in the simulator.

The only way to have it in the X20S simulator is to save it under C:\Users\Franco\.ethos\X20S\scripts . So have create this directory SCRPTS by myself.  

I thinks it will be great to have the same directory structure of the SD card to simplify the copy process when I like to upload my models, my LUA scripts, my model bitmaps, etc. in the simulator.

Also model images and model configuration are under two different directories

I suggest to have all this information under C:\Users\Franco\.ethos\X20S\

Thanks,

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42831968/7a2fb097-ef0a-47ed-96fc-5862f79912ad)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42831968/4acdf319-0e29-4a70-9a07-6f77dc782cbb)

**Comment by bsongis-frsky** [comment] 2024-07-15 07:29
Duplicate of #4270 
Will be fixed in the next nightlies

**Closed as completed by bsongis-frsky** 2024-07-15 07:29 UTC
