### ISSUE TITLE
Alerting system: Multiple audio selection / Chain execution

### ISSUE THREAD

**Issue by rafaelbiriba** [FrSkyRC/ETHOS-Feedback-Community#2313] opened 2023-01-09 11:46 UTC
Hi team,

For today feature suggestion, I did some field research first! This feature request is backed for at least 10 local pilots using Ethos. And some using opentx that are now jealous!

## Context:
Over the internet, is is very easy to download packages with thousands of wav files. 
For the sake of the explanation, consider:
warning.wav, vibration.wav, too.wav, high.wav.

There is NO way to setup an alert, where the telemetry reports vibration, to have the files:
`warning.wav, vibration.wav, too.wav, high.wav` to play on this sequence.

The overall internet solution for this is to download an audio editor and join the audios. This is WAY complex for most pilots and for people that does not have such ability with computers.

## Field research:

I spoke with a Mikado developer, and their radio have a hard coded set of audio selection. So no, they can not do it either. This questioning provided him the same idea of implementation. If we rush, we may be able to be the first one.

Opentx also does not support this.

Multiple pilots reporting that this is actually a great feature. A plane pilot reported to have at leat 10 virtual switches on ethos to make a chain of alerting...

## Usage:

Instead of selecting one audio for the alerting, we could have a multiple selection and execute the wav files in that order. The benefits are unlimited, since this audio packs are already over the internet, the combination of the files to make full sentences is unlimited.

Personally I want to use it to proper report my telemetry data, for example: "Wind is too strong", "Landing gear is still down", "Throttle hold not engaged", "Can not detect RPM"

**Comment by mawzthefinn** [comment] 2023-01-09 13:45
This would be great, note this already exists today in effect on iX Airware thanks to text to speech and arbitrary texts phrases.

That said, you can chain multiple special functions to do this, they play in order from top to bottom if they have the same trigger. You can also include play value in these changing.

**Comment by strgaltdel** [comment] 2023-01-10 18:15
So in case you are exceeding a Threshold like Altitude >150 m you want this:

(1)
LSW triggers the warning

(2)
A predefined chain / sequence of SFs is started

A) Play "warning" 
B) Play "altitude"
C) Play "too"
D) Play "high"

??

personally, for me, it would be more easier to generate the complete phrase as one wav by using tts tools
it would end in a 1:1 match lsw<>SF

more wave files but less  configuration work

What would make sense to me:
A global definition of self defined  audio sequences,
Maybe with the ability to support telemetry Values announcements, so that you wohl need only one SF, and these call outs would be available for all models.

Is this your request?

**Comment by rafaelbiriba** [comment] 2023-01-10 18:18
>A global definition of self defined audio sequences,
Would also works, as long as I can pre-select multiple wav files.

>personally, for me, it would be more easier to generate the complete phrase as one wav by using tts tools
It is not! I spent 1h last weekend updating 3 radios of old people that doesn't know how to proper use a computer.

**Comment by mawzthefinn** [comment] 2023-01-10 19:44
For me right now cloning Special Functions and adjusting them works reasonably well. That said, I'd love a 'play sequence' SF that allows me to select an arbitrary set of tracks & values to play in order.

**Comment by mawzthefinn** [comment] 2023-01-13 22:40
As a note, this is a duplicate of #441 and I'm closing in favour of that one.

**Closed by mawzthefinn** 2023-01-13 22:40 UTC
Labels: duplicate
