### ISSUE TITLE
Override Channel Value in Special Functions

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#1945] opened 2022-10-01 16:21 UTC
Dear Ethos Team,
is it possible to include override CH X in the special function? In many cases it is helpful to set a specific value on a channel output with a (log) switch.

Thx a lot.

![bild](https://user-images.githubusercontent.com/68751162/193418641-10f192be-8196-47b3-8c48-30f9ea44ed51.jpg)

**Comment by MIKE-DAILEY** [comment] 2022-10-01 17:43
Duplicate of #525

**Closed by MIKE-DAILEY** 2022-10-01 17:43 UTC
