### ISSUE TITLE
Switch-on crackling in the Varioton

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#2280] opened 2023-01-03 15:22 UTC
Hello
For another reason, I checked the Variotone in my X10 Express with Ethos 1.4.5. The vario is a Vario HP.
I now also have the "switch-on crackling" before and after each Varioton. If I adjust the repetition rate in General, the rate seems to remain at 200ms when sinking at a rate of 800ms, and only the rise is slowed down accordingly. In this case, the crackling is hardly noticeable, but when sinking, a fast tacking can be heard in the continuous tone. In the standard setting of 500ms, the disturbance is clearly audible when rising and sinking. This was not the case in the previous versions.
Thank you for your interest.

**Comment by yak55** [comment] 2023-01-03 15:32
Problem in the sinking tone I have since 1.4.5 also on the Tandem X20S.
Of course, also always on the Tandem XE.

Sounds like constant activation of the audio output.

Solution: Disable sink - to min -2.0m/s.

Greetings Eugen

**Comment by aalain8** [comment] 2023-01-03 21:09
I confirm that since 1.4.4 (maybe av) the sound of the Vario is bad.
Especially towards the bottom.
X20S Ethos 1.4.5

**Comment by tflyerofrc** [comment] 2023-01-04 00:05
I have same experience since 1.4.4 and continued in 1.45 on X20 and X18.

**Comment by strgaltdel** [comment] 2023-01-04 07:48
maybe a hint:
i observed strange audio sounds by producing tones via lua too.
when i tried to produce frequencies below app. 50Hz i god bad "crackling" sounds.
my personal explanation was, that the sound frequency runs below lua handler frequency and so the audio wave was "cut" before it finished its first complete "round"and starts again.
This cut produces "high frequency artefacts" which is audible as this crackling noise.

maybe the vario tone has similar problems during sinking at it produces audio frequencies below ist software driven "repetition" frequency ?

regards
udo

**Comment by Wolepo** [comment] 2023-01-04 13:48
Hello
Here is a Variotone example. Recorded with Audacity and the headphone output of the X10S Express transmitter.
[unbenannt.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10344606/unbenannt.zip)

**Comment by tflyerofrc** [comment] 2023-01-04 14:20
Pretty much the same background noise I hear now.   But just since upgrading beyond 1.4.4.

**Comment by yak55** [comment] 2023-02-20 21:44
Is there any hope that the vario, especially in the sink will work again without cracking noises?

Have currently only one sound when rising - crack is just annoying!

THAT WAS NOT ALWAYS SO!  

Greetings Eugen

**Comment by NorbertHeli** [comment] 2023-02-27 09:28
I own 2 x X20S - one on 1.3.0 - one one 1.4.6
Tryid with the same receiver under ACCESS - just new binding
1.3.0 is ok - 1.4.6 at sinking and rising tone this cracking
The adjustments under Vario has no effekt on the cracking. 
Maybe the amplfier is switched on and off?

**Comment by Hermann62** [comment] 2023-02-27 15:16
X18SE: A terrible choppy sound, completely unusable.

**Comment by aalain8** [comment] 2023-02-27 16:49
I mainly fly gliders and since 2 months the only solution I found to use the vario is to cut the sound down, otherwise it is unbearable.

**Comment by bsongis-frsky** [comment] 2023-02-27 18:01
One of you has tried with the nightlies of 1.5.0?

**Comment by KevinFairgrieve** [comment] 2023-02-27 18:12
> One of you has tried with the nightlies of 1.5.0?

I would like to try the Nightly, but alas it is not available for the X12S.

As I only have one glider with a vario in it "UnisensE" I will for now resort to turning the volume down

**Comment by yak55** [comment] 2023-02-27 18:41
Hello Bertrand, you are doing really good work.

Do you think I can try a test flight with vario with the 1.5.0?

 

Desk is just not flying!

 

If so, should I take the XE or X20S?

 

Go to the airfield every day, so the past 8 weeks were also very very long with the bad vario.

 

Would use a simple model for testing.

 

Greetings Eugen

 

Von: Bertrand Songis @ FrSky ***@***.***> 
Gesendet: Montag, 27. Februar 2023 19:02
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: yak55 ***@***.***>; Comment ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] Switch-on crackling in the Varioton (Issue #2280)

 

One of you has tried with the nightlies of 1.5.0?

**Comment by bsongis-frsky** [comment] 2023-02-27 18:49
Please backup your radio first, because you won't return from 1.5.0 to 1.4.X
Also take time to try everything on ground and if you find any issue, give it up and just report the issue here
I think it will be repaired, when you confirm it, please don't fly anymore with 1.5.0 as it is moving everyday!

**Comment by yak55** [comment] 2023-02-27 20:06
Hi Bertrand, just installed the 1.5.0 with the suite on the X20S EU.
Test in the apartment still has the same unpleasant crackling especially when sinking - like a dripping faucet.

No improvement on my X20S.
Try it again tomorrow, maybe something new comes tonight.

Tested vario: FrSky VAR ADV

Greetings Eugen

**Comment by yak55** [comment] 2023-02-27 22:05
Hi Bertrand, current 1.5.0 (2 hours old) I can not get to run on my X20S.
After the update also from 1.4.7 is no longer readable model.

Can therefore no longer test it.
Greetings Eugen

**Comment by bsongis-frsky** [comment] 2023-02-28 12:02
Reproduced.
1.3.0 is good
1.4.3 and later are bad

**Comment by bsongis-frsky** [comment] 2023-02-28 17:46
Fixed, it will be in 1.4.8 when released
And 1.5.0 nightlies tonight

**Closed by bsongis-frsky** 2023-02-28 17:46 UTC
Labels: bug
