### ISSUE TITLE
Ethos Suite

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#2681] opened 2023-06-10 06:28 UTC
Is it possible that in Ethos Suite there is a list of receivers updates which can be downloaded from the suite, than having to go to FrSky, download to SD card and flash through OTA?

It will make it a lot easier to flash receivers.

**Comment by mawzthefinn** [comment] 2023-06-10 13:09
Duplicate of #1568

**Closed** 2023-06-10 19:55 UTC
Labels: duplicate
