### ISSUE TITLE
request: VAR Mixer improvement

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#2126] opened 2022-11-26 09:09 UTC
Please make it possible to change the active VAR value by a switch / button / logical switch.

i am thinking of a mix between the VAR mixer and the Trim mixer.

for example:

if you have a var mixer with 3 values , every value can be changed by a button, but only if it is aktive.
one for increment and one for decrement.

So we have a nice digital potentiometer that can store 1 to x values wich can be easy changed in flight (for helicopter gyro gain / headspeed  or something else)

**Comment by mawzthefinn** [comment] 2022-11-26 13:57
This is a duplicate of #1602 

This is the last real capability gap between VAR mixers and GVAR’s as well.

Note that you can do this today in one case. If you use a spare trimmer as the input for the VAR mix weights you want to be adjustable, and select weights with Flight Mode, and also have that trimmer set to Independent Trims per FM, this works.

**Closed by mawzthefinn** 2022-11-26 13:57 UTC
Labels: duplicate
