### ISSUE TITLE
Missing Stick position curve menu

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1756] opened 2022-06-28 13:28 UTC
Customers ask us about why the stick position is not shown if they create a curve.

It will be good to add it because it make it much easier to create a curve.

**Comment by EngelMT** [comment] 2022-06-29 12:17
Why? The user create a curve and will check it on his plane. So he move the stick. But now he do not know what the stick position means since he doesn't see it on the curve.  But if the stick moves, then you still have the input.

**Comment by bsongis-frsky** [comment] 2022-06-30 10:53
Duplicate of #24

**Comment by bsongis-frsky** [comment] 2022-06-30 10:54
Luo is right, there are many cases where we don't know the input for the user curve

**Closed by bsongis-frsky** 2022-06-30 10:53 UTC

**Comment by df7320** [comment] 2022-06-30 13:49
Are you saying that if the curve is created within the mixer that you don't know the input?  I can understand if the curve was created from the "Curves" menu then that would be the case. I have attached a couple of screenshots of how it appears in OTX 2.3.11 thru 2.3.15.  I just want to make sure we are talking about the same thing here. Thanks

![OTX1](https://user-images.githubusercontent.com/81670152/176691743-dc3ac0c1-8867-4b7d-b684-9dc5a4aaca5b.png)
![OTX2](https://user-images.githubusercontent.com/81670152/176692631-50c164fb-9a97-4507-9ca9-177d1916e18b.png)
