### ISSUE TITLE
X18RS Missing RF remote version and will not update but did the RF manually frsk from FrSky and still will not update and Ethos still says missing RF

### ISSUE THREAD

**Issue by kensterman** [FrSkyRC/ETHOS-Feedback-Community#4900] opened 2024-12-22 13:27 UTC
Houston we have a problem. I have 2 X18RS From day one Ethos does not recognize the RF version. I couldn't flash firmware 3.0.1 it says do it manually so I went to Frsky and installed it manually and it updated in the info screen but ethos still doesn't recognize version and tells me to update rf module 1st before installing 1.6.0. it has RF 3.0.1 now you can see it in the info screen but Ethos doesn't see it.
So I can't update 1.6.0 what is funny Rf instruction say install Ethos 1.6.0 1st before the RF and the and Ethos say install the RF firmware 1st before you can install ethos.
Same problem on 2 X18RS radios.
![PXL_20241222_130831045](https://github.com/user-attachments/assets/bdc055ec-9b33-4167-85ad-009e2ee8a9cb)
<img width="883" alt="Screenshot 2024-12-22 080544" src="https://github.com/user-attachments/assets/c2017d9b-6ad6-487f-a029-181aa7f2b9ea" />
<img width="887" alt="Screenshot 2024-12-22 080724" src="https://github.com/user-attachments/assets/3fa20ff0-5088-4092-b82f-a09006d80f84" />

**Comment by strgaltdel** [comment] 2024-12-22 13:59
in case it is a suite malfunction you could update the 1.6 firmware also manually, right ?

**Comment by kensterman** [comment] 2024-12-22 14:02
<img width="878" alt="Screenshot 2024-12-22 095306" src="https://github.com/user-attachments/assets/5ff9227c-38de-469a-8951-83ec4f6f0b82" />
<img width="882" alt="Screenshot 2024-12-22 095345" src="https://github.com/user-attachments/assets/e288b7a7-53c3-45e9-a589-526e063bf75f" />
<img width="881" alt="Screenshot 2024-12-22 095413" src="https://github.com/user-attachments/assets/9ca26e7f-2604-482e-8aec-a795abf3c17c" />
I manually updated Ethos Suite and everything works now so ethos must have a problem.

**Comment by kensterman** [comment] 2024-12-22 16:02
I tried a reinstall using Ethos Suite and you can'
<img width="882" alt="Screenshot 2024-12-22 105109" src="https://github.com/user-attachments/assets/089f12a9-e738-4f41-832e-cf15ab6c036a" />
t select only Firmware only all.

**Comment by Nicholas-Luoyi** [comment] 2024-12-23 02:32
X18RS does have an issue with getting RF info in bootloader mode. And the issue is fixed in bootloader 1.6.0

**Closed as completed** 2024-12-23 13:49 UTC

**Comment by mrdhhall** [comment] 2025-02-05 17:35
just managed to sort this exact issue out on my X18RS and update it to 1.6.0
1st i downloaded the RF module V3.0.1 and flashed it once by installing it in the Radio nand drive root directory and then going to radio file manager and finding it in there then pressing enter and select flash...this flashed it sucessfully however it still didnt show up in ETHOS suite ...

so i decided to flash it  manually through ETHOS suite so located the TD-ISRMRS .frsk file pessed FLASH and it again successfully flashed it BUT THIS TIME TX wouldnt boot up...
So after a lot of head scratching i decided to try to see if i could ROLL back the firmware and sure enough it did reflash the older 1.5.19 firmware but this time the RF MODULE WAS ALSO updated and now it let me flash it to 1.6.0 firmware 
i hope this helps
