### ISSUE TITLE
1.5.0 N  Log Viewer Zoom the X-Axis at Cursor  (X20 Simulator)

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#3337] opened 2024-01-27 05:18 UTC
Logviewer (Simulator)
How to zoom the X-Axis at the coursor-position?
can set Cursor, then should select Zoom x5 round the Cursor in X Axis

X20 is there a zoom funktion?
X20S how to zoom?

**Comment by bsongis-frsky** [comment] 2024-02-14 09:26
Yes, there is a Zoom feature!
Duplicate of #3349

**Closed by bsongis-frsky** 2024-02-14 09:26 UTC
Labels: information needed
