### ISSUE TITLE
Recreateable Emergency Mode (1.5.0 Release)

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#3558] opened 2024-03-04 15:55 UTC
Please see the model definition, attached below, for an X20S.

Select this model
Ignore the checklist warning by selecting OK
Select Model
Select Mixes
Select Ailerons 
Select View per channel for Ailerons  (seems to work with various channel)
Select the Ailerons mix under ch1 (already highlighted, but again seems to work with any mixer under ch1 etc.)
Select Table View
and you get Emergency Mode
(maybe I have fat fingers, but sometimes when I select Table view I don't get it and get returned to above, but reselecting seems to result in the Emer mode).

I've managed to recreate on a fairly simple model but it's not reliably repeatable. The key seems to be having multiple mixers which use the same channels, e.g. Mix Aileron uses ch1,5,6,7 and then Mix Flaps also uses ch6,7. When you go into table view, select a channel fed from multiple mixers and select one of the mixers below it and table view from there.

[v tail 1.5.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14483562/v.tail.1.5.zip)

Thanks

**Comment by Jedsters** [comment] 2024-03-04 15:59
I've just noticed 1.5.1 which may well fix this problem. 
Please just close if this is the same bug.

**Comment by bsongis-frsky** [comment] 2024-03-04 16:10
Duplicate of #3545

**Closed as completed by bsongis-frsky** 2024-03-04 16:10 UTC
