### ISSUE TITLE
Downloading Ethos updates take forever (from 1.4.12 to 1.4.13)

### ISSUE THREAD

**Issue by FlipAirboost** [FrSkyRC/ETHOS-Feedback-Community#2992] opened 2023-10-21 11:01 UTC
Same problem as issue n° 2918.
I try  booth server .
I tried the recommendations from the previous issue.
Suddenly after three of four tries it works.

But i get the following pop up : auto update failed.

Really painful these updates. 
It works for some then you have to uninstall the ethos suite and download the new version directly from the ad hoc site.

**Comment by OldGazer** [comment] 2023-10-21 14:13
I just had to uninstall ETHOS suite, download it from FRSky-RC and reinstall it.  The previous version took forever to download the latest version and then it would hang verifying the installation.  The latest version had no issues.  X20 firmware update was successful

**Comment by mawzthefinn** [comment] 2023-10-21 15:26
Yes, this should be fixed in ETHOS Suite 1.4.13, it was an issue in both Suite 1.4.11 (slow downloads) and 1.4.12 (faster, but still kind of slow downloads, updating failed)

**Comment by mawzthefinn** [comment] 2023-10-21 15:27
Note this is a duplicate of #2989 So closing in favour of that issue

**Closed by mawzthefinn** 2023-10-21 15:27 UTC
Labels: duplicate
