### ISSUE TITLE
Surplus line when inserting new actions

### ISSUE THREAD

**Issue by Wolepo** [FrSkyRC/ETHOS-Feedback-Community#4127] opened 2024-06-03 08:25 UTC
Hello,
If you insert a new action into a mixer, one line is left over. There is probably one line too many. If you close this mixer and open it again, the excess line is no longer displayed.
Ethos 1.5.9 and 1.5.10 in the sim and transmitter 
Best regards from Wolfgang
[Ashampoo_Snap_Sonntag, 2. Juni 2024_09h38m05s_002_.zip](https://github.com/user-attachments/files/15530986/Ashampoo_Snap_Sonntag.2.Juni.2024_09h38m05s_002_.zip)

**Comment by bsongis-frsky** [comment] 2024-06-03 15:17
It's a duplicate of #4126? Or do you mean something else?

**Closed as completed** 2024-06-03 15:44 UTC

**Comment by Wolepo** [comment] 2024-06-03 17:33
No, I don't mean anything else. It's a duplicate
