### ISSUE TITLE
Screen call with assignable switch (feature req)

### ISSUE THREAD

**Issue by Droptank** [FrSkyRC/ETHOS-Feedback-Community#1481] opened 2022-02-17 03:34 UTC
Would like to be able to assign a switch to quickly call up various widget screens.

**Comment by Isidorus21** [comment] 2022-02-18 10:20
Das wäre super, das Problem habe ich auch.

**Comment by mawzthefinn** [comment] 2022-11-27 17:27
Good idea, but a duplicate of #652 Closing off in favour of that issue

**Closed by mawzthefinn** 2022-11-27 17:27 UTC
Labels: duplicate
