### ISSUE TITLE
1.5 nightly - problems with Positive and !Positive action conditions

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3008] opened 2023-10-28 16:52 UTC
I'm trying to migrate one of my glider templates, and it's revealed some further issues:

1. Action conditions _Positive_ and _!Positive_ appear when migrating mixes from 1.3.12. However, they are not available for mixers created within 1.5  - they don't appear as options in the action conditions dropdown menu.

2. In the action:
`Condition=Positive, weight=-CH15`
The negative sign is ignored when evaluating the line. So the result is the same as `Condition=Positive, weight=+CH15`

Also I notice that there is no 'delay' action.

**Comment by mawzthefinn** [comment] 2023-10-28 17:57
Delay doesn’t exist in mixers in ETHOS, only in LSW’s. This was a deliberate choice.

**Comment by RC-SOAR** [comment] 2023-10-29 12:13
Thanks Adam, understood.
It seems that the action stack is still work in progress. That said, it would be great if points 1 & 2 above could be fixed soon to allow migration and testing of legacy setups (the workarounds are not simple).

**Comment by mawzthefinn** [comment] 2023-10-29 18:10
Yes, I hope to see that in a new build pretty quickly, it's a must-fix for me.

**Comment by bsongis-frsky** [comment] 2023-10-30 19:01
Point 1 will be fixed in next nightlies.
Instead I am not able to reproduce Point 2

**Closed by bsongis-frsky** 2023-10-30 19:01 UTC
