### ISSUE TITLE
 enhancement: voice alert when timers elapsed

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1381] opened 2022-01-25 08:27 UTC
please add a voice file for each timer elapsed (1,2,3..)
it makes no sense that timers read out the last 10 seconds but nothing is read when timer has elapsed.

and makes no sense to request the user to do it via logic switch / special function per model.

**Comment by bsongis-frsky** [comment] 2022-01-25 09:25
Duplicate of #1288

**Closed by bsongis-frsky** 2022-01-25 09:25 UTC
