### ISSUE TITLE
No Issue Just a suggestion. 

### ISSUE THREAD

**Issue by vlugardo** [FrSkyRC/ETHOS-Feedback-Community#4480] opened 2024-09-03 13:59 UTC
I would love to be able to move around the icons in the main screen.  In particular "Curves" in place of "RF System". For me it's more convenient having adjustable settings all on one page then a "one and done" setting like "RF system" on a frequently used icons page.

**Comment by RealTadango** [comment] 2024-09-04 10:45
Like a custom layout for the model/system screen. Maybe an additional user/quick/favorite layout with only the items we use often would be helpful (including the custom lua registered apps ;)). Modern camera's also have this option to make often used settings quickly available. Not sure how to activate it but with the home button mappings this would be up to the user i guess. The layout(s) configuration could be a lua script maybe. Nice idea for the list :)

**Comment by bsongis-frsky** [comment] 2024-09-04 13:21
Duplicate of #2661

**Closed as completed by bsongis-frsky** 2024-09-04 13:21 UTC
