### ISSUE TITLE
Feature Proposal: Multiple Value Readout

### ISSUE THREAD

**Issue by jasc76** [FrSkyRC/ETHOS-Feedback-Community#2434] opened 2023-02-23 06:32 UTC
it would be nice to have a special function to read out not only one, but multiple values.

**Comment by mawzthefinn** [comment] 2023-02-23 08:09
This is a duplicate of #441

**Closed by mawzthefinn** 2023-02-23 08:09 UTC
Labels: duplicate

**Comment by jasc76** [comment] 2023-02-23 08:26
Hmm
I dont know if this is a duplicate. Also #441 reads very complicated. 
I thought about a possibility like the play value thats already there but where I can just activate more than one value and they are just read one after another. In fact it could just be possible to define more than one value in play value ...

**Comment by mawzthefinn** [comment] 2023-02-23 08:30
Yes, that is the functionality in #441, just allowing both play value and play track interspersed as needed.
