### ISSUE TITLE
Overwrite global function with model function

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#2980] opened 2023-10-16 08:21 UTC
is possible to overwrite global functions with model functions?
in models with different configurations (gliders, motor models, drones) it is not always possible to use one global function in the same situation, especially in the case of play track or play value.
Solutions?

**Comment by mawzthefinn** [comment] 2023-10-16 19:05
This is functionally a duplicate of #1587 

Please continue discussion there

**Closed by mawzthefinn** 2023-10-16 19:05 UTC
Labels: duplicate
