### ISSUE TITLE
LuA to mimic the forward programming of Spectrum for multımodule

### ISSUE THREAD

**Issue by toganalper** [FrSkyRC/ETHOS-Feedback-Community#3988] opened 2024-05-05 20:37 UTC
I have an Eflite viper that I am using with X20s and multimodule. I would like to be able to play with parameters such as the bank angle limit, gain of the gyros etc., as you would in Spectrum forward programming. Is there a way to do it. 
Also I would like to assign a switch to turn off the gyros ? How do I find out which channel this function is assigned in Spectrum

**Comment by robthomson** [comment] 2024-05-05 23:20
Currently this is not possible as no lua script exists.

I have however done some prelims work to port this code to ethos - but right now just have not had time to dig in and sort fully.

**Comment by frankiearzu** [comment] 2024-05-06 00:14
@robthomson let me know if you need any help.. the key is that Ethos needs to support the "multibuffer" that is the way to move the forward programming data from the MM to the LUA script.  The GUI simulator is very useful to get the GUI running on an Ethos Simulator without connecting to a real RX.

**Comment by mawzthefinn** [comment] 2024-05-09 14:43
This is a functional duplicate of #3980 

Closing to bring all discussion into the one issue

**Closed as not planned by mawzthefinn** 2024-05-09 14:43 UTC
Labels: duplicate
