### ISSUE TITLE
upper display flickers, XEs

### ISSUE THREAD

**Issue by HolgerJr** [FrSkyRC/ETHOS-Feedback-Community#2271] opened 2023-01-02 21:15 UTC
Hello,
the bottom half of the XEs top display flickers yellow-green intermittently.
ETHOS 1.4.5
upper display configured to show 4 channels
if one of the 4 channels is changed, the lower half of the display flickers yellow-green

Best regards
Holger

**Comment by HolgerJr** [comment] 2023-01-02 21:29
https://user-images.githubusercontent.com/121034000/210279132-e26a11a4-69c1-4b86-ae4e-4e7a891987e8.MP4

here is a little video

**Comment by bsongis-frsky** [comment] 2023-01-03 11:17
I have fixed this issue in 1.4.5 and it is strange that it happens again. Would you share your radio.bin and model file?
Unless you can reproduce it with an empty model? I have tried here and I cannot replicate it.

**Comment by bsongis-frsky** [comment] 2023-01-03 11:19
What is the info displayed in System / Information / Firmware Version on your radio?

**Comment by HolgerJr** [comment] 2023-01-03 12:47
Firmware Ethos-XE
Version    1.4.5,EU #802cb7d0
Datum     Dec 27 2022, 12:10:32
Stick Mode    ADC

**Comment by HolgerJr** [comment] 2023-01-03 12:54
[kraftw_or.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10336714/kraftw_or.txt)

here the model.bin, renamed to.txt, otherwise the system won't upload it

**Comment by HolgerJr** [comment] 2023-01-03 13:39
I also created a new model for testing, only with 4 free mixers and the same yellow-green flickering occurs.

**Comment by HolgerJr** [comment] 2023-01-03 16:49
here the radio.bin, renamed to .txt, otherwise the system won't upload it
sorry, i had overlooked that you need the file
[radio.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10338306/radio.txt)

**Comment by pldmn** [comment] 2023-08-30 07:13
Still have the same issue as stated by HolgerJr with version 1.4.11 (eu).

**Comment by bsongis-frsky** [comment] 2023-10-20 10:43
Duplicate of #2983

**Closed by bsongis-frsky** 2023-10-20 10:43 UTC
