### ISSUE TITLE
1.0.10 RC3 Telemetry Fuel % Limit 100%

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#625] opened 2021-07-13 11:51 UTC
First a big compliment for the virtual keyboard :-)
I don't know if it's on purpose or a foult because in RC2 it wasn't? However in RC3 **I'm not able to go over 100% for the Fuel** Sensor of Kiss ESC which shows actually consumption. 
I have already deleted all sensors and discovered new.
![consumption-1](https://user-images.githubusercontent.com/78207054/125446688-7b58db1b-67ff-44b7-a640-c8e903897517.JPG)
![consumption-2](https://user-images.githubusercontent.com/78207054/125446766-e8271f18-f157-4daa-a2bf-0a64a04057c6.JPG)

**Comment by Cipta-de** [comment] 2021-07-13 13:34
Hello ,
for me it would be good if I could go up to 10000 - I know it's not so logic to have 10000 % but who knows why KISS-ESC have fuel in % even if it's mAh??? I use some of the KISS-ESC and use the "fuel" for flighttime. I have also tested the calculated sensor consumption but its not so precise because the telemetry to the kiss-ESC often lost (not because ETHOS) and so the calculated consumption doesn't show the correct value - always too less. 
Is there a way to change the % from the fuel sensor? 
And what is the meaning of "Telemetry sensors limits fixed (splitted now to protocol and user limits)" ? User Limits are in Telemetry - I guess and protocol limits fixt in the system? RIGHT?

**Comment by bsongis-frsky** [comment] 2021-07-13 15:21
Will be possible with DIY sensors which repurpose FrSky standard IDs

**Comment by bsongis-frsky** [comment] 2021-07-13 18:24
Duplicate of #459

**Closed by bsongis-frsky** 2021-07-13 18:24 UTC
