### ISSUE TITLE
Problem with Sticky LSW with Edge at model load

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2320] opened 2023-01-11 17:40 UTC
I want to create a looping list of multiple LSW each triggered by the previous one ending (Invert, Edge)
While the following isn't exactly what I'm trying to do, it does demonstrate the problem with a list of just 3 items...

![image](https://user-images.githubusercontent.com/96293240/211875849-bf27d35e-1dcf-47a7-a48b-6929aa93f676.png)

Pressing SJ should trigger the list to start
Then repeated presses of SI should cycle the list around OPT1, OPT2, OPT3, OPT1, OPT2... etc.. to allow e.g. playing a track.

However, when the model is loaded, LSW2 and LSW4 are both ON for no apparent reason. SJ has not been pressed so the list should not have been triggered and therefore none of the OPTx should have become active for them to become inactive to trigger the next item.

Thanks

**Comment by mawzthefinn** [comment] 2023-01-11 18:19
You have a logic problem, The True condition for OPT1 and OPT3 will fire at the same time, so your chain is actually flipping between OPT2 and OPT1/3

I fixed this by Changing Trigger to a sticky, trigegred by Opt2, disabled by Edge !OPT3 and set OPT1 to be triggered by !Trigger

**Comment by Jedsters** [comment] 2023-01-11 20:11
> You have a logic problem, The True condition for OPT1 and OPT3 will fire at the same time, so your chain is actually flipping between OPT2 and OPT1/3
> 
> I fixed this by Changing Trigger to a sticky, triggered by Opt2, disabled by Edge !OPT3 and set OPT1 to be triggered by !Trigger

Thanks for the reply, but I'm sorry, I'm struggling to agree with you. Suely when the model loads Opt1, 2, 3 should all be inactive? (The problem is they aren't.) 
SJ will make Trigger active and Opt1 active as a result (with Trigger immediately becoming inactive). SI deactivates Opt1 which activates Opt2. SI then deactivates Op2 which activates Opt3. SI then deactivates Opt3 which briefly makes Trigger active again thence making Opt1 active etc..  Which part of my logic disagrees with this? Indeed, with my screen grab above initially Opt1 and Opt3 are active, if I then don't press SJ but just press SI it works as desired and rotates around Opt1 first being active, then Opt2, then Opt3, then Opt1 etc., the problem being that Opt1 and Opt3 are initially active when the model loads for no reason. 

I did try your suggestion and edit, however, that appears to flip between opt1 being active and opt2/3 being active (but I may have got it wrong).

**Comment by Jedsters** [comment] 2023-01-11 21:07
I've just tried something else. In my example above, I've changed Opt1 to Sticky Invert Edge Opt3 which actually should make it unusable as there is no trigger to enter the loop. However, when you select the model Opt1 and Opt 3 are active. Why?

**Comment by mawzthefinn** [comment] 2023-01-11 21:43
Undefined to off is a valid edge condition in ETHOS it seems.

The problem in your original logic is that the On condition for both Opt1 and Opt3 is valid if Opt2 is currently de-activating. If OPT2 is active, then pressing SJ enables Trigger, which activates OPT1 and disabled OPT2 which activates OPT3. It then flip/flops between OPT1/3 and OPT2.

I tested my solution on 1.4.5 and it works correctly. Yours behaves as I described.

What my solution does is twofold

1. Give a condition which forces OPT1 to true on initialization (namely !Trigger)
2. Locks out Opt3 when OPT1 is active and OPT1 when OPT2 or OPT3 is active (Active condition of Trigger)

You can have any number of LSW's in the sequence so long as Trigger goes Active on OPT2 and de-activates when the last LSW in the chain de-activates. Then any LSW's after OPT must have an active condition of Trigger

Note if you are doing a step-through, OPT1 is a landing spot/reset to the chain, not step 1.

**Comment by mawzthefinn** [comment] 2023-01-11 21:48
I should note that OPT2 should activate if OPT1 goes false on activation, so you need that landing spot on the chain as far as I can currently figure.

**Comment by mawzthefinn** [comment] 2023-01-11 22:26
I think I've cracked the logic to have an initialization step, then cycle continuously through the steps

![Cycling LSW](https://user-images.githubusercontent.com/34381975/211931163-a239833f-6beb-4a1b-ab18-05d02f3231cf.jpg)

**Comment by mawzthefinn** [comment] 2023-01-11 22:30
And I just saw another optimization. Trigger is not needed.

![Cycling LSW2](https://user-images.githubusercontent.com/34381975/211931854-32ae6069-e865-4031-b028-db590d1c63a5.jpg)

**Comment by Jedsters** [comment] 2023-01-12 10:55
Thanks for what appears to be a clever work-around I can use. 

Maybe I'm wrong, but I still feel that my original example should work - there still seems to be an underlying problem in that some / all of my original LSW are being randomly(?) triggered at model load for no obvious reason. As you say, there appears to be an element of LSW states being undefined where edge is being used. Surely all LSW should be off at model load unless there is a condition which turns them on. What you have done is clever in that you have prevented the chain from starting during model load with an active condition which doesn't rely on an edge - but then my chain shouldn't have started either. It is a clever work-around. 

I'd be interested to know if there is a reason something which feels like a bug can't be fixed. If so and I can't use my original example then I feel the manual should be updated to explain what is going on during model load with LSW and Edge (if that's where the problem is) so that we know how to program logic around the situation. 

Again, thanks for your clever work-around!!

**Comment by mawzthefinn** [comment] 2023-01-12 13:50
It’s not a bug, it’s the consequence of how an Edge trigger works with the processing queue and order of evaluation of LSW’s.

When the model comes on, everything goes from undefined to a set state. This is False for an LSW that doesn’t initialize with its Active condition already active. Because you have edge triggers on the !LSW state, they fire on that transition and go into the queue. So there is a !OPT1 trigger, !OPT2 trigger and !OPT3  trigger all queued from the initialization process.

They then process in order. Because of the !OPT3 trigger queued, your Trigger LSW fires, then OPT1 fires because of Trigger, but that changes the edge event for OPT1 from !OPT1 to OPT1 (because it last went true). So OPT2 does not fire, but the !OPT2 edge event is still queued so OPT3 fires. 

Thus you always start off with OP1 and OPT3 active.

The core takeaway here is that a !LSW edge event will fire on initialization of the model unless you deliberately work around it.

**Comment by Jedsters** [comment] 2023-01-12 17:01
Thanks, that's clearer now. I notice you've mentioned in #2321 that the book of words could do with a sentence to better explain initialisation and that would be appreciated.

While you are in that area, is there any chance the paragraph about Active Conditions with Sticky can be reworded?  Namely: "Note that the Sticky function continues to operate, even if its output is gated by the ‘Active Condition’ switch. As soon as the ‘Active Condition’ switch condition becomes True again, the Sticky function's condition is switched through to the Logic Switch output."  I did try playing around with Active Conditions myself while trying to fix my logic before raising this issue, but couldn't get them working as I wanted (so gave up), I did read this paragraph but struggled to understand the implications.

Thanks in particular for the assistance with the work-around.

**Comment by mawzthefinn** [comment] 2023-01-12 17:26
I'm not the author of the manual, but I will review that and try and come up with some better wording on both items for the author to consider adding to the manual.

As you have a working logic set now, are we OK to close?

**Comment by Jedsters** [comment] 2023-01-13 10:42
I've been having a play and am still having trouble getting things to work as expected (although your example does work). You say above that _"When the model comes on, everything goes from undefined to a set state. This is False for an LSW that doesn’t initialize with its Active condition already active. Because you have edge triggers on the !LSW state, they fire on that transition and go into the queue. So there is a !OPT1 trigger, !OPT2 trigger and !OPT3 trigger all queued from the initialization process."_ 
It therefore occurred to me that since I am happy for Opt1 to be true after model load before I press SI, I could use RSSI as a 'trigger' instead of your INIT. (Although it is easier to test with a physical switch than RSSI, so I did that).
In your last example, after model load ony INIT is active. A press of SI makes it inactive which briefly triggers INIT RESET which then triggers Opt1 etc.. Opt1,2,3 are safe at load because !INIT protects them. So if I therefore change INIT RESET to 'EDGE RSSI OR ! EDGE OPT3' we can do away with INIT. Here, OPT1,2,3 would be protected at model load as RSSI is false until I turn the rx on and the loop would be triggered when RSSI becomes true (EDGE RSSI) which as before briefly triggers INIT RESET which should then trigger OPT1 etc.. Except this doesn't work, when RSSI becomes true, all OPTx become true. I'm struggling to understand how this is functionally different to your example. 
Thanks

**Comment by Jedsters** [comment] 2023-01-14 10:49
Thanks. 
I obviously don't understand how this hangs together well enough to be able to update it myself yet, but that may be partly my problem.
 
Considering the following testing example (I'm just trying to understand in this example) from the current state:

![image](https://user-images.githubusercontent.com/96293240/212467688-2164a83d-7273-4307-ab08-cc5f86a333a5.png)

it seems that if SA goes 'Not Up' then O1, O2, O3 all go false as expected. However when SA then goes 'Up' O1 and O2 are now True! That looks like when the 'Active Condition' goes False, that causes O1 to go False which incorrectly triggers O2 to become True (despite the fact that the Active Condition is no longer True) It isn't detecting the difference between a LSW going false via an Active Condition which should gate all of the LSW at the same time and going false via an LSW. Surely when the Active Condition becomes true that should suspend all processing of gated LSW before further processing? It appears the logic is processing the Active Condition and LSW in the same cycle without checking if the Active Condition shouldn't allow it. 

Thanks!

**Comment by mawzthefinn** [comment] 2023-01-14 13:37
Nothing ever processes at the ‘same time’, they process  in sequence from top to bottom. Active Condition is part of the LSW processing, not separate from it. 

Stickies are also very unique in terms of how  Active Conditions are handled. See the manual note above. The Active condition is merely forcing the state change, the logic continues to operate in the background. Think of the state of the LSW to be its output, and the processing sequence to be from top to bottom of the settings for the LSW. All the logic continues to operate regardless of the Active Condition, but the !SAup state forces the output to false until it changes.

**Comment by Jedsters** [comment] 2023-01-14 14:18
Thanks! The sentences "Think of the state of the LSW to be its output, and the processing sequence to be from top to bottom of the settings for the LSW. All the logic continues to operate regardless of the Active Condition, but the !SAup state forces the output to false until it changes." explains a lot. I'd worked out the processing was top to bottom, but I didn't know it worked as per the 2nd sentence. I'd recommend something like that for the manual. As you may have worked out, I was thinking that the Active Condition stopped all processing for the LSW.

Some of the above may make more sense to me now - I'll need to have a re-read and play.

Again, thanks for your patience.

**Comment by mawzthefinn** [comment] 2023-01-17 19:36
Closing the issue off as explanation and answers are provided. Will address manual update

**Closed by mawzthefinn** 2023-01-17 19:36 UTC
