### ISSUE TITLE
1.0.10 RC1 Home Screen Telemetry MAX doesn't work with Neuron ESC

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#567] opened 2021-07-01 07:35 UTC
Have discovered all Telemetry values new - then in "config screen" all values added - long press enter - MAX 
X20S EU / **Neuron ESC** 
MAX Value for RPM / Current / SBEC V / Sbec A doesn't work
Also I'm somehow confused about the RPM displayed from the Neuron ESC - I use a 18 Pole Outrunner - with OTX on Horus 10 it was diplayed RPM x 1/2 Poles - so in OTX in Telemetry Number for Blades input 9 but with ETHOS there is something displayed like 1/8 of real RPM (without adding some factor into Telemetry - 1 Balde / Gear 1 -1) confused
With flydruino KISS ESC MAX / RPM works perfect (there Poles of motor are adjusted in ESC)

**Comment by Hobby4life** [comment] 2021-07-01 08:40
> Have discovered all Telemetry values new - then in "config screen" all values added - long press enter - MAX
> X20S EU / **Neuron ESC**
> MAX Value for RPM / Current / SBEC V / Sbec A doesn't work
> Also I'm somehow confused about the RPM displayed from the Neuron ESC - I use a 18 Pole Outrunner - with OTX on Horus 10 it was diplayed RPM x 1/2 Poles - so in OTX in Telemetry Number for Blades input 9 but with ETHOS there is something displayed like 1/8 of real RPM (without adding some factor into Telemetry - 1 Balde / Gear 1 -1) confused
> With flydruino KISS ESC MAX / RPM works perfect (there Poles of motor are adjusted in ESC)

Duplicate of #559 and #563

**Closed** 2021-07-01 10:00 UTC
