### ISSUE TITLE
Ethos suite for linux

### ISSUE THREAD

**Issue by carlogianneschi** [FrSkyRC/ETHOS-Feedback-Community#1726] opened 2022-06-10 06:34 UTC
Hello, is possible to recompile the Ethos suite for linux?

**Comment by bsongis-frsky** [comment] 2022-06-10 13:31
Which Linux?

**Comment by carlogianneschi** [comment] 2022-06-10 18:41
Ubuntu

Il 10/06/22 15:31, Bertrand Songis @ FrSky ha scritto:

**Comment by Jamest95max** [comment] 2022-06-11 03:24
And Linux mint if possible, app image would be the easiest for the user

**Comment by dystechnic** [comment] 2022-06-18 14:29
Arch Linux please.
But an appimage will do also.

**Comment by CoyotteDundee** [comment] 2022-06-20 16:48
Hello,
You can add me to the Linux User count...
As a long time OpenTx user, I cannot imagine switch to Ethos without a Linux version of the Ethos Suite :-)
(I just tried the Window$ version under Wine but it crashed at start)
Any version that could be run on latest Mint / Ubuntu will be fine.
Thanks by advance,

Coyotte

**Comment by darkernoise** [comment] 2022-07-25 02:38
Another request for a deb package of the Ethos Suite.  Linux Mint user here.

**Comment by tysonfromcanada** [comment] 2022-08-24 01:31
+1 for linux for suite + simulator for some lua scripting work

**Comment by Jamest95max** [comment] 2022-11-10 20:49
Hello, is there any news on this, ethos suite on linux, are there any developments, unless i have missed something there seems to me no one willing to do this, will i get a reply i really would appreciate one
thanks.

**Comment by bsongis-frsky** [comment] 2022-12-02 17:26
Duplicate of #1576

**Closed by bsongis-frsky** 2022-12-02 17:26 UTC
Labels: suite

**Comment by bytedicer** [comment] 2023-05-19 09:25
+1 Count me in!

**Comment by elliopitas** [comment] 2026-04-08 17:00
I am using arch and fedora.
I have the tandem x20R
