### ISSUE TITLE
Hf Firmware Problem X20pro 

### ISSUE THREAD

**Issue by Boxxxer64** [FrSkyRC/ETHOS-Feedback-Community#2985] opened 2023-10-19 11:59 UTC
Receiver TWGr6 with 1.05 firmware servos run jerkily. With firmware 1.03 everything works normally. transmitter x20pro. No newer HF firmware available for x20pro.

**Comment by Boxxxer64** [comment] 2023-10-19 12:12
Look like same here #2952

**Comment by mawzthefinn** [comment] 2023-10-19 12:34
Yes, duplicate of #2952 

Please continue discussion there

**Closed by mawzthefinn** 2023-10-19 12:34 UTC
Labels: duplicate, RF issue
