### ISSUE TITLE
Ethos 1.5.0 RC7 Spektrum telemetry sensors missing with multi protocol module

### ISSUE THREAD

**Issue by rwijnhov** [FrSkyRC/ETHOS-Feedback-Community#3509] opened 2024-02-27 10:17 UTC
Ethos 1.5.0 RC7 Spektrum telemetry sensors missing with multi protocol module. 
I get all the Rx telemetry. But it won't show the esc telemetry like voltage of the pack and power draw. It works on opentx, edgetx and ersky so it.has to do with the opentx implementation.

I am missing
telemetry from the ESC:
RPM
Voltage (FASV)
Current (Amps)
BEC temperaure (TEMP2)
BEC current (SBCA)
BEC voltage (SBCV)
AccX, AccY and AccZ

[SPM_Telemetry_Developers_Specs.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14417919/SPM_Telemetry_Developers_Specs.pdf)

**Comment by RealTadango** [comment] 2024-02-27 13:31
You must update the multi lua script, but it is not released yet. @bsongis-frsky said it should be in the 1.5 branch but it is not. I am also waiting for this to be released....

**Comment by bsongis-frsky** [comment] 2024-02-29 08:42
Duplicate of #3326

**Closed by bsongis-frsky** 2024-02-29 08:42 UTC
