### ISSUE TITLE
Ethos 1.5.0 Emergency Mode when setting up TD SR18 X20Pro

### ISSUE THREAD

**Issue by Joetrin** [FrSkyRC/ETHOS-Feedback-Community#3543] opened 2024-03-03 14:32 UTC
Created a new plane (120cc Skywing Yak54) using the new model wizard
Specified 4 ailerons, 2 Elevators, 1 Rudder, 1 throttle
Mode 1 on Channel 14 / Mode 2 on Channel 15 / Gain on Channel 13 
Registered the TD SR18
Flashed new firmware on TDSR18
Reboot RX
Bound TDSR18
Clicked on options
Verified all ports vs Channels
Backed out to System in order to run the calibration function
Went back into the Options on TDSR18 to verify ports vs channels
Plug in HV Servos (Bluebird M55) outside of the aircraft
Backed out and went into the system / SRX Stab menu
Ran Self test (forgot the name) function on page 1
Ran Self Test on Page 2 (this is needed for all stab functions to run

While running the self test, the radio went into "Emergency Mode".. 

Note: It happened once, and could not repeat.

**Comment by bsongis-frsky** [comment] 2024-03-03 21:09
Have you checked the Model / Mixes menu with the View per Channel?

**Comment by Joetrin** [comment] 2024-03-03 21:10
Yes I did, I forgot to mark that in one of the steps.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsongis-frsky** [comment] 2024-03-03 21:16
Perfect, because it explains the issue!

**Comment by bsongis-frsky** [comment] 2024-03-03 21:16
Duplicate of #3545

**Closed as completed by bsongis-frsky** 2024-03-03 21:16 UTC
