### ISSUE TITLE
Ail, Ele and Rud Mixer Outputs without Trim

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#2069] opened 2022-11-10 11:30 UTC
When the output from a main control function (Ail, Ele, Rud) is used as input for another mixer, the trim must normally be disabled. I take the Snap-Flap as an example, where the corresponding pre-defined mixer does not use the Ele trim, which is corrrect.
A problem occurs if different weights/expo settings are specified within the Ele mixer, as these are not applied to the input of the Snap-Flap mixer. It is necessary to replicate these settings in the Snap-Flap mixer, with the additional problem that multiple weight settings are not possible. Hence a complex mixer construct becomes necessary in order to make Snap-Flap work as expected, i.e. taking into account all weight/expo settings of the Ele mixer but not using the Ele trim.

The above problem would go away if there was an output from each of the Ail, Ele and Rud mixer that takes into account all weight/expo settings but does not contain the trim. Similar functions that would benefit from such an enhancement are the Ail -> Rud, Rud -> Ele and Rud -> Ail mixers, generally all mix functions using one of the main controls as input.

**Comment by strgaltdel** [comment] 2022-11-14 15:55
I have done some similar considerations.

My idea was:

- add a class (e.g. "Inputs").
- add a "bool switch" before the "number of channels" line in the mixer menus.
- This switch would "publish an input entity" that could be used by mixers, Lua, LSWs, etc.

In the end, I disagreed with myself that this approach would be simple enough for normal users,
(for complex models)
perhaps a special mixer with a "self-organised" naming convention would be a more understandable solution for "the public".
These "input mixers" could be used for all kinds of applications, I think ethos provides enough mixer entries even for complex models.

Something like a "label" for organizing / filtering Mixers would have been a great addition. 


... just my 2 cents


greetings 
Udo

**Comment by mawzthefinn** [comment] 2022-11-25 03:01
The proposed solutions to #752 would address these gaps, this really is a duplicate of that issue in terms of the underlying fix.

**Comment by Hartinger** [comment] 2022-11-25 06:58
I agree, provided we talk about the proposed Solution **2** to #752.
(Solution 1 implies that you would have to replicate the weight/curve settings for the secondary mix.)

**Comment by mawzthefinn** [comment] 2022-11-25 13:20
In that case, please make the comment in support of Solution 2 over there and we can close this issue off as a duplicate.

**Comment by Hartinger** [comment] 2022-11-25 14:16
Yep, no problem with that.

**Closed** 2022-11-25 15:27 UTC
Labels: duplicate
