### ISSUE TITLE
GPS speed has no relationship to actual 

### ISSUE THREAD

**Issue by miggy1952** [FrSkyRC/ETHOS-Feedback-Community#3971] opened 2024-05-03 16:46 UTC
Latest EU firmware, X18S, Matek GPS running latest INAV.

when I fly LOS I have speed set up on my Tx but it is totally random. Speed displayed on OSD is accurate and plausible

**Comment by miggy1952** [comment] 2024-05-05 01:26
This may be the same thing as Ethos 1.5.6 with ELRS wrong telemetry value for GPS Speed #3919

**Comment by bsongis-frsky** [comment] 2024-05-06 17:02
#3919 is after ELRS GPS Speed, do you use CRSF protocol (ELRS or Crossfire) with your latest INAV / Matek GPS?

**Comment by bsongis-frsky** [comment] 2024-05-06 17:02
Perhaps you can have a quick check o the latest 1.5.8 nightlies to see if it fixes your problem?

**Comment by miggy1952** [comment] 2024-05-07 06:04
Yes using ELRS CRSF into a flight controller running INAV

**Comment by bsongis-frsky** [comment] 2024-05-07 09:46
Duplicate of #3919 then!

**Closed as completed by bsongis-frsky** 2024-05-07 09:46 UTC
Labels: information needed
