### ISSUE TITLE
[Ethos Suite] [Enhancement] Posibility to update firmware files for receivers via Ethos Suite

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#1652] opened 2022-05-12 18:18 UTC
As it is already possible to update to a newer Ethos Version with Ethos Suite and it it possible to update the audio files, I would like to have the option to update/copy the actual firmware of all the receivers.

If I get a new receiver or maybe people convert to Ethos from openTX it is recommended to check the firmware version of the receivers.
New receivers have to get bound anyway and it would be great to have the firmware files already on the transmitter.

I like to bind a receiver and then update it right after.
Until now I have to go to the FrSky page and load the firmware from every receiver manually one by one.

So a button to update the firmware files from receivers automatically would save a lot of work and it does not matter which receiver U buy next, the right firmware would be already on my transmitter and updating those files would be easy, too.

**Comment by pld74** [comment] 2022-05-13 11:19
> As it is already possible to update to a newer Ethos Version with Ethos Suite and it it possible to update the audio files, I would like to have the option to update/copy the actual firmware of all the receivers.
> 
> If I get a new receiver or maybe people convert to Ethos from openTX it is recommended to check the firmware version of the receivers. New receivers have to get bound anyway and it would be great to have the firmware files already on the transmitter.
> 
> I like to bind a receiver and then update it right after. Until now I have to go to the FrSky page and load the firmware from every receiver manually one by one.
> 
> So a button to update the firmware files from receivers automatically would save a lot of work and it does not matter which receiver U buy next, the right firmware would be already on my transmitter and updating those files would be easy, too.

Love this idea!!!

**Comment by mawzthefinn** [comment] 2022-05-14 12:37
Agreed, and I’ve requested this in the past as well.

**Comment by bsongis-frsky** [comment] 2022-05-16 08:03
Right, I also think Suite can simplify life for users more & more. New features will be added during the next weeks

**Comment by Dsrenger** [comment] 2022-12-03 16:54
Comment, as it is still a good idea.

**Comment by arshish1612** [comment] 2023-01-19 05:04
Absolutely. This is a must have feature. Can this please be fast tracked @bsongis-frsky ?

**Comment by mawzthefinn** [comment] 2023-02-02 21:54
Duplicate of #1568 closing in favour of the older issue

**Closed by mawzthefinn** 2023-02-02 21:54 UTC
Labels: duplicate, suite
