### ISSUE TITLE
Capacity Sensor for FAS40/100 and 150 missing

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#298] opened 2021-05-21 14:46 UTC
Customers inform us about that thes missing the following (current) sensors, the sensor for "withdrawn battery capacity" in mAh is missing in the Tandem X20, presumably also with the X10 and X12.

FrskY 40 A current sensor FAS40
FrSky 100 A current sensor FAS100
FrSky 150 A current sensor FAS150

**Comment by bsongis-frsky** [comment] 2021-05-21 15:14
Duplicate of #4

**Closed by bsongis-frsky** 2021-05-21 15:14 UTC
