### ISSUE TITLE
Using a Source ideas

### ISSUE THREAD

**Issue by bbdmarch** [FrSkyRC/ETHOS-Feedback-Community#1019] opened 2021-09-30 20:47 UTC
I've been looking at the mixers and by accident came across using a source for a weight/rate/expo/differential etc and had a fun time making some interesting graphs.... little things, I know!

However, as a means of fine tuning differential/expo/rates/weight etc, it's a brilliant tool. However I've had a couple of ideas for it....

1. In the special functions section have the option to convert the sources to a value across all/some of the mixes as it would be time consuming to do it individually to all mixes.

2. Using a free mix you can limit/add a curve to the source by adjusting the weights, adding a curve etc so limiting the amount of effect the source has on the weight/rate/expo/differential etc.  Could a limiter be added into the source option when selecting??

3. Using a source in conjunction with a fixed value...  For example, you set a fixed expo of 20% and have a source that allows for a 10% adjustment of this, allowing the expo to be between 10% and 30%, again to allow for fine tuning

Although I've added three ideas, I'd personally like to see options 1 & 3 implemented, as option 2 can be done by adding additional mixes.

**Comment by centertrim** [comment] 2021-10-01 13:06
Change your source to use a Channel instead of an Analog (use a virtual channel like channel 64 or something).  Then add a free mix on that virtual channel you selected to manipulate/limit the value of the analog you want to use as your adjuster.  If you want to fix the value later on (request #1), then just set the free mix to a fixed output instead of using an analog as a source.

**Comment by hrenz** [comment] 2021-10-01 19:16
Analog sources first bring -100% to +100%.
This is usually too much and deadly for the model.

Therefore you have to preprocess this source with an auxiliary mixer to get the desired setting range e.g. 0% to 30%.

Only then you can use this auxiliary mixer as an analog source.

to simplify this there are already the first drafts

**Comment by bsongis-frsky** [comment] 2021-10-04 09:51
This is duplicate of the big "Global Vars" issue opened here

**Closed by bsongis-frsky** 2021-10-04 09:51 UTC
