### ISSUE TITLE
Ch7/8/9 under SRX Stab cannot be disabled for new SR receivers

### ISSUE THREAD

**Issue by LeoCheung123** [FrSkyRC/ETHOS-Feedback-Community#3077] opened 2023-11-22 11:40 UTC
Channels 5/6 can disabled by changing the selection to Aux1/2 on the Srx Stable script. 

So can channels 10/11.

But not channels 7,8,9?

Sure the second bank can be turned off entirely. But for many larger turbine jets we need rudder2 for separate nose steering gains, and other channels for non-corrected things like smoke and brakes etc.

Same problem under TWsr12, and archer plus sr receivers. 
X20S. 
All latest firmware as of november 2023.

**Comment by mawzthefinn** [comment] 2023-11-22 14:13
This is how Basic mode works. It's two sets of the same basic stabilizer feature. 

On the 12 and 18 port receivers, the RB25S and RB35S you can run ADV mode and select exactly which channels are stabilized and how. This is setup with the RBMIxer app which was recently works

This is a duplicate of #2824 which is addressed the same way. Closing tihs off as a duplicate

**Closed by mawzthefinn** 2023-11-22 14:13 UTC
Labels: duplicate

**Comment by LeoCheung123** [comment] 2023-11-24 01:22
Maws…fwiw almost all of the new EDF jets made by FMS or Freewing have thrust reverse default on channel 7. All the new gyro receivers are of the SR type with channel 7 active by default. I had a crash three months ago which I suspected on a faulty esc or poor reverse thrust programming…now i have an another theory. Did the beta testers not say a thing when the defaults were set?  Or did they spend time instead on the ever popular omnipresent knife edge and hover mode settings?!!!!!!On 22 Nov 2023, at 22:14, mawzthefinn ***@***.***> wrote:﻿
Closed #3077 as not planned.
