### ISSUE TITLE
Screen navigation proposal

### ISSUE THREAD

**Issue by Tomppy** [FrSkyRC/ETHOS-Feedback-Community#2259] opened 2022-12-29 09:29 UTC
It would be cool to be able to navigate in the differents screens of a model with sliders.
As I d'ont have all information on the same screen because I want few widgets per screen, if I want to have a quick look to check something It would be nice to be easily able to switch screen with the handy sliders

**Comment by mawzthefinn** [comment] 2022-12-29 13:50
That would be possible with #652 so  this is a duplicate of that in terms of implementation. Please post in support of that issue.

**Closed by mawzthefinn** 2022-12-29 13:50 UTC
Labels: duplicate

**Comment by Tomppy** [comment] 2022-12-29 14:26
ok thanks!
