### ISSUE TITLE
Delay in telemetry data

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#323] opened 2021-05-24 04:34 UTC
There seems to be a significant delay of several seconds in receiving the esc telemetry data. E.g. if throttle set to max it takes several second before the max current data and rpm data is achieved and viceversa when throttled closed takes several second to reach zero. Tested on a couple of my different telemetry Esc's. Using access receiver, x20s and ethos 1.07

**Comment by bsongis-frsky** [comment] 2021-05-24 08:13
There is no reason Ethos introduces a delay! I will tag this issue as RF

**Comment by aalain8** [comment] 2021-05-24 12:14
I confirm the problem. 
When we switch off the receiver we get a lost telemetry announcement after 5s
With opentx it takes 1.5s

**Comment by bsongis-frsky** [comment] 2021-05-24 14:07
Closed by mistake, the issue is valid

@aalain8 "Telemetry lost" has nothing to see with the @islandflight issue, and the timeout is 5 seconds on purpose, anything wrong with this timeout value?

**Comment by aalain8** [comment] 2021-05-24 14:33
You are right, I got confused because of the translation.
For the delay if shortening it to 1 or 2s would not be a problem it would be better.
Thank you very much.

**Comment by islandflight** [comment] 2021-05-24 21:28
I have been doing further testing. The delay is not present when using open tx, therefore suggesting if it is an rf issue then it must be the x20 rather than the receivers.

There is no delay in current capacity when using a  yge esc which report 'current' telemetry data at address 
12 0200 (ISRM Rx0). The delay seems to be occurring at 'esc current' at address 00 0B50 (ISRM Rx0).

Hope this may help in solving the problem?
Thanks

**Comment by Adelaxie** [comment] 2021-05-26 01:07
being discussed in other respository.
https://github.com/FrSkyRC/Firmware-Test/issues/121
so keep ETHOS only here

**Closed by Adelaxie** 2021-05-26 01:07 UTC
Labels: RF
