### ISSUE TITLE
Touch area in upper left corner of screen too small 1.5.11

### ISSUE THREAD

**Issue by pmullen503** [FrSkyRC/ETHOS-Feedback-Community#4255] opened 2024-07-12 00:49 UTC
Since upgrading my X18 and X20RS from 1.5.9 to 1.5.11 the touch spot for the menu return arrow has gotten smaller and moved to the left. So much so it seems like I have to hit the border of the screen to actuate the return arrow.

It went back to normal on both TXs when I retrograded to 1.5.9.

**Comment by bsongis-frsky** [comment] 2024-07-12 05:16
Duplicate of #4248

**Closed as completed by bsongis-frsky** 2024-07-12 05:16 UTC
