### ISSUE TITLE
Ethos Suite always reports 'errors'

### ISSUE THREAD

**Issue by Billy60** [FrSkyRC/ETHOS-Feedback-Community#1675] opened 2022-05-18 09:56 UTC
Good morning,
Ethos suite never can update anything. The latest version is installed (W10) for a X10 Exp and whenever I ask for some updating it answers "error transferring xxxfile" it is Firmware file or Model file or image file. Never works.
Please advise how to use that Suite because it would be very useful.
Thanks

**Comment by bsongis-frsky** [comment] 2022-05-18 10:09
Duplicate of #1672 
1.2.6 / 1.2.7 don't work very well for Horus radios, the fix is ready for 1.2.8

**Closed by bsongis-frsky** 2022-05-18 10:09 UTC

**Comment by Billy60** [comment] 2022-05-18 12:15
Thanks Bertrand, you are the best !
