### ISSUE TITLE
sensor:value(OPTION_CELL_COUNT) will not work in Version 1.1.3 X20S Simulator

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#1552] opened 2022-03-27 10:48 UTC
Error in sensor:value(OPTION_CELL_COUNT) function
no longer delivers the number of Lipo cells but volts

**Comment by Benno00** [comment] 2022-03-27 12:15
this works for CELL Count sensor:member(OPTION_CELL_COUNT)
Returns the number of cells
these functions no longer work either
the voltage of the LIPO is always supplied
sensor:value(OPTION_CELL_INDEX(i)) sensor:stringValue(OPTION_CELL_LOWEST)
sensor:stringValue(OPTION_CELL_HIGHEST)

**_here my source_**
local sensor = system.getSource("LIPO")
print("Name:"..sensor:name())
print("Member:"..sensor:member())
print("Value:"..sensor:value())
print("stringValue:"..sensor:stringValue())
print("rawValue:"..sensor:rawValue())
print("CELL count:"..sensor:value(OPTION_CELL_COUNT))
print("CELL Lowest:"..sensor:stringValue(OPTION_CELL_LOWEST))
print("CELL Highest:"..sensor:stringValue(OPTION_CELL_HIGHEST))
for i=1,sensor:member(),1 do
	print("CELL "..i.." Volt:"..sensor:value(OPTION_CELL_INDEX(i)))
end

**_here my output_**
Name:LIPO
Member:6.0
Value:19.2
stringValue:19.20V
rawValue:1920
CELL count:19.2
CELL Lowest:19.20V
CELL Highest:19.20V
CELL 1 Volt:19.2
CELL 2 Volt:19.2
CELL 3 Volt:19.2
CELL 4 Volt:19.2
CELL 5 Volt:19.2
CELL 6 Volt:19.2


and here from the Version 1.1.0
**_my source_**
local sensor = system.getSource("LIPO")
print("Name:"..sensor:name())
print("Value:"..sensor:value())
print("stringValue:"..sensor:stringValue())
print("rawValue:"..sensor:rawValue())
print("CELL count:"..sensor:value(OPTION_CELL_COUNT))
print("CELL Lowest:"..sensor:stringValue(OPTION_CELL_LOWEST))
print("CELL Highest:"..sensor:stringValue(OPTION_CELL_HIGHEST))
for i=1,sensor:value(OPTION_CELL_COUNT),1 do
	print("CELL "..i.." Volt:"..sensor:value(OPTION_CELL_INDEX(i)))
end
**_my outputs_** 
Name:LIPO
Value:19.2
stringValue:19.20V
rawValue:1920
CELL count:6.0
CELL Lowest:3.20V
CELL Highest:3.20V
CELL 1 Volt:3.2
CELL 2 Volt:3.2
CELL 3 Volt:3.2
CELL 4 Volt:3.2
CELL 5 Volt:3.2
CELL 6 Volt:3.2

**Comment by bsongis-frsky** [comment] 2022-03-28 19:53
Duplicate of #1547

**Closed by bsongis-frsky** 2022-03-28 19:53 UTC
