### ISSUE TITLE
Emergency mode on function

### ISSUE THREAD

**Issue by ronron84** [FrSkyRC/ETHOS-Feedback-Community#4263] opened 2024-07-12 16:24 UTC
Hi,

When open the function menu, i've got a red triangle in the top left of the screen and if i touch it i go directly in emergency mode... see picture below

![20240712_181418](https://github.com/user-attachments/assets/2ec39bc4-83b4-4458-b389-3a3c6efdc056)
![20240712_181427](https://github.com/user-attachments/assets/b8186809-a3ce-4001-b40d-f9ebde63e5d8)
My radio is Tandem x20 i've got the same issue with 1.5.10 and 1.5.11 
thanks for your help

**Comment by strgaltdel** [comment] 2024-07-12 18:00
maybe some more infos for the devs would be helpful.
(clicking on the alarm icon typically doesnt force an em)
detailed infos about what caused the alarm icon / triangle can be seen under system / info

most probably a lua error.

upload of the model can even be helpfull

**Comment by ronron84** [comment] 2024-07-12 18:25
[mytho s50 e.zip](https://github.com/user-attachments/files/16197994/mytho.s50.e.zip)
here is the file there is no lua used in this model only sounds

**Comment by bsongis-frsky** [comment] 2024-07-12 20:19
I will need your radio settings too (radio.bin) as I cannot reproduce with just the model and it seems you have a lot of global functions!

**Comment by bsongis-frsky** [comment] 2024-07-12 21:23
I would need your Lua scripts too, even if not used in this model. Perhaps one is filling your memory with a lot of errors that cannot be displayed!

**Comment by ronron84** [comment] 2024-07-13 06:37
HI Bertrand,
Here is the link https://we.tl/t-5hfUfVWNg4

I found out that the warning diseapered if i erase the line playing sequences sounds named SJ  in Mythos 50 e functions.

**Comment by bsongis-frsky** [comment] 2024-07-15 08:54
I reproduce the crash on simulator with your ZIP file

**Comment by bsongis-frsky** [comment] 2024-07-15 09:39
It will be fixed in the next nightlies

**Closed as completed** 2024-07-15 09:39 UTC

**Comment by ronron84** [comment] 2024-07-15 10:56
thanks :-)
