### ISSUE TITLE
Ethos 1.5.12 will not recognize my X20S

### ISSUE THREAD

**Issue by rits68** [FrSkyRC/ETHOS-Feedback-Community#4876] opened 2024-12-15 04:45 UTC
I tried connecting my X20S earlier to Ethos (I first placed the unit in bootload mode and then connected the device to my Mac computer, with Ethos suite 1.5.12 running)).   It seems that the system first recognized my unit as an X20s (as shown within the "Radio-Ethos" box), but I received the  message, "the disk you attached was not readable by this computer".   Now after various attempts to reconnect my unit, I then disconnected it from my computer and shut it off.   Now, when trying to turn the X20s back on, the power will not turn back on. It will only turn on it bootloader mode -- again, Ethos does not recognize it, nor will the "Finder" (Mac's explorer version) show that it is connected.  I checked the battery and it is fully charged.  Any thoughts on what this may be, and how to fix?   Thanks in advance,

**Comment by mawzthefinn** [comment] 2024-12-15 16:09
Known issue with recent MacOS, version 15.2 seems to resolve it for most users 

duplicate of #4526

**Closed as completed by mawzthefinn** 2024-12-15 16:09 UTC
Labels: duplicate

**Comment by rits68** [comment] 2024-12-15 23:58
Hi.  I was able to use Mac’s disk utility to successfully mount the drives for my X20 S after I sent my initial email.  But the other problem remains in that I can initialize the bootloader when turning on my device, but the device no longer turns on by itself if I was just to hit the power button (ie the X20s only turns in in bootloader mode).   I was wondering if it had to do with the version of Ethos, or whether the upgrade thru Ethos may have somehow compromised my device?  I’m looking for some ideas on how to troubleshoot this problem for a Tandem system that I’ve had for two years having had no issues before.   Thanks in advance. Sent from my iPhoneOn Dec 15, 2024, at 11:09 AM, mawzthefinn ***@***.***> wrote:﻿
Known issue with recent MacOS, version 15.2 seems to resolve it for most users
duplicate of #4526

**Comment by mawzthefinn** [comment] 2024-12-16 01:42
ETHOS only booting in bootloader mode are symptoms of trying to upgrade ETHOS with an old bootloader and a version of ETHOS Suite before 1.5.6

First off check your bootloader version in the upper right corner of the display. If nothing is reported there, or it's older than 1.4, you'll need to update both ETHOS and the bootloader, if it's 1.4.something, you just need to get ETHOS 1.4.15 on the radio. 

Manually install ETHOS 1.4.15 by downloading it from here:

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.4.15

Unzip, put teh firmware.bin file on the SD card of your radio and reboot in bootloader mode, it will auto install.

If updating the bootloader as well, download it from the same link above, unzip and put it on the SD card next to radio.bin

After updating ETHOS, go to System->File Manager, tap on the bootloader.frsk file and select flash bootloader. 

Then manually install ETHOS Suite 1.5.12 and use that to update your radio to latest (this will also fix any missing icons or audio files)

You still likely will have to manually force mount the drives in Disk Utility, that's a Mac issue unrelated to your other issue.

**Comment by rits68** [comment] 2024-12-17 04:04
Hi. Bootloader is version 1.4.3). This is the version I used when trying to upgrade the radio and IRan into problems.  Is there something more recent than 1.4.3?  What I’ve done subsequently was to upgrade Ethos Suite to 1.5.12. I can’t remember  if I did this upgrade before or after trying to upgrade the radio itself.  Does that matter? Other questions: -when uploading the new firmware.bin file, do I need to rename or delete the old version first?-if I need to upgrade bootloader and firmware.bin, does it matter which one is done first (ie should I upgrade bootloader first)?-inYourParagraph Where you say, “After updating Ethos, go to system>file manager, tap on the bootloader.frsk file and select flash bootloader..”. —- I take it you are referring to finding the bootloader.frsk file which is found through my Finder app(I’m using a Mac)?     Same para- where does “flash bootloader” command show?Sorry for all these questions but I wanted to make sure I do everything correctly and it’s been quite a longTime since I’ve done these updates. Thanks in advance for your assistance and patience. Sent from my iPhoneOn Dec 15, 2024, at 8:43 PM, mawzthefinn ***@***.***> wrote:﻿
ETHOS only booting in bootloader mode are symptoms of trying to upgrade ETHOS with an old bootloader and a version of ETHOS Suite before 1.5.6
First off check your bootloader version in the upper right corner of the display. If nothing is reported there, or it's older than 1.4, you'll need to update both ETHOS and the bootloader, if it's 1.4.something, you just need to get ETHOS 1.4.15 on the radio.
Manually install ETHOS 1.4.15 by downloading it from here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.4.15
Unzip, put teh firmware.bin file on the SD card of your radio and reboot in bootloader mode, it will auto install.
If updating the bootloader as well, download it from the same link above, unzip and put it on the SD card next to radio.bin
After updating ETHOS, go to System->File Manager, tap on the bootloader.frsk file and select flash bootloader.
Then manually install ETHOS Suite 1.5.12 and use that to update your radio to latest (this will also fix any missing icons or audio files)
You still likely will have to manually force mount the drives in Disk Utility, that's a Mac issue unrelated to your other issue.

**Comment by rits68** [comment] 2024-12-17 04:09
Further question- for the link that you refer to, I presume that oneOf the files I need to upload is, X20S-fcc.zip.  Once unzipped, which of the many files do I download (is there an “English” file)?Thanks in advance. Sent from my iPhoneOn Dec 16, 2024, at 11:03 PM, Richard Lewczuk ***@***.***> wrote:﻿Hi. Bootloader is version 1.4.3). This is the version I used when trying to upgrade the radio and IRan into problems.  Is there something more recent than 1.4.3?  What I’ve done subsequently was to upgrade Ethos Suite to 1.5.12. I can’t remember  if I did this upgrade before or after trying to upgrade the radio itself.  Does that matter? Other questions: -when uploading the new firmware.bin file, do I need to rename or delete the old version first?-if I need to upgrade bootloader and firmware.bin, does it matter which one is done first (ie should I upgrade bootloader first)?-inYourParagraph Where you say, “After updating Ethos, go to system>file manager, tap on the bootloader.frsk file and select flash bootloader..”. —- I take it you are referring to finding the bootloader.frsk file which is found through my Finder app(I’m using a Mac)?     Same para- where does “flash bootloader” command show?Sorry for all these questions but I wanted to make sure I do everything correctly and it’s been quite a longTime since I’ve done these updates. Thanks in advance for your assistance and patience. Sent from my iPhoneOn Dec 15, 2024, at 8:43 PM, mawzthefinn ***@***.***> wrote:﻿
ETHOS only booting in bootloader mode are symptoms of trying to upgrade ETHOS with an old bootloader and a version of ETHOS Suite before 1.5.6
First off check your bootloader version in the upper right corner of the display. If nothing is reported there, or it's older than 1.4, you'll need to update both ETHOS and the bootloader, if it's 1.4.something, you just need to get ETHOS 1.4.15 on the radio.
Manually install ETHOS 1.4.15 by downloading it from here:
https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.4.15
Unzip, put teh firmware.bin file on the SD card of your radio and reboot in bootloader mode, it will auto install.
If updating the bootloader as well, download it from the same link above, unzip and put it on the SD card next to radio.bin
After updating ETHOS, go to System->File Manager, tap on the bootloader.frsk file and select flash bootloader.
Then manually install ETHOS Suite 1.5.12 and use that to update your radio to latest (this will also fix any missing icons or audio files)
You still likely will have to manually force mount the drives in Disk Utility, that's a Mac issue unrelated to your other issue.

**Comment by mawzthefinn** [comment] 2024-12-17 13:56
there should only be a firmware.bin file in the X20S-FCC.zip file. That's the one you need. YOu also need bootloader 1.4.15, which I provided instructions on how to install.

Please review the instructions I gave in order, the specific order matters, and they cover the questions you asked already. They are for the radio, not the Mac unless otherwise specified. System->File Manager is teh file manager app on the radio.

**Comment by rits68** [comment] 2024-12-17 19:40
So do I transfer all the files from the X20S-FCC.zip file to the radio as well as the firmware.bin file (because along with the firmware.bin file is an “I18n” folder with a whole bunch of of files)?  Or just the firmware.bin file that I use.    Sorry but I was confused when you referred to downloading Ethos 1.4.15 on the radio as there is also a version of Ethos suite which is 1.4.15 (but much older than the current 1.5.12.  Just wanting to clarify that you are referring to 1.4.15 radio Ethos as opposed to the suite.  

Thanks for your patience.

Richard Lewczuk
***@***.***
(M) 416-457-5125

**Comment by rits68** [comment] 2024-12-17 20:21
Please disregard the below email.   I EXPLICITLY followed your instruction, then unplugged my radio after transferring the bin and firmware files (My problem was that I saw more recent versions of the Ethos files on the internet which confused me).  In any event, the unit rebooted and my system is now up and running.    So I should be good to go from here.

Thanks for your help.


Richard Lewczuk
***@***.***
(M) 416-457-5125
