### ISSUE TITLE
X20RS Rotary Dial is Too Sensitive

### ISSUE THREAD

**Issue by BladeScraper-Designs** [FrSkyRC/ETHOS-Feedback-Community#4721] opened 2024-11-11 01:21 UTC
I notice a significant difference between my older radios (X18SE, X20S, X20 PRO, TW XLite, X10SE) and my new X20RS, the RS rotary encoder knob is much more sensitive than the other radios.  It acts jumpy, sometimes seeming to move values without intention.  It also seems to just scroll and accelerate much faster, too fast.

**Comment by teamdavey** [comment] 2024-11-11 01:29
Same issue with my new 20R

**Comment by rburrow87** [comment] 2024-11-11 01:35
Yes, my X20RS rotary dial can be frustrating. The rotary dial on my X18SE is much more consistent and easier to use.

**Comment by Cloudyifr** [comment] 2024-11-11 03:33
Same with my X20R. Nice radio but yes, very frustrating for sure.
Curtis

**Comment by RealTadango** [comment] 2024-11-11 07:01
TERRIBLE design choice. The encoder of the X20 was SO MCUH better, the R series feels like 2 steps back :(

**Comment by strgaltdel** [comment] 2024-11-11 09:20
duplicate of #4687 ?

**Comment by pmullen503** [comment] 2024-11-11 13:57
> duplicate of #4687 ?

Yes, it's the same problem. It still needs a fix.

**Comment by RealTadango** [comment] 2024-11-11 13:59
How can software fix a bad encoder? I don't see how that is even considerable.....

**Comment by BladeScraper-Designs** [comment] 2024-11-11 14:05
> How can software fix a bad encoder? I don't see how that is even considerable.....

Did you read my post in RCGroups?
"It could very well be that the implementation of debounce/step detection logic in Ethos simply doesn't work on this encoder the same way it does on the other ones, and a change to how that is handled in the R/RS firmware very likely can/will fix that."

If it is fixable in software, at least we have this GitHub issue so they know to try.  If not, well, then it's a hardware issue that needs addressed.  But having worked with rotary encoders in Arduino, I have first hand experience in knowing that different implementations of debounce, step-counting, and scroll acceleration can make or break an encoder's functionality.  

I'm not talking about mechanical differences here, that all comes down to personal preferences.  I'm talking about the behavior in software.

**Comment by BladeScraper-Designs** [comment] 2024-11-11 14:13
> duplicate of #4687 ?

Sorry, I did not realize there already was an Issue!

**Comment by Cloudyifr** [comment] 2024-11-11 14:19
If it's software I have confidence they'll address it, if it's hardware, I think we're out of luck.

**Comment by alb1661** [comment] 2024-11-11 15:13
+1  had two from amazon that I  returned because of this issue, hope it gets fixed on the new x18rs

**Comment by bsongis-frsky** [comment] 2024-11-12 09:36
Duplicate of #4687 
I need one unit to try to find a solution.
Debouncing is there, but perhaps it needs to be adapted to the new encoder!

**Closed as completed by bsongis-frsky** 2024-11-12 09:36 UTC
