### ISSUE TITLE
Odd mixing behaviour with "Sx" and "!Sx" mixing lines as active condition

### ISSUE THREAD

**Issue by jreis1** [FrSkyRC/ETHOS-Feedback-Community#902] opened 2021-09-04 23:35 UTC
I've a plane with flaps that sometimes I use as extended ailerons. My programing is as follows: 
- In SD switch, I have 3 flaps positions (e.g. 10,20,30 deg)
- In SC switch, I can select between normal flap mode or extended ailerons. 
To do so, in flap mixing entry, where I have several weights, I set the active condition to "!Sc". Then I use a free mixing entry, with active condition set to "Sc" to extend the ailerons.

In 1.0.9 this programing was working as expected! 

Now in 1.0.10, when I switch from normal flaps mode to extended aileron, my flaps go to the maximum amplitude and slowly go to center.  Also, if I swith from extended aileron to normal flap mode, my flaps go to the minumum amplitude and slowly go to center.  Please have a look at the video: https://youtu.be/40R1vlG5dhI

I believe it is something very similar to what is being described in #891 

I've noticed this only happens if I have 2 mixing entries, one with active condition set at "Sx" and other set at "!Sx".   If I use a different switch for both entries,  the max/min spike movement disappear.

**Comment by bsongis-frsky** [comment] 2021-09-07 20:34
Duplicate of #891

**Closed by bsongis-frsky** 2021-09-07 20:34 UTC
