### ISSUE TITLE
Should trims T1-T4 have option to disable fade

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2546] opened 2023-03-26 11:10 UTC
It appears that the physical trim switches T1, T2, T3, T4 fade when changing FM. This is of course entirely desirable much of the time, e.g. if changing from Normal to Thermal FM and they have different Elevator trim I want the trim to fade for a gradual transition of flight mode.

However, sometimes these trims are not used directly for control surfaces but repurposed, e.g. on a glider without a motor, the throttle trim may be repurposed for elevator compensation (as I believe per RC-Soars templates) and is now used as a weight. This now causes problems when the trim fades as we end up with a fade between 2 weights which can cause discontinuities in the control surface, e.g. jumping to a lower level before fading back up.

If there was an option on the Trims to disable fade on a per-trim basis hopefully this woud get around this problem.  Currently the Disable Step totally disables the Trim so it becomes unusable, maybe an extra option of Disconnect would be appropriate which would disconnect it from the output control surface and disable fading while leaving the trim producing a value which can be used e.g. as a weight?

Thanks

**Comment by mawzthefinn** [comment] 2023-03-26 13:48
A fade will not cause a jump in and of itself. 

A jump is indicative of a programming issue, where the FM going false is making the original value false and another value true before the new value for the new FM has finished fading in. This is typically due to  the inconsistent use of FMs or the FM’s controlling switches as selectors for values.

**Comment by Jedsters** [comment] 2023-03-26 15:04
Indeed I am using FMs to select values. The solution could therefore be to use the same trigger I use for a FM as the trigger to select the value, e.g if SA down selects Thermal then SA down could select the value as this would avoid the fade. But it seems that disabling fade in trims could bypass this requirement and allow a more intuitive selecting of a value from a FM rather than SW / LS.

**Comment by mawzthefinn** [comment] 2023-03-26 15:20
If you are purely tying values to FM’s directly, then you wouldn’t have this issue.

Disabling fade in trims won’t fix your issue, because it’s not the source of your issue. I’ve seen this issue quite a few times and it’s always due to the use of indirect or inconsistent value selection.

You have a situation here where one value is directly selected by FM’s and another one indirectly (or by something tied to say SA instead of the switch itself) and the the first one is changing immediately when the FM becomes false and that shifts the start point for  the fade.

**Comment by Jedsters** [comment] 2023-03-26 17:17
Your last para describes the situation. However I'm not sure I understand my cause yet. It feels like there is an element of Ethos allowing me to shoot myself in the foot by e.g. using a FM to change a value where it is inappropriate (e.g. in a 1.5.0 VAR?). If you have seen this a few times would it make sense to disable use of FM(?) where it could cause problems?
For now I'll change my selection via FM to the corresponding SW / LS which invokes the FM in the hope that fixes it.
Thanks.

**Comment by mawzthefinn** [comment] 2023-03-27 12:39
Closing off as the described issue is normal behaviour.

Whatever you do, be consistent. The jumps fundamentally come from having different values in one spot selected via inconsistent means. Either all on a switch, all on a referenced VAR or all directly by FM. Mixing these up will cause unexpected behaviour unless you work through all possibilities in advance.

**Closed by mawzthefinn** 2023-03-27 12:39 UTC
