### ISSUE TITLE
RB-25 + TD MX intermittent sensor loss

### ISSUE THREAD

**Issue by petermumford** [FrSkyRC/ETHOS-Feedback-Community#2629] opened 2023-05-05 20:18 UTC
### Versions
Ethos Version: 1.4.8
TD MX Firmware: 1.0.9

### Issue
I've wired the TD MX to use the S.Port which is configured to FBUS and then connected to the RB-25 RX1 port. I've also configured port 18 on the RB-25 to S.Port. I'm using port 18 to connect to my ECU's telemetry.

All is good and I receive all sensor data from the RB-25 and from the ECU. However, the sensors from the ECU is intermittent where it keeps dropping out. Please see video of what is happening.

### NOTE
I've tried a different receiver, a R10 Pro using ACCESS. The same setup as above, using the S.Port and changing to FBUS. And I don't get any issues, everything is stable. 

https://user-images.githubusercontent.com/331905/236559467-ea346d8c-5e3d-4112-82ea-ae9eaaf12481.mov

**Comment by RealTadango** [comment] 2023-05-08 09:58
I have the same issue with a TD-MX and RB10. I think TD telemetry needs some work. It works on the bench but when i fly it is terrible and losses sensors all the time.

**Comment by SmartTommy** [comment] 2023-05-09 09:12
could you configure your TDMX to S.PORT and connect to your ECU directly, and check if it works fine?

**Comment by petermumford** [comment] 2023-05-09 11:02
> could you configure your TDMX to S.PORT and connect to your ECU directly, and check if it works fine?

@SmartTommy - Just so I understood what you're asking, please confirm and I'll try tonight:

1. Use `SBUS out` on TD-MX and plug into RX1 port on RB-25
2. Change TD-MX config setting back to S.Port from FBUS
3. With the S.Port wire from TD-MX, plug into ECU telemetry port directly.

**Comment by petermumford** [comment] 2023-05-09 20:05
I can't do **Option 2** as I don't get any power from the telemetry port on the ECU

I can confirm doing **Option 1** works and all sensors seem stable from the ECU. However, doing this means I don't get any of the sensors from the RB-25. I tried using port 18 but nothing. Also, noticed I can't use the LUA config script either. I'm assuming this is something to do with not using the FBUS protocol anymore?

**Comment by petermumford** [comment] 2023-05-09 20:10
I can't do **Option 2** as I don't get any power from the telemetry port on the ECU.

I can confirm doing **Option 1** works and all sensors seem stable from the ECU. However, doing this means I don't get any of the sensors from the RB-25. I tried using port 18 but nothing. Also, noticed I can't use the LUA config script either. I'm assuming this is something to do with not using the FBUS protocol anymore?

Video showing **Option 2**
https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/331905/904077c6-81bc-4d8f-bd8a-9f300737ccf3

**Comment by SmartTommy** [comment] 2023-05-10 00:37
> I can't do **Option 2** as I don't get any power from the telemetry port on the ECU.
> 
> I can confirm doing **Option 1** works and all sensors seem stable from the ECU. However, doing this means I don't get any of the sensors from the RB-25. I tried using port 18 but nothing. Also, noticed I can't use the LUA config script either. I'm assuming this is something to do with not using the FBUS protocol anymore?
> 
> Video showing **Option 2** https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/331905/6daae7f1-8df2-46f5-84c2-235ebe35f025


thank you for your test. it seems the RF works noarmal, maybe there's something wrong with RB25

**Comment by SmartTommy** [comment] 2023-05-10 00:40
> ### Versions
> Ethos Version: 1.4.8 TD MX Firmware: 1.0.9
> 
> ### Issue
> I've wired the TD MX to use the S.Port which is configured to FBUS and then connected to the RB-25 RX1 port. I've also configured port 18 on the RB-25 to S.Port. I'm using port 18 to connect to my ECU's telemetry.
> 
> All is good and I receive all sensor data from the RB-25 and from the ECU. However, the sensors from the ECU is intermittent where it keeps dropping out. Please see video of what is happening.
> 
> ### NOTE
> I've tried a different receiver, a R10 Pro using ACCESS. The same setup as above, using the S.Port and changing to FBUS. And I don't get any issues, everything is stable.
> 
>  mov.mov

when  do this, you only connect one Receiver(TDMX) to the  RB25, there is nothing connect to the RX2 and RX3, is it?

**Comment by petermumford** [comment] 2023-05-10 13:51
> when do this, you only connect one Receiver(TDMX) to the RB25, there is nothing connect to the RX2 and RX3, is it?

Yes, only using one TDMX receiver in RX1 port

> thank you for your test. it seems the RF works noarmal, maybe there's something wrong with RB25. do you have any SPORT sensor produced by FrSky? could you connect the FrSky Sensors (instead of you ECU)to the configured port 18 on the RB-25 and check if the sensor works?

I reverted back to my original configuration, which I mentioned in my first post. I used a FLVS ADV Lipo sensor and everything is stable and works as expected.

However, I'm not sure why this would work as I also mentioned in my first post that I used a R10 Pro ACCESS receiver and everything worked as expected with the ECU sensors. 

Why does the ECU work with ACCESS but not with TD?

**Comment by SmartTommy** [comment] 2023-05-11 00:24
> However, I'm not sure why this would work as I also mentioned in my first post that I used a R10 Pro ACCESS receiver and everything worked as expected with the ECU sensors.
> 
> Why does the ECU work with ACCESS but not with TD?

I cannot determine the specific reason either，could you please send me your ECU manual and model, Maybe I need to buy one for testing.

**Comment by petermumford** [comment] 2023-05-11 10:42
> could you please send me your ECU manual and model

- Turbine
  - Swiwin 80b - https://www.sw-jet.com/
- Manual 
  - https://www.sw-jet.com/uploads/1/1/1/0/111064875/sw_manual.pdf
- Model
  - Swiwin V3 ECU

**Comment by petermumford** [comment] 2023-05-18 21:16
@SmartTommy I've just tried a TDR10 receiver. Firstly, I configured port 9 to FBUS and connected to RB-25 and I get the same issue where the senors are intermittent. Next, I configured port 10 to S.Port and connected the telemetry from the ECU to port 10 directly to the TDR10 receiver. Now the sensors are all stable.

So the conclusion is there an issue with the RB-25 sending the telemetry sensors, which are not produced by FrSky, via FBUS when using any TD receivers.

**Comment by SmartTommy** [comment] 2023-05-19 01:15
> @SmartTommy I've just tried a TDR10 receiver. Firstly, I configured port 9 to FBUS and connected to RB-25 and I get the same issue where the senors are intermittent. Next, I configured port 10 to S.Port and connected the telemetry from the ECU to port 10 directly to the TDR10 receiver. Now the sensors are all stable.
> 
> So the conclusion is there an issue with the RB-25 sending the telemetry sensors, which are not produced by FrSky, via FBUS when using any TD receivers.

thanks, I am seeking to purchase a sample and will update you as soon as there is progress

**Comment by MichaelETHOS** [comment] 2023-06-01 17:34
i have the same problems with the rb25s i use 2x tdrx in rx2 and rx3.  the telemetry sensor is configured on channel 18 and via the Lua on sport.  but the sponsor gets no signal.  after a restart, the sensor is lost.  @frsky I'm not your test pilot and I don't get paid for showing you the bugs in your products.  put their product on the market after they have tested it themselves.  I want to buy and use a product and not stand in the basement all year round.  Are you finally getting your products in such a way that you can use them after you buy them? I'm pissed off.

**Comment by SmartTommy** [comment] 2023-06-02 00:12
> i have the same problems with the rb25s i use 2x tdrx in rx2 and rx3. the telemetry sensor is configured on channel 18 and via the Lua on sport. but the sponsor gets no signal. after a restart, the sensor is lost. @frsky I'm not your test pilot and I don't get paid for showing you the bugs in your products. put their product on the market after they have tested it themselves. I want to buy and use a product and not stand in the basement all year round. Are you finally getting your products in such a way that you can use them after you buy them? I'm pissed off.

which one s.port senseor do you used? could you show us your connect？

**Comment by SmartTommy** [comment] 2023-06-02 00:37
> * Swiwin V3 ECU

@petermumford ，does the ECU will works if does not connect to the engine? i mean will the ECU telemetry data without the engine.

**Comment by MichaelETHOS** [comment] 2023-06-02 05:14
> > Ich habe die gleichen Probleme mit den RB25s, ich verwende 2x TDRX in RX2 und RX3. Der Telemetriesensor wird auf Kanal 18 und über Lua auf Sport konfiguriert. aber der Sponsor bekommt kein Signal. Nach einem Neustart geht der Sensor verloren.@frskyIch bin nicht Ihr Testpilot und werde nicht dafür bezahlt, Ihnen die Fehler in Ihren Produkten zu zeigen. bringen ihr Produkt auf den Markt, nachdem sie es selbst getestet haben. Ich möchte ein Produkt kaufen und nutzen und nicht das ganze Jahr im Keller stehen. Erhalten Sie Ihre Produkte endlich so, dass Sie sie nach dem Kauf nutzen können? Ich bin angepisst.
> 
> Welchen Anschlusssensor hast du verwendet? Könnten Sie uns Ihre Verbindung zeigen?

I use the xicoy Telemetrie Adapter.
I used the Same engine and Adapter in a other plane with sr10 pro Everything works fine.
Without fbus....
and now I'm doing her job of finding bugs again...I've had ethos x20 from the start and followed your strategy and it's still not finished.  and that annoys me that the community is doing their job

**Comment by SmartTommy** [comment] 2023-06-02 07:03
> and now I'm doing her job of finding bugs again...I've had ethos x20 from the start and followed your strategy and it's still not finished. and that annoys me that the community is doing their job

sorry about that. we will contact the manufacturer of the xicoy Telemetrie Adapter to figure out the problem and fix that.

**Comment by MichaelETHOS** [comment] 2023-06-02 16:03
https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/84266308/0838827a-32b5-4e33-82ad-d08f88ece2d5

Only click Option the rb25s send telemetrie

**Comment by MichaelETHOS** [comment] 2023-06-02 16:09
This was the Last Help for you do your Job an fix that...i will fly and Not Work for frsky..i pay a lot of Money and can't fly.

**Comment by SmartTommy** [comment] 2023-06-05 01:53
These two products are both third-party compatible products，they never contacted us and have not apply for the S.PORT protocol. i believe this is the reason for incompatibility.we tried to contact them, but there was no response,can you provide them to us or have them contact FRSKY if you have communication channels,

**Comment by MichaelETHOS** [comment] 2023-06-05 06:14
I sent gaspar an email to contact you

**Comment by T3chDad** [comment] 2023-06-22 22:38
I'm having the same issue with RB-25S and two TDMX.  While I need to use the RDT turbine telemetry adapter, the issue is not related to that specifically because I have issues with just the sensors integrated into the RB-25S and the FrSky GPS plus/v2 sensor.

- TDMX are both setup for FBUS.  Plugged into ports Rx1 & Rx2, HW: 1.5.0  FW: 1.0.8
- X20S FW: 1.4.8 FCC
- FrSky GPS v2
- RB-25S  Ports 17 and 18 configured for SPort

**Connections:**
![RB-25S Setup](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/5139966/875ce71b-345d-4733-b57f-e2f1cd1b884e)

I have intermittent detection and loss of most sensors.  I have not been able to establish a reliable pattern whatsoever.  Even if I don't have any external sensors connected, the RB-25 integrated sensors all exhibit the same intermittent behavior.  Sometimes I lose just a couple of the RB-25 sensors like the two batteries and one of the accels. Sometimes I lose them all.  Sometimes the GPS will work after power-up, sometimes not...same with the turbine telemetry.  The only sensors that never seem to fail are the  RSSI and VFR for both bands, and the RxBatt.

**Comment by i3dm** [comment] 2023-06-23 04:04
im the developer of Zavionix RDT and did some testing as well.
TD R10
RB 25S connected to Rx via sbus/s.port (2 cables)
RDT turbine telemetry connected to RB25S.

both RDT and RB25S data is coming from telemetry. no special issues.

i can not comment on other third part sensors. have only tested mine.

**Comment by i3dm** [comment] 2023-06-23 04:10
video of my test:

https://youtu.be/Pb0J4QLqM-o

**Comment by MichaelETHOS** [comment] 2023-06-23 05:34
> Ich bin der Entwickler von Zavionix RDT und habe auch einige Tests durchgeführt. TD R10 RB 25S über SBUS/S.Port (2 Kabel) mit Rx verbunden . RDT-Turbinentelemetrie mit RB25S verbunden.
> 
> Sowohl RDT- als auch RB25S-Daten stammen aus der Telemetrie. keine besonderen Probleme.
> 
> Zu anderen Sensoren von Drittanbietern kann ich nichts sagen. habe nur meines getestet.

do you also make telemetry adapters for xicoy?

**Comment by RealTadango** [comment] 2023-06-23 05:58
I have a TD-MX with RB-10 and FAS-150 and have many sensor lost warnings. About 1 every 20 seconds. Never on the ground, only in flight.

**Comment by SmartTommy** [comment] 2023-06-25 00:36
We have conducted some testing and modifications, but due to our lack of third-party cooperation, we do not guarantee that this new program will fully address compatibility issues. We are also in contact with some third-party manufacturers, but have not replied yet.

[FrSkyRB25S_20230509.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11858477/FrSkyRB25S_20230509.zip)

**Comment by SmartTommy** [comment] 2023-06-25 00:39
> 

what is your RF version?EU or FCC ?

**Comment by MichaelETHOS** [comment] 2023-06-25 04:30
> > 
> 
> Was ist Ihre RF-Version? EU oder FCC?

I use EU

**Comment by SmartTommy** [comment] 2023-06-25 05:19
> > > 
> > 
> > 
> > Was ist Ihre RF-Version? EU oder FCC?
> 
> I use EU

hi,does the new RB25 firmware "FrSkyRB25S_20230509.frsk" works with your xicoy Telemetrie Adapter? we don't have the Adapter.

**Comment by T3chDad** [comment] 2023-06-25 15:27
> We have conducted some testing and modifications, but due to our lack of third-party cooperation, we do not guarantee that this new program will fully address compatibility issues. We are also in contact with some third-party manufacturers, but have not replied yet.
> 
> [FrSkyRB25S_20230509.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11858477/FrSkyRB25S_20230509.zip)

This RB-25S firmware resolved my issues.  I have stable telemetry from the RB-25S now.

**Comment by i3dm** [comment] 2023-06-25 15:33
> > Ich bin der Entwickler von Zavionix RDT und habe auch einige Tests durchgeführt. TD R10 RB 25S über SBUS/S.Port (2 Kabel) mit Rx verbunden . RDT-Turbinentelemetrie mit RB25S verbunden.
> > Sowohl RDT- als auch RB25S-Daten stammen aus der Telemetrie. keine besonderen Probleme.
> > Zu anderen Sensoren von Drittanbietern kann ich nichts sagen. habe nur meines getestet.
> 
> do you also make telemetry adapters for xicoy?

of course!
https://youtu.be/-vqXTL6gJU0

**Comment by i3dm** [comment] 2023-06-25 15:34
> We have conducted some testing and modifications, but due to our lack of third-party cooperation, we do not guarantee that this new program will fully address compatibility issues. We are also in contact with some third-party manufacturers, but have not replied yet.
> 
> [FrSkyRB25S_20230509.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11858477/FrSkyRB25S_20230509.zip)

i was never contacted (zavionix)
and im happy to help.

**Comment by SmartTommy** [comment] 2023-06-26 01:07
> > We have conducted some testing and modifications, but due to our lack of third-party cooperation, we do not guarantee that this new program will fully address compatibility issues. We are also in contact with some third-party manufacturers, but have not replied yet.
> > [FrSkyRB25S_20230509.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11858477/FrSkyRB25S_20230509.zip)
> 
> i was never contacted (zavionix) and im happy to help.

hi,does the "FrSkyRB25S_20230509.frsk" works for you? i have no your adapters.

**Comment by i3dm** [comment] 2023-06-26 04:05
> > > We have conducted some testing and modifications, but due to our lack of third-party cooperation, we do not guarantee that this new program will fully address compatibility issues. We are also in contact with some third-party manufacturers, but have not replied yet.
> > > [FrSkyRB25S_20230509.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11858477/FrSkyRB25S_20230509.zip)
> > 
> > 
> > i was never contacted (zavionix) and im happy to help.
> 
> hi,does the "FrSkyRB25S_20230509.frsk" works for you? i have no your adapters.

sorry i was using a borrowed rb25s for testing. i dont havr it here.
i can send you an adapter for testing if needed.

**Comment by SmartTommy** [comment] 2023-06-26 05:02
> > > > We have conducted some testing and modifications, but due to our lack of third-party cooperation, we do not guarantee that this new program will fully address compatibility issues. We are also in contact with some third-party manufacturers, but have not replied yet.
> > > > [FrSkyRB25S_20230509.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11858477/FrSkyRB25S_20230509.zip)
> > > 
> > > 
> > > i was never contacted (zavionix) and im happy to help.
> > 
> > 
> > hi,does the "FrSkyRB25S_20230509.frsk" works for you? i have no your adapters.
> 
> sorry i was using a borrowed rb25s for testing. i dont havr it here. i can send you an adapter for testing if needed.

i think it will works,please test the new firmware

**Comment by petermumford** [comment] 2023-07-05 16:00
> We have conducted some testing and modifications, but due to our lack of third-party cooperation, we do not guarantee that this new program will fully address compatibility issues. We are also in contact with some third-party manufacturers, but have not replied yet.
> 
> [FrSkyRB25S_20230509.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11858477/FrSkyRB25S_20230509.zip)

@SmartTommy is this for the 'S' version only? I have the non 'S' version - RB25

**Comment by Dsrenger** [comment] 2023-07-05 16:15
I think the firmware was just released officially on the website:

https://www.frsky-rc.com/rb-25-rb-25s/

**Comment by SmartTommy** [comment] 2023-07-06 00:14
> > We have conducted some testing and modifications, but due to our lack of third-party cooperation, we do not guarantee that this new program will fully address compatibility issues. We are also in contact with some third-party manufacturers, but have not replied yet.
> > [FrSkyRB25S_20230509.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/11858477/FrSkyRB25S_20230509.zip)
> 
> @SmartTommy is this for the 'S' version only? I have the non 'S' version - RB25

for RB25S&RB25

**Comment by mawzthefinn** [comment] 2023-10-16 19:54
Closing off, new RB25/S firmware released

**Closed by mawzthefinn** 2023-10-16 19:54 UTC
Labels: RF issue

**Comment by noamkrief** [comment] 2023-11-25 05:15
@mawzthefinn I bumped into this via google search.
I have the EXACT same problem. Swiwin telemetry intermittent.
TDR6 or TDMX connecting to RB35S
Then then RB35S connected to Swiwin ECU.

The solution is RX -> RB35S SBUS mode. 100% reliable telemetry.
If RX -> RB35S FBUS - we can replicate the issue consistently. Intermittent ECU tele loss.
I'll submit a new ticket when I get home and can describe the bug in better detail.
