### ISSUE TITLE
Update X20S to 1.5.7 from 1.5.6, unclear msg when I try to run again I18N update

### ISSUE THREAD

**Issue by fdapport** [FrSkyRC/ETHOS-Feedback-Community#3944] opened 2024-04-29 18:29 UTC
Hardware: X20S
Ethos Suite vers 1.5.5
Ethos ver: 1.5.6 to 1.5.7

Not sure if it is a error or just a msg from the system but it is not clear for me. 
I have update the radio from 1.5.6 to 1.5.7 with Ethos suite 1.5.5. I have forget to check the Italian display language to "Italian".. The update goes ok and the radio it is on 1.5.7.  To be sure that I didn’t lost some translation in the display I have tried to update only the firmware and I18n. When I try to do it I have a error as showed. I assume that If I like to update the radio with the same version is some thinks that I am able to do it. The error msg that comes out is "Operation Error, the update is aborted"

![Update](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42831968/d20de5db-5b44-45fa-a4d0-cb21b55b6901)
![Update002](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42831968/240a6779-634f-4e69-aa14-a5dd26c1f303)
![Update003](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42831968/633ad3a6-7b1a-408f-a060-e073f5a0e3cc)

**Comment by fdapport** [comment] 2024-04-29 18:44
if I downgrade to Ethos suite. .5.4 look like that all works ok

**Comment by strgaltdel** [comment] 2024-04-29 18:46
duplicate of #3942 ?

**Comment by fdapport** [comment] 2024-04-29 18:57
yes, it is a duplicate issue but in my scenario  I was able to update to 1.5.7 via Ethos Suite 1.5.5, only when I try to update again part of the firmware  I have the error. You could close it if you think it is the same issues. Thanks

**Closed as completed** 2024-04-30 02:52 UTC
Labels: suite
