### ISSUE TITLE
1.4.3. FCC small issues

### ISSUE THREAD

**Issue by Richrfl** [FrSkyRC/ETHOS-Feedback-Community#2120] opened 2022-11-23 16:17 UTC
The pot/sliders position in the check list work as expected. However there are a couple of details that need to be addressed:
1) If the only warning is originated by the pots position, only a voice warning is heard, but the screen is not locked as if a switch position is wrong.
2) If besides the pots/sliders, there is a switch warning, then the regular screen verifying that switch and sliders are in the right place, However, if the switch is set to the right position, the screen is active without forcing to set the pots/sliders to the right position.
3) If in the above case the pots are set to position and after the switch is set to the right position, then the warning screen is cleared but instead of going to the model screen, it stays requesting a key to skip.
I hope this detail is clear enough for the development team to take care of it.

**Comment by bsongis-frsky** [comment] 2022-11-23 21:16
Needs to be confirmed

**Comment by bsongis-frsky** [comment] 2022-11-23 21:36
Duplicate of #2077

**Closed by bsongis-frsky** 2022-11-23 21:36 UTC
