### ISSUE TITLE
LS cant change value with pressure sensor and different units

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#4215] opened 2024-07-03 19:23 UTC
X10S
checked on 1.4.15 and 1.5.9 - same result.
air pressure sensor, default units Pa - made a LS A<X - all ok.
changed sensor unit to PSI - made a LS A<X - value is stuck at 0PSI and will not change.

**Comment by mawzthefinn** [comment] 2024-07-03 21:11
It will change, but takes a LOT of spinning the dial. The steps are still in pascals and the unit is being translated for display only

**Comment by i3dm** [comment] 2024-07-03 21:17
Sorry but this makes no sense for it to be this way.
I think it should be rectified.

**Comment by mawzthefinn** [comment] 2024-07-04 02:20
Which is why #2589 is still open

**Comment by i3dm** [comment] 2024-07-04 05:02
Yes. Quite an old bug. Shall I close this issue then?

**Comment by mawzthefinn** [comment] 2024-07-04 13:00
Yes, as it is a duplicate.

**Comment by bsongis-frsky** [comment] 2024-08-20 09:08
Duplicate of #2589

**Closed as completed by bsongis-frsky** 2024-08-20 09:08 UTC
Labels: duplicate
