### ISSUE TITLE
Push-button on the VARS mixer cannot be used sensibly 

### ISSUE THREAD

**Issue by Peterbilt84** [FrSkyRC/ETHOS-Feedback-Community#2482] opened 2023-03-07 15:34 UTC
With the VARS mixer, the value should change per button press when adding or subtracting and not as long as the button is pressed. 

I am using the firmware update 1.5.0 which was uploaded 7 hours ago.

**Comment by mawzthefinn** [comment] 2023-03-07 16:34
Duplicate of #2463 

Repeat is being addressed.

**Closed by mawzthefinn** 2023-03-07 16:34 UTC
Labels: duplicate
