### ISSUE TITLE
Incorrect Triggering of Sticky LSw by System Event 'Throttle active'

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#3871] opened 2024-04-19 08:00 UTC
I am using a Tandem X20S with ETHOS 1.5.6 and found that triggering a Sticky LSw by the system event 'Throttle active' does not work properly. The LSw is triggered as soon as the 'Throttle cut' is removed, even if the throttle stick is in the idle position. There seems to be some transient that triggers the Sticky.

This can be underpinned by the following test:
A LSw 'Throttle active' OR 'Throttle active' correctly considers the throttle stick position, in principle. However, it can be seen in the list of LSw's that quite often it gets temporarily TRUE (for a short period) when the 'Throttle cut' is removed with the throttle stick in the idle position.

**Comment by Dsrenger** [comment] 2024-04-19 08:06
Will be fixed in 1.5.7 and is already fixed in the nightly.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3842

**Comment by Hartinger** [comment] 2024-04-19 08:11
Ups, I have overlooked that the problem has already been reported and a fix is already available. Sorry for that.

**Comment by bsongis-frsky** [comment] 2024-04-19 09:51
Duplicate of #3842

**Closed as completed by bsongis-frsky** 2024-04-19 09:51 UTC
