### ISSUE TITLE
Servos Stutter when in info screen is selected Using Tandom x20 on 900mhz R9Stab rx 

### ISSUE THREAD

**Issue by ETHOSWarrier** [FrSkyRC/ETHOS-Feedback-Community#1489] opened 2022-02-19 12:29 UTC
Hello All,I think I have just found a bug. Whilst setting up my ASW28 Hotliner on 900mhz(as I had rx spare!)Using an R9STAB rx on my Tandom x20 EU LBT.

Everything works as normal ,controlling the servos on my F5J template on ETHOS 1.1.1. EU LBT ,TD firmware 2.2.0 and  rx firmware 1.3.1

R9Stab is set to ch10 middle(all stab stuff off)Default on the template anyway. Don't need the stab, just the 8ch PWM outs 

Whilst waggling the sticks...all normal...then go into "system" ...all normal but hit the Info tab and the servos start to stutter with a loss of proportional control. ..Very weird...now I know you wont do this while flying but if on the ground ,it might upset the throttle..I have only two sx plugged into ch1 and 2 at the moment when I saw the stutter..

Its totally repeatable too, every time. Can anyone confirm theirs does the same.... Chris.T

PS....I tried to add a video of it but its 30meg and the limit is 10meg so it wont load.Now I have made it smaller and  Tried at 10.6meg..toolarge..I can email if required.

**Comment by rkeck** [comment] 2022-02-19 14:40
900 MHz telemetry is known to cause servo stuttering when the antenna is placed near the servo wires. Don't know about the system info tab, but maybe there is some telemetry channel opened to the RX to get additional info. On my system (Tandem X20S, 1.1.1 EU LBT and R9-MX with 1.3.1) it doesn't stutter so maybe it really is the servo wires/telemetry problem.

**Comment by EngelMT** [comment] 2022-02-20 08:26
Please check #1467. Seems the same issue. RSSI goes up and down. But only in Info menu. In normal mode all is working well.

**Comment by bsongis-frsky** [comment] 2022-03-03 14:02
Duplicate of #1467

**Closed by bsongis-frsky** 2022-03-03 14:02 UTC
