### ISSUE TITLE
 UGREEN aptX LL Bluetooth Receiver 5.0  Unable to connect to  X20s

### ISSUE THREAD

**Issue by Ashley757** [FrSkyRC/ETHOS-Feedback-Community#424] opened 2021-06-07 22:34 UTC
I have been unable to connect to my UGREEN aptX LL Bluetooth Receiver 5.0 
everything works with my Bluetooth Anker speakers

**Comment by bsongis-frsky** [comment] 2021-09-20 05:48
Duplicate of #160 . Not sure your bluetooth receiver is compatible? Please answer in #160

**Closed by bsongis-frsky** 2021-09-20 05:48 UTC
