### ISSUE TITLE
Autotrim or triminstantaneous

### ISSUE THREAD

**Issue by alexestevezfpv** [FrSkyRC/ETHOS-Feedback-Community#2330] opened 2023-01-14 20:17 UTC
A very important function that I have been using to trim airplanes in flight and due to the difficulty of seeing the buttons while flying, is the autotrim or instant trim option to facilitate this configuration.

**Comment by mawzthefinn** [comment] 2023-01-14 21:22
This is a duplicate of #295 

Please add any comments on that issue. Closing as a duplicate

**Closed by mawzthefinn** 2023-01-14 21:22 UTC
Labels: duplicate
