### ISSUE TITLE
Problem to read .wav bank in Ethos 1.0.11 rc1

### ISSUE THREAD

**Issue by Tonio62** [FrSkyRC/ETHOS-Feedback-Community#816] opened 2021-08-18 18:13 UTC
Hello,
Since I installed Ethos 1.0.11 candidate 1, the radio no longer wants to read my .wav file bank...
It only reads system files.
My sound bank is still in the right place.

The radio does not read the sounds either, when I go to look for them directly in the files on the radio

**Comment by Hobby4life** [comment] 2021-08-18 19:02
radio?

**Comment by Tonio62** [comment] 2021-08-18 19:14
Frsky X20
--
Envoyé depuis l'application myMail pour Android mercredi, 18 août 2021, 09:02PM +02:00 de Hobby4Life  ***@***.*** :

**Comment by jhammann13** [comment] 2021-08-19 05:09
It seems that only 32bit WAV files work.
Even voice announcements with a lower bit rate no longer work.

**Comment by FBarrao** [comment] 2021-08-19 05:32
Same here, the sounds that worked fine on 1.0.10 doesn´t work on 1.0.11 c1

**Comment by FBarrao** [comment] 2021-08-19 05:32
Radio X20, EU firmware

**Comment by Tonio62** [comment] 2021-08-19 05:49
You have to concert them in 32khz instead of 16khz.
Audacity program is good for that 
--
Envoyé depuis l'application myMail pour Android jeudi, 19 août 2021, 07:32AM +02:00 de FBarrao  ***@***.*** :

**Comment by FBarrao** [comment] 2021-08-19 05:59
Thank you.
With audacity you have to do one by one, if you ave generated the sounds with tts automate or opentx speaker is better to change the settings and create them again.

**Comment by Tonio62** [comment] 2021-08-19 06:06
Ok, for me it's a french bank sounds so one per one... ^^
--
Envoyé depuis l'application myMail pour Android jeudi, 19 août 2021, 08:00AM +02:00 de FBarrao  ***@***.*** :

**Comment by Hobby4life** [comment] 2021-08-19 06:07
> Thank you.
> With audacity you have to do one by one, if you ave generated the sounds with tts automate or opentx speaker is better to change the settings and create them again.

You can do perfect batch conversion with audacity:

Check out my git page about sound generating.

https://github.com/Hobby4life/ETHOS-OpenTX-Soundpacks-EN-NL

**Comment by Tonio62** [comment] 2021-08-19 06:08
Thank you very much !
--
Envoyé depuis l'application myMail pour Android jeudi, 19 août 2021, 08:07AM +02:00 de Hobby4Life  ***@***.*** :

**Comment by centertrim** [comment] 2021-08-19 08:10
I understand that people are making the conversions now in order to continue using 1.0.11 RC1, but surely this is considered a bug and 16kHz playback will be fixed in the near future?

**Closed** 2021-08-19 08:30 UTC
Labels: bug

**Comment by Hobby4life** [comment] 2021-08-19 08:39
> I understand that people are making the conversions now in order to continue using 1.0.11 RC1, but surely this is considered a bug and 16kHz playback will be fixed in the near future?

This is not a bug, sound format have always been 16bit, 32khz.. that 16khz works was just pure luck.
Frsky must do more and better documentation with specifications.

**Comment by bsongis-frsky** [comment] 2021-08-19 08:41
No it is not pure luck. 16kHz should work

**Comment by Hobby4life** [comment] 2021-08-19 08:46
> No it is not pure luck. 16kHz should work

I was always told 32khz was the standard.

Again this proves the lack of good proper documentation

**Comment by hrenz** [comment] 2021-08-19 16:20
OTX was  16KHZ standarad but 32kHz runs too
