### ISSUE TITLE
Differential in V-Tail menu for GLIDERS

### ISSUE THREAD

**Issue by yesyes2a** [FrSkyRC/ETHOS-Feedback-Community#1822] opened 2022-07-31 09:52 UTC
Hi,
Since several mouth, the option of making differential in the Vtail menu is still missing.
It is very important for gliders like F3J or F3Q.
Now I make a copy of the rudder menu (one for left and one for right) and I make a curve or eatch .

I would be more easy with including differential option in the rudder menu (like as ailerons)

Thanks

**Comment by m0p3d** [comment] 2022-07-31 14:03
Same : V- Tail mixer diff. #1746

**Comment by aeroplanebelg** [comment] 2022-08-04 09:05
Hello Mr Songis,
this gentleman is absolutely right, for a glider with v-tail, the differential on the direction is essential! Could you please add that (you did it on the prof, why not on the direction?) a copy paste will do.
I thank you in advance and thank you again for this beautiful Ethos which takes shape over time.
thank you
Robert.R

**Comment by m0p3d** [comment] 2022-09-01 09:40
@bsongis-frsky please pick up - should be very easy to implement thanks

**Comment by aeroplanebelg** [comment] 2022-09-01 14:50
Hello Mr Songis,
thank you for taking the trouble to look at this tiket.
It is true that the differential is very easy to implement especially for all old open tx but then why place this function on the depth? (this is not of much interest and just as easy to program, right?) here we are in a logic of simplification to allow the less gifted to find their happiness very simply. Therefore, do you not find it logical that we find THE function differential in the direction menu  ? ? once again why on the profondeur and not on direction ???? I don t understand this .
Thank you again for this beautiful ETHOS.
Rasquin Robert x20s 1.3.2

**Comment by Furietto** [comment] 2022-09-12 10:09
I join the other requests to introduce the function of the differential in the rudder mixer in the case of V-Tail

**Comment by mawzthefinn** [comment] 2022-11-10 02:27
Duplicate of https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/119

**Comment by jurajjurej** [comment] 2022-11-10 02:57
I join the other requests to introduce the function of the differential in the rudder mixer in the case of V-Tail.
It was already late yesterday. Well thank you.

**Comment by bsongis-frsky** [comment] 2022-11-10 07:28
Closed as duplicated issue

**Closed** 2022-11-10 07:27 UTC
