### ISSUE TITLE
Request: More elegant reversed throtle ( Toppossition of stick =0% closed bottompossition of stick = 100% open)

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#1275] opened 2022-01-02 11:55 UTC
At the moment the way to reverse throttle = long press on the throttle mix and select reverse.
When you look at the outputs menu  everything seems to do what it should  stick in toppossition =-100 stick at the bottompossition = 100
![screenshot-2022-01-02-45830](https://user-images.githubusercontent.com/12456410/147875123-9583e24d-76b9-49f9-808e-ede297b32f81.png)

The problem is that it stops there. 

The values of the stick don't change /don't get reversed automatically
The top position of the stick stays -100 and the bottom position stays 100.

This gives "problems" in logic switches etc...
![screenshot-2022-01-02-45811](https://user-images.githubusercontent.com/12456410/147875128-35781827-eafd-4cf4-9f9b-ab2e5f052ca2.png)

Proposal:

Make a throttle reverse ( system setting) that really reverses the stick  so stick down is 100 and stick up is -100 
No reversing in mixers and stuff this will make everything much easier and more fail-proof.

**Comment by guycnicholas** [comment] 2022-01-03 16:46
I notice you had posted one of the first issues on this over here: https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/12 and the feedback from @MIKE-DAILEY was to mod the output.  I would like to mention there was another manner to accomplish this in OTX which was to edit the throttle input by giving it a weight of -100.  Then everything that works off the throttle would work for you with your reversed throttle the same as it would for me with my normal throttle.
Ethos doesn't have that, at least not now, so I think what we are left with is to create a new throttle on an unused channel which is again, weighted at -100, and then use it as our throttle stick.
Personally, I don't think this is nearly as handy as having the input section OTX had, but I haven't played with it enough to do a full assessment.

**Comment by 00steven** [comment] 2022-01-05 10:16
It works for me. I'm just trying to help and create the best transmitter firmware there is. It gets rid of a lot of frustration and problems. I think this is a very small thing but it would make the user experience way better.

**Comment by mawzthefinn** [comment] 2022-11-24 03:14
ETHOS does not ever invert the stick. 

What it does do is allow the Input to the Throttle mixer to be inverted, so all mixer processing is using the inverted data.

Analogs is the equivalent of the raw sticks in OpenTX, not the Inputs layer, that is really merged into the canned surface mixers. 

You can use the canned surface mixers like a set of input layers, outputting to high channels, then use Free Mixers for the final outputs.

**Comment by mawzthefinn** [comment] 2022-12-29 19:12
Closing off as the current solution is working as intended.

**Closed by mawzthefinn** 2022-12-29 19:12 UTC
