### ISSUE TITLE
Trim not functional

### ISSUE THREAD

**Issue by radlouni** [FrSkyRC/ETHOS-Feedback-Community#1636] opened 2022-05-09 14:57 UTC
I have an FrSky X10S Express, installed Ethos 1.1.4, bootloader from 1.1.1, Trims enabled and set to medium, but when i press the trim switches on the transmitter, there is no movement on the servos.

**Comment by bsongis-frsky** [comment] 2022-05-09 15:18
Which trim(s)?

**Comment by bsongis-frsky** [comment] 2022-05-09 20:18
Did you try any 1.2.x release?

**Comment by mawzthefinn** [comment] 2022-05-09 22:03
Are you using the regular Aileron and Elevator mixes? 

This would be expected behaviour if you built Free Mixes for both surfaces.

**Comment by radlouni** [comment] 2022-05-09 22:11
> Did you try any 1.2.x release?

no i have not

**Comment by radlouni** [comment] 2022-05-09 22:12
> 

i dont remember whether its standard or free mixes for elevator and aileron. But why would this behavior be expected for free mixes ? i checked and made sure trim is enabled.

**Comment by mawzthefinn** [comment] 2022-05-09 22:21
It's expected for Free Mixes because they are a straight source->output mix. Only canned mixes have integrated Trim support.

If using Free Mixes for your primary control surfaces, you need a second trim mix that connects the trimmer to the output channel. 

Free mixes don't know that you are mixing aileron or elevator, and since there's no input layer in ETHOS, you can't do trims there instead.

**Comment by bsongis-frsky** [comment] 2022-05-12 06:58
May we close this issue then?

**Comment by radlouni** [comment] 2022-05-12 16:33
> May we close this issue then?

why not have an option in the free mix to bind it to a specific trim ? one of the golas behind ethos is to make it more user friendly than other systems. If this option is implemented, it would give users the freedom to free mix while giving the the clear option from within the mix to bind it to a trim. In this current implementation, its not clear and users will make mistakes thinking that their mixes are already bound to trims.

**Comment by mawzthefinn** [comment] 2022-05-12 16:59
The issue with binding Free Mixes to trims is that will break if the canned surface & throttle mixes are used.

It would first need the option to disable trims in the canned mixers (which is BADLY needed)

**Comment by hrenz** [comment] 2022-05-24 11:31
You program only from the programmer's point of view, 
not from the user's point of view.
That's why many things are solved too awkwardly.

**Comment by hrenz** [comment] 2022-06-04 19:44
Under ETHOS, one always comes across 
the 2 same defects in the flap mixers,

Absence of offset
Absence of trim function

this leads again and again to awkward unnecessary additional auxiliary constructions

also the free mixer which should be a universal mixer has exactly this deficiency
especially since the T18 finally has 2 free trimmers.

**Comment by mawzthefinn** [comment] 2022-12-02 04:12
#702 is the request for trims to be available as an option for Free Mixes.

I'm closing this off as a duplicate of that issue, as the solution is the same. Please continue discussion over there, this is a needed enhancement

**Closed by mawzthefinn** 2022-12-02 04:12 UTC
Labels: duplicate
