### ISSUE TITLE
Calculated sensors

### ISSUE THREAD

**Issue by islandflight** [FrSkyRC/ETHOS-Feedback-Community#4] opened 2021-03-15 06:42 UTC
Please could we have support for custom sensors e.g. multiplyer for consumption,  calculator for power ie voltage multiply current etc

**Comment by bsongis-frsky** [comment] 2021-03-26 21:01
It will come later, it would have been already done if copied from opentx, but the whole telemetry system is completely new

**Comment by Hartinger** [comment] 2021-04-02 07:37
Will it be possible to feed telemetry data into ETHOS from the external module bay?
I use an M-link module for some models, together with an Arduino converting the M-Link telemetry data into the D8 format.
(The D8 hub data can be processed by OpenTx.)
I do not expect ETHOS to support the legacy D8 hub protocol, but if telemetry input using S-Port is supported, I could rework my telemetry converter to output the data in the S-Port format.

**Comment by JaroslavFalcon** [comment] 2021-05-06 19:13
I agree
missing calculated sensors is a big drawback.
example
For a helicopter pilot, it is good to have two altimeters, one ground and one in the air. This eliminates drift due to pressure change. It is possible to accurately measure the height and automatically activate the rescue in the FBL controller

so we run it in opent TX.
With the access protocol it is even easier, because it is possible to connect 2x RX with telemetry

**Comment by JaroslavFalcon** [comment] 2021-05-06 19:16
there is no correction factor for sensor values

**Comment by bsongis-frsky** [comment] 2021-06-11 05:59
Duplicate of #377

**Closed by bsongis-frsky** 2021-06-11 05:59 UTC
