### ISSUE TITLE
Unable to connect transmitters after OSX update to Sequoia 15

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#4570] opened 2024-09-26 15:51 UTC
I updated my Mac to the latest OS a couple of days ago.   I am now unable to connect any of my transmitters to the Mac as it fails to read the drives and asked if you want to initialise them.

X20Pro and X20S have the same result.   Currently 1.5.13 on the transmitters.    
I have pulled my old Mac out of the draw and powered it up, loaded latest Ethos Suite and connect without issues.

<img width="1470" alt="Screenshot 2024-09-26 at 16 46 02" src="https://github.com/user-attachments/assets/f392b614-badc-4394-b95d-92b285c05ad4">

**Comment by mawzthefinn** [comment] 2024-09-26 17:15
Yep, latest Mac OS seems pretty broken right now with usb devices. I’m having all sorts of issues with a bunch of devices on latest MacOS

**Comment by kramgrand** [comment] 2024-09-26 19:54
Managed to get it to connect and load storage every now and then by plugging / unplugging several times.  Very hit and miss.    Def not a fix.  Once connected backup and update worked.

**Comment by bsongis-frsky** [comment] 2024-09-26 21:14
We have enough with our own issues. Don't forget to close this one when they have provided a fix ;)

**Comment by mawzthefinn** [comment] 2024-09-26 21:23
It's a duplicate of #4526 in practice, so closing in favour of that one.

**Closed as not planned by mawzthefinn** 2024-09-26 21:23 UTC
Labels: duplicate, information needed
