### ISSUE TITLE
Channel twitches with FM changes and Fade In / Out can result in non-contiguous channel output

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2370] opened 2023-01-24 12:42 UTC
Please note the following is just to demonstrate the problem as simply as possible rather than being a meaningful scenario, although it recreates a part  of my template hence how I noticed it. It also just demonstrates it with one particular setup, I'm not sure how wide the problem is, whether it just relates to Trims etc.. I confess that although this is a problem in my template I found it slightly trick to recreate so the scenario is possibly narrow (but problematic).

There are two flight modes

![image](https://user-images.githubusercontent.com/96293240/214286522-1433da5d-b728-480b-9b5c-c00a54960118.png)

FM Default has a small delay 

![image](https://user-images.githubusercontent.com/96293240/214293092-671e75e4-ecb9-419c-affd-c94cf7af0db5.png)

FM1 has a longer delay to ease testing 

![image](https://user-images.githubusercontent.com/96293240/214286705-4ff8320d-b212-46b3-b984-18c98180f518.png)

I have a LSW defined 

![image](https://user-images.githubusercontent.com/96293240/214286817-d7f22bd0-a0ff-44a7-92aa-e3abef4aa588.png)

and a few mixers 

![image](https://user-images.githubusercontent.com/96293240/214286922-91ff1564-db38-4795-b5d6-9a5cb5a93b3f.png)

you'll note mixer  'Trim' just uses SI and SJ to adjust Ch9 in FM 1 so no need for screen grab.

Mixer 'Var' selects between Ch9 and Slider Right depending on FM and the LSW.

To demontrate the problem make sure SE isn't Down, go into edit on 'Var':
Adjust Slider Right to 100%
Select FM1 (SA Down) and increase Ch9 to e.g. 90% by pressing SJ
Changing back to FM0 (SA middle) you'll notice Ch10 drop from 90% to perhaps 70% (delay dependant) before sweeping back up to 100% in the FM0 fade time. 
Changing back to FM1 (SA Down) you'll notice Ch10 drop to 0% before creeping back up to 90% in the fade time.

The problem is these should be fading between 90% and 100% not going below 90% and going nowhere near 0%.

The partial bypass is to change the fade to 0% (not ideal), however, even when doing this you can sometimes see Ch10 glitch momentarily to 0% (no doubt a single cycle).

Even if Ch9 and Slider Right are both 100% and the fade is 0s I still get twitches on contol surfaces.

I notice that if I change the 'Var' mixer to change 'FLAPS' to FM0 then Ch10 behaves as expected, gradually dropping from 100% to 90%

Thanks

**Comment by mawzthefinn** [comment] 2023-01-24 13:55
I’m unable to duplicate this based on the description provided. My test works correctly with no glitches.

Can you post your model.bin file?

**Comment by Jedsters** [comment] 2023-01-24 14:25
@mawzthefinn also, FWIW I'm still at 1.4.5. The above was created using the glider option in the new model wizard and accepting all defaults just changing the name to 'play' at the end, before making the above changes. 
Thanks

**Comment by mawzthefinn** [comment] 2023-01-24 14:29
I'm able to duplicate on your model file, digging in now.

**Comment by Jedsters** [comment] 2023-01-24 14:40
Thanks!

**Comment by mawzthefinn** [comment] 2023-01-24 14:42
The issue is in your Trim mixer, you have it selected per-FM.

What's happening is you are stacking two fades. You have both the VAR mix and the Trim mix fading on FM switch. So the VAR mix is fading from the slider value to the currently fading Ch9 value because Ch9 is going from '0' (undefined) to the current Trim mix value (only valid on FM1)

There's two ways to make this work.

1. Fade between a Free Mix and the Trimmer value, both on Ch10
2. Have the trim mix always active (ie not active only on FM1) and use the VAR mix to select.

**Comment by Jedsters** [comment] 2023-01-24 15:49
Thanks for the explanation which I believe I understand.

Apologies, but I'm struggling to understand option 1, if you'd be able to clarify please?

Option 2 isn't quite so easy in my template, doing as you suggest would leave the Trim Ch9 adjustable in all FM, i.e. I could inadvertently change Ch9 from 100% to -100% in one FM where it is not used which could cause a problem when I change back to the FM it is in use. (I also overload SI / SJ).  I suspect I can get around this however by making Trim mixer active in all FM but changing Up / Down from just SI / SJ to a LSW of FM1 + SI or FM1 + SJ so I could only actually adjust it when it was in use. 

Thanks

**Comment by mawzthefinn** [comment] 2023-01-24 15:52
Option 1 uses the FM to directly to switch between the values. Because the FM0 channel value is the Free mix, the issue with the two trim mixer values will not show up.

For option 2, using the FM-selected LSW's is what I'd do in that situation.

**Comment by Jedsters** [comment] 2023-01-24 16:31
Hmm, option 2 isn't working for me. To test I changed mixer 'Trim' to FM 0 (D) and 1. However, when I change from FM0 to FM1 Ch10 still goes from 100% to 0% before increasing to 90%. 

For option 1 are you suggesting an additional FM, i.e. FM0, FM1 and FM2 becomes FM0 + FLAPS?

**Comment by Jedsters** [comment] 2023-01-24 17:10
@mawzthefinn  I don't believe the problem is quite how you describe. 

Try changing the default weight in the 'Var' mixer from 100% to 200%. You will now see that Ch10 jumps to 200% and drops from there. It appears that the Ch10 output is starting from the Default Weight and moving to the new desired weight.

**Comment by Jedsters** [comment] 2023-01-24 17:44
Thanks. 

The 200% default was just a test to determine what was happening and is as you suggest meaningless here. In reality my 0% is a valid default (no flaps), however so are right slider (adjustable flaps  which could be (0% to 100%) or Ch9 (semi-fixed flaps in thermal mode (probably more in the middle around 50%). It is valid to switch between any 2. I may want to go from 
Normal mode with no flaps to Thermal mode (0% to maybe 50%) or Normal mode with adjustable flaps to thermal mode (maybe 30% to 50%) or Normal mode with no flaps to normal mode with adjustable flaps (0% to 30%) and obviously back. 
It doesn't matter which I select to be the default (note the 30% and 50% could be the other way around), if the Fade is always going via the default weight there is always the chance it may move in the wrong direction initially and cause non contiguous output and twitches to control surfaces. Of course this is even then only using a default and 2 other weights. There may be scenarios where there are numerous possible weights to choose from. There is no meaningful always valid default / starting point.

The only valid option is that the Fade etc. should go from the current value to the desired value whateever the source of  each of those. 

Thanks

**Comment by mawzthefinn** [comment] 2023-01-24 18:02
If that's what you want, then you need consistent switchology. Right now your switchology is fighting what you want because in some places it's FM controlled and in some places it's LSW controlled (which is controlled by FM). LSW's don't fade. 

All your issues here are because you are stacking different methods of selecting settings which behave differently, without laying out exactly how you want each switch to be used and then deciding on the implementation. 

Everything you want to achieve in the last post is doable.

In this case, changing the trigger for the Slider selection from the FLAPS LSW to !SEdown will allow fixed flaps (default, FM0), trimmer (FM1) and Slider (!SEdown and FM0) to work, and will fade between any 2. The caveat is if you flip SE while the flaps are transitioning you will get a jump, but only in that case. This works because VAR mixers have priority like FM's, the highest non-default true value is active. 

The issue there is that the LSW transitions immediately and changes the active VAR mixer value.

**Comment by Jedsters** [comment] 2023-01-24 19:34
Thanks again for the insights into how Ethos hangs together. 

Firstly a caveat that the example I've used above is the simplest model I could create to demonstrate my problem, it isn't my template which has dozens of mixers and LSW and multiple FM so please don't read too much into that, although of course it is a useful way to discuss the problem. 

Are you saying that for VAR mixers all the weight switches / triggers should be from the same source, i.e. they should all be FM or all be LSW etc? And if they are all FM then they should be in the same order as they are on the FM page?  If I've got that right can I safely mix LSW and physical switches and their order is unimportant?

If so, that shouldn't be  a problem (athough I need to check my template) as the FM are mostly just selected from LSW or SW anyway! I could just change them from a FM to the FM Active Condition (not sure if order is important for SW / LSW) or I guess create a new FM to replicate the LSW in the example. 

I suspect the caveat here is that using LSW may not give me fades while FM will - I can live with that to avoid twitches etc. or if not then I add a FM so they are all FM.

Thanks

**Comment by mawzthefinn** [comment] 2023-01-24 20:15
I'm not saying that you should only do the VAR mixer only from LSW or only from FM. I'm saying that you should not mix FM-triggered LSW's with direct FM triggering in the same mixer chain if you have fades in the mix, because you will get inconsistent behaviour

You need one or the other consistently.

**Comment by Jedsters** [comment] 2023-01-24 21:18
Thanks. Yes, I was thinking within any given VAR mixer but you're right, I didn't make that clear so thanks for clarifying. 
I'll give that a go tomorrow.

May I request the manual be updated to make that suggestion and warning please?

Thanks for all your support as always.

**Comment by mawzthefinn** [comment] 2023-01-25 13:20
Closing this off as the question has been answered

**Closed by mawzthefinn** 2023-01-25 13:20 UTC
