### ISSUE TITLE
Increase the Aileron mix maximum channels count

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#2523] opened 2023-03-19 07:42 UTC
There are some large-scale models that may need to use 3 servos per each aileron to spread the weight on control horns. Noticed, the maximum Output channels count is limited to 4 in Aileron Mixer and all other mix templates.

Is it a big problem to increase this number to let's say 8 which will be probably well above any wild imagination?

There is a possible workaround to use the template as input for 2 non-PWM channels and use 2 free mixes with sources from these two channels to drive more outputs but a cleaner solution would be just increasing the number of outputs.

**Comment by mawzthefinn** [comment] 2023-03-19 14:16
Better workaround is to clone the aileron mix which will give you another 4 channels of ailerons with full trim and input capabilities. With the new VAR implementation in 1.5.0 you will be able to use VAR's to set the configuration values and have both mixers reference the same vars and share settings.

Note this is a duplicate of #2377, so please continue the conversation there, this should be changed anyways.

Closing as a duplicate issue

**Closed by mawzthefinn** 2023-03-19 14:16 UTC
Labels: duplicate
