### ISSUE TITLE
X20 Pro with TW GR6 receiver shows no Lora RSSI and no black box recordings.

### ISSUE THREAD

**Issue by enzo-molinari** [FrSkyRC/ETHOS-Feedback-Community#2906] opened 2023-09-20 21:03 UTC
20 Pro with TW GR6 receiver shows no Lora RSSI and no black box recordings.

X20 Pro: 1.4.11 Flex
HF: FW: 1.0.11
TW GR6 FW: 1.O.5

As can be seen from the pictures it does not have Lora telemetry.
The black box shows nothing.
Strangely the black box has 2.4Ghz RSSI and VFR listed and instead of Lora it has 868MHz RSSI and VFR listed.

Thanks Enzo

![20230920_224537](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/8d6d5142-d858-4325-a3b1-cf5fd470d41c)
![20230920_224553](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/de0481cc-c2d3-426e-b28b-26fd1a1a4177)
![20230920_224628](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/525e7442-d191-4c2c-a609-9c0d8f3f3f13)
![20230920_224713](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/2972c74f-56ec-4bd1-b0c2-76edf6d5887e)
![20230920_224732](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87656206/b4eafaac-2f55-48fb-80e5-236ea8edd676)

**Comment by mawzthefinn** [comment] 2023-09-21 12:40
Duplicate of #2897 and several others. TWIN receivers only transmit 1 set of RSSI and VFR values. This is a TWIN firmware issue.

**Closed by mawzthefinn** 2023-09-21 12:40 UTC
Labels: duplicate, RF issue

**Comment by enzo-molinari** [comment] 2023-09-21 13:08
But the Blackbox does not Work on X20Pro

**Comment by mawzthefinn** [comment] 2023-09-21 13:24
Good point, I see you opened a separate issue for that. It's also an RF side issue (several of the new receivers have Black Box functionality not working and waiting for a firmware update to enable).
