### ISSUE TITLE
Support iMSB FrSky real time logging

### ISSUE THREAD

**Issue by wmayvis** [FrSkyRC/ETHOS-Feedback-Community#627] opened 2021-07-13 16:13 UTC
![IMG_1597](https://user-images.githubusercontent.com/7701921/125493433-8d318da3-a616-4cab-9d12-826cdc2cf17c.png)
I would like to use the IMSB app for collecting realtime telemetry data. I can connect my x20 to the app.
By click on the "Start" button the following message occurred "**Bluetooth Smart timeout**, No telemetry data received please insure that the Bluetooth module is properly set up and connected"

I've already contact the developer of the app and his answer was:
I think that the feature TX sends data over BT might not yet implemented.

**Comment by bsongis-frsky** [comment] 2021-07-13 18:22
Duplicate of #160

**Closed by bsongis-frsky** 2021-07-13 18:22 UTC
